### ISSUE TITLE
Firewall Policy Rule Collection Group deleting and recreating all the rules if new added

### ISSUE THREAD

**Issue by PadreGregor** [hashicorp/terraform-provider-azurerm#10083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.2
provider registry.terraform.io/hashicorp/azurerm v2.41.0

### Affected Resource(s)

azurerm_firewall_policy_rule_collection_group

### Expected Behaviour

Adding a new rule in any of the rule collections should only add the rule

### Actual Behaviour

It seems terraform deleting all the existing rules then recreating them along with the new ones

### Steps to Reproduce

1. `terraform apply`

**Comment by adamday2** [comment]
I can confirm that this is still the case with azurerm 2.49.0

**Comment by pranavdesai1900** [comment]
### Terraform (and AzureRM Provider) Version
### Terraform v0.14.2
provider registry.terraform.io/hashicorp/azurerm v2.77.0

### Affected Resource(s)
azurerm_firewall_policy_rule_collection_group

### Expected Behaviour
Adding a new rule in any of the rule collections should only add the rule. 

### Actual Behaviour
It seems terraform deleting all the existing rules then recreating them along with the new ones. Checked with latest provider version, but still the same issue, it deletes and recreates the rule collection when you add any new rule.

### Steps to Reproduce
terraform apply

**Comment by Dilergore** [comment]
Hi @gro1m,

Could you please double check this? It seems like the issue is still happening.

Thanks!

**Comment by MoritzSchuermann** [comment]
We tested it yesterday with azurerm provider 2.7x and still there.

Plus what we would also need is a dedicated resource like azurerm_firewall_network_rule or azurerm_firewall_application_rule like there is for a route table or network security group! With something like this the problem from above would be "solved"...

**Comment by Dilergore** [comment]
@magodo I can see a similar situation [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/d6b935f75fc0b4818783ff90e5bd4d4465903c75/internal/services/firewall/firewall_policy_rule_collection_group_resource.go#L88) to what you mentioned on the other [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/11181#issuecomment-1004491787). Would it be possible to ask the Firewall Team about this as well? Might be the same API, I am not sure, TBH I am more interested in this one than the other.

Thanks for your help.

**Comment by magodo** [comment]
@Dilergore Already asked out for the firewall policy, though they are using the different endpoints.

**Comment by Dilergore** [comment]
> So we don't have any fix for that? Does it cause any downtime when it deletes existing rules and add them back due to add/update any rule?

My understanding is that it does not cause any downtime as in reality it does not destroy anything (unless on purpose you delete from the code itself ofc). The problem is that it is almost impossible to determine mistakes since in the plan it always shows as it destroys/recreates everything. If you have more than a few rules it becomes unreadable...

**Comment by AshishDadhich4h2** [comment]
Thank you @Dilergore
