### ISSUE TITLE
Deprecated sql_server but no note on top

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-azurerm#10217]
Could you add a 'this resource is deprecated' on top? because people land on the deprecated resource a lot and like me spend hours searching on what the differences are between sql_server and mssql_server 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server

**Comment by tombuildsstuff** [comment]
hi @Dakpan94 

Thanks for opening this issue.

This resource isn't strictly deprecated - there's two usage models (sku vs vcores) available in the two different resources, which is why these are separate, however (as I understand it) Microsoft are no longer adding new functionality to the older `sku` based model, rather recommending folks switch to using the `vcores` instead - but as far as I understand it this hasn't been officially deprecated at this point in time.

Since this resource isn't strictly deprecated, at this point in time deprecating this resource is likely unnecessary - but I could see an argument for cross-linking between the two resources to better highlight this, something along the lines of:

```
~> **Note:** The `azurerm_mssql_server` resource provides support for `vcores` and is recommended going forwards - the `azurerm_sql_server` resource (this resource) provides support for the older `sku` based model.
```

What do you think?

Thanks!

**Comment by Dakpan94** [comment]
Hi @tombuildsstuff ,

This would be a great addition IMHO and could some time for future developers!

Kind regards :)

**Comment by ruandersMSFT** [comment]
@tombuildsstuff Here are some thoughts:

- It's a fair statement that both DTU and vCore models are supported [Choose between the vCore and DTU purchasing models](https://docs.microsoft.com/en-gb/azure/azure-sql/database/purchasing-models)
- There is **one** [API to create an Azure SQL Database](https://docs.microsoft.com/en-us/rest/api/sql/databases/createorupdate); yet, Terraform still has **two separate** object implementations ([azurerm_sql_server](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server) vs. [azurerm_mssql_server](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server)) and ([azurerm_sql_database](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database) vs. [azurerm_mssql_database](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database)).
- As observed in my PR #10192 in support of #9492 (where Storage Account Type can't be added given the out of date API), you can observe further challenges associated with having two versions of Terraform objects to deploy the same Azure Resources (one object is based on outdated API that isn't evolving).

Rather than this being an issue of "has not been announced as depreciated", I would look at it from the perspective of there should be a (single) Terraform object that is up to date with deploying / configuring the (single) Azure Resource.

The _editions_ (skus) documented in [azurerm_sql_database](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database):

![image](https://user-images.githubusercontent.com/16927960/104987827-cf8c9300-59d3-11eb-9b87-9059d4e3b3d5.png)

Are represented via the skus in the new object / API:

![image](https://user-images.githubusercontent.com/16927960/104988203-b89a7080-59d4-11eb-89b5-e2e5894eadd8.png)

While I understand Terraform can't rush to deprecate the object today (I'm envisioning the need for all the of the Terraform Imports as a result), I highly recommend that these objects provide warning output that they are old objects, no longer maintained, reference out of date APIs (almost 4 years old in this case -- 2017-03-01-preview) and will be deprecated at an undetermined time down the road.

I would also recommend Terraform not split to "two Terraform objects that control the same Azure Resource type" in the future, as this is the primary challenged being faced now, as opposed to awaiting announcement of deprecation from an API version perspective.

**Comment by katbyte** [comment]
@ruandersMSFT - when we implemented vcore support i believe there wasn't an single API version that supported both at the time, so we needed to have two resources to support both. If that's changed and there is an API that supports both we can add sku support to the new mssql resource (as its using the newer API version) and finally deprecate/remove the old one.
