### ISSUE TITLE
Errors not bubbling up from autorest/azure

### ISSUE THREAD

**Issue by booyaa** [hashicorp/terraform-provider-azurerm#10858]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```sh
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.50.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* `azurerm_app_service_plan`
* `azurerm_function_app`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

Please see the following example repo: [booyaa/tf_azurerm_bug_10858](https://github.com/booyaa/tf_azurerm_bug_10858)

### Debug Output

https://gist.github.com/booyaa/249d1a670fce94be3218d72a673500b8

### Expected Behaviour

The following error message should be displayed:

```
Cannot update the site 'FUNCTION APP NAME' because it uses AlwaysOn feature which is not allowed in the target compute mode.
```

### Actual Behaviour

```sh
Error: Error creating/updating App Service Plan "plan-tfbug-b78d100425" (Resource Group "rg-tfbugb78d100425"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

  on main.tf line 49, in resource "azurerm_app_service_plan" "this":
  49: resource "azurerm_app_service_plan" "this" {
```

### Steps to Reproduce

Please use this EXAMPLE TBC repo

1. Create the initial Azure function with a dedicated plan `terraform plan` and `terraform apply`
2. Change to consumption plan

```sh
TF_VAR_sku_tier=dynamic TF_VAR_sku_size=Y1 TF_VAR_site_config={} terraform plan
TF_VAR_sku_tier=dynamic TF_VAR_sku_size=Y1 TF_VAR_site_config={} terraform apply
```

### References

* #0000

**Comment by edomaur** [comment]
@tombuildsstuff so, does solving this issue would solve the "Unmarshalling JSON Error" linked above ?

**Comment by mivica** [comment]
@tombuildsstuff, what is ETA on this? Also, what does the "upstream-microsoft" label mean?

**Comment by tombuildsstuff** [comment]
@mivica #15404 is an issue with the base layer used by the Azure SDK (which is what this meta issue is tracking) - yes it’s going to be worked on - but unfortunately we can’t commit to timeframes - if you’re an enterprise customer, feel free to open a support ticket to track this.

**Comment by katbyte** [comment]
@Va55ago - in `v2.96` we updated the SDK/API we used for automation from `2018-06-30` to `2020-01-13` to support managed identities and it looks like the Microsoft SDK for that version/API is not able to deserialize the errors properly. Unfortunately it appears we are not able to just roll back that change since it would mean losing that functionality and as its a bug in the Microsoft SDK itself there is not much we can do to fix it without rolling out our new base layer & generated SDKs (which while we do intend to do sooner then later, there is no public timeframe yet)

**Comment by Va55ago** [comment]
@katbyte, thanks for the update. Not the answer I was hoping for, but at least now I know where I stand.

**Comment by edomaur** [comment]
@katbyte thanks for the update, really. So, now, what we need to do is to help with the new base layer rolling out :-) Can you provide us with links to the available work ? (branches and so on)

**Comment by tombuildsstuff** [comment]
@edomaur unfortunately that work isn't public at this time, this issue is the public meta issue for that work - there's a Swagger PR to try and fix the issue with the Automation API in the interim, but (to be frank) I think it's unlikely the Azure SDK team will merge it unfortunately since it'd be a breaking change to the SDK at this point in time.

**Comment by andyoll** [comment]
any updated on progress? thnx.

**Comment by richshadman** [comment]
> @edomaur unfortunately that work isn't public at this time, this issue is the public meta issue for that work - there's a Swagger PR to try and fix the issue with the Automation API in the interim, but (to be frank) I think it's unlikely the Azure SDK team will merge it unfortunately since it'd be a breaking change to the SDK at this point in time.

I am in a position where  I am dependent on post 2.95.0 changes in the provider (mainly for kubernetes changes) yet this DSC issue blocks my module as it is written. I am sure I'm not the only one in this position.

I feel I only have a handful of options to workaround this issue:

1. Convert all the azurerm_automation_dsc_configuration resource to arm template resources and lose change tracking (I handle it mostly code using file hashes to determine when to push changes but it is only one sided and assumes the dsc config is current in the automation account).
2. Download the 2.95 provider and use it as a "local" provider the way 3rd party providers used to be handled before the registry (not sure if this will work with the official provider). This way I can keep the dsc resources and use the "local" provider for these resources only. I am not sure if this will work - will be trying it next as it is faster than rewriting all the resources as ARM templates
3. Split the module(s) impacted up, separating out the DSC/automation resources into it's own module and read state as data where necessary. I'm not sure if this is a reasonable approach as I suspect there could be breaking changes in the stored states between 2.95 and current (3.36 at the time of this post) - can 2.95 azurerm provider read 3.36 state successfully?

These work around would not be needed if any of the below options were feasible:

1. Ability to specify and download multiple versions of a provider in one module (not ideal but in a real world situation like this there is plenty of good arguments to support this model). Currently attempting to do this will run into a version constraint as only one version of a provider will download and be set in the lock file at a time. Attempts to have two clashing versions in one module result in an error during initialization.
2. Specify the api version to be used by the resource (the resource would have to support both api's) - this way we could choose to use the older api for the dsc configuration resource
3. Similar to that approach, have two different resources available - one tied to the newer api and one tied to the older one that works for dsc configurations

Can you please let us know if any of the 3 options above could be implemented in the provider or in terraform itself (for #1)? For now I will attempt the workarounds above while waiting for your response.

**Comment by edomaur** [comment]
To be honest, we abandoned DSC for config management and are in the process of moving on Ansible. DSC is not stable enough, even without taking in account the problem of the azurerm provider...

**Comment by mathiash98** [comment]
Until it is fixed: add `TF_LOG=DEBUG` to terraform apply when met with this issue as described in https://github.com/hashicorp/terraform-provider-azurerm/issues/17319#issuecomment-1161597825

**Comment by tombuildsstuff** [comment]
👋 

The updated versions of the App Service Resources now use `hashicorp/go-azure-sdk` and it's base layer rather than `Azure/azure-sdk-for-go (and it's base layer of `Azure/go-autorest`), which means that the newer App Service resources now correctly surface these errors from the Azure API. The older App Service resources are deprecated and will be removed in the future, and as such we're not planning to migrate those over to the new SDK/base layer at this time.

Whilst I'm referencing App Service above since that's where this primarily surfaced - this issue can happen across multiple different APIs (ultimately anything using the older base layer `Azure/go-autorest` - which is [primarily] used by `Azure/azure-sdk-for-go` but also `tombuildsstuff/kermit`). At this point in time we're mostly moved off the older SDKs, and ultimately as resources are migrated over to `hashicorp/go-azure-sdk` instead, this issue will go away in time.

Since this issue is primarily focused on App Service, which has a fix available - I'm going to close this issue for the moment - but this problem will resolve itself as the remaining resources are refactored over to `hashicorp/go-azure-sdk`. However if you're still seeing this issue with a resource that's been migrated over to using `hashicorp/go-azure-sdk` then please feel free to open a new issue and we can take another look.

Thanks!
