### ISSUE TITLE
Terraform: ID was missing the `userAssignedIdentities` element | Azure Virtual Machine Scale Sets

### ISSUE THREAD

**Issue by shubhamsre** [hashicorp/terraform-provider-azurerm#10964]
I am working on creating disk alerts on Azure VMSS, which are part of AKS using Azure Monitor. I am using a data_block for getting the VMSS ID. The VMSS has a user managed identity.

Terraform Version v0.13.5

**Providers**
**Azurerm** Version v2.43.0
**AzureAd** Version v1.2.2

I am facing the following **error**

```
Error: ID was missing the `userAssignedIdentities` element

  on data.tf line 41, in data "azurerm_virtual_machine_scale_set" "aks_vmss":
  41: data "azurerm_virtual_machine_scale_set" "aks_vmss" {
```

**Data block for VMSS**
```
data "azurerm_virtual_machine_scale_set" "aks_vmss" {
  name                     = local.aks_vmss_name #aks-xxxnodepool-xxx83883-vmss
  resource_group_name      = local.aks_vmss_resource_group_name #MC_xxx-xxx-xxx-xxx-xxx_xxx-aks-xxx-xxx_eastus
}
```

**Comment by tombuildsstuff** [comment]
hi @shubhamsre 

Taking a look through here it appears that this has been fixed in more recent versions of the Azure Provider - as such I'm going to close this issue for the moment, but if your still seeing this issue with the latest version of the Azure Provider then please feel free to open a new issue and we'll take another look.

Thanks!
