### ISSUE TITLE
azurerm_monitor_diagnostic_setting - Error resource already exists - to be managed via Terraform this resource needs to be imported into the State

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-azurerm#11076]
_This issue was originally opened by @mikeTM3 as hashicorp/terraform#28159. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    

### Terraform Version

Terraform v0.14.8
```
...
```

### Terraform Configuration Files

```terraform

https://www.dropbox.com/s/jj3umbrveilihhk/terraformdatabase.zip?dl=0

...
```

### Debug Output

https://www.dropbox.com/s/4punljlpwz6rg1k/terraform%20debug%20output.txt?dl=0

### Expected Behavior

Terraform should have created the azurerm_monitor_diagnostic_setting resource without completing with an errors
### Actual Behavior

Terraform creates the Azure  azurerm_monitor_diagnostic_setting resource but produce an error, indicating resource exists. This is wrong as Azure environment, is empty at start of Terraform Apply, so looks like that possibly the fist setting update works but subsequent error because Terraform believes resource already exists, when Teraform created it

**Comment by premaarya** [comment]
Is this issue resolved? I am getting this today within Terraform v0.14.10.

**Comment by angegar** [comment]
We have the same issue with the following configuration.

```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.73.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

We are trying to enable diagnostic settings on AKS Cluster. During cluster update we encounter the "Error ressource already exists" issue, thus we tried to delete the cluster and re-create it. Even during a new creation we have this issue, it appears that the cluster deletion had not removed the diagnostic settings components.

We are still investigating ....

**Comment by DesislavaNPetrova** [comment]
Is this issue resolved?
I am getting this today within Terraform v0.13

**Comment by ms-zhenhua** [comment]
Thank you for reaching out. 
According to this [issue](https://github.com/MicrosoftDocs/azure-docs/issues/67267) and this [document](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/resource-manager-diagnostic-settings#diagnostic-setting-for-activity-log): **Diagnostic settings for Activity logs are created for a subscription, not for a resource group like settings for Azure resources**. So when you delete an Azure resource in the Azure portal or through Azure command, the associated diagnostic setting resource will not be deleted together with this Azure resource. Next time when you use terraform to re-create the same Azure resource, this diagnostic setting resource will still be associated with this Azure resource automatically. Then when the diagnostic setting resource is being re-created with the Terraform scripts, you will get the error of the resource already exists because it was not deleted before.
However, if you use the Terraform to destroy this Azure resource, the associated diagnostic setting resource will be deleted first before this Azure resource is deleted because these two resources have a relation in the terraform.
If you already get this issue, there are two workaround ways:
1. Use **[Terraform import](https://www.terraform.io/docs/cli/import/index.html)** command to import the associated diagnostic setting resource, then use **Terraform Apply** to make sure the imported diagnostic setting resource have the same configuration with that defined in the .tf file.
2. Use **[Rest API](https://docs.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/delete)** to delete the associated diagnostic setting resource and then use Terraform Apply to re-create the diagnostic setting resource.

**Comment by DesislavaNPetrova** [comment]
Thank you for your assistance! 
Workaround is working.

**Comment by tombuildsstuff** [comment]
Closing this out since this is fixed, as mentioned above this can be resolved by importing the existing resource into your Terraform State (and either managing this, or destroying it) or deleting this through the Azure CLI / Portal
