### ISSUE TITLE
Support for AKS private cluster dns zone ID export

### ISSUE THREAD

**Issue by dtupy** [hashicorp/terraform-provider-azurerm#11100]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful if one of the exported outputs by azurerm_kubernetes_cluster was the ID of the Private DNS zone it creates when private cluster is enabled. I do like having the ability to create my own zone and use it for the cluster, but this would be even easier. 

### New or Affected Resource(s)

azurerm_kubernetes_cluster

**Comment by stephybun** [comment]
Hi @dtupy,

Thanks for raising this issue. It is possible to set this property and to access it in [`azurerm_kubernetes_cluster`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#private_dns_zone_id). Since this is already supported I am going to close this issue.
