### ISSUE TITLE
[G] General question - PR reviews

### ISSUE THREAD

**Issue by IanMoroney** [hashicorp/terraform-provider-azurerm#11188]
I've noticed a shifting trend over the last few releases of the provider where the majority of accepted and reviewed PR's are from within the azurerm provider team, and community provided PR's of any size over an L are being ignored.

Is there a reason for this?

I appreciate that XL and XXL PR's take effort to review, but if the team can review and approve (and add instant milestones) to their own PR's which are XL, XXL, and XXXL, why not the communities?

I don't like complaining in a community that I love so dearly, and yes this note is borne of an outstanding PR of my own, but I just want to understand if there is anything that the community can do to help this situation.

Can more people be delegated to review PR's, can there be an agreed quota of XL+ PR's reviewed in a month, or just anything really that can bring the backlog down a bit?

Thank you for your time.

**Comment by favoretti** [comment]
@IanMoroney I lurk on slack when I need attention to the PRs that I submit, it helps. The sheer amount of PRs incoming and issues being raised is quite large, hence it does take time to review.

**Comment by gro1m** [comment]
I made similar observations as Ian and I think he has a point there. I have been following this repo for almost a year now and did my Terraform implementations based on it (yet did not contribute any code to the repo). There has been the one or other time where I had hoped that community contributions would be merged in faster.
Now I am thinking to maybe implementing some machine learning resources myself as there are very important to my team and I am in principle happy to contribute (but unfamiliar with Go, so not quickest). Still, I worry about development time and time to release as there are still no contribution guidelines and I am very uncertain when the PR would be merged after possibly a lot of effort from my side. 

What’s more is that I have the feeling that Terraform is the only viable tool to keep up software engineering priniciples such as traceability for infrastructure as code. It also helps not to rebuild everything from scratch (i.e. maintaining state is really helpful) every time. The biggest counter-argument against using Terraform in my organization is that a lot of Azure resources are still not available via Terraform (or are not feature-complete) and so people resort to using additional Azure CLI (which is also buggy) and Azure PowerShell, which leads to a mix of techniques and that is far from optimal. In my opinion, there should be more support from Microsoft if there are problems with mapping Azure resources to Terraform, as it is really crucial to the success of the Azure platform.

I guess that most organizations that employ agile principles that have roughly a 3-months plan for features and 3-4 weeks time window to complete bigger tasks. So I think I would be great if the principle goal were to review a „working“ PR within 4 weeks and to merge in a green branch within 3 months from then onwards. There are still PRs from last year that have merge conflicts but otherwise look good that weren’t merged and do not make a good impression on the outsiders (there may be valid reasons, but it looks not well maintained and then questions come like: „Will this finally be merged?“ et cetera).

I think it would also be really great if there were some contributing guidelines. Terraform provides some main guidelines here: https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md and on https://www.terraform.io/docs/extend/community/maintainers.html. I know that some efforts have been made here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/2688, but there does not seem yet to be a finally version of this.

It would certainly also be helpful to have some more information on testing infrastructure as code, handling of branches (naming convention, git rebase?, …) and which forums to use: The Slack channel you mentioned, @favoretti, does not seem to be public or I do not seem to find it. The Azure Terraform community forum (https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) does not look right.

Still, I want that you keep the great work up with Terraform for Azure. This is my subjective impression and I hope my feedback helps.

**Comment by favoretti** [comment]
@gro1m Slack channel is the 4th link in the README of the repo:
![image](https://user-images.githubusercontent.com/805046/113691666-f736f180-96cc-11eb-843b-b485af2c4d29.png)

**Comment by favoretti** [comment]
Thank you for opening this issue. As you have probably heard Azure Provider team has expanded recently, a couple more people joined the team over the summer and there's some involvement from community-based collaborators, such as myself. We welcome your feedback on current support and review process and we're doing our best to keep you all happy of course :)

We've mentioned above that joining our Slack community is a great way to get in touch with all of the maintainers. There are guidelines on how to contribute in the README file. There are also efforts underway to make development experience and contributing an easier experience, more to come on that later.

With all this being said, I'd like to close the issue, since this isn't related to any particular issue in terraform provider and we welcome you to continue this discussion on Slack or contribute in form of community-driven developer documentation as a PR (that of course will be reviews with lots of love and appreciation :))
