### ISSUE TITLE
site_config isn't swapped to production slot on slot swap

### ISSUE THREAD

**Issue by benbelow** [hashicorp/terraform-provider-azurerm#11368]
According to documentation here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_slot

```When using Slots - the app_settings, connection_string and site_config blocks on the azurerm_app_service resource will be overwritten when promoting a Slot using the azurerm_app_service_active_slot resource.```

We've set a couple of values in the staging slot only based on this documentation - specifically `always_on = true`, and cors urls, in addition to app settings and connection strings.

We've seen that the app settings and connection strings are copied across to the production slot on swap as expected. 

However, the settings stemming from site_config are not being copied across, leading to issues in our production slot.

Is this documentation out of date, or otherwise conditional?

Cheers!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this and apologies for the delayed response. We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). The azurerm_app_service resource is deprecated and will be removed in v4.0 - I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead, if you have not already done so.
With that in mind, I'm going to close this issue.
