### ISSUE TITLE
Support for usage of azurerm_kubernetes_cluster_node_pool as backend_address_pool for azurerm_application_gateway

### ISSUE THREAD

**Issue by michail-nikolaev** [hashicorp/terraform-provider-azurerm#11573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Application Gateway allows specifying Kubernetes node pool as backend address pool (because it is a virtual machine scale set internally). But it is impossible to do it using Terraform (but supported for raw VMSS https://github.com/terraform-providers/terraform-provider-azurerm/issues/1501).

### New or Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool
* azurerm_application_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "test" {
  # ..
}

resource "azurerm_kubernetes_cluster_node_pool" "test" {
  # ..
  application_gateway_backend_address_pool_ids = ["${azurerm_application_gateway.test.id}"]
}
```

### References

*  https://github.com/terraform-providers/terraform-provider-azurerm/issues/1501

**Comment by aristosvo** [comment]
Hi @michail-nikolaev!

You can either configure it on the raw VMSS or using add-on `ingress_application_gateway`:

```
resource "azurerm_kubernetes_cluster_node_pool" "test" {
  # ..
  addon_profile {
    application_ingress_gateway {
      enabled = true
      gateway_id = <your gateway>
    }
  }
}
```
See [this page](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing) for further details, as specified in the [Terraform docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#gateway_id).

Does this answer fulfil your needs?

**Comment by michail-nikolaev** [comment]
No, my configuration is more complex than ApplucationGatewayIngress. It is like ApplicationGateway(TLS, WAF)->nginx ingress(tricky retry, custom complex routing)->app. So, I need kubernetes node pool to be registered as backend address pool.

**Comment by aristosvo** [comment]
Okay, sure. How would you configure this without Terraform? If we have an example of this configuration with the `az CLI`, we can more easily work our way backwards to Terraform.

If it can't be done with the CLI, it isn't something we can easily support with Terraform.

**Comment by michail-nikolaev** [comment]
It is not a clear solution (because `grep`, but the possible way).

So, we want to add `$POOL_NAME` node pool to application gateway.

For first we need to know the name of the node pools resources group
```
CLUSTER_NODE_RESOURCE_GROUP=$(az aks show --resource-group $CLUSTER_RESOURCE_GROUP --name $CLUSTER_NAME --query nodeResourceGroup -o tsv)
```
After - list VMSS and get the name (dirty part here - don't know how to match VMSS with the node pool in better way)
```
VMSS_NAME=$(az vmss list --resource-group $CLUSTER_NODE_RESOURCE_GROUP --query '[*].name' -o tsv | grep aks-$POOL_NAME-)
```

Get id of backend address pool:
```
BACKEND_ADDRESS_POOL=$(az network application-gateway address-pool show -g $GATEWAY_RG --gateway-name $GATEWAY_NAME -n $BACKEND_ADDRESS_POOL_NAME --query 'id')
SET_JSON=$(echo \'{\"id\": $BACKEND_ADDRESS_POOL}\')
```

Update VMSS:
```
az vmss update --resource-group $CLUSTER_NODE_RESOURCE_GROUP --name $VMSS_NAME --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].ApplicationGatewayBackendAddressPools !!!PUT SET_JSON HERE!!!
```

Update VMSS
```
az vmss update-instances --instance-ids '*' \
    --resource-group $CLUSTER_NODE_RESOURCE_GROUP \
    --name $SCALE_SET_NAME
```

**Comment by generalconsensus** [comment]
> Hi @michail-nikolaev!
> 
> You can either configure it on the raw VMSS or using add-on `ingress_application_gateway`:
> 
> ```
> resource "azurerm_kubernetes_cluster_node_pool" "test" {
>   # ..
>   addon_profile {
>     application_ingress_gateway {
>       enabled = true
>       gateway_id = <your gateway>
>     }
>   }
> }
> ```
> 
> See [this page](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-existing) for further details, as specified in the [Terraform docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#gateway_id).
> 
> Does this answer fulfil your needs?

Documentation for azurerm_kubernetes_cluster_node_pool does not currently provide for a addon_profile block. Can this be configured in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster which does have an addon_profile -- however under kubernetes_cluster I'm not seeing anything in the addon_profile block for app gateway.

It seems rather disappointing and limiting that in order to use app gateway we are unable to use VMSS or App Services which exist within the console UI on Azure cloud. 

What this means is that at present app gateway is not a good candidate for integration with AKS clusters that have VMSS and autoscaling as new pods that get scheduled on new nodes which are meant to be forwarded traffic for AGIC will not work as the current deployed applications will not receive new traffic as the app gateway could not possible know about these new systems unless we grab the new private ip's and append them to our backend pools.

Thank you for taking a look at this, it means a lot to our team!

**Comment by ashwatthb** [comment]
Hi  @michail-nikolaev!

This feature will be useful in below scenario.

Deploy AKS cluster and install istio-ingress-gateway as your ingress solution. If we want to use the AKS node pools as backend and automatically populate the instances as targets in application gateway,  we need a way to attach VMSS created by node pools to application gateway. 

It will be helpful to know if this feature is already being implemented in terraform

Thanks advance

**Comment by rcskosir** [comment]
Thank you for taking the time to open this feature request. This is not something we are able to implement currently based on what we manage in this repo, this would be better served as an upstream request. I am going to close this issue for now, since it is not something we are able to add, but if an upstream request is made and implemented and support is needed on our side, we can either reopen this issue or feel free to raise a new one. 
Thanks!
