### ISSUE TITLE
azurerm_security_center_automation: Support for `RegulatoryComplianceAssessment`

### ISSUE THREAD

**Issue by MaxiPalle** [hashicorp/terraform-provider-azurerm#11571]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As 'regulatory compliance' is already in preview for exported data types within continuous export, it would be helpful to add this data type.
Currently this `event_source` type of data is missing. Should be a set of strings.

* azurerm_security_center_automation

### Potential Terraform Configuration

```hcl
source {
    event_source = "RegulatoryComplianceAssessment"
    rule_set {
      rule {
        standard  = [ "String1", "String2"]
      }
    }
}
```
and

```hcl
source {
    event_source = "RegulatoryComplianceAssessmentSnapshot"
    rule_set {
      rule {
        standard  = [ "String1", "String2"]
      }
    }
}
```

### References

https://docs.microsoft.com/en-us/rest/api/securitycenter/automations/createorupdate#eventsource

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. Looking at the current version of the SDK - it does not support this value as of this moment unfortunately.

**Comment by Grant-Rc** [comment]
Just a note from my issue

Updated all our subscription to use continuous export to log_analytics_workspace via the Azure portal, got asked to manage this via terraform so I found azurerm_security_center_automation in the latest version and updated. Then struggled to find the resource id in order to import, but found you can get this information via API. https://docs.microsoft.com/en-us/rest/api/securitycenter/automations/list

Ran an import and this imported the following 

source {
    event_source = "SecureScoresSnapshot"
  }
  source {
    event_source = "SecureScoreControlsSnapshot"
  }
  source {
    event_source = "RegulatoryComplianceAssessment"
  }
  source {
    event_source = "RegulatoryComplianceAssessmentSnapshot"

Running terraform plan I get "Error: expected source.event_source to be one of [Alerts Assessments SecureScoreControls SecureScores SubAssessments], got SecureScoresSnapshot"

Is anyone able to look at this to add these sources to Azurerm?

**Comment by nickel-tyler** [comment]
this is done I think?

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/154907002/0631ab9b-bf19-493d-81e4-62fc77211bbf)
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/154907002/f9b10e98-cb08-4d39-987a-60f1e037eec6)

**Comment by favoretti** [comment]
Looks like it, will close it then, thank you!
