### ISSUE TITLE
azurerm_network_security_group dynamic rules not being removed

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-azurerm#11724]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azurerm v2.47.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)

* `azurerm_network_security_group`

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "nsg_obj" {
    for_each = {
        for key, value in var.subnets:
            key => value
            if lookup(value,"nsg_creation",true) != false
    }

    name                               = "${module.names.standard["network-security-group"]}-${each.value.name}"
    resource_group_name                = var.resource_group
    location                           = var.location
    tags                               = var.tags
    dynamic "security_rule" {
        for_each                       = concat(each.value.nsg_inbound, each.value.nsg_outbound)
        content {
            name                       = security_rule.value[0]
            description                = security_rule.value[1]
            priority                   = security_rule.value[2]
            direction                  = security_rule.value[3]
            access                     = security_rule.value[4]
            protocol                   = security_rule.value[5]
            source_port_range          = security_rule.value[6]
            destination_port_range     = security_rule.value[7]
            source_address_prefix      = security_rule.value[8]
            destination_address_prefix = security_rule.value[9]
        }
    }
}
```

### Expected Behaviour

When an NSG rule is removed from var.subnets, terraform plan/apply should notice this rule has been removed and removes it.

If you ADD a rule it will then notice rules that need to be deleted, but not when taking rules out without adding a new one...

### Actual Behaviour

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by magodo** [comment]
@matt-garner-nw Thank you for submitting this issue!

When the issue happens, is that always the case or it only happens when the NSR got removed is the only rule defined inside the current subnet under iteration? If it is the latter case, then you might need to specifically check on this case (1->0), and when detected, you'll have to set the `security_rule = []` - rather than omitting the `security_rule` block at all, as for now.

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here - but as per @magodo's comment above, these can be nil'd out here by specifying an empty list in the config for now (e.g. `security_rule = []`, which [is called out in the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_group#security_rule) - v4.0 of the Provider may well change this to be un-Computed but this isn't something we can do until then since this'd be a breaking change unfortunately, as per this comment: https://github.com/hashicorp/terraform-provider-azurerm/pull/16505#discussion_r856192250
