### ISSUE TITLE
Please enable Secured Hub for virtual_wan 

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-azurerm#11842]
https://discuss.hashicorp.com/t/converting-vwan-hub-to-secure-hub-azure-firewall/24493 

Would it be possible to create a module that enables Secure Hub (AZ Firewall)?
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub_security_partner_provider works for the security providers, but I don't see anything similar for az Firewall.

Thanks very much!

**Comment by magodo** [comment]
@danabrash In order to create a secured vhub, you'll need to:

- Create a `azurerm_firewall_policy`
- Create a `azurerm_firewall` and setting its `virtual_hub` block and `firewall_policy_id` field.

See below reference template from the AccTest: https://github.com/terraform-providers/terraform-provider-azurerm/blob/090fa6506f7693306b53b613c08ff6de86fc64e2/azurerm/internal/services/firewall/firewall_resource_test.go#L850-L897

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where the topic came from. With that in mind, I'm going to close this issue.
