### ISSUE TITLE
azurerm_frontdoor_custom_https_configuration and new Front Door endpoints precedence.

### ISSUE THREAD

**Issue by la-sanchez** [hashicorp/terraform-provider-azurerm#11857]
### Terraform Version

```
0.15.3
```

### Terraform Configuration Files

```terraform
resource "azurerm_frontdoor_custom_https_configuration" "frontend_endpoint_https_config" {
  for_each = var.frontend_endpoints
  frontend_endpoint_id = azurerm_frontdoor.fd.frontend_endpoints[each.value.name]
  custom_https_provisioning_enabled = each.key != "default" ? true : false
  dynamic "custom_https_configuration" {
    ...
  }
}
```

### Error raised

Error: Invalid index
│
│   on ../../modules/network/front_door/main.tf line 4, in resource "azurerm_frontdoor_custom_https_configuration" "frontend_endpoint_https_config":
│    4:   frontend_endpoint_id = azurerm_frontdoor.fd.frontend_endpoints[each.value.name]
│     ├────────────────
│     │ azurerm_frontdoor.fd.frontend_endpoints is map of string with 5 elements
│     │ each.value.name is "contoso-com"
│
│ The given key does not identify an element in this collection value.

### Expected Behavior

New Front Door endpoint is created **BEFORE** the azurerm_frontdoor_custom_https_configuration for that new endpoint is created.

### Actual Behavior

Terraform returns an error trying to create a new azurerm_frontdoor_custom_https_configuration because the new endpoint is not created yet.

### References

https://github.com/hashicorp/terraform/issues/28785

**Comment by Poil** [comment]
Hi,

I have the same issue, I have been able to resolve it by doing something like that, but I need 2 runs to have SSL on new endpoints

```
for_each = { for fek, fev in azurerm_frontdoor.frontdoor.frontend_endpoints : fek => fev if lookup(lookup(local.rm_frontend_endpoints, fek, {}), "custom_https_configurations", null) != null ? true : false }
```

Also I still not understand why we have a big "resource" for frontdoor (except SSL now). AZ Cli can create FE / RR / ... independently I think it's a very bad design choice (same apply on Azure App GW).

Best regards,

**Comment by rscottwatson** [comment]
I had the same problem but went back to 2.49 provider version and used the inline custom_https_configuration block of the azurerm_frontdoor resource.  While not optimal it allowed me get past my problem until this is resolved.

**Comment by yube-sitecore** [comment]
Is there are any updates or plans regarding this issue?
We facing the same problem, so it's not possible to add or change the existing frontendendpoint, without removing **azurerm_frontdoor_custom_https_configuration**, because **azurerm_frontdoor_custom_https_configuration ** doesn't track upcoming changes from the frontendpoint resources and as result, we need to comment all **azurerm_frontdoor_custom_https_configuration**  resources, apply changes to frontendendpoints and after deploy **azurerm_frontdoor_custom_https_configuration**. If **azurerm_frontdoor_custom_https_configuration** will evaluate upcoming changes to frontendendpoints.

**Comment by ksheytanov** [comment]
Same thing here. Currently this issue stands in our way to fully automating infrastructure changes across all our environments.

**Comment by michelefa1988** [comment]
Same issuer here

**Comment by michelefa1988** [comment]
@Poil Would you be able to share the code on how you managed your work around?

I have tried to use your for_each but dont know enough to know the details on how to use it in the endpoint ID. 

I am trying something like this 



```
resource "azurerm_frontdoor_custom_https_configuration" "frontdoor_custom_https_configuration" {

  count = length(var.frontdoor_applications)

  frontend_endpoint_id = azurerm_frontdoor.frontdoor.frontend_endpoints[var.frontdoor_applications["${count.index}"].name]

  custom_https_provisioning_enabled = var.frontdoor_applications["${count.index}"].custom_https_provisioning_enabled

  custom_https_configuration {
    certificate_source                      = var.certificate_source
    azure_key_vault_certificate_secret_name = var.secret_name
    azure_key_vault_certificate_vault_id    = var.key_vault_id
  }

  depends_on = [
    azurerm_frontdoor.frontdoor
  ]
}
```

**Comment by yube-sitecore** [comment]
Right now we are going it in 2 steps:
1. Create endpoints
2. Create https configuration

It prevents us from automation of scenarios around FrontDoor. But we already accepted this situation, as found other blockers with FrontDoor, for instance now we can't update URL for the existing FrontendEndpoint, but it was possible before.
Also, there are missing engines rules, as I saw.

**Comment by stevef51** [comment]
@michelefa1988 not sure if this is still an issue for you or not.  I have a workaround using @yube-sitecore 2 step approach, and I do it with a single Terraform script, but I have to modify the script before running it a 2nd time, excerpts of scripts .. below explains how I add a new domain to the Frontdoor

variable "front_ends" {
  type = list(object({
    name                  = string
    domain                = string
    enable_https          = bool
    key_vault_secret_name = string // The name of the secret within the single keyvault defined above
  }))
}

  front_ends = [{
    name                  = "existing-fep"
    domain                = "*.existing-sample-domain.com"
    enable_https          = true
    key_vault_secret_name = "secret-for-sample-domain-from-keyvault"
    }, {
    name                  = "new-fep"
    domain                = "*.new-sample-domain.com"
    enable_https          = false                        
    key_vault_secret_name = "secret-for-new-domain-from-keyvault"
  }]

locals {
  front_ends       = var.front_ends
  front_ends_https = [for fe in var.front_ends : fe if fe.enable_https]
}

resource "azurerm_frontdoor_custom_https_configuration" "https" {
  count                             = length(local.front_ends_https)
  frontend_endpoint_id              = azurerm_frontdoor.fd.frontend_endpoints[local.front_ends_https[count.index].name]
  custom_https_provisioning_enabled = true
  custom_https_configuration {
    certificate_source                      = "AzureKeyVault"
    azure_key_vault_certificate_vault_id    = data.azurerm_key_vault.kv.id
    azure_key_vault_certificate_secret_name = local.front_ends_https[count.index].key_vault_secret_name
    // by not specifying a version it will default to "Latest"
  }
}

resource "azurerm_frontdoor" "fd" {
  name                = local.front_door_name
  resource_group_name = var.resource_group

  dynamic "frontend_endpoint" {
    for_each = local.front_ends
    content {
      name      = frontend_endpoint.value.name
      host_name = frontend_endpoint.value.domain
    }
  }

Hopefully above is enough detail, I run "terraform apply" with the above which will create the new frontend_endpoint on the Front door, I then mod the script to set the new domains "enable_https" = true

 front_ends = [{
    name                  = "existing-fep"
    domain                = "*.existing-sample-domain.com"
    enable_https          = true
    key_vault_secret_name = "secret-for-sample-domain-from-keyvault"
    }, {
    name                  = "new-fep"
    domain                = "*.new-sample-domain.com"
    enable_https          = true                        
    key_vault_secret_name = "secret-for-new-domain-from-keyvault"
  }]

and re-run "terraform apply", this will then create the https config for the now created "new-fep" endpoint

It is a pain, but better than manually managing Frontdoor through Azure portal

I think the only solution to this is to have the azurerm_frontdoor resource split into smaller resources, break out the frontend_endpoint (and other sub-resources if they have similar issues??) so that the real creation order dependency tree can be evaluated since this is the crux of the issue.

**Comment by rcskosir** [comment]
Thanks for opening this issue. There have been large changes to the azurerm_frontdoor resources as noted here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor. As such I am going to mark this issue closed. If this is still an issue with the 4.x version of the provider for the azurerm_cdn_frontdoor_custom_domain resource please do let us know by opening a new issue, thanks!
