### ISSUE TITLE
CosmosDB - Allow access from Azure Portal 

### ISSUE THREAD

**Issue by stravze** [hashicorp/terraform-provider-azurerm#11965]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform still unable in code to set the option "Allow Access from Azure Portal"

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_account" "cosmos_account" {
     azure_portal_access = true / false
}
```

### References

https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-the-azure-portal
* #0000

**Comment by sinbai** [comment]
Terraform has supported this feature. This is implemented by [`ip_range_filter`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#ip_range_filter) and [`is_virtual_network_filter_enabled`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#is_virtual_network_filter_enabled).

For "Allow access from Azure Portal", the tf config can be like this:
```
resource "azurerm_cosmosdb_account" "cosmos_account" {
     is_virtual_network_filter_enabled = true
     ip_range_filter   = "104.42.195.92,40.76.54.131,52.176.6.30,52.169.50.45,52.187.184.26"
}
```
`References:` https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-the-azure-portal


At the same time, support "Accept connections from within public Azure datacenters", then add ipAddress "0.0.0.0" to the script, for example:
```
resource "azurerm_cosmosdb_account" "cosmos_account" {
     is_virtual_network_filter_enabled = true
     ip_range_filter   = "104.42.195.92,40.76.54.131,52.176.6.30,52.169.50.45,52.187.184.26,0.0.0.0"
}
```

 `References:` https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-global-azure-datacenters-or-other-sources-within-azure

**Comment by iMichka** [comment]
So the idea is to hard-code the IP adresses?
0.0.0.0 is fine I guess, but the others might change (it's unlickely, but that kind of things happens sometimes).

But at least we have a workaround.

I think it might be interesting to improve the documentation of terraform with an example. Maybe as a note under https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#is_virtual_network_filter_enabled

I guess that it should just be editing this document to regenerate the docs? https://github.com/hashicorp/terraform-provider-azurerm/blob/ce649d383edcc9a5c5789a02a1814132db907e4c/website/docs/r/cosmosdb_account.html.markdown

**Comment by sinbai** [comment]
From what I know Terraform is not another version of the portal, it provides `ip_range_filter` to support IP access control, not limited to the corresponding functions listed on the portal of "Allow access from Azure portal" and "Accept connections from public Azure data centers" . It can also be your current public IP address, virtual machine public IP address, etc. In other words, this IP/IP range list is controlled by the user, not terraform.

**Comment by mybayern1974** [comment]
@stravze @iMichka by digesting all contexts here, I may vote for what sinbai suggested that encapsulating this metric as a single property say `allow_portal_access`, as what you've identified, would also be a maintenance cost for Terraform since that needs Terraform to keep an eye to changes of required IP (adding example belonging to this kind of cost). As for the reason of why portal can provide that "elegant" way, I assume it's because it's the same Azure engineering team who implement the backend service and the portal so they can control overall magics. 

In the meantime, @sinbai , @iMichka  given we have identified this solution, it would be great if any one of you could kindly contribute a doc PR introducing this method. I suggest the content of that doc is not expected to put down detail IP range (sine it needs to be maintained) but a high level introduction with navigating users to the right MS docs link.

With all above, is everyone here ok if we close this issue?

**Comment by iMichka** [comment]
I opened a pull request: #14552
