### ISSUE TITLE
Terraform plan fails when VM is offline

### ISSUE THREAD

**Issue by FarshadHadei** [hashicorp/terraform-provider-azurerm#12158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Debug Output
Error: reading Sql Virtual Machine (Sql Virtual Machine Name "xxxxxxx" / Resource Group "xxxxxxx"): sqlvirtualmachine.SQLVirtualMachinesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="VmNotRunning" Message="The VM: /subscriptions/xxxxx/resourceGroups/xxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxxx is not in running state."

### Expected Behaviour

When we have bunch of VMs, we should be able to turn some off if we don't need them to save on costs.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by eissko** [comment]
One year left and no move here. This is problem is related to Microsoft.SqlVirtualMachine/sqlVirtualMachines which specification is over here - https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/{sqlVirtualMachineName}?api-version=2021-11-01-preview.

Basically, if the VM is stopped the response on GET request is 
```json
{
  "error": {
    "code": "VmNotRunning",
    "message": "The VM: <resource id> is not in running state."
  }
}
```
Still I believe this could be handled better in the provider itself instead of waiting for some API change which usually takes in years.

**Comment by tombuildsstuff** [comment]
@eissko this is by design in the API, since "SQL Virtual Machines" are essentially just a wrapper for VM Extensions - rather than something Terraform necessarily has direct control/permissions over unfortunately.

As such unfortunately this isn't something we can fix in the Provider since this error message is coming from the API - so you'd need to [open an issue on the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs) where someone from the Service Team should be able to take a look.

Thanks!
