### ISSUE TITLE
Importing resource fails with Invalid index error

### ISSUE THREAD

**Issue by michaelelleby** [hashicorp/terraform-provider-azurerm#12296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.64.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_private_endpoint`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
locals {
  is_premium = var.sku == "Premium" ? true : false
}

resource "azurerm_redis_cache" "redis" {
  name                          = var.name
  location                      = var.resource_group.location
  resource_group_name           = var.resource_group.name
  capacity                      = var.capacity
  family                        = local.is_premium ? "P" : "C"
  sku_name                      = local.is_premium ? "Premium" : "Standard"
  enable_non_ssl_port           = false
  minimum_tls_version           = "1.2"
  subnet_id                     = local.is_premium ? azurerm_subnet.redis[0].id : null
  public_network_access_enabled = false

  patch_schedule {
    day_of_week    = var.patch_day
    start_hour_utc = var.patch_start_hour
  }
}


resource "azurerm_private_endpoint" "redis" {
  count = local.is_premium ? 0 : 1

  name                = "privateendpoint-${azurerm_redis_cache.redis.name}"
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name
  subnet_id           = var.private_endpoint_subnet_id

  private_service_connection {
    name                           = "connection-${azurerm_redis_cache.redis.name}"
    is_manual_connection           = false
    private_connection_resource_id = azurerm_redis_cache.redis.id
    subresource_names              = ["redisCache"]
  }
}

output "ipaddress" {
  value = local.is_premium ? azurerm_redis_cache.redis.hostname : azurerm_private_endpoint.redis[0].private_service_connection[0].private_ip_address
}
```

### Expected Behaviour

Terraform should have imported the diagnostic settings.

### Actual Behaviour

```
module.database.azurerm_monitor_diagnostic_setting.logs: Importing from ID "/subscriptions/<id>/resourcegroups/<rg>/providers/microsoft.dbforpostgresql/servers/<server>\\|logs"...
module.database.azurerm_monitor_diagnostic_setting.logs: Import prepared!
  Prepared azurerm_monitor_diagnostic_setting for import
module.database.azurerm_monitor_diagnostic_setting.logs: Refreshing state... [id=/subscriptions/<id>/resourcegroups/<rg>/providers/microsoft.dbforpostgresql/servers/<server>\|logs]
╷
│ Error: Invalid index
│ 
│   on ../terraform-modules/redis/output.tf line 2, in output "ipaddress":
│    2:   value = local.is_premium ? azurerm_redis_cache.redis.hostname : azurerm_private_endpoint.redis[0].private_service_connection.0.private_ip_address
│     ├────────────────
│     │ azurerm_private_endpoint.redis is empty tuple
│ 
│ The given key does not identify an element in this collection value.

```

### Steps to Reproduce

1. ` terraform import azurerm_monitor_diagnostic_setting.log "/subscriptions/<id>/resourcegroups/<rg>/providers/microsoft.dbforpostgresql/servers/<server>\|logs"`

### References

* #0000

**Comment by michaelelleby** [comment]
A workaround for this bug is to use azurerm_private_endpoint_connection as a data source, as the example https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/private_endpoint_connection in documentation shows.

**Comment by BigFrog-coding** [comment]
I am seeing similar issue.  When importing azurerm_linux_web_app apps, after I import the first app the second one fails with index error: The given key does not identify an element in this collection value.


terraform import 'module.projects.module.name.module.primary_linux_webapp.azurerm_linux_web_app.app[\"resourcename\"]' /subscriptions/subid/resourceGroups/RG/providers/Microsoft.Web/sites/resourcename
var.environment
  Enter a value: UAT

module.projects.module.name.module.primary_linux_webapp.azurerm_linux_web_app.app["resourcename"]: Importing from ID "/subscriptions/subid/resourceGroups/RG/providers/Microsoft.Web/sites/resourcename"...
module.projects.module.name.module.primary_linux_webapp.azurerm_linux_web_app.app["resourcename"]: Import prepared!
  Prepared azurerm_linux_web_app for import
module.projects.module.name.module.primary_linux_webapp.azurerm_linux_web_app.app["resourcename"]: Refreshing state... [id=/subscriptions/subid/resourceGroups/RG/providers/Microsoft.Web/sites/resourcename]
╷
│ Error: Invalid index
│
│   on projects\name\locals.tf line 172, in locals:
│  172:               module.primary_linux_webapp.app_service_data[upper("app-${local.project}${var.environment}-${local.location_map[local.location["primary"]]}-api")].default_hostname
│     ├────────────────
│     │ local.location["primary"] is "westus2"
│     │ local.location_map is object with 6 attributes
│     │ local.project is "name"
│     │ module.primary_linux_webapp.app_service_data is object with 1 attribute "resourcename"
│     │ var.environment is "UAT"
│
│ The given key does not identify an element in this collection value.

projects\name\locals.tf line 172, in locals: = 
            fqdns = [              module.primary_linux_webapp.app_service_data[upper("app-${local.project}${var.environment}-${local.location_map[local.location["primary"]]}-api")].default_hostname
            ]


The collection of course doesn't have both sites since I have to import them one at a time.  I was able to work around by commenting out the line that uses the index in locals, but now the FQDN values are missing and the TF plan is showing it will get updated in place and will remove the FQDN.  This is impactful, so we need to be able to import regardless of current index.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
