### ISSUE TITLE
Support for default port allocation within azurerm_lb_outbound_rule

### ISSUE THREAD

**Issue by lukebrogan** [hashicorp/terraform-provider-azurerm#12328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a limitation in the azurerm_lb_outbound_rule module where you can only specify allocated_outbound_ports. It would be helpful if there was an argument to allow 'Use the default number of outbound ports'. 

### New or Affected Resource(s)

* azurerm_azurerm_lb_outbound_rule

### Potential Terraform Configuration

enable_default_outbound_ports boolean 

```hcl
resource "azurerm_lb_outbound_rule" "test" {
  resource_group_name     = azurerm_resource_group.test.name
  loadbalancer_id         = azurerm_lb.test-lb.id
  name                    = "test-outbound"
  protocol                = "All"
  enable_tcp_reset        = true
  backend_address_pool_id = azurerm_lb_backend_address_pool.test-backend-pool.id
```

**Comment by tombuildsstuff** [comment]
hey @lukebrogan 

Thanks for opening this issue.

Would you be able to clarify your feature request, by definition the ports used by Load Balancer Rules depend on the associated configuration - so I'm wondering if your requesting that we pull this information from the Backend Address Pool? If so, this would mean that we're unable to track diff's to this field (since it's not user configurable and would be updated mid-run, once the Backend Address Pool has updated, rather than being detectable at the start of the run) - so we'd need the ports mapped as a regular field as today, unfortunately.

Thanks!

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.
