### ISSUE TITLE
Expand support for azurerm_purview_account

### ISSUE THREAD

**Issue by smitp11** [hashicorp/terraform-provider-azurerm#12334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to expand the capabilities to provision azure purview accounts with terraform
https://azure.microsoft.com/en-us/services/purview/

to include the `Create Purview Account` > `Configuration` >`Managed Resources` > `Managed Resource Group Name` as an argument on the [azurerm_purview_account](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/purview_account) template.

### New or Affected Resource(s)

* azurerm_purview_account

### Potential Terraform Configuration

```hcl
resource "azurerm_purview_account" "example" {
  name                        = "example"
  resource_group_name         = azurerm_resource_group.example.name
  location                    = azurerm_resource_group.example.location
  sku_name                    = "Standard_4"
  managed_resource_group_name = azurerm_resource_group.xxxxxxxxx.name
}
```

### References

* #0000

**Comment by mosharief** [comment]
I also want to prioritize this above request for including managed resource group name as an argument.

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. I see that latest swagger in the API version that we're using supports this, however, azure-sdk-for-go doesn't yet (at least not the version we're on). As soon as SDK is released that supports this property, we'll be able to implement this in provider.

// cc @ArcturusZhang 55.3 doesn't seem to include this yet, would this be coming in the next release?

**Comment by ArcturusZhang** [comment]
@favoretti please let me to communicate with the corresponding service team to see if it is ready for release

**Comment by gerardwolf** [comment]
Looks like the GA API is now available:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/purview/resource-manager/Microsoft.Purview/stable/2021-07-01/purview.json

**Comment by jdelforno** [comment]
I just went snooping through the go SDK and came across this; https://pkg.go.dev/github.com/AZURE/azure-sdk-for-go/profiles/latest/purview/mgmt/purview

Does this indicate that the go-sdk has been updated and that we could potentially see an update against the provider to see it implemented?

**Comment by tombuildsstuff** [comment]
Taking a look through here it appears that the [`managed_resource_group_name` field being requested in this issue is supported by the Purview Account resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/purview_account#managed_resource_group_name) and as such I'm going to close this issue for the moment - however if you're looking for additional fields/support would you mind opening a new issue so that we can track those enhancements specifically.

---

@jdelforno FWIW we no longer use `Azure/azure-sdk-for-go` - but instead use `hashicorp/go-azure-sdk` - which supports the newer API version (`2021-12-01`) needed for this feature, which the Provider is already using (meaning that the `sdk/not-yet-supported` label is now outdated).
