### ISSUE TITLE
Data Source: azurerm_api_management_group should have name as an attribute

### ISSUE THREAD

**Issue by pucciniplagiarist** [hashicorp/terraform-provider-azurerm#12368]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.12.31

### Affected Resource(s)

* Data Source:  `azurerm_api_management_group`

### Expected Behaviour

This data source should have a name attribute as other resource depend on name rather than id for example  `azurerm_api_management_product_group`

### Actual Behaviour

Have to hard code names of groups

**Comment by xiaxyi** [comment]
Hi @pucciniplagiarist , I tested the data source ```azurerm_api_management_group``` and turns out there is a name attribute which can be referred by others. below is the same and the output:
data "azurerm_api_management_group" "example" {
  name                = "Developers"
  api_management_name = "testname"
  resource_group_name = "testrg-name"
}
output "group_name" {
  **value       = data.azurerm_api_management_group.example.name**
  description = "api management group name"
}

output:
PS D:\test-tf\testAPIManagementGroup\dataSource> terraform012 apply --auto-approve=true
data.azurerm_api_management_group.example: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

**group_name = developers**

Terraform version:
PS D:\test-tf\testAPIManagementGroup\dataSource> terraform012 version
Terraform v0.12.31
+ provider.azurerm v2.81.0

Can you share more details about your user case and the provider version? thx

**Comment by mybayern1974** [comment]
@pucciniplagiarist I'm closing this issue since per comment above this feature should have already been supported in latest AzureRM provider versions. While fee free to suggest to reopen this issue if you believe your question has not been resolved.
