### ISSUE TITLE
Azure Service bus azurerm_servicebus_queue_authorization_rule throws a provider error.

### ISSUE THREAD

**Issue by dilipdesingaon** [hashicorp/terraform-provider-azurerm#12444]
When i tried to run terraform apply for Azure Service bus azurerm_servicebus_queue_authorization_rule , terraform apply throws the following error. 

Terraform Apply 

```hcl 

Error: Provider produced inconsistent result after apply

When applying changes to
module.service-bus.azurerm_servicebus_queue_authorization_rule.reader["auth_rule_sender_1"],
provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own

issue tracker.

```

### Affected Resource: 

azurerm_servicebus_queue_authorization_rule 

> However terraform plan looks perfect.

> I also tried terraform destroy and apply few times and still the same error. 
> Deleted the terraform state-file and crated a new state file and still the same error. 

I have tried all the latest provider and the latest terraform versions but the issue is still the same. 

Some of the provider and the terraform vesions i have tried as below. 

1. v0.14.5 and  v2.57.0
2. v0.15.0 and v2.57.0
3. v0.15.0 and  2.58.0 
Also i have tried few other combinations but it didn't seems to be working. 

Any suggestions will be really helpful.

**Comment by apparentlymart** [comment]
Hi @dilipdesingaon,

For this sort of problem, where the problem is reported in the provider but you think it might actually be in Terraform Core, it's important to include the full debug log as mentioned in [our bug template](https://raw.githubusercontent.com/hashicorp/terraform/main/.github/ISSUE_TEMPLATE/bug_report.md), because only with those details can we see exactly where this inconsistent value originated.

Would you please follow the instructions under the "Debug Output" heading in the template and share the result via [GitHub Gist](https://gist.github.com/)? Thanks!

**Comment by dilipdesingaon** [comment]
Hello team, 
Is there any updates or follow-up on this issue?

**Comment by catriona-m** [comment]
Hi @dilipdesingaon thanks for opening this. Would it be possible to provide the config that led to this error so we can take a look at reproducing it? Thank you!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
