### ISSUE TITLE
Add threshold_type "Forecasted" to azurerm_consumption_budget_

### ISSUE THREAD

**Issue by thecomalley** [hashicorp/terraform-provider-azurerm#12530]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add option for Forecasted cost alerts

### New or Affected Resource(s)

- azurerm_consumption_budget_subscription
- azurerm_consumption_budget_resource_group

### Potential Terraform Configuration

```hcl
resource "azurerm_consumption_budget_subscription" "example" {
  name            = "example"
  subscription_id = data.azurerm_subscription.current.subscription_id

  amount     = 1000
  time_grain = "Monthly"

  time_period {
    start_date = "2022-06-01T00:00:00Z"
    end_date   = "2022-07-01T00:00:00Z"
  }

  notification {
    enabled   = false
    threshold = 100.0
    operator  = "GreaterThan"

    threshold_type = "Forecasted"

    contact_emails = [
      "foo@example.com",
      "bar@example.com",
    ]
  }
}
```

### References
Blog post announcing the feature
- https://azure.microsoft.com/en-au/blog/prevent-exceeding-azure-budget-with-forecasted-cost-alerts/

Rest API docs, ThresholdType is missing "Forecasted" as option in docs but appears to work
- https://docs.microsoft.com/en-us/rest/api/consumption/budgets/get#thresholdtype

**Comment by stephybun** [comment]
Hi @thecomalley, thank you for this request. There are a few things that need to happen before this can be implemented fully. Creation of a budget with `threshold_type` Forecasted is possible but updating the value to Actual or back again doesn't yield the expected behaviour. In order to update the values we need to retrieve and send the eTag for the resource in question. Unfortunately this field is not supported by the latest version of the consumption API in the azure sdk. It will need to be added on their side before we can proceed, a request for this has been raised https://github.com/Azure/azure-sdk-for-go/issues/15303
