### ISSUE TITLE
Error: parsing Resource ID "/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.Network/frontdoors/xxxxxxxx": ID was missing the frontDoors

### ISSUE THREAD

**Issue by Poil** [hashicorp/terraform-provider-azurerm#12548]
**Terraform (and AzureRM Provider) Version**

```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/azurerm v2.60.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.20.0
+ provider registry.terraform.io/terraform-providers/mysql v1.9.0
```

**Affected Resource(s)**

* `azurerm_frontdoor`

**Expected Behaviour**

* Import existing FrontDoor

**Actual Behaviour**

* If using the real resource ID
```
Error: parsing Resource ID "/subscriptions/xxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/frontdoors/xxxxx": ID was missing the `frontDoors` element
```

* If changing the resource ID to "/subscriptions/xxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/frontDoors/xxxxx"
```
Error: Cannot import non-existent remote object` if using `frontDoors/xxx
```

* Steps to Reproduce
```
 terraform import "azurerm_frontdoor.frontdoor" "/subscriptions/xxxxxxxx/resourceGroups/xxxx/providers/Microsoft.Network/frontdoors/xxxx"
 terraform import "azurerm_frontdoor.frontdoor" "/subscriptions/xxxxxxxx/resourceGroups/xxxx/providers/Microsoft.Network/frontDoors/xxxx"
```

Best regards

**Comment by tombuildsstuff** [comment]
hi @Poil 

Each Terraform resource within the Azure Provider has an `import` section available highlighting the casing we're expecting here - in this case [this is available on here on the `azurerm_frontdoor` resource documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor#import). Since Terraform is expecting this to be in a specific format, namely containing the segment `frontDoors` - Terraform is correctly raising the error here that this segment is missing when specifying this in a different casing.

As you've mentioned that Terraform is unable to find this when using the correct ID format, presuming your authenticating using the Azure CLI, I believe this is down to the default Subscription ID of the Azure CLI being different to what your specifying here - as such I'd recommend double-checking that this is set specifically (or defaulting it explicitly in the Provider block).

However since this appears to be a configuration issue rather than a bug in Terraform, whilst I'd like to thank you for opening this issue I'm going to close this for the moment.

Thanks!
