### ISSUE TITLE
Support for Azure Video Analyzer

### ISSUE THREAD

**Issue by EliiseS** [hashicorp/terraform-provider-azurerm#12603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Azure Video Analyzer](https://azure.microsoft.com/en-us/products/video-analyzer/) is a new preview Azure resource, meant to be a replace for the Live Video Analytics. It's encouraged to migrate from LVA to AVA, but in order to do so for terraform setups new resources are needed.

Looking at the [Azure API endpoint](https://docs.microsoft.com/en-us/rest/api/videoanalyzer/video-analyzers/create-or-update#storageaccount) and [ARM template found sample for deploying AVA](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/get-started-detect-motion-emit-events) and specifically the [video-analyzer.deploy.json](https://raw.githubusercontent.com/Azure/video-analyzer/main/setup/video-analyzer.deploy.json) referenced there, there are two potential terraform resources to be created from `Microsoft.Media/videoAnalyzers` and `Microsoft.Media/videoAnalyzers/edgeModules`

### New or Affected Resource(s)

* azurerm_video_analyzer
* azurerm_video_analyzer_edge_module

### Potential Terraform Configuration

Inspired by: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/media_services_account

```hcl
resource "azurerm_video_analyzer" "example" {
  name                = "example_video_analyzer"
  resource_group_name = azurerm_resource_group.example.name
  location            = local.location

  storage_account {
    id         = azurerm_storage_account.example.id
    is_primary = true # The API doesn't state how to set a storage account to be primary, only that the primary storage account must of a certain type
  }
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_video_analyzer_edge_module" "example" {
  name                = "example_edge_module"
  resource_group_name = azurerm_resource_group.example.name
  video_analyzer_name = azurerm_video_analyzer.example.name
}
```

#### Example Argument Reference `azurerm_video_analyzer`

The following arguments are supported:

* `name` - (Required) Specifies the name of the Media Services Account. Changing this forces a new resource to be created.

* `resource_group_name` - (Required) The name of the resource group in which to create the Media Services Account. Changing this forces a new resource to be created.

* `location` - (Required) Specifies the supported Azure location where the resource exists. Changing this forces a new resource to be created.

* `storage_account` - (Required) One or more `storage_account` blocks as defined below.

* `identity` - (Optional) An `identity` block is documented below.

* `storage_authentication_type` - (Optional) Specifies the storage authentication type. 
Possible value is  `ManagedIdentity` or `System`.

* `tags` - (Optional) A mapping of tags assigned to the resource.

---

A `storage_account` block supports the following:

* `id` - (Required) Specifies the ID of the Storage Account that will be associated with the Media Services instance.

* `is_primary` - (Required) Specifies whether the storage account should be the primary account or not. Defaults to `false`.

~> **NOTE:** Whilst multiple `storage_account` blocks can be specified - one of them must be set to the primary

---

A `identity` block supports the following:

* `type` - (Required) Specifies the type of Managed Service Identity that should be configured on this Media Services Account. Possible value is  `SystemAssigned`. 

---

### References

* Azure API link: <https://docs.microsoft.com/en-us/rest/api/videoanalyzer/>
* Video analyzer in the go sdk: <https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/videoanalyzer/mgmt/2021-05-01-preview/videoanalyzer>

**Comment by EliiseS** [comment]
I've been doing a bit of digging and would like to try to pick up the work @tombuildsstuff @manicminer

- I'll need to add the video analyzer into the vendor folder
- Would the media service resource be an okay point to start?
- When it comes to the resources, is the convention to go with two resources or make the `azurerm_video_analyzer_edge_module` a property of the `azurerm_video_analyzer`?

**Comment by jackofallops** [comment]
Hi @EliiseS - by "add the video analyser to the vendor folder" do you mean include the Azure SDK, or an actual 3rd party software package?  (former is fine, the latter is probably not)

The vendor folder is managed by Go, rather than by hand.  To include an API that is not currently present, you only need to make reference to it in an import, and if it's already part of the Azure SDK version in use (in `go.mod`), it will be added to the `vendor` folder for you by running `go mod tidy && go mod vendor`.  (usually a good way to do this is by creating the client elements for the API you're going to use).

I'm going to throw out a couple big caveats here, I've not looked at that preview API or service, so I can't advise on how suitable it may or may not be for the provider. Previews have, on occasion, been somewhat problematic and highly subject to change without prior warning. Your work may be undone before you've even finished.

It's a completely new Service, which carries quite a bit of overhead in terms of set up within the provider. Other resources are a good place to start for guidance on structure, whether media specifically is a good match, that's difficult to say.  If you do decide to undertake this, I'd recommend joining the slack referenced in the project README, as the community there is very helpful and the maintainers _try_ to swing by as often as we can.

I hope that helps?

**Comment by EliiseS** [comment]
Hey @jackofallops,

Thanks for replying and for highlighting concerns about the stability of the API I'll be sure to double check with the product group about near term plans for the API. We've also already spoken with them and they said they'd be interested in us doing this.

And yeah, by adding to the vendor folder I meant importing and vendoring what I need from here: https://github.com/Azure/azure-sdk-for-go/tree/main/services/preview/videoanalyzer/mgmt/2021-05-01-preview/videoanalyzer

I'll definitely join the slack channel and I'm aware that I'll probably run into a wide range of issues *smile* I've worked on other terraform providers before, so I'm hopeful I'll be able to get something useful done.
