### ISSUE TITLE
ineffective virtual_network_rules for azurerm_cognitive_account

### ISSUE THREAD

**Issue by mikemowgli** [hashicorp/terraform-provider-azurerm#12626]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.5
azurerm v2.68.0

### Affected Resource(s)

* `azurerm_cognitive_account`

### Terraform Configuration Files

Both 
```hcl
resource "azurerm_cognitive_account" "tamers_cognitive_translator" {
  name                  = "example"
  location              = var.azure_region
  resource_group_name   = local.main_rg_name
  kind                  = "TextTranslation"
  sku_name              = "F0"
  custom_subdomain_name = local.main_rg_name
  network_acls {
    default_action = "Deny"
    virtual_network_subnet_ids = [
      module.data_sources.databricks_public_subnet_id,
      module.data_sources.databricks_private_subnet_id,
      data.azurerm_subnet.databricks_sandbox_public_subnet.id,
      data.azurerm_subnet.databricks_sandbox_private_subnet.id
    ]
  }
}
```
and
```
resource "azurerm_cognitive_account" "tamers_cognitive_translator" {
  name                  = "example"
  location              = var.azure_region
  resource_group_name   = local.main_rg_name
  kind                  = "TextTranslation"
  sku_name              = "F0"
  custom_subdomain_name = local.main_rg_name
  network_acls {
    default_action = "Deny"
    virtual_network_rules = [
      {
        ignore_missing_vnet_service_endpoint = false
        subnet_id = module.data_sources.databricks_public_subnet_id
      },
      {
        ignore_missing_vnet_service_endpoint = false
        subnet_id = module.data_sources.databricks_private_subnet_id
      },
      {
        ignore_missing_vnet_service_endpoint = false
        subnet_id = data.azurerm_subnet.databricks_sandbox_public_subnet.id
      },
      {
        ignore_missing_vnet_service_endpoint = false
        subnet_id = data.azurerm_subnet.databricks_sandbox_private_subnet.id
      },      
    ]
  }
}
```
tell me that the whole `virtual_network_rules` block will have `null` value when I `terraform plan`

### Expected Behaviour

The subnet ids listed in the config should not be removed when applying.

**Comment by manicminer** [comment]
Hi @mikemowgli, thanks for reporting this. Do you see the same behavior if you hardcode the subnet IDs in your Terraform config, and can you see the correct subnet IDs if you create output variables using the values from your config snippets above? Thanks!

**Comment by mikemowgli** [comment]
@manicminer:
- yes, whatever the input (even when hardcoding) in a `virtual_network_rules` or `virtual_network_subnet_ids` block, Terraform tells me the whole block will be removed.
- yes, the subnet IDs are correct when I output them.

**Comment by jacob-egdorf** [comment]
I ran into this same issue while developing a Sentinel policy, so I thought I would add some additional information I found in case it is of any help.

I am running Terraform `plan` on the following Terraform code (Terraform version 0.12.31):

```
provider "azurerm" {
  features {}
  version = "2.68"
}

resource "azurerm_resource_group" "rg" {
  location = var.location
  name     = "example-rg"
}

resource "azurerm_cognitive_account" "example" {
  name                = "example-account"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  kind                = "Face"
  sku_name = "S0"
  custom_subdomain_name = "example"

  network_acls {
    default_action = "Deny"
    virtual_network_rules {
      subnet_id = var.example_subnet_id
    }
  }
}
```

I am then using Sentinel to print out the `network_acls` block of this `azurerm_cognitive_account` resource upon running Terraform `plan`:

![2 68_print_message](https://user-images.githubusercontent.com/81453524/126392939-68f79246-5047-4fb0-8d87-4421189cbb62.png)

I noticed that the `virtual_network_rules` block is not listed in the `network_acls` block, as if Terraform is not expecting this argument. Indeed, even though I have not specified `ip_rules` in my Terraform code, the `ip_rules` argument has the value `null`, since Terraform is expecting this argument as a property of the resource within the `network_acls` block. Thus, it seems `virtual_network_rules` is `undefined` regardless of what is provided in Terraform code.

**Comment by frolovandreydanone** [comment]
Hello, we are also facing this issue in 2.77.0 and 2.78.0 version of provider.
So far we end up using deprecated virtual_network_subnet_ids with list of subnet_ids + setting up at least one IP address in ip_rules. Otherwise, terraform was failing to obtain proper endpoint_id (it was giving a public one).

**Comment by frolovandreydanone** [comment]
> > Hello, we are also facing this issue in 2.77.0 and 2.78.0 version of provider. So far we end up using deprecated virtual_network_subnet_ids with list of subnet_ids + setting up at least one IP address in ip_rules. Otherwise, terraform was failing to obtain proper endpoint_id (it was giving a public one).
> 
> Can you provide a code snippet? I may need to implement this also

```
  network_acls {
    default_action             = "Deny"
    ip_rules                   = each.value.ip_rules
    virtual_network_subnet_ids = each.value.subnet_ids
  }
```

**Comment by gaya3kris** [comment]
I am having the same issue. Any way to resolve this issue?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
