### ISSUE TITLE
Support for [thing]

### ISSUE THREAD

**Issue by vikram111** [hashicorp/terraform-provider-azurerm#12773]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Documentation update to provide data types and examples of returned attributes. Example here:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api#is_online

### New or Affected Resource(s)
Have seen this in the documentation for Azure resources. 

* azurerm_api_management_api
* azurerm_api_management
### Potential Terraform Configuration

NA

* #0000

**Comment by tombuildsstuff** [comment]
hi @vikram111 

Thanks for opening this issue.

Whilst we'd like to provide the data types for fields - in practice this isn't something we're able to do in the short-term, since this needs to be done consistently across the entire provider at once to be useful.

One of the longer-term projects in flight in the provider is to look at the documentation and work out how we can automate more of that, whilst being able to expose sufficient information about the behaviours of the Azure API. Whilst there's some functionality available within the Terraform Plugin SDK today, unfortunately these hooks are insufficient to be able to generate  of documentation we're aiming for - and so will need to be enhanced to support this (which would enable exposing the types).

Ultimately this is something that we want to enable in the long-term, but since this would need to be added across the entire provider at once (and that's blocked on the changed mentioned above) - in practice this isn't something we're going to be able to add in the near-future. As such whilst I'd like to thank you for opening this issue, I'm going to close this for the moment - since this'll be addressed when the documentation becomes more automated.

Thanks!
