### ISSUE TITLE
AKS cluster with PSP enabled should not be blocked

### ISSUE THREAD

**Issue by sozercan** [hashicorp/terraform-provider-azurerm#12814]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Expect to see AKS cluster created with PSP enabled

### Actual Behaviour

AKS cluster has a client side check to block PSP creation.
https://github.com/terraform-providers/terraform-provider-azurerm/blob/e4ff2ccc529c7c15317987d667001b51ea42fd8c/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L891

AKS PSP deprecation has been removed/delayed until removal of PSP until K8s v1.25
https://docs.microsoft.com/en-us/azure/aks/use-pod-security-policies

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @sozercan 

Thanks for opening this issue.

Unfortunately we have no plans to reintroduce support for Pod Security Policies since they're end-of-life (and have been marked as such multiple times by AKS) and as such the field is deprecated within Terraform.

Whilst it's possible that we could look to re-introduce support for this field and immediately deprecate it - that just means we'd be setting users up for a breaking change in the future when we re-remove the field - as such since we've already removed support for this functionality based on one of the original deadlines for this from the AKS Team. Whilst I can appreciate there's demand for this functionality, since the AKS Team have committed to removing this functionality we have no plans to re-introduce support for Pod Security Policies to the `azurerm_kubernetes_cluster` resource.

In this instance it's on the AKS Team to announce a consistent deprecation policy here, since both customers and downstream tooling (including Terraform) and [other integrators](https://github.com/azure-deprecation/dashboard) need to account for this within their codebases. That said when a replacement for Pod Security Policies is available (which is why this was deprecated in the first place) we can look to add support for this which should solve that issue.

Thanks!

**Comment by katbyte** [comment]
reopening as the sunset date for the property has been pushed waaaaay back

**Comment by stephybun** [comment]
Closing since [PSP is deprecated as of 01-06-2023](https://learn.microsoft.com/en-us/azure/aks/use-pod-security-policies).
