### ISSUE TITLE
Support for SQL user management

### ISSUE THREAD

**Issue by stalmok** [hashicorp/terraform-provider-azurerm#12959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There's no way to manage SQL users on the `azurerm_sql_database` resource. 

### New or Affected Resource(s)

* update `azurerm_sql_database` or add a new `azurerm_sql_user` or similar.

### Potential Terraform Configuration

```hcl
resource "azurerm_sql_user" "users" {
  name        = "azure-service-principal-name"
  instance    = azurerm_sql_database.main.id
  password    = "xxx"
  roles       = [ "db_datareader", "db_datawriter" ]
  permissions = [ "UNMASK", "ALTER ANY MASK" ]
}
```

**Comment by tombuildsstuff** [comment]
hi @stalmok 

As far as I'm aware there's no API for managing users directly within Azure SQL Database exposed by Azure - but you can manage [AzureAD Administrators for a SQL Database within Terraform](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_active_directory_administrator).

As such I believe this should be possible using [the SQL Active Directory Administrator resource mentioned above](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_active_directory_administrator) or by adding these [directly within SQL using a MSSQL Terraform Provider](https://registry.terraform.io/search/providers?q=mssql). However since Azure doesn't expose an API for managing Users within a SQL Database directly at this time (or at least, non-AzureAD Administrators) - whilst I'd like to thank you for opening this issue, I'm going to close this issue for the moment.

Thanks!
