### ISSUE TITLE
Error after azurerm upgrade from 2.14.0 to 2.37.0

### ISSUE THREAD

**Issue by ameet-nandihal** [hashicorp/terraform-provider-azurerm#12973]
Hi,

it was all working fine with azurerm provider version 2.14.0 but we had to upgrade to 2.37.0 for some reason and all of sudden we started getting below error during terraform plan. 

Please let me know if we can have any fix for this.

Versions:
terraform: 0.14.7
azurerm provider: 2.37.0
Kubernetes provider: 1.12

Error: Get "http://localhost/api/v1/namespaces/notifications": dial tcp 127.0.0.1:80: connect: connection refused
Error: Get "http://localhost/api/v1/namespaces/account": dial tcp 127.0.0.1:80: connect: connection refused

**Comment by tombuildsstuff** [comment]
hi @ameet-nandihal 

This looks like an issue with the Kubernetes provider where the port-forwarding has been disabled and so Terraform can't access the Kubernetes API to plan.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
