### ISSUE TITLE
Creation of the key vault failed with Code="SoftDeletedVaultDoesNotExist"

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-azurerm#12972]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
❯ terraform -v
Terraform v0.14.10
azurerm  = "2.40.0"

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "kv" {
  location                   = var.location
  name                       = format("kv-${local.short_location}-${var.application}-${var.stage}")
  resource_group_name        = var.rg_name
  sku_name                   = "standard"
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  soft_delete_enabled        = true
  soft_delete_retention_days = 90
  purge_protection_enabled   = true

  network_acls {
    default_action             = "Deny"
    virtual_network_subnet_ids = [module.static_variables.subnet_ids_all_dict[var.stage][var.location].id]
    bypass                     = "AzureServices"
    ip_rules                   = module.static_variables.public_ips_all_list
  }

  tags = merge(
    local.ccoe_tags,
    var.tags
  )
}
```

### Debug Output

Doesn't make any sense in my case

### Panic Output

No panic

### Expected Behaviour

key vault successfully deployed
### Actual Behaviour

```
Error: Error creating Key Vault "kv-dev" (Resource Group "rg-dev"): keyvault.VaultsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SoftDeletedVaultDoesNotExist" Message="A soft deleted vault with the given name does not exist. Ensure that the name for the vault that is being attempted to recover is in a recoverable state. For more information on soft delete please follow this link https://go.microsoft.com/fwlink/?linkid=2149745"

  on main.tf line 27, in resource "azurerm_key_vault" "kv":
  27: resource "azurerm_key_vault" "kv" {
```
### Steps to Reproduce

1. create key vault
2. destroy key vault
3. try to create key vault again

### Important Factoids

Nothing important here

### References
No references

**Comment by tombuildsstuff** [comment]
hi @ghost

Thanks for opening this issue.

Taking a look through here this is a question related to Soft Delete within Key Vault - as such the Key Vault must be purged (which is controllable [via the `features` block in the Provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#features).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
