### ISSUE TITLE
Azure key vault certificate recreate error when purge protection is enabled

### ISSUE THREAD

**Issue by acc0613** [hashicorp/terraform-provider-azurerm#13012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_key_vault_certificate`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Key vault certificate will be recreated (there's an update with validity_in_months so it's forced to be replaced)

### Actual Behaviour

Error: 403 (Forbidden) because purge protection is enabled on the key vault

### Steps to Reproduce

1. Create a key vault certificate resource
2. Update validity in months
3. terraform apply

### References

* #0000

**Comment by LP0101** [comment]
Also facing this issue. When updating the value of a certificate, terraform will try to recreate the cert object rather than just updating its value. This fails if the keyvault has purge-protection enabled.

**Comment by CorrenSoft** [comment]
Are you using "purge_soft_delete_on_destroy=false"? That could send away the error.

I am having a related situation, but instead of getting a 403 error, I got the certificate recreated but without applying the update.
- Plan shows that the certificate is going to be recreated.
- On Apply, the certificate gets destroyed and created (recovered).
- The certificate is having the same data as before.
- Next run, all the process is going to repeat.

**Comment by djsly** [comment]
there seems to be two issues here, 
1. purge_protection prevents the management for the Certificate 
2. Some operation should be done in-place but terraform seems to be forcing a recreate.

**Comment by jrversion** [comment]
I am also experiencing this issue using provider versions 3.7.0 and 3.13.0 when a certificate update in place is performed

Error: purging of Certificate ....: keyvault.BaseClient#PurgeDeletedCertificate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed

The key_vault provider options are:
- recover_soft_deleted_key_vaults = true
- purge_soft_delete_on_destroy = false

Prior to upgrading the provider to 3.0+ this error did not occur.

**Comment by jku-sr** [comment]
When destroying a secret using Provider Azurerm Version 3.14.0 this behavior still occurs

`provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }`

Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: kv-TestKeyVault1;location=eastus"

The secret still gets soft deleted but Terraform Exits with a 1 error code making it look like our CI/CD pipeline failed.

**Comment by utrescu** [comment]
Destroying a secret with `purge_protection_enabled = true` and `purge_soft_delete_on_destroy=false`. 

Example:

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.0"
    }
  }

  required_version = ">= 0.14.9"
}

provider "azurerm" {

  features {
    key_vault {
      recover_soft_deleted_key_vaults = true
      purge_soft_delete_on_destroy    = false
    }
  }
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "rg" {
  name     = "rg-intent"
  location = "West Europe"
}

resource "azurerm_key_vault" "intent" {
  name                        = "intentkeyvault"
  location                    = azurerm_resource_group.rg.location
  resource_group_name         = azurerm_resource_group.rg.name
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = true

  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    secret_permissions = [
      "Set",
      "Get",
      "Delete",
      "Purge",
      "Recover"
    ]
  }
}

resource "azurerm_key_vault_secret" "intent_secret1" {
  name         = "One"
  value        = "1"
  key_vault_id = azurerm_key_vault.intent.id
}

resource "azurerm_key_vault_secret" "intent_secret2" {
  name         = "Two"
  value        = "2"
  key_vault_id = azurerm_key_vault.intent.id
}
```

The first `terraform apply`  works as expected.  

Then I remove `intent_secret2` 

```
terraform apply
```

The plan shows the secret to be destroyed, but ends with:

```log
Error: purging of Secret "Two" (Key Vault "https://intentkeyvault.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: intentkeyvault;location=westeurope"
```

Purges the secret, ignoring `purge_soft_delete_on_destroy  = false`

**Comment by CorrenSoft** [comment]
> The same occurs in destroying a secret with `purge_protection_enabled = true` and `purge_soft_delete_on_destroy=false`.
> 
> Example:
> 
> ```terraform
> terraform {
>   required_providers {
>     azurerm = {
>       source  = "hashicorp/azurerm"
>       version = ">=3.0"
>     }
>   }
> 
>   required_version = ">= 0.14.9"
> }
> 
> provider "azurerm" {
> 
>   features {
>     key_vault {
>       recover_soft_deleted_key_vaults = true
>       purge_soft_delete_on_destroy    = false
>     }
>   }
> }
> 
> data "azurerm_client_config" "current" {}
> 
> resource "azurerm_resource_group" "rg" {
>   name     = "rg-intent"
>   location = "West Europe"
> }
> 
> resource "azurerm_key_vault" "intent" {
>   name                        = "intentkeyvault"
>   location                    = azurerm_resource_group.rg.location
>   resource_group_name         = azurerm_resource_group.rg.name
>   enabled_for_disk_encryption = true
>   tenant_id                   = data.azurerm_client_config.current.tenant_id
>   soft_delete_retention_days  = 7
>   purge_protection_enabled    = true
> 
>   sku_name = "standard"
> 
>   access_policy {
>     tenant_id = data.azurerm_client_config.current.tenant_id
>     object_id = data.azurerm_client_config.current.object_id
> 
>     secret_permissions = [
>       "Set",
>       "Get",
>       "Delete",
>       "Purge",
>       "Recover"
>     ]
>   }
> }
> 
> resource "azurerm_key_vault_secret" "intent_secret1" {
>   name         = "One"
>   value        = "1"
>   key_vault_id = azurerm_key_vault.intent.id
> }
> 
> resource "azurerm_key_vault_secret" "intent_secret2" {
>   name         = "Two"
>   value        = "2"
>   key_vault_id = azurerm_key_vault.intent.id
> }
> ```
> 
> The first `terraform apply` works as expected.
> 
> Then I remove `intent_secret2`
> 
> ```
> terraform apply
> ```
> 
> The plan shows the secret to be destroyed, but ends with:
> 
> ```
> Error: purging of Secret "Two" (Key Vault "https://intentkeyvault.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: intentkeyvault;location=westeurope"
> ```
> 
> Tries to purge the secret, ignoring `purge_soft_delete_on_destroy = false`

Since V3, `purge_soft_delete_on_destroy` only applies to the keyvault, not to the internal content. Try with `purge_soft_deleted_secrets_on_destroy = false`.

[More Info](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#purge_soft_deleted_secrets_on_destroy).
