### ISSUE TITLE
Azurerm web 2.70+ api version not available in us gov

### ISSUE THREAD

**Issue by jrudley** [hashicorp/terraform-provider-azurerm#13018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0 +
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_web
* 

### Expected Behaviour

provision webapp

### Actual Behaviour

Error: Error creating/updating App Service Plan "aspName" (Resource Group "rgName"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'usgovvirginia' and API version '2021-01-15' for type 'serverFarms'. The supported api-versions are '2020-12-01, 2020-10-01, 2020-09-01, 2020-06-01, 2019-08-01, 2018-11-01, 2018-02-01, 2017-08-01, 2016-09-01, 2016-03-01, 2015-08-01, 2015-07-01, 2015-06-01, 2015-05-01, 2015-04-01, 2015-02-01, 2014-11-01, 2014-06-01, 2014-04-01, 2014-04-01-preview'. The supported locations are 'usgoviowa, usdodeast, usgovvirginia, usdodcentral, usgovarizona, usgovtexas'."

### Steps to Reproduce

use latest azurerm or any version 2.70+

1. `terraform apply`

### Important Factoids

Running in Azure gov

### References

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#2700-july-30-2021 introduced change to web api

* #0000

**Comment by tombuildsstuff** [comment]
hi @jrudley 

Unfortunately in this instance this is something which'd need to be fixed by Microsoft rather than the Azure Provider - once an API is available in Azure Public it's supposed to be rolled out to the different Azure Environments within ~3 months - as such this API should be available in Azure Government (even if it's not right now).

Whilst Terraform could look to conditionally support different API versions depending on the environment being used, unfortunately that'd break support for Azure Public where this new functionality is necessary and as such we tend to target Azure Public API's a quarter (or so) after they become available (since at that point these should be available in other Azure Environments, such as China and Germany).

It's possible to workaround this in the interim by pinning to an older version of the Provider until support for this updated API is rolled out in Azure Government - but ultimately this needs Microsoft to deploy those API's within Azure Government, so I'd recommend reaching out to Microsoft Support here who should be able to give a timeframe/update.

Thanks!

**Comment by jrudley** [comment]
Thanks for the quick response.
