### ISSUE TITLE
[kube_dashboard addon] AddonInvalid" Message="Kubernetes Dashboard addon is deprecated for Kubernetes version >= 1.19.0." Target="AddonProfiles.KubeDashboard

### ISSUE THREAD

**Issue by gbmarimuthu** [hashicorp/terraform-provider-azurerm#13119]
AddonInvalid" Message="Kubernetes Dashboard addon is deprecated for Kubernetes version >= 1.19.0." Target="AddonProfiles.KubeDashboard

Please update the documentation.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @gbmarimuthu 

Thanks for opening this issue.

This is an AKS feature which changes depending on the version of Kubernetes being used, as such that information is available on the AKS Documentation site / in the AKS upgrade notes - rather than within the Terraform documentation since there's a lot of functionality that changes depending on the version of Kubernetes being used.

As such whilst I'd like to thank you for opening this issue, since this is specific to AKS rather than the Terraform resource, I'm going to close this for the moment, but you should be able to fix this by removing the `kube_dashboard` block.

Thanks!
