### ISSUE TITLE
Error: Failed to install databricks provider 

### ISSUE THREAD

**Issue by Saikishore031** [hashicorp/terraform-provider-azurerm#13138]
Trying to deploy databricks resource into azure using terraform when i am trying to initialize getting below error.

![image](https://user-images.githubusercontent.com/50044342/130801126-6d0ec67b-bc3f-4622-8407-a256219117eb.png)

C:\Temp\Terraform\Test>terraform init

Initializing the backend…

Initializing provider plugins…

Finding databrickslabs/databricks versions matching “0.3.7”…
Reusing previous version of hashicorp/azurerm from the dependency lock file
Using previously-installed hashicorp/azurerm v2.73.0
Installing databrickslabs/databricks v0.3.7…
╷
│ Error: Failed to install provider
│
│ Error while installing databrickslabs/databricks v0.3.7: archive has incorrect checksum
│ zh:298e63588879abf0dd4c8b5610312ac0644c806d2bda102ee3bcfb7f7eaa13a5 (expected
│ zh:fd2b875e9949371a0fb33c98565d352806ef8b448c8f0198acdae2e541712d5f)
╵
C:\Temp\Terraform\Test>terraform -version
Terraform v1.0.5
on windows_amd64

provider registry.terraform.io/hashicorp/azurerm v2.73.0

**Comment by tombuildsstuff** [comment]
hi @Saikishore031 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
