### ISSUE TITLE
ASEv3 gets replaced when a tag is changed

### ISSUE THREAD

**Issue by larsmaes** [hashicorp/terraform-provider-azurerm#13256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
2.75.0

### Affected Resource(s)

* `azurerm_app_service_environment_v3`

###
Whenever is change a tag on a asev3 resource. Tf will plan a replacement of de ASEv3

**Comment by tombuildsstuff** [comment]
hi @larsmaes 

As mentioned [in this comment](https://github.com/hashicorp/terraform-provider-azurerm/pull/13251#issuecomment-929158113) unfortunately this is a limitation of the Azure API / SDK at this point in time, since the update App Service Environment API call doesn't support updating Tags.

Whilst we'd like to support this functionality within Terraform, unfortunately we can only do this when support for this is available in the Azure API - as such I'd recommend [opening an issue on the Azure Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs) where someone from the App Service Team should be able to take a look.

Thanks!

**Comment by adamyager** [comment]
@tombuildsstuff  Hope all is well. He has a discussion with the App service Product team yesterday on a different topic and this Tag item came up. The suggest the correct pattern is below:

**Comment by adamyager** [comment]
thanks for the reply. This will be good info. I can work directly with the product(or privately connect you with them) if we determine this cannot be done. As of now, they believe this is not a actual issue until we tell them it is.

How was this solved in ASE v2? I think the pattern(and API) is the same

**Comment by jackofallops** [comment]
> How was this solved in ASE v2? I think the pattern(and API) is the same

Both V2 and V3 are `ForceNew` on change for tags, as they use the same API and approach.

FWIW - We've discussed internally and I'm going to be taking a look into possibilities soon.

**Comment by adamyager** [comment]
@jackofallops  thanks for the insights. let me know what you find. I have a contact on the Product team that will intake your analysis.  At this time, they think you can do it with a BeginCreateorUpdate. If that's not possible, I want to provide them that feedback so they can implement an API
