### ISSUE TITLE
Azure KV secret error

### ISSUE THREAD

**Issue by tech7857** [hashicorp/terraform-provider-azurerm#13261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Description

Keyvault with soft delete and purge protection enabled giving below error when running apply after destroying once

error: a resource with the id already exists - to be managed via terraform this resource needs to be imported into the state. Please see the resource documentation for azurerm_key_vault_secret for more information.

affected resources
Azurerm_key_vault

Expected Behaviour

secret should be created/updated without giving any error.

Hi

i am new to this. I create a key vault with soft delete and purge protection enabled having 1 secret.

when i ran it the first time it was created successfully. Then I ran destroy , it was deleted successfully. Now when I tried running apply again, it failed with the above when creating the secret. Seems like because of soft delete and purge protection, terraform restores the previous deleted kv along with secret. KV gets created/ restored successfully but secret creation results in error. I am not able to figure out why it fails, if I am doing something wrong or missing or it is bug.

terraform version:1.0.4
Azure rm provider: 2.72.0

please assist.

thanks

**Comment by tombuildsstuff** [comment]
hi @tech7857 

As per the error message coming back from Terraform here this resource already exists in Azure and needs to be imported into the state:

> a resource with the id already exists - to be managed via terraform this resource needs to be imported into the state. Please see the resource documentation for azurerm_key_vault_secret for more information.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
