### ISSUE TITLE
automatic_channel_upgrade impacting Production

### ISSUE THREAD

**Issue by k7faq** [hashicorp/terraform-provider-azurerm#13447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 0.12.31
* AzureRM Provider version: 2.60 and 2.72

### Terraform Configuration Files

Terraform Plan snip without having specified the setting in our code base:

```hcl
  # module.cluster_1.azurerm_kubernetes_cluster.this will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "this" {
        api_server_authorized_ip_ranges = []
      - automatic_channel_upgrade       = "unspecified" -> null
```

### Description / Feedback

Terraform should have run a clean plan. We have _not_ opted into the preview of this feature for different subscriptions. Now one of two clusters per Subscription are now requiring us to select an Automatic Upgrade Channel. ***WE MUST*** know how to set this to `none`! My employer runs mission critical healthcare services and we cannot afford downtime! We have already seen upgrades cause breaking changes. We _cannot_ afford an untested (in our environment) upgrade to go to Production without first being validated Staging that has previously been tested in Development. 

I am ABSOLUTELY STUNNED that anyone would not allow the option of `none` to be set as a valid option here! [Microsoft Documentation](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel) calls out via the CLI to be able to set this to none. So why does the AzureRM provider for Terraform not? 

***This is already impeding our ability to deploy updates into Production! And we are not even opted into the Preview!***

Please help!

**Comment by tombuildsstuff** [comment]
hi @k7faq

Taking a look through here, unfortunately this appears to be a behavioural change to AKS. As such I'm going to suggest [opening an issue on the AKS Repository](https://github.com/Azure/AKS/issues) where someone from the AKS Team should be able to take a look.

For some background: the AKS API provisions clusters based on the settings in the AKS API at the time of deployment - this varies per region (as the API is deployed _per-region_). Once the deployment is complete, these clusters then become long-lived, with those settings embedded.

Unfortunately, the reality of this approach is that an AKS Cluster provisioned today and one provisioned next month through the exact same payload (using Terraform, ARM Templates, the Portal etc.) _may_ have behavioural differences by design due to the way the AKS Service works. 

Furthermore the AKS API doesn't necessarily return a default value for settings used when provisioning the cluster. For example if a cluster is provisioned with a default value for a setting, and that value later changes - since the default value was used, the AKS API doesn't necessarily return that value (it can be `null`), which means the onus is on users of the API to determine what that default value should be.

Whilst Terraform attempts to workaround this by massaging breaking changes in the API payloads where possible to not be breaking changes in the Terraform Configuration - ultimately it's on the AKS Team to provide an upgrade path (for example, returning the default value for a field, rather than null, for an older cluster - should it have one, or `null` otherwise).

Terraform uses the `null` value to specify that a field shouldn't be configured (which, in this case would be setting this to none) - as such it's possible to specify this value to none in Terraform by omitting this value (or explicitly setting it to null).

From what I can see in the bug report above, it appears that the AKS API is rolling out a new value for this setting/a behavioural breaking change - as such clusters provisioned in different regions (or newly created/upgraded clusters) may have different settings to existing clusters - due to the way the AKS Service is designed.

Whilst this is something we're working with the AKS Team to fix, unfortunately due to the design of this Service today, this isn't something we can immediately workaround - as such I'm going to suggest [opening an issue on the AKS Repository](https://github.com/Azure/AKS/issues) where someone from the AKS Team should be able to dig into this.

Thanks!

**Comment by k7faq** [comment]
So I am to guess there will be no discussion as to why we will not be afforded the ability to opt out of these forced upgrades?
