### ISSUE TITLE
How to change "Backup storage redundancy" for "Azure SQL Managed Instance" ?

### ISSUE THREAD

**Issue by stsathya** [hashicorp/terraform-provider-azurerm#13461]
I have tried all possible attributes and I get error as "An argument named "account_replication_type" is not expected here."

How can I mention backup redundant like "GRS/LRS/ZRS" to Azure SQl Managed Instance? By default it takes only "GRS" but I want to change to "LRS/ZRS"

**Comment by tombuildsstuff** [comment]
hi @stsathya 

Thanks for opening this issue.

Taking a look through here this appears to be a configuration question, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
