### ISSUE TITLE
Panic : Terraform Init not working

### ISSUE THREAD

**Issue by mgardi85** [hashicorp/terraform-provider-azurerm#13521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.2
AzureRM v2.69.0
AzureAd v1.6.0

### Affected Resource(s)

We are using azure Storage as a tf state store. All things were working fine till morning and now we are seeing an error on " **terraform init** "

```hcl
terraform {
  backend "azurerm" {    
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.69.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "1.6.0"
    }
  }
  required_version = "1.0.2"
}

```
### Expected Behaviour

Terraform Init should successful and the ve

### Actual Behaviour

The command fails below error log

```


Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Reusing previous version of hashicorp/azuread from the dependency lock file
- Finding latest version of hashicorp/azure...
- Installing hashicorp/azurerm v2.69.0...
- Installed hashicorp/azurerm v2.69.0 (signed by HashiCorp)
- Installing hashicorp/azuread v1.6.0...
- Installed hashicorp/azuread v1.6.0 (signed by HashiCorp)
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/azure: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/azure
│ 
│ Did you intend to use terraform-providers/azure? If so, you must specify
│ that source address in each module which requires that provider. To see
│ which modules are currently depending on hashicorp/azure, run the following
│ command:
│     terraform providers
╵

##[error]Error: The process '/opt/hostedtoolcache/terraform/1.0.2/x64/terraform' failed with exit code 1

```

### Steps to Reproduce

terraform init

**Comment by tombuildsstuff** [comment]
hi @mgardi85 

Thanks for opening this issue.

Taking a look through here it appears that one or more of the resources defined in your configuration is referencing the end-of-life Azure Classic Provider (`azure`), rather than the AzureRM Provider (`azurerm`). As such you should be able to fix this by updating any resources in your Terraform Configuration referencing the `azure` provider (e.g. `azure_{name}`) to use the `azurerm` provider instead (by updating the resources to `azurerm{name}`).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
