### ISSUE TITLE
Support for Azure Synapse Disable Public Network Access when using Managed Network

### ISSUE THREAD

**Issue by jceval** [hashicorp/terraform-provider-azurerm#13535]
When deploying Azure Synapse in a Managed Network, how can I disable PublicNetworkAccess to that Resource to only allow Private Endpoint traffic?

```
module "synapse_npe_new" {
  source = "git::git@ssh.dev.azure.com:v3/source"

  labels_context                  = module.centralus_synapse_labels_new.context
  resource_group_name             = azurerm_resource_group.this["primary"].name
  name                            = local.name
  database_pools                  = local.database_pools
  sql_administrator_login         = local.sql_administrator_login
  aad_admin                       = local.aad_admin
  managed_virtual_network_enabled = true
}
```

**Comment by tombuildsstuff** [comment]
hi @jceval 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
