### ISSUE TITLE
Support for switching between subscriptions using different containers

### ISSUE THREAD

**Issue by edvinas31** [hashicorp/terraform-provider-azurerm#13575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, all. I have a situation where I want to manage every environment using different subscription. In every subscription should be separate container created where I will store specific environment terraform state. I want to use use `az login` command to authenticate to azure and use it in terraform.  Switching between environments now is a bit additional work, because every time I switch between environments I have to set subscription specifically for environment using `az set subscription` "<<subscription>>"

In my directory structure every environment is different directory and it looks like following: 
![image](https://user-images.githubusercontent.com/49708029/135583342-a1dbed02-cf43-4e30-9d38-3d3a1c90665c.png)

Is there any way to go through subscriptions without executing `az set subscription` command?

**Comment by jackofallops** [comment]
Hi @edvinas31 - Issues on this repo are for bug reports and feature requests for the provider itself, rather than for individual user implementations or workflows.  I can recommend joining the community Slack (link and instructions in the project readme) where there are lot of helpful folks that may be able to provide you some guidance.  I should also mention that there are multiple ways to authenticate Terraform, and you might consider using another auth method, rather than cli? for example: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret

Since this isn't specifically to do with the provider, I'm going to close the issue.
