### ISSUE TITLE
In azurerm_storage_account Unable to Enable the setting for Infrastructure Encryption during creation using terraform which is a Security Reccomendation

### ISSUE THREAD

**Issue by HarryKishore** [hashicorp/terraform-provider-azurerm#13597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: [fill in]
* AzureRM Provider version: [fill in]

### Terraform Configuration Files

![image](https://user-images.githubusercontent.com/89765588/135778723-11363895-542d-4a19-8c7f-20fe003af20a.png)

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

**Comment by HarryKishore** [comment]
resource "azurerm_storage_account" "idamSta" {

  name                     = "< Storage Account Name> "
  location                 = var.location["loc"].region
  resource_group_name      = azurerm_resource_group.resourceGroup.name
  account_tier             = "Standard"
  account_replication_type = "GRS"
  min_tls_version          = "TLS1_2"

}

**Comment by tombuildsstuff** [comment]
hi @HarryKishore 

Thanks for opening this issue.

See [the `azurerm_storage_account_customer_managed_key` resource which can be used to achieve this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_customer_managed_key). This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
