### ISSUE TITLE
Support for CMK disk encryption on virtual machine scale sets

### ISSUE THREAD

**Issue by gchagan36** [hashicorp/terraform-provider-azurerm#13618]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to see Terraform support CMK disk encryption. Since this is supported for single VM workloads, it makes sense that it should be supported for workloads that require scaling, especially since disk encryption is a security best practice when operating in the cloud.

### New or Affected Resource(s)

* azurerm_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_machine_scale_set" "example" {
  name = "vmss-example"
  resource_group_name = azurerm_resource_group.rg-example.name
  location = azurerm_resource_group.rg-example.location
  automatic_os_upgrade = false
  upgrade_policy_mode = "Manual"
  network_profile {
    name = "vmss-example-profile"
    primary = true
    ip_configuration {
      name = "vmss-example-ipconfig"
      primary = true
      subnet_id = data.azurerm_subnet.subnet.id
    }
  }
  os_profile {
    computer_name_prefix = "vmss-example-"
    admin_username = "azureuser"
  }
  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      path = "/home/azureuser/.ssh/authorized_keys"
      key_data = file("keys/example.pub")
    }
  }
  sku {
    name = "Standard_B2s"
    tier = "standard"
    capacity = 2
  }
  storage_profile_image_reference {
    id = data.azurerm_image.example.id
  }
  storage_profile_os_disk {
    name = ""
    caching = "ReadWrite"
    create_option = "FromImage"
    managed_disk_type = "Premium_LRS"
    disk_encryption_set_id = azurerm_disk_encryption_set.example.id
  }
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @gchagan36 

The `azurerm_virtual_machine_scale_set` resource has since been superseded by the `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources. Whilst the existing `azurerm_virtual_machine_scale_set` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

Support for Disk Encryption Sets is instead available in the newer resources - as such I'd recommend looking into the [`azurerm_linux_virtual_machine_scale_set`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set) and [`azurerm_windows_virtual_machine_scale_set`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine_scale_set) resources going forward. However since the older `azurerm_virtual_machine_scale_set` resource is feature-frozen (and so won't be receiving any further updates) - whilst I'd like to thank you for opening this issue, I'm going to close this issue for the moment.

Thanks!
