### ISSUE TITLE
Support for Azure Route Server

### ISSUE THREAD

**Issue by Andriy-dev** [hashicorp/terraform-provider-azurerm#13612]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looking for Azure Route Server implementation in azurerm ( https://azure.microsoft.com/en-us/services/route-server/ )

### New or Affected Resource(s)

* azurerm_route_server

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @Andriy-dev 

Thanks for opening this feature request.

Taking a look through [the documentation](https://docs.microsoft.com/en-gb/azure/route-server/quickstart-configure-template) this appears to be a new brand name for Virtual Hubs, which are already supported in the Provider: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub - as such I believe this is already supported. Since this appears to be supported I'm going to close this issue for the moment, but if that's not what your looking for let us know and we'll take another look.

Thanks!

**Comment by Andriy-dev** [comment]
Hi @tombuildsstuff , thanks for the doc link, indeed it is a subset of a Virtual Hubs, however I could not find a way to _configure_ the Virtual Router, or even create it with Virtual Hub template. 
I can do it with ARM, but not with Terraform :(
