### ISSUE TITLE
CreateVMSSAgentPoolFailed on terraform apply

### ISSUE THREAD

**Issue by dev-samples** [hashicorp/terraform-provider-azurerm#13625]
Using:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      //version = "~>2.78.0"
      version = "2.59.0"
    }    
  }
  required_version = ">= 1.0.8"
}

```
and:
```
$ az version
{
  "azure-cli": "2.28.0",
  "azure-cli-core": "2.28.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```
On Ubuntu 21.04

I keep getting the below error when I run `terraform apply`

`│ Error: waiting for creation of Managed Kubernetes Cluster "k8s-dev-01" (Resource Group "k8s-dev-01"): Code="CreateVMSSAgentPoolFailed" Message="AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID: 5368c10f-cf89-0844-a563-1d0956de8343, Operation ID: 8ace0571-0cf4-4709-a4ca-fccb0e7136c6, Timestamp: 2021-10-05T13:10:52Z."`

I found:

https://github.com/Azure/AKS/issues/1972
https://github.com/hashicorp/terraform-provider-azurerm/issues/13436

But not really sure how to proceed from here.

Also I have tried to add `export TF_LOG=TRACE` but not seeing other errors that the error above.

**Comment by tombuildsstuff** [comment]
hi @dev-samples 

As you've mentioned this is a bug in the AKS API where this temporary failure is returned as a hard failure - https://github.com/Azure/AKS/issues/1972 is tracking exposing a means for Terraform to determine if this is a temporary or permanent failure - but at the current point in time there's no means of determining that reliably unfortunately.

Since this functionality needs to be exposed by the AKS Team, I'm going to close this issue in favour of https://github.com/Azure/AKS/issues/1972 - would you mind subscribing to that issue for updates?

Thanks!
