### ISSUE TITLE
Support for azurerm_lb_nat_rule - Target Virtual Machine

### ISSUE THREAD

**Issue by Lou089** [hashicorp/terraform-provider-azurerm#13627]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform Does not support adding Target Virtual Machines within an inbound nat Rule. 

### New or Affected Resource(s)

azurerm_lb_nat_rule

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @Lou089 

This is available [in the `azurerm_network_interface_backend_address_pool_association` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_interface_backend_address_pool_association) - see [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/2f0fd6676bd40551379733ac3bd831d05b05155e/examples/virtual-machines/linux/load-balanced/main.tf#L102-L107) for an example.

Since this is a configuration question rather than an issue in Terraform I'm going to close this issue for the moment but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
