### ISSUE TITLE
Data source not supported for azurerm_virtual_desktop_host_pool

### ISSUE THREAD

**Issue by olbees** [hashicorp/terraform-provider-azurerm#13623]
Getting error when trying to use WVD host pool as a data source:

The provider provider.azurerm does not support data source "azurerm_virtual_desktop_host_pool"

**Comment by tombuildsstuff** [comment]
hi @olbees 

When opening Feature Requests we ask that you complete the Feature Request template since it contains all of the necessary information - as such [would you mind reopening this completing the template](https://github.com/hashicorp/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Feature_Request.md&title=Support+for+%5Bthing%5D)?

Thanks!
