### ISSUE TITLE
azurerm_kubernetes_cluster fails to deploy because cluster auto-upgrade for AKS clusters is a preview feature.

### ISSUE THREAD

**Issue by michaelelleby** [hashicorp/terraform-provider-azurerm#13661]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.79.1"
    }
  }
}

# Configure the Microsoft Azure Provider
provider "azurerm" {
  features {}
}

# Create a resource group
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "East US"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output

https://gist.github.com/michaelelleby/dd58e16c7f73ee9b97fa595686679bbb

### Expected Behaviour

Terraform should not specify the `autoUpgradeProfile` property at all, if no value is selected.

### Actual Behaviour

Terraform generated JSON body with `autoUpgradeProfile":{"upgradeChannel":"none"}` when `automatic_channel_upgrade` is not specified.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Ensure you do not have the AutoUpgradePreview feature enabled on the subscription, on which you are testing this issue.

### References

* #0000

**Comment by nerddtvg** [comment]
@y3sy,

The provider is following the API documentation specs: https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update#managedclusterautoupgradeprofile

The property is valid and the default is 'None'. The fact that the API does not handle that correctly is not the fault of the Terraform provider.

**Comment by tombuildsstuff** [comment]
@y3sy this is an API bug, not something to fix in Terraform - as mentioned [in this comment](https://github.com/Azure/AKS/issues/2584#issuecomment-938391325) and as @nerddtvg [has mentioned](https://github.com/hashicorp/terraform-provider-azurerm/issues/13661#issuecomment-938688796) unfortunately the API doesn't match the behaviour it's supposed to.

Whilst not setting a value for this field would work if there weren't multiple default values for this field - [as mentioned in this comment](https://github.com/Azure/AKS/issues/2584#issuecomment-938391325) this isn't the case - so this _has_ to be fixed in the Azure API.

Since this needs to be fixed in the AKS API rather than Terraform, I'm going to lock this issue for the moment - but as mentioned above AKS API issue is being tracked in https://github.com/Azure/AKS/issues/2584
