### ISSUE TITLE
azurerm_app_configuration_feature resource creates invalid feature flags when no filters are defined

### ISSUE THREAD

**Issue by lennykean** [hashicorp/terraform-provider-azurerm#13673]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.79.1

### Affected Resource(s)

* `azurerm_app_configuration_feature `

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp


resource "azurerm_app_configuration_feature" "test" {
  name  = "TestFlag"
}
```

### Expected Behaviour

The resource should be created without any filters

### Actual Behaviour

The resource is created with a Microsoft.Percentage filter and a value of zero, which isn't a valid feature flag.

**Comment by danmastrowcoles** [comment]
I think this might be caused by https://github.com/hashicorp/terraform-provider-azurerm/blob/6b6985f58e49fbc92ade4a4a8082cf17afc5174c/internal/services/appconfiguration/app_configuration_feature_resource.go#L379
The Percentage filter is always added, an additional if statement could be added to check the model, similiar to the other filters.
Unless this was intentional? 
Do you have any context on this @koikonom or could you assist us with this one?
