### ISSUE TITLE
Service Bus Namespace Network Rule Set doesn't always set default_action to Deny when specified

### ISSUE THREAD

**Issue by wozneyr** [hashicorp/terraform-provider-azurerm#14001]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.14.6
AzureRM Provider: 2.83.0

### Affected Resource(s)

* `azurerm_servicebus_namespace_network_rule_set`

### Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "CentralUS"
}

resource "azurerm_servicebus_namespace" "example" {
  name                = "example-sb-namespace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Premium"

  capacity = 1
}

resource "azurerm_servicebus_namespace_network_rule_set" "example" {
  namespace_name      = azurerm_servicebus_namespace.example.name
  resource_group_name = azurerm_resource_group.example.name

  default_action = "Deny"
}
```

### Expected Behaviour

`azurerm_servicebus_namespace_network_rule_set` sets `default_action` to "Deny"

### Actual Behaviour

`default_action` does not get set to "Deny". Subsequent applies will show as wanting to change from "Allow" -> "Deny", but will not actually change the value.

### Steps to Reproduce

`terraform apply`

### Description

I'd like to use a Private Endpoint on the Service Bus Namespace and Deny all traffic by default via `azurerm_servicebus_namespace_network_rule_set`. However, if I don't specify `ip_rules` or `network_rules`, it doesn't set the `default_action` to "Deny". If I specify `ip_rules` and/or `network_rules` it sets the `default_action` as intended.

**Comment by DotNetSparky** [comment]
I can also reproduce using the new 2.84.0 provider.

What's more, it's not a "it won't change it", but it WILL change it to the wrong value.  For example, if I manually "fix" it in the Azure Portal ("Allow access from: Selected Networks"), then on the next `terraform apply`, Terraform will:

* Show that it's currently set to `Allow` (which is incorrect)
* Plan to change it from `Allow` to `Deny`
* And will actually change the setting  back to `Allow` when applied (oops!)

Thank-you, @wozneyr, for pointing out that it works when `ip_rules` it set. Setting it to an empty list (`[]`) didn't work, but I set it to `["127.0.0.1/32"]` and that worked. It not only correctly set `default_action` back to `Deny`, but the next `terraform plan` showed everything matched the configuration. (I can use this at least as a temporary workaround until fixed)

**Comment by xiaxyi** [comment]
Thanks @wozneyr and @DotNetSparky for pointing out this behavior.

This is actually an expected behavior of the service bus resource, specifically, the default action is `Allow` and the service will respect the setting `defaultAction = deny`, however, when there are 0 IPFilters and 0 VirtualNetworkRules, you are actually setting the default action to `deny` and this may not be accepted.

I understand this may be a little confusing since there is no message, I will figure out something with the code and let you know if there is any update.

hope it makes sense, feel free to let me know if there is anything needed.

**Comment by AlexisHW** [comment]
Please clarify what Allow action with empty array of ip_rules does since version 2.91?
We would like to block all traffic by default without specifying the exact IP range, what action should we use?

**Comment by fgarcia-cnb** [comment]
this is still an issue. a previous provider cleared our service bus setting to Allow. trying to use 2.91 to fix

```hcl
~ resource "azurerm_servicebus_namespace_network_rule_set" "sbus_net" {
      ~ default_action           = "Allow" -> "Deny"
...
    }
```

`Error:  The default action of Namespace Network Rule Set: (Networkruleset Name "default" / Namespace Name "td04wgc96tgi00-sbus" / Resource Group "dc04-dev-cnrwm-rg2") can only be set to `Allow` if no `ip_rules` or `network_rules` is set`

error doesnt make much sense since im trying to set to deny, not allow

**Comment by xiaxyi** [comment]
@fgarcia-cnb , Thanks for the comments, as I mentioned above, the default value of the property `default_action` can only be set to `Allow` if there is no IPFilters and VirtualNetworkRules specified, this is the current design.

**Comment by fgarcia-cnb** [comment]
as i mentioned before, im not setting to allow. im setting to Deny

**Comment by xiaxyi** [comment]
@fgarcia-cnb , The service won't take `Deny` as an accepted value for the `default_action` if there is no IPFilters or VirtualNetworkRules being specified(`ip_rules` or `network_rules`). 

if you are configuring the network rule sets for the service bus like:
```
 resource "azurerm_servicebus_namespace_network_rule_set" "sbus_net" {
      default_action           = "Deny"
    }
```

The service will change the "Deny" to "Allow" without notifying the user, we just throws an error in terraform to notify the user about this behavior

hope it makes sense to you

**Comment by AlexisHW** [comment]
@xiaxyi as posted above the explained behavior is not what we want. This is exactly opposite.

I also ready asked to explain what will `default_action = Allow` with empty ip_rules will do? Will it block everything or allow everything (because by sense Allow with empty array allows **nothing**)? if it's not the case we MUST have a possibility to set Deny with empty ip_rules meaning everything is blocked.

**Comment by fgarcia-cnb** [comment]
in the azure portal, you can absolutely set the network to disabled, whch means default rule is to deny, with an empty IP filter and empty virtual network list. this means that only private endpoint addresses are allowed. The portal states "Traffic to this namespace will be restricted over Private Endpoints only."

after disabling public access, tf is still reading the default action ias "allow". so maybe the question is where is this attribute being read from?  its almost as if an empty ip filter is automatically read as "default_action = allow". disabling public access and setting default action to deny do not appear to be the same thing.

**Comment by DotNetSparky** [comment]
To help with what everyone is saying, it's worth pointing out that the network rule sets do NOT apply to any connections to the private-endpoint, only the public endpoint (this is the way Microsoft designed it, not just with service bus). So it's a completely valid configuration when you want to disable the public endpoint completely and require all connections to use only the private endpoint, it's even mentioned in their documentation.

@xiaxyi, are you saying the Azure API is throwing an error to Terraform? If so, maybe a bug should be reported on Microsoft's side.

(for everyone else, _as a workaround_, may I suggest trying to set the filter list to non-empty, e.g. `["127.0.0.1/32"]` -- that shouldn't expose anything since no connections could originate from localhost, but at least unblocks us while we help them understand 🙃)

**Comment by xiaxyi** [comment]
@DotNetSparky , nope, Azure API won't throw an error to Terraform, instead, terraform detects the config :DefaultAction = Deny + 0 IPFilters and 0 VirtualNetworkRules and throws an error.

**Comment by DotNetSparky** [comment]
OK--then the question is "Why?"  As we're pointing out, it's a valid configuration...

**Comment by xiaxyi** [comment]
@DotNetSparky , because service doesn't throws an error in the current api version 2021-06-01-preview, you can test it using rest api by setting the default_action to "deny" together with 0 IPFilters and 0 VirtualNetworkRules. event you are passing the value "Deny", api will return "allow"

**Comment by DotNetSparky** [comment]
Sounds like maybe it needs to set the publicNetworkAccess property that @fgarcia-cnb mentioned (that might be what the Portal is doing behind the scenes, when you save this configuration in the UI).

**Comment by DotNetSparky** [comment]
(and thank-you for continuing the discussion with us--I love Microsoft's stuff, but sometimes their APIs are.... well, intesting.... lol)

**Comment by xiaxyi** [comment]
No worries, yes, I think we need to expose the publicNetworkAccess in terraform as well, let me have an intertal discussion and get back to you guys.

**Comment by fgarcia-cnb** [comment]
should we re-open this issue? or create a new one?

**Comment by AlexisHW** [comment]
Just in case you are interested what UI does when public access is disabled:
![2022-01-14_19h38_39](https://user-images.githubusercontent.com/85733574/149552105-6a8684b6-7166-4653-b8a8-272ac56dc874.png)

![2022-01-14_19h39_00](https://user-images.githubusercontent.com/85733574/149552088-897e01bf-2753-4e9b-9afb-3ff5449665fe.png)
