### ISSUE TITLE
Support for bicep template deployment in terraform

### ISSUE THREAD

**Issue by mrshiva** [hashicorp/terraform-provider-azurerm#14014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Couldn't find if terraform provider for Azure supports 'bicep' template deployments, like we have for ARM templates.
If not, please could add this feature? 

Then instead of arm deployments, simplified 'bicep' templates may be used.

### New or Affected Resource(s)

* azurerm_bicep_template_deployment

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @WascawyWabbit 

Thanks for opening this issue.

Bicep ultimately compiles their templating language down to ARM Templates - so ultimately support for this is already available in Terraform via the `azurerm_resource_group_template_deployment` and `azurerm_subscription_resource_group` resources.

Whilst it's possible there's a separate API for Bicep deployments in the future, at this point in time supporting these natively within Terraform would be either wrapping the Bicep binary, or reimplementing support for the entire compiler (and it's ongoing changes) within Terraform - if I'm being honest I don't think that's something we'll support natively within the provider.

Instead you can use the `null_resource` to compile the Bicep template to an ARM Template using the `bicep` CLI - and then the `azurerm_resource_group_template_deployment` and `azurerm_subscription_resource_group` resources to deploy the compiled template with Terraform:

```hcl
provider "azurerm" {
  features{}
}

resource "null_resource" "example" {
  provisioner "local-exec" {
    command = "bicep build test.bicep"
  }
}

data "local_file" "example" {
    depends_on = [ null_resource.example ]
    filename = "${path.module}/test.json"
}

resource "azurerm_resource_group_template_deployment" "example" {
    name = "example-deployment"
    resource_group_name = "example-rg"
    template_content = data.local_file.example.content

    deployment_mode = "Complete"
}
```

However since this isn't something we plan to support natively, whilst I'd like to thank you for opening this Feature Request I'm going to close this issue for the moment.

Thanks!
