### ISSUE TITLE
Support for app gateway resources being broken out

### ISSUE THREAD

**Issue by sirsnork** [hashicorp/terraform-provider-azurerm#14076]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Break out App Gateway config into resources so the site level configuration can be split up among files for the sites. I have several 1000+ line TF files that are just app gateway configs. Breaking out the site specific settings to their own resources would allow these to be moved to the app service file and could contain them together rather than having to have the app gateway configuration in a separate file/project.

Oddly this appears to be the only resources in this azurerm module that requires this. Pretty much everything else appears to be broken out as requested

### New or Affected Resource(s)

azurerm_app_gateway

Add the following resources

azurerm_app_gateway_http_listener
azurerm_app_gateway_backend_address_pool
azurerm_app_gateway_backend_http_settings
azurerm_app_gateway_frontend_port
azurerm_app_gateway_redirect_configuration
azurerm_app_gateway_request_routing_rule

### Potential Terraform Configuration

Code could just exactly match the the existing settings in these block, just as dedicated resources

* #0000

**Comment by tombuildsstuff** [comment]
hi @sirsnork 


Thanks for opening this issue.

Unfortunately the Azure API requires specifying at least one of (almost all of) these components when creating the Application Gateway - as such whilst there's an API available to create each of the components, we're unable to introduce separate resources for these at this time as they would conflict with the components defined inline within the Application Gateway resource.

Whilst this is something we'd like to support in Terraform (and has been previously requested, for example #6703) - unfortunately at this time the Azure API requirement means that we're unable to do this - as such I'm going to suggest [opening an issue on the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs) where someone from the Network Service Team should be able to take a look.

Once this requirement in the Azure API is relaxed such that you can provision an Application Gateway without these components, then we can take a look into supporting this - but for the moment since we're unable to support this I'm going to close this issue.

Thanks!
