### ISSUE TITLE
Error loading : Role definition list

### ISSUE THREAD

**Issue by Kishanbhatk** [hashicorp/terraform-provider-azurerm#14128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version - 2.84.0 , 2.62.1
Azure version - 0.13.3

### Affected Resource(s)

* `azurerm_role_definition`
* 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
required_providers {
azurerm = {
source = "hashicorp/azurerm"
version = "=2.62.1"
}
}}
provider "azurerm" {
features {}
}

data "azurerm_subscription" "primary" {
}
resource "azurerm_role_definition" "test_role" {
name = "test_role_302"
scope = data.azurerm_subscription.primary.id
permissions {
actions = [
"Microsoft.Compute/virtualMachines/read",
"Microsoft.Network/networkInterfaces/read",
"Microsoft.Network/publicIPAddresses/read",
"Microsoft.Network/virtualNetworks/subnets/read"
]
}
assignable_scopes = [
data.azurerm_subscription.primary.id,
]
}

data "azurerm_role_definition" "select_test_role" {
name = "test_role_302"
scope = data.azurerm_subscription.primary.id
depends_on = [
azurerm_role_definition.test_role,
]
}

output "permission" {
value = data.azurerm_role_definition.select_test_role.permissions[0].actions
}

```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Kishanbhatk** [comment]
Debug output
[https://gist.github.com/Kishanbhatk/818332c1aa4f147422733bebbbbe445a](url)

**Comment by Kishanbhatk** [comment]
[Output](https://gist.github.com/Kishanbhatk/818332c1aa4f147422733bebbbbe445a)

**Comment by aristosvo** [comment]
Hi @Kishanbhatk, I know you're struggling with this issue, it doesn't help to open a second issue unfortunately.

I would advise to retrieve the role data only in case you didn't create it just before. The outputs you need can be filled based on the same logic as the decision whether to create it or not with data/resource data.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the [Community Resources](https://discuss.hashicorp.com/c/terraform-providers/tf-azure). As such I'm going to close this issue for the moment, but I believe you should be able to get a more detailed answer for this using one of the [Community Resources](https://discuss.hashicorp.com/c/terraform-providers/tf-azure).

**Comment by Kishanbhatk** [comment]
@aristosvo  Thank you for your support , Okay will check Community sources as well as the work around which you had suggested.
