### ISSUE TITLE
Error 429 preventing migration from terraform 0.13.5

### ISSUE THREAD

**Issue by MrBasset** [hashicorp/terraform-provider-azurerm#14213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
azurerm v2.85.0

### Affected Resource(s)

* `azurerm_dns_a_record`
* `azurerm_dns_cname_record`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Sanitised gist - sorry, I had to remove customer information; hopefully I haven't butchered too much. https://gist.github.com/MrBasset/f42701d8b9e4571376687b92bdc4261a

### Expected Behaviour

I should be able to execute a terraform plan with the request backing off for 5 minutes when the 500 request limit (error 429) rate limit is triggered.

### Actual Behaviour

I have a project that was put on hold due to COVID, most resources were torn down to save the client money as their business was closed during the lock down. The project has restarted and we are in the process of upgrading all the tooling. I'm attempting to run a terraform plan/apply with version 0.13.5 as part of migrating the tooling to version 1. I want to check that no changes are needed in the environment prior to upgrading to 0.14 and then 0.15 of Terraform. However the script fails to run, failing with an error 429 - context deadline exceeded.

This script manange a large number (~700) A and CNAME DNS records. The zone is created in a different script, with other scripts managing other records in this zone.

Printing out the debug log and executing with a parallelism of 1 shows that the request that fails with a 429 error (search the gist for "Remaining-Subscription-Resource-Requests: -1", the domain that failed (domain-429-fail.example.com) is never submitted again, and is raised as an error when the plan finishes.

### Steps to Reproduce

Here is the frustrating part - I have not been able to replicate this issue in a smaller project (source: https://github.com/MrBasset/terraform-429-error). I'm stuck for how to proceed.

I (and other colleagues) are only able to get this issue to occur when running the scripts against our client's subscription with their state file. I can't provide the client's scripts, but the attached is a close approximation of the offending scripts (the primary different being that the client scripts iterate over a list of objects, holding the domain names and IPs to create). Note, the TF under the setup folder creates the DNS zone and resource groups, much the same as the client scripts do as the Zone is shared by several different environments. In total there are over 2k DNS records in the zone, with the broken script managing almost 700 of them.

### Important Factoids

n/a

### References

n/a

**Comment by tombuildsstuff** [comment]
hey @MrBasset 

Thanks for opening this issue.

Taking a look through the log here, as you've mentioned this is a HTTP 429 coming back from the Service:

> {"error":{"code":"ResourceRequestsThrottled","message":"Number of requests for action 'Microsoft.Network/dnsZones/CNAME/read' exceeded the limit of '500' for time interval '00:05:00'. Please try again after '307' seconds."}}: timestamp=2021-11-16T07:39:14.641-0500

Whilst Terraform will retry behind the scenes, what's happening here is the 5m read timeout for each resource is being exceeded by the wait time - since the DNS API's have a very low limit (500 calls/5m) verses the rest of Azure (iirc 15000/in a sliding 60m window) - and since the delay from Azure here exceeds the default 5m read timeout for each resource, Terraform's then raising a `context deadline exceeded`:

> 2021/11/16 07:44:14 [ERROR] eval: *terraform.EvalRefresh, err: retrieving CNAME Record domain-429-fail (DNS Zone "example.com" / Resource Group "customer-shared-dns-rg"): dns.RecordSetsClient#Get: Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded
> 2021/11/16 07:44:14 [ERROR] eval: *terraform.EvalSequence, err: retrieving CNAME Record domain-429-fail (DNS Zone "example.com" / Resource Group "customer-shared-dns-rg"): dns.RecordSetsClient#Get: Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded

As of version 2.0 of the AzureRM Provider, all Resources in the Provider now support Custom Timeouts - what this means is that each Resource has timeouts which are user-overridable to workaround issues such as this one. These timeouts are documented against each resource - for example here's the default timeouts for the `azurerm_dns_cname` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_cname_record#timeouts) - which can be overridden like so:

```hcl
resource "azurerm_dns_cname" "example" {
  # ...

  timeouts {
    read = "30m"
    # or, for example:
    # delete = "2h"
  }
}
```

In general these timeouts are designed to cover the normal use-case, however depending on the configuration options used it may be necessary to override them (for example provisioning an App Service Plan normally takes ~15m, which we double to a default timeout of 30m - however when provisioning an App Service Plan inside of an App Service Environment this can take considerably longer, and depends on the configuration provided).

In this case I believe it should be possible to workaround this by overriding the timeouts against each resource, which should enable you to workaround this issue - would you be able to take a look and see if that works for you? Since I believe this should be fixed by overriding the read timeout here, I'm going to close this issue for the moment - but should that not solve this for you then please let us know and we'll take another look.

Thanks!

**Comment by MrBasset** [comment]
Hi @tombuildsstuff ,

Sorry, I should have mentioned (and included in the above), when I researched this I did see that the custom timeouts were recommended. I've been using these with no luck so far:

```
resource "azurerm_dns_cname_record" "brands" {

  count               = length(local.brands)

  name                = local.brands[count.index].name
  zone_name           = data.terraform_remote_state.shared-setup.outputs.dns-zone-name
  resource_group_name = data.terraform_remote_state.shared-setup.outputs.dns-rg.resource-group-name
  ttl                 = var.dns-ttl
  record              = local.brands[count.index].fqdn

  tags                = local.tags

  timeouts {
    read              = "60m"
  }
}
```

Hence the confusion.

**Comment by MrBasset** [comment]
To anyone else facing this problem - we couldn't find a solution that worked within terraform. It seemed to be specifically related to this particular script/state file. In the end we deleted all the resources within the resource group and the terraform state and recreated everything from scratch using TF version 1.0.11 and azurerm 2.85.0.

When done this way the timeout value appears to be respected and we don't get the error.
