### ISSUE TITLE
Azure Service Principal Certificate

### ISSUE THREAD

**Issue by HamzaBennis** [hashicorp/terraform-provider-azurerm#14210]
Hello, 

we have created a service principal in azure, we are facing some issues with the pfx certificate as we are generating the plan, with terraform plan command, error as shown below:

" Error: building AzureRM Client: 1 error occurred:
        * The Client Certificate Path is not a valid pfx file: pkcs12: unknown digest algorithm: 2.16.840.1.101.3.4.2.1 "

Can someone please guide us with this problem.

Kind Regards,
Hamza

**Comment by tombuildsstuff** [comment]
hi @HamzaBennis 

Thanks for opening this issue.

Taking a look through here this is a configuration question where the Client Certificate being provided doesn't appear to be valid (so I'd suggest checking the particular types of Certificate that Azure supports for this purpose). Azure requires that a PFX file is used when authenticating as a Service Principal using a Client Certificate, you [can find out more about how to generate a Client Certificate that Azure will support here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate#generating-a-client-certificate).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
