### ISSUE TITLE
azurerm_virtual_desktop_workspace_application_group_association doesnt work as it works in v2.35

### ISSUE THREAD

**Issue by pranav03singh** [hashicorp/terraform-provider-azurerm#14233]
│ Error: ID was missing the `applicationGroups` element
│
│   on main.tf line 3, in resource "azurerm_virtual_desktop_workspace_application_group_association" "this":
│    3:   application_group_id = var.wvd_application_group_id
│

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant portions of your Terraform configuration file(s). We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out all the requested information so that we can try to reproduce the problem.
