### ISSUE TITLE
Is there a snapshot schedule for VMs in Azure?

### ISSUE THREAD

**Issue by manfred0191** [hashicorp/terraform-provider-azurerm#14242]
Just a short question:

Is there any kind of possibility existing to create snapshots of VMs (not backups!) on a regular basis with terraform?

**Comment by tombuildsstuff** [comment]
hi @manfred0191 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
