### ISSUE TITLE
Importing existing Subscriptions

### ISSUE THREAD

**Issue by JanIsaksson** [hashicorp/terraform-provider-azurerm#14295]
Hi

Until now it has working fine working with existing Subscriptions in Terraform by having their GUIDs assigned as Terraform string variables. It works with Management Groups i.e. to put different Subscriptions into different Management Groups. 

But now I also want to assign Policies to the existing Subscriptions and got an error when giving the Subscription GUID as below: 

resource "azurerm_subscription_policy_assignment" "example" {
  name                 = "example"
  policy_definition_id = azurerm_policy_definition.example.id
  subscription_id      = var.sub_hub_we    #     <==  What is the requirements on this ID?
}

Do I first need to Import the Subscription into Terraform management? I have tried to import the Subscription with no luck and also seen other people struggle with the same issues. Do I need an Alias to the Subscription? But there is no such thing as Subscription Alias in Azure. 

Please Help

Best Regards
Jan Isaksson

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_subscription_policy_assignment`

### Terraform Configuration Files

<

variable sub_hub_we {
  description = "The Hub Subscription"
  type = string
  default = "4c19dd9e-b3c3-4ae2-a639-4dd4373a843c"
}
provider "azurerm" {
  alias  = "provider-sub-hub-we"
  subscription_id = var.sub_hub_we
  tenant_id = var.azure-tenant-id
  features {}
}

resource "azurerm_subscription_policy_assignment" "az-keyvault-dispub1" {
  name = "az-keyvault-dispub"
  display_name = data.azurerm_policy_definition.az-keyvault-dispub.display_name 
  policy_definition_id = data.azurerm_policy_definition.az-keyvault-dispub.id
  subscription_id = var.sub_hub_we #Not working
  enforce = true
}
>

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @JanIsaksson 

Thanks for opening this issue.

This is the Subscription ID (e.g. `/subscriptions/00000000-0000-0000-000000000000`) rather than the Subscription UUID (e.g. `00000000-0000-0000-000000000000`) - however you shouldn't need to import the Subscription into Terraform to do so, you can instead specify the Subscription ID here which should be sufficient.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
