### ISSUE TITLE
Azure-AD Only Authentication on SQL Server should be enabled in create request

### ISSUE THREAD

**Issue by timwebster9** [hashicorp/terraform-provider-azurerm#14314]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.86.0
```

### Affected Resource(s)

`azurerm_mssql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server" "aad_admin_only" {
  name                         = "aadadminonly"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  version                      = "12.0"
  administrator_login          = "missadministrator"
  administrator_login_password = "thisIsKat11"
  minimum_tls_version          = "1.2"

  identity {
    type = "SystemAssigned"
  }

  azuread_administrator {
    login_username              = azuread_group.example.display_name
    object_id                   = azuread_group.example.object_id
    azuread_authentication_only = true
  }
}
```

### Debug Output

https://gist.github.com/timwebster9/7524746e97451b067fe8ae55d11e867e#file-sql-aad-admin-txt

### Panic Output

n/a

### Expected Behaviour

The Azure AD authentication only setting should be set in the original request that creates the server.  The way it is now, Azure Policy cannot enforce this setting.  The API supports setting this at server creation.

This is a pattern I'm seeing quite frequently.  Is there a reason things are developed in this manner?  It is a problem for users of Azure Policy.  Is there some guidance that contributors could follow to encourage them to avoid this issue?

### Actual Behaviour

The Azure AD authentication only setting is set in a subsequent request

### Steps to Reproduce

Run the above Terraform configuration

1. `terraform apply`

### Important Factoids

n/a

### References

This is a very similar issue to #13677, in that Azure Policy cannot be used to enforce this setting.  There is a built-in policy for this as well.

**Comment by aristosvo** [comment]
Hi @timwebster9! Thanks for raising this issue. I agree this should optimise implementation, I may even have the time to apply the fix this week.

I implemented both functionalities, the ability to create AD authentication with one call and AD Authentication Only. It happened at the same time, therefore the implementation of AD Authentication Only was done still as a separate call. I don't recall my exact considerations at that time tbh, it makes sense to fix that now.

Usually the reason this is developed the way it is developed is because the APIs have weird behaviour around updating these resources inline (I believe if you do a lookup of issues I filed for the REST API repository you'd get some insight) or the option to do it inline is non-existent in the first versions allowing this functionality.

Inline makes a lot of sense to apply from the start, usually this is tried 👍🏽

**Comment by timwebster9** [comment]
Hi @aristosvo! Thanks for the quick reply (and thank you for fixing 13677 🙏 ! - I just finished putting my policy in to enforce the use of AAD admins thanks to that 😄  ).

I figured it was something to do with the APIs, and yeah am aware that early versions of features sometimes need to be done separately, etc.  However it would be good to somehow ensure that the inline option is always explored first because of Policy.  I can't emphasise enough how critical it is in enterprise environments.
