### ISSUE TITLE
Ability to create azurerm_monitor_diagnostic_setting logs by category GROUP

### ISSUE THREAD

**Issue by guywood13** [hashicorp/terraform-provider-azurerm#14333]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

MS have just introduced category groups for diagnostic settings.  See refs for documentation.  It would be great if we could add these category groups rather than having to specify individual categories or loop through a data source/list.  This can now be seen in the Portal for app services under Diagnostic Settings.

### New or Affected Resource(s)

* azurerm_monitor_diagnostic_setting

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_diagnostic_setting" "example" {
  name               = "example"
  target_resource_id = data.azurerm_key_vault.example.id
  storage_account_id = data.azurerm_storage_account.example.id

  log {
    category_group = "AllLogs"
    enabled  = true

    retention_policy {
      enabled = false
    }
  }
```

### References

* [API Documentation](https://docs.microsoft.com/en-us/rest/api/monitor/diagnostic-settings-category)
* [Diagnostic Settings Documentation](https://docs.microsoft.com/en-gb/azure/azure-monitor/essentials/diagnostic-settings?WT.mc_id=Portal-Microsoft_Azure_Monitoring&tabs=CMD) - search for 'Category Groups' section

**Comment by xiaxyi** [comment]
working on it

**Comment by benjamin37** [comment]
Hi @xiaxyi,

do you have an expected time of arrival of your PR? We also rely on this feature. If it will take some time, we could also provide the PR for this.

Kind regards
Benjamin

**Comment by benjamin37** [comment]
Just saw that the api version in [azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go) lacks behind. So the azure-sdk-for-go has to be updated first in order to get this feature in the azurerm provider. `CategoryGroup` was introduced in api version 2021-05-01, see [Azure api documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2021-05-01-preview/diagnosticsettings?tabs=bicep). Please see the following references in the azure-sdk-for-go

* https://github.com/Azure/azure-sdk-for-go/issues/16192
   * [Api versions of monitor](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/readme.md#tag-package-2021-09) use diagnostic settings api version 2017-05-01-preview which does not support `categoryGroup` 
   * Latest version of the model does not contain `categoryGroup`: https://github.com/Azure/azure-sdk-for-go/blob/47ef6e21d28afc670b4f391e4ccc401712767454/services/preview/monitor/mgmt/2021-09-01-preview/insights/models.go#L4709-L4716

**Comment by doronha** [comment]
Is there any workaround that can be used from TF ?

**Comment by manfred0191** [comment]
Any idea when this will be implemented ??
