### ISSUE TITLE
Terraform reports Azure Diagnostic Setting as existing even though it is deleted.

### ISSUE THREAD

**Issue by prabirkrsarkar** [hashicorp/terraform-provider-azurerm#14498]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform -v
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0

### Affected Resource(s)

azurerm_monitor_diagnostic_setting
* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "azurerm_monitor_diagnostic_setting" "example" {
  name               = "diagsettings"
  target_resource_id = data.azurerm_iothub.example.id
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.example.id

 log {
    category = "Connections"
    enabled = true
    
    retention_policy {
      enabled = true
    }
  }

   log {
    category = "DeviceTelemetry"
    enabled = true
    
    retention_policy {
      enabled = true
    }
  }

    log {
    category = "DistributedTracing"
    enabled = true
    
    retention_policy {
      enabled = true
    }
  }

  metric {
    category = "AllMetrics"
    enabled = true

    retention_policy {
      enabled = true
    }
  }
}

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @prabirkrsarkar 

Thanks for opening this issue.

Monitor Diagnostic Settings exist outside the lifecycle of the Resource Group - as such this won't be removed like other resources, as such since Terraform is finding this resource unfortunately this still exists in the API (and so needs to be imported).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by prabirkrsarkar** [comment]
Thanks @tombuildsstuff. We figured out the same. Once we manually deleted the diag settings in the IoT hub and then deleted the resource group we could redeploy using terraform without any issues.

Thanks.
