### ISSUE TITLE
Support for authentication using federated credentials

### ISSUE THREAD

**Issue by troyready** [hashicorp/terraform-provider-azurerm#14525]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be ideal to be able to use Azure federated identity credentials with Terraform (specifically with [GitHub Actions](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure)).

I'm not certain what the best path forward is, but some thoughts:

* Looking into the authentication a tiny bit, would it make the most sense to support the [oath token](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#third-case-access-token-request-with-a-federated-credential) as a distinct provider authentication source?
* I'm not sure if the issue(s) described in [#3814](https://github.com/hashicorp/terraform-provider-azurerm/issues/3814) still apply -- if not, one path forward would be to support `az` logins for a service principal without a secret/cert.

### References

* I've also opened an issue on the [azure/login GitHub action to inquire about it exporting the principal secret as an alternative to this issue's request](https://github.com/Azure/login/issues/188).

**Comment by tombuildsstuff** [comment]
hi @troyready 

Thanks for opening this issue.

Whilst we've got no plans to support Service Principal auth using the CLI (as you've called out #3814) - support for OIDC is being tracked in this upstream issue: https://github.com/hashicorp/go-azure-helpers/issues/91

As such rather than having multiple issues open tracking the same thing, I'm going to close this in favour of [the upstream issue](https://github.com/hashicorp/go-azure-helpers/issues/91) would you mind subscribing to that issue for updates?

Thanks!
