### ISSUE TITLE
Error building ARM Config: Error populating Client ID from the Azure CLI: No Authorization Tokens were found - please ensure the Azure CLI is installed and then log-in with `az login

### ISSUE THREAD

**Issue by jsadique** [hashicorp/terraform-provider-azurerm#14560]
I am trying to implement the module "hashicorp/terraform-azurerm-nomad" for our production environment.  I am getting an error when I run "terraform init"  "Error building ARM Config: Error populating Client ID from the Azure CLI: No Authorization Tokens were found - please ensure the Azure CLI is installed and then log-in with `az login`. " I am using azurerm v2.56.0 because i got errors when i used azurerm v2.88.1 as well. Please help me to resolve this issue. Kindly suggest me what is the  azurerm version and terraform version required to consume this module for production environment.

**Comment by jsadique** [comment]
I am using azure cli version 2.31

**Comment by tombuildsstuff** [comment]
hi @jsadique 

Thanks for opening this issue.

Taking a look through here this appears to be a configuration question, as @solonrice has mentioned there was a breaking change within the Azure CLI in version 2.30 - as such you'll need to either use the latest Azure Provider and Azure CLI to use MSAL - or an older version of each (to use ADAL).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by solonrice** [comment]
I thought I was on the latest provider when I ran into the problem, but not able to confirm at the moment, or check if an even newer version was released. Thanks for confirming the new versions of both will work together.
