### ISSUE TITLE
azurerm_management_lock errors on creation 2.89

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#14568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform (and AzureRM Provider) Version
Terraform 1.0.11
AzureRM provider 2.89

Affected Resource(s)
azurerm_management_lock

### Terraform Configuration Files
```go
provider "azurerm" {
  features {}
  skip_provider_registration = true
}

required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.89"
     }
    }
}

resource "azurerm_management_lock" "virtual_machine" {
  name       = "virtual_machine_lock"
  scope      = local.virtual_machine_id
  lock_level = "CanNotDelete"
  notes      = "Locked because it's managed by Terraform"
  depends_on = [
    azurerm_windows_virtual_machine.virtualmachine_windows,
    azurerm_linux_virtual_machine.virtualmachine_linux, azurerm_virtual_machine_extension.virtualmachine_linux, azurerm_virtual_machine_extension.virtualmachine_windows
  ]
}
```
### Expected Behaviour

Resource lock is created on the resource group and terraform exits successfully

### Actual Behaviour

Apply exits with an error on scope parsing :
```go
│ Error: parsing "virtual_machine_lock": parsing scope prefix: unable to find the scope prefix from the value "virtual_machine_lock" with the regex "^((.){1,})/providers/Microsoft.Authorization/locks/(.){1,}"
│ 
│   with module.linux_virtualmachine_106.azurerm_management_lock.virtual_machine,
│   on .terraform/modules/linux_virtualmachine_106/locks.tf line 3, in resource "azurerm_management_lock" "virtual_machine":
│    3: resource "azurerm_management_lock" "virtual_machine" {
```
### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @mpjtaylor 

Thanks for opening this issue.

Taking a look through from what I can see this appears to be an issue with the Terraform Configuration being used, however unfortunately since the value of `local.virtual_machine_id` isn't provided it's hard to confirm the issue in question. It's worth noting that since you're creating the Virtual Machines in the same Terraform Module as the Lock (from the config above) - you should be able to interpolate the Resource ID of the Linux/Windows resource rather than passing in the Resource ID of the Virtual Machine as a local variable, which I believe should fix this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
