### ISSUE TITLE
azurerm_private_endpoint private_dns_zone_ids providing list of IDs does not seem to work

### ISSUE THREAD

**Issue by faisaleem-na** [hashicorp/terraform-provider-azurerm#14582]
Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
Terraform (and AzureRM Provider) Version
Terraform v0.14.10
on linux_amd64

provider registry.terraform.io/hashicorp/azurerm v2.89.0

Affected Resource(s)
azurerm_private_endpoint

Terraform Configuration Files
````
 locals {
  dns_zone_id = join(",", flatten([
  for dns_key in data.azurerm_private_dns_zone.dns_zone : dns_key.id
  ]))


#dns_zone_id2 = tolist(local.dns_zone_id)

#dns_zone_id_list = tostring(local.dns_zone_id)
}


resource "azurerm_private_endpoint" "pl" {
  for_each            = var.private_endpoint
  name                = each.value.plname
  location            = each.value.resource_group_location
  resource_group_name       = each.value.rg_name == null ? lookup(var.resource_group_output, each.value.resource_group_name, "ERROR") : data.azurerm_resource_group.resource_group[each.value["sta_key"]].name
  subnet_id           = data.azurerm_subnet.snet[each.key].id
  tags                = each.value.tags

  private_dns_zone_group {
    name                       = each.value.dzg_name
    private_dns_zone_ids       = [local.dns_zone_id]
  }

  dynamic "private_service_connection" {
    for_each                        = var.private_endpoint[each.key].private_service_connection
    content {
    name                           = lookup(private_service_connection.value, "plsname" )
    private_connection_resource_id = azurerm_storage_account.acc[each.value["sta_key"]].id
    is_manual_connection           = false
    subresource_names              = lookup(private_service_connection.value, "subresource_names" )
    }
  }
}
````

Possibly i have not got the correct configuration or providing a list seems not work.

Debug Output
n/a

Panic Output
n/a

Expected Behaviour
for private endpoint to be created with mutliple private dns zone records.

Actual Behaviour
Below error message is generated:
Error: ID contained more segments than required: "/subscriptions/<subid>/resourceGroups/test-rg/providers/Microsoft.Network/privateDnsZones/privatelink.dfs.core.windows.net,/subscriptions/<subid>/resourceGroups/test-rg/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net", map[subscriptions:<subid>]

Steps to Reproduce

Important Factoids
n/a

References
n/a

**Comment by tombuildsstuff** [comment]
hi @faisaleem-na 

Thanks for opening this issue.

Taking a look through here this appears to be an issue with the Terraform Configuration rather than a bug in the Provider, where the argument:

> private_dns_zone_ids       = [local.dns_zone_id]

is being provided as a string containing multiple values, when this needs to be a list of strings (e.g. "a,b,c" is being provided rather than ["a", "b", "c"] - as such when trying to parse the value:

> /subscriptions//resourceGroups/test-rg/providers/Microsoft.Network/privateDnsZones/privatelink.dfs.core.windows.net,/subscriptions//resourceGroups/test-rg/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net

As a Private DNS Zone ID, this is failing since there's extra segments present in the Resource ID (namely, the second Resource ID) - as such updating your Terraform Configuration to provide a list of strings rather than providing these as a CSV'd string should fix this.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
