### ISSUE TITLE
Duplicate name servers are found when azurem_dns_zon is made the default option.

### ISSUE THREAD

**Issue by dpa456** [hashicorp/terraform-provider-azurerm#14598]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.3

### Affected Resource(s)

azurerm_dns_zone 

### Terraform Configuration Files

```
resource "azurerm_dns_zone" "dns_zone" {   
  for_each            = toset(local.dns_zone_names)   
  name                = each.key   
  resource_group_name = azurerm_resource_group.rg.name    
  }
```

### Expected Behaviour

Non-overlapping name server

### Actual Behaviour

When i check the domain deployed by default, it is duplicated in the name server.

I don't know if it was intended or not.

```
ex)
domain1.net    @ NS 172800 ns1-07.azure-dns.com. ns2-07.azure-dns.net. ns3-07.azure-dns.org. ns4-07.azure-dns.info.
domain2.com  @ NS 172800 ns1-07.azure-dns.com. ns2-07.azure-dns.net. ns3-07.azure-dns.org. ns4-07.azure-dns.info.
domain1.tv       @ NS 172800 ns1-07.azure-dns.com. ns2-07.azure-dns.net. ns3-07.azure-dns.org. ns4-07.azure-dns.info.
```

### Steps to Reproduce

1. default azurerm_dns_zone
2. A large number of test domains(I have 70 domains.)
3. terraform apply

### Important Factoids

local : useast2 virginia

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_zone

**Comment by tombuildsstuff** [comment]
hi @dpa456 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding the Azure Service behaviour rather than something specific to Terraform - the name servers returned from Azure are part of the Azure API - and so fall outside of the scope of Terraform.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by dpa456** [comment]
Thank you for your quick confirmation.
