### ISSUE TITLE
azurerm_kubernetes_cluster - can't set value `none` to automatic_channel_upgrade

### ISSUE THREAD

**Issue by nbs-TomB** [hashicorp/terraform-provider-azurerm#14594]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Version: 1.0.1
AzureRM version: 2.83.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster `  - `automatic_channel_upgrade`

### Terraform Configuration Files

```hcl
  automatic_channel_upgrade = var.change_blackout == true ? "none" : "node-image"
```

### Debug Output
```
│ Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none
│ 
│   with module.aks.azurerm_kubernetes_cluster.aks,
│   on /path/to/module/ line 101, in resource "azurerm_kubernetes_cluster" "aks":
│  101:   automatic_channel_upgrade = var.change_blackout == true ? "none" : "node-image"
```

### Expected Behaviour

As per the [Azure Docs](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel) setting `none` in `automatic_channel_upgrade` appears to be a valid value. It's also referenced in the [AzureRM docs](https://registry.terraform.io/providers/hashicorp/azurerm/2.83.0/docs/resources/kubernetes_cluster#automatic_channel_upgrade)

### Actual Behaviour

setting `none` causes the tf plan to fail.
### Steps to Reproduce

1. Configure AKS cluster via terraform and set the `automatic_channel_upgrade` to `none`
2. `terraform plan`

### Important Factoids

We have strict change blackouts and need to be able to prove the automatic upgrades are disabled during those periods.

### References
<https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel>

**Comment by tombuildsstuff** [comment]
hi @nbs-TomB 

Thanks for opening this issue.

Terraform makes use of the `null` value for cases where this should be omitted - as such setting this to `null` instead of `None` will fix this for you.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by nbs-TomB** [comment]
Hi @tombuildsstuff 

Thank you for the super quick response, really appreciated.
