### ISSUE TITLE
Support for [AKS Node Image Upgrade]

### ISSUE THREAD

**Issue by luckeyca** [hashicorp/terraform-provider-azurerm#14600]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for weekly AKS node image upgrade alone as documented here: https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade.

Currently, if AKS stays at the same kubernetes version in terraform, the node image will not be upgraded.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @luckeyca 

Support for this is already available in the Provider by upgrading the Control Plane and (Default or External) Node Pools as required, at which point Terraform will do a rolling upgrade as required.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
