### ISSUE TITLE
Error: Invalid resource type: "azurerm_lb_backend_address_pool_address"

### ISSUE THREAD

**Issue by autocloudarc** [hashicorp/terraform-provider-azurerm#14612]
╷
│ Error: Invalid resource type
│ 
│   on ..\net\net.tf line 141, in resource "azurerm_lb_backend_address_pool_address" "bpa":
│  141: resource "azurerm_lb_backend_address_pool_address" "bpa" {
│ 
│ The provider hashicorp/azurerm does not support resource type "azurerm_lb_backend_address_pool_address".
╵
PS: 12/14/2021 09:53:46>

**Comment by tombuildsstuff** [comment]
hi @autocloudarc 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
