### ISSUE TITLE
data for azurerm_app_service has no object called identity

### ISSUE THREAD

**Issue by kennethsparre1980** [hashicorp/terraform-provider-azurerm#14624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.12.0
+ provider registry.terraform.io/hashicorp/azurerm v2.89.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

### Affected Resource(s)
data.azurerm_app_service

### Debug Output

│ Error: Unsupported attribute
│
│   on main.tf line 206, in module "sql_database_instance":
│  206:   principal_id      = data.azurerm_app_service.asset_app_service_container.identity.0.principal_id
│
│ This object has no argument, nested block, or exported attribute named "identity".

### Terraform Configuration Files

```hcl

# #########################################################################
# DATA 
# #########################################################################
data "azurerm_app_service" "asset_app_service_container" {
  name                = "${var.asset_app_srv_name}-${var.subscription_name}-${var.environment}-${var.ver}"
  resource_group_name = local.resource_group_app_srv_name
}

# #########################################################################
# SQL DATABASE INSTANCE
# #########################################################################
module "sql_database_instance" {

  source = "./modules/sql_database_instance"

  sqlserver_id      = module.sql_server.id
  sqlserver_name    = local.sqlserver_name
  database_name     = local.database_name
  database_instance = "${local.sqlserver_name}.${local.private_dns_transit_zone_name}"

  principal_id      = data.azurerm_app_service.asset_app_service_container.identity.0.principal_id

}


```

**Comment by tombuildsstuff** [comment]
hi @kennethsparre1980 

Thanks for opening this issue.

Taking a look through this appears to be a Terraform Configuration question, at this time the `azurerm_app_service` Data Source doesn't expose the Managed Identity - if you'd like to see support for this feel free to open a new Feature Request and someone can take a look.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
