### ISSUE TITLE
Web application firewall - max_request_body_size_in_kb

### ISSUE THREAD

**Issue by endreigesund** [hashicorp/terraform-provider-azurerm#14637]
max_request_body_size_in_kb in owasp 3.2 supports up to 2000kb.

setting this value in terraform allows only up to 128kb

**Comment by tombuildsstuff** [comment]
hi @endreigesund 

Thanks for opening this issue.

Taking a look through this appears to be a question, if this is a Feature Request then please [feel free to open a new Feature Request](https://github.com/hashicorp/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Feature_Request.md&title=Support+for+%5Bthing%5D) for this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by endreigesund** [comment]
It wasn't ment to be a question. It is a bug/feature request..
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_application_firewall_policy#managed_rules
states this:
max_request_body_size_in_kb - (Optional) The Maximum Request Body Size in KB. **Accepted values are in the range 8 to 128. Defaults to 128.**

In azure portal you can specify up to 2000:
![image](https://user-images.githubusercontent.com/22214517/146383424-6c38149d-0597-43f0-b451-3b3b15d1c96c.png)
