### ISSUE TITLE
Enable Azure Recovery Services VM replication between availability zones (single region)

### ISSUE THREAD

**Issue by crestj** [hashicorp/terraform-provider-azurerm#14641]
With the option to use availability zones instead of regions as Disaster Recovery source / targets for the Recovery Services Vault VM replication, it appears this is not possible to implement this with Terraform yet.

Is this the case?

There doesn't seem to be any reference to zones in azurerm_site_recovery_replicated_vm.

All the TF documentation references using a separate region for this feature, although the notes on AzureRM v3.0 do mention adding "zones" parameter to any object that supports it.

Is there a way to verify whether the Azure API has support for this yet?

**Comment by tombuildsstuff** [comment]
hi @crestj 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

To clarify the "Zones" question, 3.0 won't be adding Zones to all resources which support it (these are the same as any other feature request, insofar as we'd encourage you to open a Feature Request for specific functionality/resources) - however all resources which currently support Zones will be made behaviourally consistent.

Thanks!

**Comment by crestj** [comment]
Sorry, my aim was for this to be a feature request as the option to use zones instead of regions is currently not possible with the Azure provider.
