### ISSUE TITLE
Support for [Add service-endpoints to existing subnet]

### ISSUE THREAD

**Issue by ValeruS** [hashicorp/terraform-provider-azurerm#14655]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

add the ability to add service-endpoints to the existing subnet
when creating subnet from scratch is the possibility to add service-endpoints

### New or Affected Resource(s)

* azurerm_XXXXX

### References

https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az_network_vnet_subnet_update

az cli
```
az network vnet subnet update -g RG --vnet-name VNET -n SUBNET --service-endpoints Microsoft.XXXX
```

**Comment by tombuildsstuff** [comment]
hi @ValeruS 

Thanks for opening this issue.

This functionality can be configured [on the `azurerm_subnet` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#service_endpoints) - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by ValeruS** [comment]
hi @tombuildsstuff thanks for replay
the [functionality](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#service_endpoints) can be configured when creating a new subnet
but cannot be used when subnet already exist

**Comment by tombuildsstuff** [comment]
@ValeruS you can import the resource into Terraform to do so: https://www.terraform.io/cli/import

**Comment by ValeruS** [comment]
@tombuildsstuff
when have a(one) subnet, but when you have many (dozens of subnets) to import is not the best solution
