### ISSUE TITLE
azurerm_eventgrid_topic always reconstruct when using "CustomEventSchema"

### ISSUE THREAD

**Issue by poyu677** [hashicorp/terraform-provider-azurerm#14717]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0

### Affected Resource(s)

* `azurerm_eventgrid_topic`

### Terraform Configuration Files

```hcl
resource "azurerm_eventgrid_topic" "eg_topic" {
  name                = "my-eventgrid-topic"
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name

  input_schema = "CustomEventSchema"

  input_mapping_default_values {
    event_type   = "Some.Event.Type"
    data_version = "1.0"
    subject      = "some subject"
  }
}
```

### Expected Behaviour

It is expected no change when configuration is not changed. 

### Actual Behaviour

```bash
  # azurerm_eventgrid_topic.eg_topic must be replaced
-/+ resource "azurerm_eventgrid_topic" "eg_topic" {
      ~ endpoint                      = "https://my-eventgrid-topic.japaneast-1.eventgrid.azure.net/api/events" -> (known after apply)
      ~ id                            = "/subscriptions/XXXXXXXXX/resourceGroups/XXXXXXX/providers/Microsoft.EventGrid/topics/my-eventgrid-topic" -> (known after apply)
      - inbound_ip_rule               = [] -> null
        name                          = "my-eventgrid-topic"
      ~ primary_access_key            = (sensitive value)
      ~ secondary_access_key          = (sensitive value)
      - tags                          = {} -> null
        # (4 unchanged attributes hidden)


      - input_mapping_fields { # forces replacement}
        # (1 unchanged block hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Terraform will always reconstruct the event grid topic when apply.

### Steps to Reproduce

1. `terraform apply`

    It should create new event grid topic successfully for apply first time.

2. `terraform apply/plan`

   It will reconstruct the event grid topic even if you change nothing to your configuration.

**Comment by tombuildsstuff** [comment]
hi @poyu677 

Thanks for opening this issue.

Taking a look through here this appears to be an issue with the Terraform Configuration since the `input_mapping_fields` block is being set (based on the configuration being used, automatically by the Azure API) and so needs to be set in the Terraform Configuration too, so that these states match.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
