### ISSUE TITLE
http_proxy_config" is not working as expected

### ISSUE THREAD

**Issue by satyam88** [hashicorp/terraform-provider-azurerm#14720]
i am trying to use http_proxy_config argument in resource "azurerm_kubernetes_cluster" but not working 
 https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#http_proxy_config
│ Error: Unsupported argument
│ 
│   on aks_cluster.tf line 60, in resource "azurerm_kubernetes_cluster" "aks_cluster":
│   60:   http_proxy                 = "export http_proxy=http:"
│ 
│ An argument named "http_proxy" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on aks_cluster.tf line 61, in resource "azurerm_kubernetes_cluster" "aks_cluster":
│   61:   https_proxy                = "export https_proxy=http://"
│ 
│ An argument named "https_proxy" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on aks_cluster.tf line 62, in resource "azurerm_kubernetes_cluster" "aks_cluster":
│   62:   no_proxy                   = "localhost,"
│ 
│ An argument named "no_proxy" is not expected here.
╵
##[error]Terraform command 'validate' failed with exit code

Another one

│   on aks_cluster.tf line 70, in resource "azurerm_kubernetes_cluster" "aks_cluster":
│   70:     http_proxy_config     = "export https_proxy=http:///"
│ 
│ An argument named "http_proxy_config" is not expected here

**Comment by tombuildsstuff** [comment]
hi @satyam88 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
