### ISSUE TITLE
Terraform is not adding tags to network interfaces created when a private endpoint is created.

### ISSUE THREAD

**Issue by epfaffinger** [hashicorp/terraform-provider-azurerm#14721]
When you create a private endpoint using Terraform and tag the end point the NIC created for the endpoint is not tagged. Below is a sample of my config file:

resource "azurerm_private_endpoint" "apppe1" {
name = "pe-${azurerm_app_service.appsvc1.name}"
location = var.location
resource_group_name = "${azurerm_resource_group.rg.name}"
subnet_id = lookup(var.subnet_id, var.subnet_name)

private_service_connection {
name = "${azurerm_app_service.appsvc1.name}-psc"
private_connection_resource_id = azurerm_app_service.appsvc1.id
subresource_names = ["sites"]
is_manual_connection = false
}

tags = {
costCenter = lookup(var.cost_center, var.billing_dept)
}

}

This creates the private endpoint and tags it fine but the NIC is not tagged? How do we tag the NIC, my expectation would be that the NIC uses the same tag?

**Comment by tombuildsstuff** [comment]
hi @epfaffinger 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by epfaffinger** [comment]
This is ridiculous, this is a clear provider bug and every issue opened is auto closed without resolution. Until you fix it the community cannot offer any support. This issue needs to remain an open bug.
