### ISSUE TITLE
resetting  zone in azurerm_windows_virtual_machine or azurerm_linux_virtual_machine doesn't recreate new vm

### ISSUE THREAD

**Issue by rezarms** [hashicorp/terraform-provider-azurerm#14732]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.14.10
Azurerm:  2.90
### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "azurerm_linux_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  admin_ssh_key {
    username   = "adminuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }
 zone    =   1
  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
}
### Expected Behaviour

After removing value of zone , new resource should be created

### Actual Behaviour

But after running  terraform plan no changes is shown

> No changes. Infrastructure is up-to-date.

### Steps to Reproduce

1. `create new vm with either azurerm_windows_virtual_machine or azurerm_linux_virtual_machine`
2. ` pass zone value to the vm`
3. `terraform apply`
4. `remove zone parameter`
5. `terraform apply`
### References

* #0000

**Comment by mybayern1974** [comment]
@rezarms , I believe you get your expected behavior from the [document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#zone), which definitely makes sense. However, when a property got changed in terraform config, besides it either triggering resource being recreated or not, there is a "3rd" possibility that is by terraform design: the resource would only be recreated if the after-change value of that property is a non-empty value. The `zone` property in this issue belongs to this category: if your change to `zone` was from `1` to `2`, then resource recreation would happen, while your expectation did not happen was because your change was from `1` to `empty`.

Making `zone` behave like this is by design. You can get clarification from [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/linux_virtual_machine_resource.go#L290-L292). If you feel that clarification is not that clear and would like to know more contexts, I would be happy to clarify which may take non-trivial text typing : )

Lastly, I agree the [doc ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#zone) does not comprehensively reflect the actual behavior. While this doc issue does not only apply to this case you are filing but all other similar cases of this project. So refining all doc would require some more efforts which may need some doc design, but hopefully for this specific case my comment could be helpful to you.

**Comment by rezarms** [comment]
@mybayern1974  thanks for your comment.
As you mentioned it would be nicer that doc would reflect this because for me that's a change when you remove/change a property and set it to null.
What's more , when you want to create an azure managed disk and attach it to vm if I remove property  zone in vm the azure managed disk still requires me to pass zone.
