### ISSUE TITLE
Create  Azure Sql database dataset for adf using terraform.  How to please reply immediately? 

### ISSUE THREAD

**Issue by SriramAjay** [hashicorp/terraform-provider-azurerm#14785]
I am searching for create azure sql database for adf dataset with terraform. Please help me how to do that.  Please reply...

**Comment by tombuildsstuff** [comment]
hi @SriramAjay 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
