### ISSUE TITLE
Azure VM AAD Join is not working with Extension

### ISSUE THREAD

**Issue by pbeckendorf-gkgab** [hashicorp/terraform-provider-azurerm#14802]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

**_Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/glueckkanja-gab/aztools v0.0.6
+ provider registry.terraform.io/hashicorp/azuread v2.8.0
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

Your version of Terraform is out of date! The latest version
is 1.1.2. You can update by downloading from https://www.terraform.io/downloads.html_**

### Affected Resource(s)

* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "domain_join_azuread" {
  count = var.domain_join.type == "azuread" ? var.session_host_definition.count : 0

  name                       = "aad-join"
  virtual_machine_id         = local.azurerm_windows_virtual_machine_ids_list[count.index].id
  publisher                  = "Microsoft.Azure.ActiveDirectory"
  type                       = "AADLoginForWindows"
  type_handler_version       = "1.0"
  auto_upgrade_minor_version = true
  settings                   = <<-SETTINGS
    {
      "mdmId": "0000000a-0000-0000-c000-000000000000"
    }
    SETTINGS
```

### Expected Behaviour

I expected that the AAD Join as well as the Intune Onboarding shall be working.

### Actual Behaviour

Terraform Apply stops with an Error and states that the AAD Join Extension did not work.

`Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'aad-join'. Error message: \"AAD Join failed.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot "
│ 
│   with module.avd_enterprise_scale.module.session_hosts["host_pool_002_session_host_002"].azurerm_virtual_machine_extension.domain_join_azuread[1],
│   on .terraform/modules/avd_enterprise_scale/modules/terraform-azuerm-avd-session-host-0.0.1/main.tf line 153, in resource "azurerm_virtual_machine_extension" "domain_join_azuread":
│  153: resource "azurerm_virtual_machine_extension" "domain_join_azuread" {`

### Steps to Reproduce

Without the Settings Attribute, the Deployment works fine and VM's get joined to AAD.
Once the Settings Attribute is added, i get the Error above.

**Comment by tombuildsstuff** [comment]
hi @pbeckendorf-gkgab 

Thanks for opening this issue.

Unfortunately the design of Azure VM Extensions means that they're not trivial to debug - how these work behind the scenes is that when a VM Extension is provisioned through the API, the guest agent on the VM downloads and runs the appropriate VM Extension with the configuration options provided - writing any debug logs to a local file.

Each VM Extension can decide which information should be exposed through the API, which is what Terraform is outputting as an error, in this case:

> AAD Join failed. More information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot

As mentioned above since the full debug log is on the Virtual Machine itself, you'd need to dig into those logs to get the full error here (which appears to now be located at `C:\WindowsAzure\logs\WaAppAgent.log`) - although the link above may also provide more generalized advice.

Since this is an issue with the Azure VM Extension itself, rather than something specific to Terraform - I'm going to close this issue for the moment; but given the nature of the Azure AD extension, it could also be this resource needs to be tainted (to remove the machine from the Azure AD domain, or similar cleanup) before being re-enrolled - but unfortunately the debug logs on the Virtual Machine would likely contain the most information here.

Thanks!
