### ISSUE TITLE
Removing blob_properties block in azurerm_storage_account doesn't invalidate properties

### ISSUE THREAD

**Issue by SimonGasparKentico** [hashicorp/terraform-provider-azurerm#14804]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.1.2 (windows_amd64)
AzureRM v2.90.0

### Affected Resource(s)

* `azurerm_storage_account` -> `blob_properties` block

### Terraform Configuration Files

```hcl
dynamic "blob_properties" {
    for_each = var.data_protection_enabled ? [1] : []
    content {
      versioning_enabled  = local.data_protection.versioning_enabled
      change_feed_enabled = local.data_protection.change_feed_enabled
      delete_retention_policy {
        days = local.data_protection.delete_retention_policy
      }
      container_delete_retention_policy {
        days = local.data_protection.container_delete_retention_policy
      }
    }
  }
```

### Expected Behaviour

If var.data_protection_enabled is true, it will set values for every property of `blob_properties` block.
If var.data_protection_enabled change from true to false, it will disable or set false for every property of `blob_properties` block.

### Actual Behaviour
When var.data_protection_enabled is changed from true to false, nothing changes.

### Actual Workaround
```hcl
  blob_properties {
    versioning_enabled  = local.data_protection.versioning_enabled && var.data_protection_enabled
    change_feed_enabled = local.data_protection.change_feed_enabled && var.data_protection_enabled
    dynamic "delete_retention_policy" {
      for_each = var.data_protection_enabled ? [1] : []
      content {
        days = local.data_protection.delete_retention_policy
      }
  }
    dynamic "container_delete_retention_policy" {
      for_each = var.data_protection_enabled ? [1] : []
      content {
        days = local.data_protection.container_delete_retention_policy
    }
  }
}
```

### Steps to Reproduce

1. Create azurerm_storage_account with `blob_properties` block
2. `terraform apply`
3. Remove `blob_properties` block from azurerm_storage_account

### Question
Is this the expected behavior and I can't assume that removing the dynamic block from resource will invalidate the setting?

**Comment by magodo** [comment]
@SimonGasparKentico The `blob_properties` maps to the default blob service that is created automatically together with the storage account. This blob service can not be deleted as long as the storage account exists. That's why you can not really force zero this property by removing it from the config (to avoid that, we explicitly set the `blob_properties` as [optional+computed](https://github.com/hashicorp/terraform-provider-azurerm/blob/8dacc6b399a040ddd6e6e3d88cc4f22885990dd9/internal/services/storage/storage_account_resource.go#L391) in the provider).

Based on above, your workaround makes more sense as you are toggling the internal settings of the `blob_properties`. Since there is nothing more we can do in the provider level, I'm gonna close this issue for now. Please feel free to reopen if you have further questions.
