### ISSUE TITLE
Changing SKU_TIER in Kubernetes Cluster forces the replacement of cluster. 

### ISSUE THREAD

**Issue by chowmean** [hashicorp/terraform-provider-azurerm#14811]
When changing the SKU_TIER from FREE to PAID or PAID to FREE in Kubernetes Resource in AKS. The terraform plan shows that SKU_TIER change is forcing the replacement of the cluster. 

### Affected Resource(s)

Kubernetes Cluster resource. 

### Expected Behaviour

The cluster should get changed to a requested tier. 

### Actual Behaviour

Cluster replacement was triggered. 

### Steps to Reproduce

Create a cluster and then try to update its SKU_TIER.

If this is a bug. Can I pick this up and fix it?

**Comment by tombuildsstuff** [comment]
hi @chowmean 

Thanks for opening this issue.

I'm not sure which version of the Provider your using since that information's been omitted from the form - however this has been fixed in a more recent release of the Azure Provider as the API now supports changing SKU's without recreating the clusters (and didn't previously) - so to get this behaviour you'd need to upgrade to the latest version of the Provider (which at the time of writing is `v2.90.0`) which should fix this.

Since this will be fixed by upgrading to the latest version of the Provider I'm going to close this issue for the moment - but if you're still seeing this in the latest version of the Provider then let us know and we'll take another look.

Thanks!
