### ISSUE TITLE
`azurerm_orchestrated_virtual_machine_scale_set`: Multiple issues with `os_disk` attributes when using a custom image

### ISSUE THREAD

**Issue by NateRickard** [hashicorp/terraform-provider-azurerm#14820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```hcl
Terraform v1.1.2
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0
```

### Affected Resource(s)

* `azurerm_orchestrated_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test_flex_vmss" {
  name     = "test-flex-vmss"
  location = "East US 2"
}

resource "azurerm_orchestrated_virtual_machine_scale_set" "test_scale_set" {
  name                = "test-flex-scale-set"
  resource_group_name = azurerm_resource_group.test_flex_vmss.name
  location            = azurerm_resource_group.test_flex_vmss.location

  platform_fault_domain_count = 1

  sku_name  = "Standard_D2s_v4"
  instances = 0

  # Error will occur with the dummy ID below, but a real ID can be used if so desired
  source_image_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test-group/providers/Microsoft.Compute/galleries/test-gallery/images/test-image"

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }

  network_interface {
    name    = "test-network-interface"
    primary = true

    ip_configuration {
      name    = "IPConfiguration"
      primary = true
    }
  }

  os_profile {
    windows_configuration {
      computer_name_prefix     = "flex-vm"
      admin_username           = "adminuser"
      admin_password           = "@dminP@ss123"
      timezone                 = "UTC"
      enable_automatic_updates = false
    }
  }
}
```

### Debug Output

https://gist.github.com/NateRickard/1d8c1dbc315331d1798732345f60e5c4

### Expected Behaviour

1) `os_disk` should be allowed to be optional/omitted [per the docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/orchestrated_virtual_machine_scale_set#os_disk)
2) Specifying `os_disk` attributes should override the os disk properties of the image being used

### Actual Behaviour

1) When omitted, error is returned:
>Error: creating Orchestrated Virtual Machine Scale Set "test-flex-scale-set" (Resource Group "test-flex-vmss"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Required parameter 'osDisk' is missing (null)." Target="osDisk"
│
│   with azurerm_orchestrated_virtual_machine_scale_set.test_scale_set,
│   on main.tf line 75, in resource "azurerm_orchestrated_virtual_machine_scale_set" "test_scale_set":
│   75: resource "azurerm_orchestrated_virtual_machine_scale_set" "test_scale_set" {

2) When specified, error is returned:
> Error: creating Orchestrated Virtual Machine Scale Set "test-flex-scale-set" (Resource Group "test-flex-vmss"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Cannot specify user image overrides for a disk already defined in the specified image reference." Target="osDisk"
│
│   with azurerm_orchestrated_virtual_machine_scale_set.test_scale_set,
│   on main.tf line 75, in resource "azurerm_orchestrated_virtual_machine_scale_set" "test_scale_set":
│   75: resource "azurerm_orchestrated_virtual_machine_scale_set" "test_scale_set" {

We're mostly interested in getting scenario (2) working; however both results seem like bugs (or at least an issue in the docs for scenario (1))

Setting the `os_disk` attributes on a non-orchestrated VMSS (`azurerm_windows_virtual_machine_scale_set`) work as expected.

### Steps to Reproduce

1. Plug in a shared image ID into the `source_image_id` attribute (or leave as is - error will be the same)
2. Run `terraform apply`

### References

PR that recently introduced enhanced `azurerm_orchestrated_virtual_machine_scale_set`support

* #14003

**Comment by WodansSon** [comment]
@NateRickard Thank you for opening this issue, both of the mention scenarios have to do with the service teams code as they are being rejected by the service when Terraform attempts to submit the request to their service as defined in the Terraform configuration file. I will contact the service team about the issues mentioned here, but it appears these scenarios are not currently supported by the orchestrated(e.g. Flex) resource at this point in time. I am sorry if this has cause you any inconvenience.

**Comment by NateRickard** [comment]
Thanks for your response.

We've had to revert our solution to use the Azure CLI via Terraform `local-exec`, which does support custom images on flex VMSS when created like so:

```console
az vmss create \
      --name my-flex-vmss \
      --subscription <subscription> \
      --resource-group test-flex-vmss \
      --location eastus2 \
      --single-placement-group false \
      --orchestration-mode flexible \
      --platform-fault-domain-count 1 \
      --network-api-version '2020-11-01' \
      --computer-name-prefix vm- \
      --admin-username AdminUser \
      --admin-password <password> \
      --image /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<resource group>/providers/Microsoft.Compute/galleries/<gallery>/images/<image> \
      --vm-sku Standard_D2s_v4 \
      --storage-sku StandardSSD_LRS \
      --instance-count 0
```

So it would at least appear there's no technical blockers to creating a flex VMSS with a custom image in Azure. Hopefully it's something the service team can help get resolved in short order.

**Comment by WodansSon** [comment]
@NateRickard, you're welcome... that is very strange indeed since the CLI and Terraform should be calling the same service. The only thing I can thing of is that the CLI is potentially calling a different version of the API than Terraform is and this maybe a regression in the service code. At any rate, the service team is currently looking into this issue. I'll update this issue with what they find out when I hear back. 🚀

**Comment by evandeworp** [comment]
I get the "Cannot specify user image overrides for a disk already defined in the specified image reference" error when trying to create a virtual machine scale set from a specialized image. An example of a correct call to the ARM REST API is found at https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/create-or-update#create-a-scale-set-from-a-specialized-shared-image. In this REST API example, the storage profile section looks like:

      "storageProfile": {
        "imageReference": {
          "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/galleries/mySharedGallery/images/mySharedImage"
        },
        "osDisk": {
          "caching": "ReadWrite",
          "managedDisk": {
            "storageAccountType": "Standard_LRS"
          },
          "createOption": "FromImage"
        }
      },

Notice, in the example above, the "imageReference" but when I enable debug on the terraform CLI, I can see that terraform is missing areference to my image ID. Terraform only sends this to ARM REST API:

      "storageProfile": {
        "osDisk": {
          "caching": "ReadWrite",
          "writeAcceleratorEnabled": false,
          "createOption": "FromImage",
          "osType": "Windows",
          "managedDisk": {
            "storageAccountType": "Standard_LRS"
          }
        }
      },

There is no reference to imageReference in what Terraform sends to ARM REST API even though I set "source_image_id" when calling azurerm_orchestrated_virtual_machine_scale_set.  (For me, for example, I set  source_image_id to "/subscriptions/.../resourceGroups/rg-app-poc-eastus/providers/Microsoft.Compute/galleries/notified_studio_poc/images/engine_vm/versions/1.0.0" and I can see that Terraform successfully asks about this image in the debug file).

**Comment by thefisk** [comment]
### Root Cause Identified

I have been debugging this and believe I have found the source of the issue.

Within [orchestrated_virtual_machine_scale_set_resource.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go#L305) there is a call to the function `expandOrchestratedSourceImageReference` on line [305](https://github.com/hashicorp/terraform-provider-azurerm/blob/5fd32b3b3cf8a4a1891dee79e8890a125a2f36ce/internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go#L305).

This function is passed two arguments, sourceImageReferenceRaw and sourceImageId.  These are populated by reading the values for the `source_image_reference` block and the `source_id` params.

However, when we look at the function, we can see on lines [1339-1341](https://github.com/hashicorp/terraform-provider-azurerm/blob/5fd32b3b3cf8a4a1891dee79e8890a125a2f36ce/internal/services/compute/orchestrated_virtual_machine_scale_set.go#L1339) that if the first argument, referenceInput (sourceImageReferenceRaw) is blank, it will simply return `nil`.  So if a `source_image_id` is defined, instead of a `source_image_reference` block, the provider will simply ignore this because the function has exited before it's had a chance to look at the value of `source_image__id`

On line [306](https://github.com/hashicorp/terraform-provider-azurerm/blob/5fd32b3b3cf8a4a1891dee79e8890a125a2f36ce/internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go#L306) this return value is what is used to populate the missing property from the JSON which Terraform PUTs to the API, as identified by @evandeworp 

Contrast this to the behaviour used by the `azurerm_linux_virtual_machine_scale_set`, which calls a similar, but different function, `expandSourceImageReference` (call [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/5fd32b3b3cf8a4a1891dee79e8890a125a2f36ce/internal/services/compute/linux_virtual_machine_scale_set_resource.go#L566), function [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/5fd32b3b3cf8a4a1891dee79e8890a125a2f36ce/internal/services/compute/shared_schema.go#L401)), and we can see that this process handles instances of blank `source_image_reference` blocks and `source_id` params correctly.

To confirm this, I repointed the call at line [305](https://github.com/hashicorp/terraform-provider-azurerm/blob/5fd32b3b3cf8a4a1891dee79e8890a125a2f36ce/internal/services/compute/orchestrated_virtual_machine_scale_set_resource.go#L305) to the `expandSourceImageReference` as per [this](https://github.com/hashicorp/terraform-provider-azurerm/commit/19cb84f2f0c43fd26ee98fb65c7b27e9d1bb16a0) commit on my fork here [source_image_if_fix branch](https://github.com/thefisk/terraform-provider-azurerm/tree/source_image_id_fix) and my **VMSS created absolutely fine** once I had all of the other params and prereqs in place (a user defined route for my subnet, the disable_password_authentication param set etc).

Now, I have no idea why the new function `expandOrchestratedSourceImageReference` was created seeing as it seems to serve the same purpose as `expandSourceImageReference`, but maybe someone at Hashicorp will know.  It could be that the prefered fix is to change the behaviour of the (presumably) new function.  Either way I have opened PR #17786 to try and progress this.

CC: @WodansSon

**Comment by WodansSon** [comment]
@thefisk thank you for debugging this issue, I just so happen to be in the middle of exposing a lot of missing fields across all of the VMSS flavors that Terraform supports with [this](https://github.com/hashicorp/terraform-provider-azurerm/pull/17571) PR. I will go ahead and pull your changes into that PR to avoid creating conflicts in `main`.

**Comment by thefisk** [comment]
No probs @WodansSon, it was something that acted as a blocker for us at my place of work and I saw this issue was open for a while so took the opportunity to try and find out what was wrong.

I can see you've removed the superfluous function in commit ed6a95d66237685a65adfe44e522b351eef96cb9 and updated the call in the resource update function too. Thanks for notifying me about the larger PR and merging my changes in as part of it.
