### ISSUE TITLE
time_series_insights_event_source_iothub forces replacement due to naming inconsistency

### ISSUE THREAD

**Issue by craigbryson** [hashicorp/terraform-provider-azurerm#14832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 1.0.8 azurerm 2.90.0

### Affected Resource(s)

* `azurerm_time_series_insights_event_source_iothub`

### Actual Behaviour

We imported a previously created resource into terraform state using terraform import, used terraform to apply some changes to tags - on subsequent terraform plans the resource says that it must be recreated with the below:

```
+ resource "azurerm_iot_time_series_insights_event_source_iothub" "tsi_event_source" {
      ~ environment_id           = "/subscriptions/mySubID/resourceGroups/myRG/providers/Microsoft.TimeSeriesInsights/environments/myEnv" -> "/subscriptions/mySubID/resourcegroups/myRG/providers/Microsoft.TimeSeriesInsights/environments/myEnv" # forces replacement
```
The only difference i can see is a case inconsistency in resourceGroups vs resourcegroups.

### Expected Behaviour

Case sensitivity should be ignored and plan should not detect change

**Comment by craigbryson** [comment]
Specifically the change we made in-between the successful import and subsequent plans reporting a difference was:
```
~ resource "azurerm_iot_time_series_insights_event_source_iothub" "tsi_event_source" {
        id                       = "/subscriptions/mySubID/resourceGroups/myRG/providers/Microsoft.TimeSeriesInsights/environments/myEnv/eventSources/myEventSourceName"
        name                     = "XXXXX"
      + shared_access_key        = "XXXXX"
        tags                     = {
            "costcenter" = "XXX"
            "service"    = "NOTASSIGNED"
        }
        # (7 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
```

redacted for obvious reasons :) but you can see that the `id` attribute there has an upper G in `resourceGroups`

**Comment by myc2h6o** [comment]
Hi @craigbryson `environment_id` is constructed in the provider with `resourceGroup` following Azure naming convention.  https://github.com/hashicorp/terraform-provider-azurerm/blob/4dd6699ec63ec21e31a7d516f3777f0c0aaa2123/internal/services/iottimeseriesinsights/parse/environment.go#L36
You would probably need to update the resource**g**roups in the `environment_id` to resource**G**roups

**Comment by craigbryson** [comment]
Thanks @myc2h6o - in that case I suspect that 

`terraform import .azurerm_iot_time_series_insights_event_source_iothub.tsi_event_source mySubID/resourceGroups/myRG/providers/Microsoft.TimeSeriesInsights/environments/myEnv/eventSources/mySource`

Isn't formatting the environment_id property in the same way during import? I can try to look into the code unless you happen to know where this routine is?

**Comment by myc2h6o** [comment]
Hi @craigbryson I've made below test to verify the scenario, please let me know if there is any difference with your case.
I created a  TimeSeriesInsights environment and an eventSource using REST API, with id set to `resourcegroups` with all lower case, the returned id of them both have lower-cased `resourcegroups`.
```
PUT https://management.azure.com/subscriptions/mySubID/resourcegroups/myRG/providers/Microsoft.TimeSeriesInsights/environments/myEnv?api-version=2020-05-15

Response Body:
{
    "id": "/subscriptions/mySubID/resourcegroups/myRG/providers/Microsoft.TimeSeriesInsights/environments/myEnv",
    ...
}

PUT https://management.azure.com/subscriptions/mySubID/resourcegroups/myRG/providers/Microsoft.TimeSeriesInsights/environments/myEnv/eventSources/mySource?api-version=2020-05-15

Response Body:
{
    "id": "/subscriptions/mySubID/resourcegroups/myRG/providers/Microsoft.TimeSeriesInsights/environments/myEnv/eventsources/mySource",
    ...
}
```
I then imported the eventSource in terraform using
`terraform import azurerm_iot_time_series_insights_event_source_iothub.tsi_event_source /mySubID/resourceGroups/myRG/providers/Microsoft.TimeSeriesInsights/environments/myEnv/eventSources/mySource`
with below main.tf
```
provider "azurerm" {
    features {}
}

resource "azurerm_iot_time_series_insights_event_source_iothub" "tsi_event_source" {
}
```
After import, in the state file, the `id` and `environment_id` both have `resourceGroups` with G in upper case.
I then filled in the properties in main.tf and updated the `tags` property, after apply, in the state file, `id` and `environment_id` still have `resourceGroups` with G in upper case.

The environment_id is set by the below code
https://github.com/hashicorp/terraform-provider-azurerm/blob/a072ff888a470067d906a7a22563d6a44c7c1626/internal/services/iottimeseriesinsights/iot_time_series_insights_event_source_iothub.go#L192
And ID() is formatted here
https://github.com/hashicorp/terraform-provider-azurerm/blob/4dd6699ec63ec21e31a7d516f3777f0c0aaa2123/internal/services/iottimeseriesinsights/parse/environment.go#L36
`environment_id` is the id of the environment, which is constructed by terraform because it isn't returned from the api directly. Even if it has low-cased g in `resourcegroups`, terraform constructs the Id with the standard format `resourceGroups` with the upper-cased G instead. The import and apply should behave in the same way as they both use the same code.

Could you check the `environment_id` in the state file after the `terraform import`? It should have an upper-cased `G` in `resourceGroups`, and in the main.tf, it should be filled in the same way.

**Comment by craigbryson** [comment]
I will try this later today and report back

**Comment by craigbryson** [comment]
Hi,

Sorry for not following up - I was unable to reproduce this behaviour again so I will close this issue for now
