### ISSUE TITLE
`azurerm_kubernetes_cluster` does not export outbound IP usable

### ISSUE THREAD

**Issue by torbendury** [hashicorp/terraform-provider-azurerm#14849]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.0.1
+ provider registry.terraform.io/hashicorp/azurerm v2.87.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# rest left out, not necessary
# [...]

  network_profile {
    network_plugin = "azure"
  }
# [...]
```

### Expected Behaviour

When letting AKS automatically provision a load balancer and a public outbound IP address, I expect the `azurerm_kubernetes_cluster` to actually output the IP as a string so it becomes re-usable for e.g. firewall rules.

The actual behavior shows that I instead get the object ID which does not help me in any manner, because other `azurerm` resources expect me to parse the IP addresses themselves as strings.

### Actual Behaviour

Actually, `azurerm_kubernetes_cluster` outputs the full object ID of the Azure public IP:

```hcl
  azurerm_kubernetes_cluster.myAKS.network_profile[0].load_balancer_profile[0].effective_outbound_ips

==> /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxx-xxxxxxxxxx/providers/Microsoft.Network/publicIPAddresses/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
which at least gives me the information about the object ID and the resource group it resides in inside a string.

### Steps to Reproduce

1. Create a standard AKS without specifying any other load balancer configs than mentioned above
2. Terraform/azurerm will do the rest and export the above infos

**Comment by neil-yechenwei** [comment]
@torbendury , thanks for raising this issue. As outbound ip is the part of public ip not aks. So suggest to retrieve it by public ip resource id. Below is the suggested code.

```
data "azurerm_public_ip" "test" {
  name                = split("/",tolist(azurerm_kubernetes_cluster.test.network_profile[0].load_balancer_profile[0].effective_outbound_ips)[0])[8]
  resource_group_name = split("/",tolist(azurerm_kubernetes_cluster.test.network_profile[0].load_balancer_profile[0].effective_outbound_ips)[0])[4]
}

output "outboundip" {
  value = data.azurerm_public_ip.test.ip_address
}
```

**Comment by torbendury** [comment]
Hi @neil-yechenwei, thank you for your quick answer! This looks quite hacky and makes us depend on Azure never ever changing the format of object IDs and `azurerm_kubernetes_cluster` forever exposing the attribute of the `load_balancer_profile` via the API.

Maybe it's an idea to let the `azurerm_kubernetes_cluster` expose the IP directly as a string?

**Comment by aristosvo** [comment]
Hi @torbendury! I'd be happy to implement it, if I didn't knew beforehand it would probably never be accepted as a PR. 

To understand why we don't want to expose the IP directly as a string, it is important to know/understand why we don't want to expose cross-resource attributes. Cross-resource attribute exposure would require (at least) read permissions on both resources (in our case Public IP and Kubernetes Cluster), instead of only on the resource a user would expect it needs read permissions (Kubernetes Cluster). This can lead to hard to debug failure scenarios and adds necessary permission assignments which are very unclear on the surface.

The IP address is part of the Public IP resource and exposed via that API, not via the Kubernetes Cluster API AFAIK. As such, and before mentioned arguments, this is a no-go. If that would not be the case I'd be happy to help.

It looks a bit hacky (I've seen worse), but that could be circumvented that by assigning the public IP yourself:
```hcl
resource "azurerm_public_ip" "test" {
  name                = "testip"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_kubernetes_cluster" "test" {
  # [...]

  network_profile {
    network_plugin = "azure"
    load_balancer_sku = "standard"
    load_balancer_profile {
      outbound_ip_address_ids = [azurerm_public_ip.test.id]
    }
  }
  # [...]
}

output "outboundip" {
  value = azurerm_public_ip.test.ip_address
}
```

I believe this answers your question and solves your problem. As such, I will close this issue for now. If you have any further questions, let us know!
