### ISSUE TITLE
Data Source: azurerm_virtual_network vnet_peerings attribute sorted not in creation order.

### ISSUE THREAD

**Issue by WotAGuy** [hashicorp/terraform-provider-azurerm#14899]
When I ask for a list of vnet peerings it is sorted alphabetically. This means that the last element of the reutned array is not the last pering created. We have a naming convention that is not strictly adhered to but for a properly automated script I need to get the latest peering to calculate the correct name for a newpeering. A sorted list screws this up. if a sorted list is needed then there are built-in functions to do this for you. I need the raw data in the order created.

**Comment by tombuildsstuff** [comment]
hi @WotAGuy 

Thanks for opening this issue.

The sorting here comes from the Azure API and (afaik) there's no guarantees made about the order of any nested objects within a given resource within the Networking API's unfortunately.

Rather than naming these sequentially, you may instead wish to use [a resource like `random_pet` for the naming](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/pet) which would mean these are unique - however since this is a configuration/usage question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but you should be able to get further assistance on [the Community Discuss forum](https://discuss.hashicorp.com) if switching to use `random_pet` doesn't work for you.

Thanks!
