### ISSUE TITLE
Enable Continuous deployment Option with private registry (ACR) in Azure app service

### ISSUE THREAD

**Issue by sumit49033** [hashicorp/terraform-provider-azurerm#14897]
Request to enable Continuous deployment Option with private registry (ACR) in Azure app service through terraform.

**Comment by tombuildsstuff** [comment]
hi @sumit49033 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
