### ISSUE TITLE
Support for ASEv3 in Logic App

### ISSUE THREAD

**Issue by kantkrish** [hashicorp/terraform-provider-azurerm#14948]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_logic_app_workflow

### References

* https://docs.microsoft.com/en-us/azure/logic-apps/single-tenant-overview-compare#resource-types-and-environments

**Comment by tombuildsstuff** [comment]
hi @kantkrish 

Thanks for opening this issue.

App Service Environment v3 is supported in Logic App Standard which is [available in the `azurerm_logic_app_standard` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_standard) - as such I believe support for this is already available in Terraform, can you take a look and see if that works for you?

Since I believe this functionality is already available I'm going to close this issue for the moment, but if that doesn't work for you then let us know and we'll take another look.

Thanks!

**Comment by kantkrish** [comment]
I did look at the Logic App workflow: azurerm_logic_app_workflow | Resources | hashicorp/azurerm | Terraform Registry<https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_workflow> before opening this request.

As of now it only support Integration Service Environment ID, unless ISE and ASE ID can be used interchangeably.

Terraform Registry<https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_workflow>
Latest Version Version 2.90.0 Published 22 days ago Version 2.89.0 Published a month ago Version 2.88.1
registry.terraform.io


________________________________

**Comment by tombuildsstuff** [comment]
@kantkrish Logic App Workflow is for the Consumption version of Logic Apps - unfortunately Logic App (Consumption) and Logic App Standard are totally different products (and thus resources).
