### ISSUE TITLE
Support for initial_instances on scale sets

### ISSUE THREAD

**Issue by cattuz** [hashicorp/terraform-provider-azurerm#14992]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to have something like `initial_instances` rather than `instances` on virtual machine scale sets. With autoscaling and such things the actual number of instances in a scale set can vary quite a lot. As it stands right now terraform will always want to scale the instances to match whenever any change is applied, which I feel is usually not what you want with a scale set.

`initial_instances` would specify the instances to create when creating the scale set, but when only applying updates it would be ignored.

Is this sort of thing in the terraform spirit? Or is there some easier way to achieve this?

### New or Affected Resource(s)

* azurerm_linux_virtual_machine_scale_set
* azurerm_windows_virtual_machine_scale_set

**Comment by tombuildsstuff** [comment]
hi @cattuz 

Thanks for opening this issue.

Both the Linux and Windows VM Scale Set resources support this via the `instances` field, which during updates isn't updated if the `ignore_changes` is used on this field (and there's no changes to the `sku` field, since these are updated together in the API) - as such I believe this is possible today using the existing resources. Note that Overprovisioning will be enabled on the VM Scale Set by default (meaning Azure provisions twice as many machines as needed, then keeps the first X machines to boot) - which can be configured via the `overprovision` setting.

Thanks!

**Comment by cattuz** [comment]
Very nice. Tested it and of course it works great!
