### ISSUE TITLE
Support volume labels definition in managed_disk resource

### ISSUE THREAD

**Issue by mkuligow** [hashicorp/terraform-provider-azurerm#14993]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a developer i'd like to have possibility to define volume label [(Linux Volume Label)](https://tldp.org/HOWTO/Partition/labels.html)
[Windows Volume Label](https://docs.microsoft.com/pl-pl/windows-server/administration/windows-commands/label). When defining virtual machine with multiple disks it's hard to recognize disks during provisioning. For example if i create 4 disks in Terraform, then i provision disk with Ansible it's hard to recognize which disks is it. I need to implement complex recognition logic or pass information  via YAML file from Terraform. Temporary drive attached to part of virtual machine already have label "Temporary Storage" [Temporary storage documentation](https://azure.microsoft.com/en-us/blog/virtual-machines-best-practices-single-vms-temporary-storage-and-uploaded-disks/), what is very helpful during disk identification.

### New or Affected Resource(s)

* azurerm_managed_disk

### Potential Terraform Configuration

add custom attribute `volume_labels`. Attribute should accept array of string, default value should be empty. Current labels shouldn't be overridden, only merged. Example: Create disk example with labels: ["DATA", "SSD_DRIVE"], then user add label manually "PROVISIONED", rerun terraform shouldn't remove PROVISIONED label only check if DATA and SSD_DRIVE are present.
```hcl
resource "azurerm_managed_disk" "example" {
  name                 = "acctestmd"
  location             = "West US 2"
  resource_group_name  = azurerm_resource_group.example.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "1"
  volume_labels      = ["DATA", "SSD_DRIVE"]
  tags = {
    environment = "staging"
  }
}
```

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_disk
* https://tldp.org/HOWTO/Partition/labels.html
* https://docs.microsoft.com/pl-pl/windows-server/administration/windows-commands/label
* https://azure.microsoft.com/en-us/blog/virtual-machines-best-practices-single-vms-temporary-storage-and-uploaded-disks/

**Comment by tombuildsstuff** [comment]
hi @mkuligow 

Thanks for opening this issue.

Unfortunately support for this functionality isn't available within the Azure API at this time - as such we're unable to add support for this to Terraform without it being available in the Azure API (and the Azure SDK), so I'd suggest [opening a Feature Request on the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs) where someone from the Service Team should be able to take a look.

It's worth noting that the behaviour `Current labels shouldn't be overridden, only merged.` isn't how Terraform works unfortunately, so when support for this gets added to the API we'd add this as with any other field, where the items defined in the Configuration should be matched (e.g. added/removed as necessary) in the API, unless these are immutable properties (where we'd need to make this field ForceNew if it changes).

However since this functionality currently isn't available in the Azure API or SDK - I'm going to close this issue for the moment but as mentioned above I'd suggest [opening a Feature Request on the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs) where someone from the Service Team should be able to take a look.

Thanks!
