### ISSUE TITLE
Support for Enable Transparent Data Encryption on SQL Database

### ISSUE THREAD

**Issue by ubaidilyas** [hashicorp/terraform-provider-azurerm#15024]
Hello, 
This is a duplicate of the already open bug:

Support for Enable Transparent Data Encryption on SQL Database
https://github.com/hashicorp/terraform-provider-azurerm/issues/7187

It was closed without resolution and I am not able to open it as I am not a contributer. 

Looking forward to a proper response.

**Comment by tombuildsstuff** [comment]
hi @ubaidilyas 

If you follow the link in the last comment there you'll see this is already available - see this comment for more information: https://github.com/hashicorp/terraform-provider-azurerm/issues/87#issuecomment-834241142

This repository is intended for bug reports and feature enhancements rather than questions about the Azure Provider, which we instead request are opened [on the Community Discuss forum](https://discuss.hashicorp.com). Since this is a question (which has been resolved via the link above) I'm going to close this issue for the moment, but should you have further questions I'd direct you towards the Community Discuss forum.

Thanks!
