### ISSUE TITLE
synapse Linked Service Provider produced inconsistent result

### ISSUE THREAD

**Issue by mcastorina08** [hashicorp/terraform-provider-azurerm#15049]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jackofallops** [comment]
Hi @mcastorina08 - Could you provide some additional detail here to help us diagnose?

**Comment by rcskosir** [comment]
Hi @mcastorina08, this issue appears to be blank at this time.
We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out all the requested information so that we can try to reproduce the problem.
