### ISSUE TITLE
Support for direct REST API calls

### ISSUE THREAD

**Issue by scott1138** [hashicorp/terraform-provider-azurerm#15050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a resource that performs REST API calls.  There are things not supported directly via resources or ARM templates, like the example below.  While it is possible to run things like az cli command using provisioners, that can be impeded when using Terraform Enterprise remote executions.

### New or Affected Resource(s)

* azurerm_rest_api

### Potential Terraform Configuration

```hcl
resource "azurerm_rest_api" "network_access_policy" {
  uri = "https://management.azure.com/subscriptions/${var.subid}/resourceGroups/{$var.rg_name}/providers/Microsoft.Compute/disks/${var.disk_name}?api-version=2021-04-01"
  method = "PATCH"
  body = jsonencode({"id":"/subscriptions/${var.subid}/resourceGroups/{$var.rg_name}/providers/Microsoft.Compute/disks/${var.disk_name}","properties":{"networkAccessPolicy":"DenyAll"}}) 
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @scott1138

Thanks for opening this issue.

When a resource is provisioned using a more recent version of the Azure API (such as a Preview API) it's not possible to manage that on an older version of the API - which can cause issues when importing these into Terraform, as Terraform (intentionally) doesn't update to the latest Preview API for every service.

Instead Terraform opts to update as needed - and whilst this maybe something we can change in the future, this is more complex than just upgrading the vendor dependency since Azure API's do not guarantee forwards/backwards compatibilities across versions.

In addition whilst the API Definitions may be published for a given API Version (and it may be available in some regions in Azure Public) - API versions don't necessarily behave the same way across different Azure Environments (such as China, US Gov etc.).

Since the Azure API doesn't guarantee backwards/forwards compatibility, unfortunately patching fields (as you've suggested in the example above) can lead to this resource become unmanageable in Terraform (since the Azure API returns an error when accessing/changing this from a different API version).

Due to the behaviour of the Azure API making these resources unusable in Terraform in a non-trivial number of scenarios unfortunately we don't plan to support this type of Resource in the Provider. When encountering this scenario we'd instead recommend filing a feature request for the missing field and using an ARM Template via [the Resource Group Template Deployment resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_template_deployment) to provision the specific resource in the interim.

As such whilst I'd like to thank you for opening this issue, since this isn't something we plan to add to the Provider at this time I'm going to close this feature request for the moment.

Thanks!
