### ISSUE TITLE
Support for recreating a private endpoint when connection status is `Disconnected`

### ISSUE THREAD

**Issue by fwiedmann** [hashicorp/terraform-provider-azurerm#15051]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When recreating an azure PaaS service which is also in use in an azure private endpoint and private service link, the status of the private endpoint changes to `Disconnected`.  

Normally if booth resources (PaaS Service and the private endpoint) are in the same terrafrom project, the endpoint will be recreated. But if they are in separated projects, the endpoint will stay in `Disconnected` status.

I suggest to recreate a private endpoint when:
- the private service link connection is not manual
- the status is `Disconnected` 

If this is a good idea, I'm willing to implement it :)

### New or Affected Resource(s)

* azurerm_private_endpoint

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by jackofallops** [comment]
Hi @fwiedmann - Assuming I've understood your intent correctly, I don't believe this would be a good idea.  `Disconnected` could be for a number of reasons, such as the remote resource not actually being there, meaning if Terraform attempted recreation it would fail, as such I don't believe there's a reliable way to know if it should be recreated. I believe that managing the link and connected service together is the only reliable way to do this, as the dependency can then be established. Where they must be maintained separately, I think the only real alternative would be to taint the link resource when the PaaS is recreated so that TF config responsible for the link can recreate it?
