### ISSUE TITLE
Not possible to create keyvault in Azure Lighthouse subscription

### ISSUE THREAD

**Issue by svenna** [hashicorp/terraform-provider-azurerm#15090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Exists in AzureRM master and backwards at least to 2.83 which i use.

Terraform 1.1.3 is used but version doesn't matter.

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "bt-tenant-keyvault" {
  name                        = "kvbttstore${var.customer}"
  location                    = data.azurerm_resource_group.bt-tenant-store.location
  resource_group_name         = data.azurerm_resource_group.bt-tenant-store.name
  enabled_for_disk_encryption = true
  tenant_id                   = "63fcf2b6-8b7b-46ce-a691-cd43650a0e7b"
  soft_delete_retention_days  = 7
  purge_protection_enabled    = false
  sku_name                    = "standard"
}
```

### Debug Output

https://gist.github.com/svenna/0a02e3f47410e2e5c2936ef348935c37

### Expected Behaviour

A non error behavior with a created resource 

### Actual Behaviour

The keyvault is actually created but fails on a readoperation in the end of the creation loop where
the code tries to read a certification via a data plane operation which is forbidden when using 
azure lighhouse subscriptions
https://github.com/hashicorp/terraform-provider-azurerm/blob/51761b04736c5cfe41f6cdf730ec67d8bfce3104/internal/services/keyvault/key_vault_resource.go#L403

I don't know why this read operation is needed. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Here is the current documentation for the limitation that create hits.
https://docs.microsoft.com/en-us/azure/lighthouse/concepts/cross-tenant-management-experience#current-limitations

Here is a link to a sample that indicates that it should be possible to create and use keyvault in azure lighthouse environments
https://github.com/Azure/Azure-Lighthouse-samples/tree/master/templates/create-keyvault-secret

Running in Azure subscription managed via Azure Lighthouse

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @svenna

Thanks for opening this issue.

Whilst the AzureRM Provider supports Azure Lighthouse in some forms, such as managing Roles and Role Definitions - unfortunately the limitations described in the link above are limitations with Azure Lighthouse and as such would need to be solved there.

There are many resources in the Provider which rely on Data Plane API's, so to be able to detect changes to these resources we need to be able to connect to these API's to retrieve the latest state - as such unfortunately this isn't something we can fix in Terraform without breaking a fundamental principal of Terraform (that is, detecting when there's a diff between the config and the remote API).

Since this is a limitation of Azure Lighthouse I'm going to close this issue for the moment, but I'd encourage you to reach out to the Azure Lighthouse team here, since I believe they should be able to fix this within the Lighthouse API by adding a Key Vault Access Policy to the Key Vault that's provisioned (which can be managed in ARM).

Thanks!
