### ISSUE TITLE
Error while installing Azure Server Vulnerability Assessment (Qualys) to a VM.

### ISSUE THREAD

**Issue by pramod1828** [hashicorp/terraform-provider-azurerm#15103]
terraform block seems to be straight forward to install Azure Server Vulnerability Assessment (Qualys) to a VM.

resource "azurerm_security_center_server_vulnerability_assessment" "example" {
  virtual_machine_id = azurerm_linux_virtual_machine.example.id
}

but getting error while using the same …!!!!!

​│ Error: create Server Vulnerability Assessment for "/subscriptions/***/resourceGroups/abc-rg/providers/Microsoft.Compute/virtualMachines/vm": security.ServerVulnerabilityAssessmentClient#CreateOrUpdate: Failure responding to request: StatusCode=424 -- Original Error: autorest/azure: Service returned an error. Status=424 Code="FailedDependency" Message="The provisioning state of the machine /subscriptions/***/resourceGroups/abc-rg/providers/Microsoft.Compute/virtualMachines/vm is not Succeeded

**Comment by tombuildsstuff** [comment]
hi @pramod1828 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by pramod1828** [comment]
Hi Team,

This seems to be bug as I'm using the terraform block to add Qualys
extension on Vm using Azure provider.

Though the inputs are straight farword still it's getting failed with
provided error.


Regards,

K.PRAMOD.
