### ISSUE TITLE
Support for moving an Azure Key Vault across resource groups

### ISSUE THREAD

**Issue by Apholisha** [hashicorp/terraform-provider-azurerm#15105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for moving an Azure Key Vault across resource groups.
The feature is now supported by Azure.
No changes to syntax but if the resource group value is changes, to change the resource and not recreate it.

This will be very handy especially when purge protection is enableded and we cannot just delete the key valut and recreate it. 

### New or Affected Resource(s)

* azurerm_key_vault

### Potential Terraform Configuration

Curent behaviour:

```
  # module.synapse.azurerm_key_vault.this must be replaced
-/+ resource "azurerm_key_vault" "this" {
        name                            = "test-keyvault"
      ~ resource_group_name             = "test" -> "new-test" # forces replacement
      ~ soft_delete_enabled             = true -> (known after apply)
      ~ vault_uri                       = "https://test-keyvault.vault.azure.net/" -> (known after apply)
        # (5 unchanged attributes hidden)
          - virtual_network_subnet_ids = [] -> null
            # (2 unchanged attributes hidden)
        }
    }
 
```

Desired behaviour:

```
  # module.synapse.azurerm_key_vault.this  has changed
-/+ resource "azurerm_key_vault" "this" {
        name                            = "test-keyvault"
      ~ resource_group_name             = "test" -> "new-test"
      - soft_delete_enabled             = true 
      - vault_uri                       = "https://test-keyvault.vault.azure.net/" 
        # (5 unchanged attributes hidden)
       - virtual_network_subnet_ids =  null
      }
  }
 
```

### References

https://docs.microsoft.com/en-us/azure/key-vault/general/move-resourcegroup

**Comment by tombuildsstuff** [comment]
hi @Apholisha 

Thanks for opening this issue.

This has come up previously and unfortunately this isn't something we plan to support at this time as it would cause larger issues within Terraform, namely where the Resource ID would change (since the Resource Group changes), meaning that any resources within the Key Vault (such as Certificates, Keys and Secrets) would be recreated (since the reference to the parent Key Vault changes).

Whilst this maybe something we look to solve in the future, given this behaviour would need to be consistently implemented across all resources (as when it's available in one, users would expect it in others) in a manner that doesn't subtly cause issues (as highlighted above) - which would also require upstream changes in Terraform Core (which would require changes to the Plan to know when a resource is being moved rather than recreated).

Ultimately this means that whilst we'd like to support this functionality, given the scope of the changes required here in practice this isn't something we're likely to support anytime soon - but it is something we'll bear in mind going forward (and will raise with the Core team).

Whilst not ideal, it should be possible to achieve this in the interim by moving these resources using the Azure CLI (or Portal etc) and then retroactively updating Terraform to account for this - namely any references to the Key Vault ID would also need to be updated to avoid the issue mentioned above. @aristosvo has a tool which maybe useful here to do this in a more automated manner: https://github.com/aristosvo/aztfmove

Thanks!

**Comment by Apholisha** [comment]
Hi @tombuildsstuff ,
Thanks for the detailed explanantion. I get the point.
Just to say that I have a reason why you should make an exception for the key vault. The purge protection. 
If on, you cannot move the resource by recreating it.
