### ISSUE TITLE
Add ability to set NAME of a Load Balancer when creating AKS with azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by owit-infra** [hashicorp/terraform-provider-azurerm#15116]
The Azure Load Balancer which gets created by the module azurerm_kubernetes_cluster - is just called "lkubernetes".

While this is not an issue, it would make it easier to identify which LB you need to open up, if you could set the name of it while deploying AKS via Terraform.

This is especially helpful for environments with MANY AKS clusters in the same region.

**Comment by tombuildsstuff** [comment]
hi @owit-infra 

Thanks for opening this issue.

Unfortunately this functionality isn't available in the Azure API at this time and as such this isn't something we can currently expose in Terraform - since this is a feature request for the AKS API I'd [recommend opening an issue on that repository](https://github.com/Azure/AKS) where someone from the Service Team should be able to take a look, and if this is exposed in the future we can look to add suport for this to the Provider.

Thanks!
