### ISSUE TITLE
Make azurerm_kubernetes_cluster work well with application gateway and identities

### ISSUE THREAD

**Issue by davidkarlsen** [hashicorp/terraform-provider-azurerm#15132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When using AKS with APPGW for ingress, one ends up in a catch 22 situation:
Defining the ingress_gateway addon, a user defined identity will be created during deployment for the ingress controller, but the ingress controller will fail to deploy the appgw, because the UDI needs to be assigned roles in the vnet in order to introspect it for subnets/create subnet for the appgw. It's not possible to pass in a UDI for the ingress, hence the permission can't be set prior to creating the cluster. Hence the deployment ends up in a half baked state, where you need to go around and hack it in place, which breaks the whole IaC concept.

One could avoid this by pre-configuring an application-gateway and pass that in as a reference to the aks-cluster, but you then end up with drift because the ingress-controller mutates the app gw configuration.

### New or Affected Resource(s)

`azurerm_kubernetes_cluster` should be able to take in a usermanaged identity, so that the permissions can be set up apriori to creating the cluster.

### References

* https://github.com/Azure/application-gateway-kubernetes-ingress
* https://github.com/Azure/terraform-azurerm-aks

**Comment by tombuildsstuff** [comment]
hi @davidkarlsen 

The `azurerm_kubernetes_cluster` resource already supports specifying a User Assigned Identity [which can be configured within the `identity` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster) - as such I believe this maybe a limitation with the AKS module being used?

With regards to pre-configuring an Application Gateway, unfortunately that functionality currently isn't available in the AKS API and so [would be a feature request to the AKS Team](https://github.com/Azure/AKS) where when it's available we can look into adding support for this into the Provider.

Since I believe support for this is already available I'm going to close this issue for the moment, but when support for a user specified Application Gateway becomes available in the AKS API we can look into adding the other functionality.

Thanks!

**Comment by davidkarlsen** [comment]
> hi @davidkarlsen
> 
> The `azurerm_kubernetes_cluster` resource already supports specifying a User Assigned Identity [which can be configured within the `identity` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster) - as such I believe this maybe a limitation with the AKS module being used?

Yes, but that's for AKS itself, another one is created dynamically and used for the agic.

> With regards to pre-configuring an Application Gateway, unfortunately that functionality currently isn't available in the AKS API and so [would be a feature request to the AKS Team](https://github.com/Azure/AKS) where when it's available we can look into adding support for this into the Provider.

It is, it can be passed like this: https://github.com/Azure/terraform-azurerm-aks/blob/master/main.tf#L109
