### ISSUE TITLE
azurerm_iothub_endpoint_servicebus_topic requires resource_group_name when iothub_id is set

### ISSUE THREAD

**Issue by kensykora** [hashicorp/terraform-provider-azurerm#15134]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.93.1
+ provider registry.terraform.io/hashicorp/external v2.2.0
```

### Affected Resource(s)

* `azurerm_iothub_endpoint_servicebus_topic`

### Terraform Configuration Files

```hcl
resource "azurerm_iothub_endpoint_servicebus_topic" "test_results" {
  name                = "test_results_topic"
  # resource_group_name = data.azurerm_iothub.hub.resource_group_name # This is required, but shouldn't be since the full iot hub resource ID is specified below
  iothub_id           = data.azurerm_iothub.hub.id

  connection_string = azurerm_servicebus_topic_authorization_rule.test_results_delivery.primary_connection_string
}
```

### Expected Behaviour

`resource_group_name` should not be required, since `iothub_id` already contains it and contains enough information in it to properly reference the parent iot hub for the service bus topic endpoint to be created

### Actual Behaviour

`resource_group_name` is required

```
│ Error: Missing required argument
│ 
│   on ../../infra/servicebus.tf line 15, in resource "azurerm_iothub_endpoint_servicebus_topic" "test_results":
│   15: resource "azurerm_iothub_endpoint_servicebus_topic" "test_results" {
│ 
│ The argument "resource_group_name" is required, but no definition was found.
```

### Steps to Reproduce

1. `terraform apply`

### Workaround

Add `resource_group_name` property to the resource

**Comment by myc2h6o** [comment]
Hi @kensykora `iothub_id` is the resource id of the Iot Hub, while 'resource_group_name' is the resource group under which the Service Bus Topic has been created.
Before release v2.91.0, `iothub_name` was used, which forces the Iot Hub and the Service Bus Topic (Same for other three routing endpoints) to be in the same resource group (#14304).
Starting from v2.91.0, `iothub_id` is introduced while deprecating `iothub_name`, so that the Iot Hub can be put in a different resource group than the Service Bus Topic.

**Comment by mybayern1974** [comment]
Hi @kensykora , are you ok if we close this issue with assuming myc2h6o's suggestion can address your issue?

**Comment by myc2h6o** [comment]
Hi @kensykora thanks for the response!
For point 1, I've done a test with REST API of creating the endpoint without giving resource group name. The endpoint can be created successfully, however when I explore the endpoint on the Azure Portal, the URI will have something like `resourceGroups/undefined`. So in order to let the Portal work correctly, probably we will need to keep the resource group name specified.
For point 2, I think what you said make sense. @katbyte to comment on this.

**Comment by kensykora** [comment]
@myc2h6o makes sense, thanks for the context. I still think it might make sense to change the name of the property for provider v3 but sounds like you're right. Thanks for looking into it!
