### ISSUE TITLE
How to link GitHub with Azure Data Factory

### ISSUE THREAD

**Issue by abhinavssingh** [hashicorp/terraform-provider-azurerm#15165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.93.1

### Affected Resource(s)

* `azurerm v2.93.1

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory" "adf" {
  name                    = "Sample Data Factory"
  resource_group_name     = "terraform-scripts"
  location                = "eastus" 
  tenant_id               = "****"
  public_network_enabled  = true
}

resource "azurerm_data_factory_github_configuration" "github" {
  account_name     = "abhinavssingh"
  branch_name      = "master"
  git_url          = "https://github.com/abhinavssingh/sample-terrform-library"
  repository_name  = "sample-terrform-library"
  root_folder      = /
}
```

### Expected Behaviour

How I have to associate GitHub with ADF ?

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @abhinavssingh 

Thanks for opening this issue.

Support for this functionality can be found in the `github_configuration` block within the `azurerm_data_factory` resource, the `azurerm_data_factory_github_configuration` resource referenced above doesn't exist.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
