### ISSUE TITLE
azurerm_key_vault_secret with vault_uri is not supported

### ISSUE THREAD

**Issue by ncmuthu** [hashicorp/terraform-provider-azurerm#15179]
I am trying to access the Azure key vault using private endpoint through terraform. I am running the terraform from outside of Azure environment. 

1. I have created the private endpoint for azure key vault.
2. I have created DNS record to resolve the IP for the private endpoint (https://mykeyvault.mydomain.com)
3. Now, to pull the secret, I should be able to specify the vault_uri to point to private endpoint.
4. I do not see option for vault_uri in azurerm_key_vault_secret resource.

```
data "azurerm_key_vault_secret" "secret1" {
  name         = "secret1"
  vault_uri    = "https://mykeyvault.autodesk.com"
  key_vault_id = data.azurerm_key_vault.vault.id
}

╷
│ Error: Unsupported argument
│
│   on keyvault.tf line 16, in data "azurerm_key_vault_secret" "secret1":
│   16:   vault_uri    = "https://mykeyvault.autodesk.com"
│
│ An argument named "vault_uri" is not expected here.

````

**Comment by tombuildsstuff** [comment]
hi @ncmuthu 

As in the code example you've shown above the field `key_vault_id` can be used to look up the Key Vault, which is intentionally used rather than the `vault_uri` to be able to track if the parent Key Vault been removed, or if there's another issue preventing connection to the Key Vault. Support for managing items over a Private Endpoint is being tracked in #9738, rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #9738 - would you mind subscribing to that issue for updates?

Thanks!
