### ISSUE TITLE
azurerm_virtual_machine  does not support Premium_ZRS

### ISSUE THREAD

**Issue by BalaAnbalagan** [hashicorp/terraform-provider-azurerm#15184]
azurerm_virtual_machine  does not support Premium_ZRS as a data disk and throws "expected storage_data_disk.0.managed_disk_type to be one of [Premium_LRS Standard_LRS StandardSSD_LRS UltraSSD_LRS], got Premium_ZRS" error.

**Comment by tombuildsstuff** [comment]
hi @BalaAnbalagan 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!
