### ISSUE TITLE
How to create a serverless azure logic app

### ISSUE THREAD

**Issue by abhinavssingh** [hashicorp/terraform-provider-azurerm#15214]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.93.1

### Affected Resource(s)

* `azurerm_2.93.1`

### Terraform Configuration Files

```hcl
How to create a Serverless Logic App
resource "azurerm_logic_app_single_tenant" "example" {
  name                       = "logic-test-azure-functions"
  location                   = azurerm_resource_group.example.location
  type                       = "consumption"
  resource_group_name        = azurerm_resource_group.example.name
}

resource "azurerm_logic_app" "example" {
  name                       = "logic-test-azure-functions"
  location                   = azurerm_resource_group.example.location
  type                       = "consumption"
  resource_group_name        = azurerm_resource_group.example.name
}

resource "azurerm_logic_app_consumption" "example" {
  name                       = "logic-test-azure-functions"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
}
```

### Debug Output

   on logicapp.tf line 25, in resource "azurerm_logic_app_single_tenant" "example":
│   25: resource "azurerm_logic_app_single_tenant" "example" {
│
│ The provider hashicorp/azurerm does not support resource type "azurerm_logic_app_single_tenant".

### Panic Output

NA

### Expected Behaviour

NA

### Actual Behaviour

NA

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @abhinavssingh 

Thanks for opening this issue.

See [the `azurerm_logic_app_workflow` resource (for consumption plan)](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_workflow) and [the `azurerm_logic_app_standard` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_standard) which covers both Consumption Plan and when running this dedicated.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
