### ISSUE TITLE
Support for Azure Resource Graph at least for discovery queries

### ISSUE THREAD

**Issue by kratkyzobak** [hashicorp/terraform-provider-azurerm#15221]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Proposal of using https://docs.microsoft.com/en-us/azure/governance/resource-graph/overview for discovery queries. This API seems to contian all beta/preview informations about resources (less significant) as Portal is mainly using it, but is working with less transition delays (probably as it has different arcihtecuture}

There are minor problems with sync of Azure Resource Manager - you can sometime see for example "Unable to determine the Resource ID for the Key Vault" for KV which definitivelly exists. This is due to implementation of azurerm_key_vault_secret which even if knowing about resource group and KV ID (passed as parameter to resource) tries to discover key vault by secret URI. It does this by searching for key vault by it's name against ARM REST API. There is problem, that ARM has some long lasting bugs (according to Micorosft support) which becomes features (distributed system syncing problems). If you create new KeyVault, there is possibility you will try to search it using ARM API only by its name, it will not be returned sometimes (my last issue last for 7 hours). This is bug in ARM, but as we don't know if Microsoft can solve it in reasonable time so I would propose adapt to this bug.

Proposal is use Azure Resource Graph for this "discovery" requests (https://github.com/hashicorp/terraform-provider-azurerm/blob/25b1fe00e1ee461839fb7b2528192293d3b98758/internal/services/keyvault/client/helpers.go#L96). I'm aware of using these requests for key_vault and storage_account. Problably is done for more resources with globaly unique URIs. As portal is responding correctly (in search bar for example) at same time ARM API responses misses some resources I hope, Azure Resource Graph is better architectured and for discovering resources. To be noted - ARM API were able to manage resource if you knew it's ID, there is only discovery problems, which is better implemented by Microsoft in ARG API.

### New or Affected Resource(s)

* azurerm_key_vault_XXXX
* azurerm_storage_account_container
* ... resources which needs to be identified by it's globally unique URI ...

### Potential Terraform Configuration

Probably provider level configuration for some alpha phase?

```hcl
provider azurerm {
    features {
        discover_using_azure_resource_graph = true
    }
}
```

### References

- Microsoft documentation https://docs.microsoft.com/en-us/azure/governance/resource-graph/overview
- https://github.com/Azure/azure-sdk-for-go/tree/main/services/resourcegraph/mgmt/2021-03-01/resourcegraph

* #0000

**Comment by tombuildsstuff** [comment]
hi @kratkyzobak 

Thanks for opening this issue.

As you've mentioned unfortunately this is an upstream (caching) issue in the Azure API which needs to be fixed by the ARM Team - there's another issue open [where folks have mentioned that Azure Support has been able to purge the cache](https://github.com/hashicorp/terraform-provider-azurerm/issues/14249#issuecomment-982419421), which has resolved this for them.

We've previously looked into using Resource Graph for these queries, we ultimately came to the conclusion not to do so due to both the design of the API (which, amongst other things is more suited to interactive queries) and that we've seen similar caching issues in other systems which make use of this API (such as the Portal) - as such unfortunately we believe these issues are still present within the API.

Whilst I appreciate that's probably not the answer you were looking for here, I believe that Azure Support should be able to fix this for you in the interim by purging this cache - however ultimately this caching issue needs to be fixed by the Service Team.

Thanks!
