### ISSUE TITLE
Support for Azure Compute Gallery when deploying Virtual Machines

### ISSUE THREAD

**Issue by masonhuemmer** [hashicorp/terraform-provider-azurerm#15255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When provisioning a windows virtual machine, I am required to pass in a source image ID, instead of being able to provide the publisher, offer, sku, and version. 

Users should be able to pull images from a private gallery, rather then having to pass in the resource ID to the shared image.

### New or Affected Resource(s)

* azurerm_windows_virtual_machine
* azurerm_linux_virtual_machine
### Potential Terraform Configuration

```
provider "azurerm" {
  features {}
}


data "azurerm_shared_image" "example" {
  name                = "my-image"
  gallery_name        = "my-image-gallery"
  resource_group_name = "example-resources-imageRG"
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "xxxxximageregion"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_windows_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  admin_password      = "P@$$w0rd1234!"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    gallery   = "Private"
    publisher = "CompanyName"
    offer     = "WindowsServer"
    sku       = "2022-Datacenter"
    version   = "latest"
  }  
}
```

### References

* https://stackoverflow.com/questions/67178590/deploy-azure-vm-based-on-customize-image-available-on-shared-image-gallery

**Comment by tombuildsstuff** [comment]
hi @masonhuemmer 

Thanks for opening this issue.

Deploying Images from a Shared Image Gallery is available in the same manner as Platform Images - and this functionality is already available in the Linux and Windows VM/VMSS resources.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by masonhuemmer** [comment]
So my reason for opening this request is because I was not able to provision a VM by supplying the source image reference. I had to use the Shared Image ID to provision the VM. So no, I do not believe the same functionality exists as does with a Platform Image.

When I open a ticket with Azure Support, they said this is a potential issue with the AzureRm provider with Terraform, which is why I opened the ticket.

If you expect this functionality exists, then I believe we need to move this to a bug.

**Comment by masonhuemmer** [comment]
Opened bug https://github.com/hashicorp/terraform-provider-azurerm/issues/15274

**Comment by tombuildsstuff** [comment]
@masonhuemmer in which case unfortunately that's an API limitation, whilst support for this was previously available in Terraform (since the API did support this at one point in time) - it appears support for this has been removed in the Compute API which Terraform uses.

Unfortunately the Compute API returns either a Source Image ID or the Source Image Reference, as such whilst we could look to try and include this into the `source_image_reference` block, the API doesn't return enough information for us to ascertain where this came from - and as such we'd be unable to coalesce this back into user input - and so this isn't something we can workaround at this time.

Given that support for this has been removed from the Azure API, my guess would be that the Compute API has moved away from this for similar reasons - but it may be worth opening a feature request on [the upstream Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs) where someone from the Compute Team should be able to clarify here.

However as discussed above, since we don't have a means of working around this API limitation, unfortunately there's not much more we can do from Terraform's side at this point in time.

Thanks!
