### ISSUE TITLE
azurerm_frontdoor import parsing error expected the segmet "frontdoors" to be "frontDoors"

### ISSUE THREAD

**Issue by on-nscom** [hashicorp/terraform-provider-azurerm#15267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.65"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "westeurope"
}

resource "azurerm_frontdoor" "frontdoor-example-1" {

}
```

### Expected Behaviour

Terraform should import the existing Azure Front Door resource.

### Actual Behaviour

```bash
azurerm_frontdoor.frontdoor-example-1: Importing from ID "/subscriptions/[...]/resourceGroups/[...]/providers/Microsoft.Network/frontdoors/frontdoor-example-1"...

Error: parsing Resource ID "/subscriptions/[...]/resourceGroups/[...]/providers/Microsoft.Network/frontdoors/frontdoor-example-1": parsing "/subscriptions/[...]/resourceGroups/[...]/providers/Microsoft.Network/frontdoors/frontdoor-example-1": parsing segment "staticFrontDoors": expected the segment "frontdoors" to be "frontDoors"
```

### Steps to Reproduce

1. `terraform import azurerm_frontdoor.frontdoor-example-1 "/subscriptions/[...]/resourceGroups/[...]/providers/Microsoft.Network/frontdoors/frontdoor-example-1"`

### Important Factoids

I triple checked the resource ID of the existing resource in Azure and the resource group is already imported.

**Comment by tombuildsstuff** [comment]
hi @on-nscom 

Thanks for opening this issue.

As the error message from Terraform Import says here, the segment `frontdoors` should be `frontDoors` - as such importing using this casing will solve this for you.

The particular casing required when importing resources is listed on the documentation for each resource, in this case [this can be found here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor#import) - and Terraform validates this matches what we expect.

Since this should be fixed by updating the Resource ID being used here I'm going to close this issue for the moment, but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
