### ISSUE TITLE
custom_error_configuration  - Requesting for solution for this ticket : https://github.com/hashicorp/terraform-provider-azurerm/issues/13790

### ISSUE THREAD

**Issue by isathish** [hashicorp/terraform-provider-azurerm#15305]
Kindly provide the solution for this issue 

https://github.com/hashicorp/terraform-provider-azurerm/issues/13790

**Comment by stephybun** [comment]
Hi @isathish 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
