### ISSUE TITLE
Request for Feedback: Your experience with the Azure Provider

### ISSUE THREAD

**Issue by opslivia** [hashicorp/terraform-provider-azurerm#15313]
:wave: 

We're looking to chat with folks about your experience using the Azure Provider to find out how to better serve the community.

We're particularly interested in:

* If you're using external tooling (such as the Azure CLI or ARM Templates) to deploy some resources instead of using Terraform?
* If you've tried to deploy something in the Azure Provider, had issues and couldn't find a workaround?
* How often you upgrade Terraform Core and/or if you're prevented from upgrading to the latest version?
* How often you upgrade the Provider and/or if you're prevented from upgrading to the latest version?

If you'd like to make your voice heard to the Azure Providers team about experiences like these or more, feel free to sign up for a quick one-on-one session with the product manager [here](https://calendly.com/hashicorp-oliviac/tf-azure-providers-experience)!

Thanks!

**Comment by holms** [comment]
Finally some ticket where I can tell about my pain.

* I'm trying to stay within terraform as much as I can.
* -- see below --
* Quite often, as I don't want any surprises later on. 
* Every few weeks

I have some remarks and questions which I'm unable to find answers pretty much anywhere.

* I'm unable to find an attribute reference in `azurerm_postgresql_flexible_server` and `azurerm_postgresql_server` for getting certificate, without the cert I can't authorize with postgresql provider in order to create users for the app. We've ended up just going to database and create users directly. If I'd like to deploy a new cluster, I'd have to provision database from backups manually. As there's no way to get certificate programmatically, maybe `azcli` can do IDK.. Even more, by default in flexible server ssl connection is enforced while in regular server there's a param `ssl_enforcement_enabled` which is fine. Finding a parameter in order to disable ssl for flexible server was a nice quest, and I had to find it because I have no way to get cert within terraform, so I can't create users too as I need to authorize with cert. In flexible server config, there is a  parameter `require_secure_transport`, I believe this somehow must be mentioned in docs of `azurerm_postgresql_flexible_server_configuration`, because I expect to have this parameter in `azurerm_postgresql_flexible_server` resource itself, but it's currently absent.
* In `azurerm_postgresql_flexible_server` also as `azurerm_postgresql_server`  resources the argument reference of port should be available. I'd go even further, the whole connection string should be available too as it's offered on azure portal. I believe many people need that.
* Something is wrong with `sku_name` available values of  `azurerm_postgresql_flexible_server`. In the docs it says that `B_Standard_B1ms` should work, well it does, but I expect other burstable b series to work too? I've tried `B_Standard_B2s` and `B_Standard_B2ms` and they doesn't work. The list of burstable sku's are in here: https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-b-series-burstable Maybe postgresql_flexible_server doesn't support this, I haven't even checked, but in such case this should be mentioned in docs. 
* It's heavily weird that so much difference between azurerm_postgresql_flexible_server and azurerm_postgresql_server resources also as related resources to each of these two resources ,like azurerm_postgresql_flexible_server_database for example. Name of attributes are different, in one you're using id, in another name.. 
* In `azurerm_kubernetes_cluster_node_pool` I've twisted my neck by trying to understand what's happening (when using spot instances) with `node_taints`. I've read docs maybe like 12 times before I've realized that I need this value in there no matter what:  `node_taints           = ["kubernetes.azure.com/scalesetpriority=spot:NoSchedule"]`. I mean if you leave it blank, then when cluster is created, this params becomes prefilled with this value, and they when you do `terraform apply`, terraform offers to recreate whole node_pool. I believe this could be articulated lot better than it is now.

I'm not sure should I open tickets for some of these issues..? A question about postgresql server certificate is the most I need answer for.

**Comment by magodo** [comment]
One idea: when provision a large scale infra, the provider is bit of a black box to them in runtime, in which case users can only observe the `terraform` output, or via inspecting the logs, to see what is happening. If everything goes fine, then it is not a big deal. Whilst if something goes wrong, especially when sometimes the provision takes too much time, or even timeout, the log is not so friendly to trouble shoot. As a solution, we can leverage the **distributed tracing** to make this a better experience.

In this point, we are refactoring the underlying Go SDK and the provider (e.g. the typed SDK). I think it is a good chance to introduce the tracing feature into the provider and the SDK (e.g. the opentelemetry). With this, the users can use the tracing to have a much better picture about what is going on. Meanwhile, the developers can use the tracing to better trouble shooting the performance issues.

I've personally integrated Jeager with opencensus (since Azure Go SDK track1 uses that) to the provider in my private build (there is also a PR #5120) when trouble shooting a bad performance issue #5067. which is really helpful. So really look forward to seeing it integrated in the provider (or even in the whole terraform).

**Comment by tombuildsstuff** [comment]
👋  hey folks

Whilst we appreciate the feedback so far, rather than having number of disparate topics covered in a single Github issue, to gain a better understanding of the use-cases and issues being faced we're looking to chat through these issues 1-to-1 instead.

As such please [feel free to schedule a session using the link above](https://calendly.com/hashicorp-oliviac/tf-azure-providers-experience) if you're interested in chatting further about your use-cases/issues - however for the moment I'm going to lock this issue so that we can coordinate the feedback in a single place.

Thanks!

**Comment by opslivia** [comment]
Thank you to everyone who met with us to share your experience with the Azure providers! I am closing this issue in favor of more targeted feedback forums around specific features. First area of focus: [Logic app resources](https://github.com/hashicorp/terraform-provider-azurerm/issues/16571).
