### ISSUE TITLE
Plan stalled with "cannot unmarshal DNS" message

### ISSUE THREAD

**Issue by doherty100** [hashicorp/terraform-provider-azurerm#15345]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* N/A: All resources affected.

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.95.0"
    }

    random = {
      source  = "hashicorp/random"
      version = "=3.1.0"
    }
  }
}

# Providers
provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  client_id       = var.arm_client_id
  client_secret   = var.arm_client_secret
  tenant_id       = var.aad_tenant_id
}

provider "random" {}
```

### Debug Output

https://gist.github.com/doherty100/cb3230844d75ca468af4a36b67cfa404 

### Panic Output

N/A

### Expected Behaviour

terraform plan operation should complete. 

### Actual Behaviour

terraform plan operation stalls with no console output for an extended period of time until interrupted with Ctrl-C. The following error message shows up in the log:

2022-02-09T12:28:54.505-0500 [DEBUG] provider.terraform-provider-azurerm_v2.95.0_x5: AzureRM Response Error: Get "https://management.azure.com/subscriptions/f6d69ee2-34d5-4ca8-a143-7a2fc1aeca55/providers?api-version=2016-02-01": dial tcp: lookup management.azure.com on 172.25.0.1:53: cannot unmarshal DNS message for https://management.azure.com/subscriptions/f6d69ee2-34d5-4ca8-a143-7a2fc1aeca55/providers?api-version=2016-02-01: timestamp=2022-02-09T12:28:54.505-0500

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

This behavior started two days ago in a seemingly random fashion. Have not been able to run any plan or apply operations since.

### References

* N/A

**Comment by doherty100** [comment]
Tagging @tombuildsstuff

**Comment by tombuildsstuff** [comment]
hi @doherty100 

We looked into this yesterday and it turned out to be a WSL / DNS issue - so we believe this is a WSL issue. This should be fixed by updating the DNS Server being used in WSL: https://askubuntu.com/questions/1364984/dns-not-working-on-wsl/1379082#1379082 / https://askubuntu.com/questions/958876/how-to-disable-ipv6-on-windows-subsystem-for-linux/1200257#1200257

Since this is a configuration issue rather than a bug in Terraform I'm going to close this issue for the moment, but since this appears to be a WSL issue I'd recommend filing an issue on the WSL repo so somebody there can take a look.

Thanks!

**Comment by d-huynh** [comment]
Hi @doherty100

The reason this doesn't work because WSL2 set your DNS server automatically and somehow sends a larger response than Go's limit. You can read the details [here](https://github.com/golang/go/issues/51127).

Until WSL2 or Go fix their problem, you can manually add the IP address of management.azure.com to your host file as explained [here](https://github.com/golang/go/issues/51127#issuecomment-1035018244).

Another solution is to disable the host file generation of WSL2 and add your desired DNS servers:
```shell
# check the current configurations
cat /etc/resolv.conf

# create the /etc/wsl.conf file to disable /etc/resolv.conf generation
printf "[network]\ngenerateResolvConf = false" >> /etc/wsl.conf

# remove the symlink WSL2 created
rm /etc/resolv.conf

# finally, add your public DNS server to the /etc/resolv.conf file. If your VPN server has a nameserver, add it too
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 1.1.1.1" >> /etc/resolv.conf
```

Hope this helps.

**Comment by derkoe** [comment]
Just compiled it with a current Go version and it works.

@tombuildsstuff can we have a patch version built with the new Go version?
