### ISSUE TITLE
`azurerm_log_analytics_linked_service.tags` still has changes after apply

### ISSUE THREAD

**Issue by heiazuo** [hashicorp/terraform-provider-azurerm#15357]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `terraform v1.1.2 on windows_amd64`
*  `azurerm v2.90.0`

### Affected Resource(s)
* `azurerm_log_analytics_linked_service.tags`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-la-232323"
  location = "West Europe"
}

resource "azurerm_automation_account" "test" {
  name                = "acctestAutomation-232323"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  sku_name = "Basic"

  tags = {
    Environment = "Test"
  }
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "acctestLAW-232323"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_linked_service" "test" {
  resource_group_name = azurerm_resource_group.test.name
  workspace_id        = azurerm_log_analytics_workspace.test.id
  read_access_id      = azurerm_automation_account.test.id
  tags = {
    ENV = "Test"
  }
}
```

### Debug Output
![azurerm_log_analytics_linked_service tags(bug)](https://user-images.githubusercontent.com/46072066/153369228-ace15969-b511-4ec2-b428-acf7ba5384cb.png)

### Expected Behaviour
do plan after apply dones have no changes

### Actual Behaviour
do plan after apply done still have changes

### Steps to Reproduce

1.`terraform init`
2.`terraform plan`
3.`terraform apply`
4.`terraform paln`

### References

* #0000

**Comment by myc2h6o** [comment]
Hi @heiazuo I'm able to repo. And per service team https://github.com/Azure/azure-sdk-for-go/issues/3883#issuecomment-623148248, tag is not supported for Linked Service. We'll probably deprecate the unsupported tag properties for this resource

**Comment by krowlandson** [comment]
Yes, this still seems to be an issue and as previously mentioned, this resource type [does not support tags](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support#microsoftoperationalinsights).

![image](https://user-images.githubusercontent.com/12268562/153584954-a30a7131-512c-4d67-a4de-8b55a85a5740.png)

Although changes were made as per https://github.com/Azure/azure-sdk-for-go/issues/3883#issuecomment-623148248 my observations of current behaviour are as follows:

- Defining the resource without a `tags` attribute in code results in the state file being updated upon a subsequent `apply`, as per the above.
- Setting `tags = {}` on the resource fixes the above, but as already mentioned, this resource doesn't support tags on the Azure platform and should therefore not have this option.
- Setting a populated `tags` attribute results in Terraform continually wanting to add the tags due to the resource type not supporting them. This results in the following upon every subsequent `apply`:

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_log_analytics_linked_service.management will be updated in-place
  ~ resource "azurerm_log_analytics_linked_service" "management" {
        id                  = <redacted>
        name                = "Automation"
      ~ tags                = {
          + "test" = "value"
        }
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Ideally, I think we need to remove the `tags` attribute completely from the resource and documentation.
