### ISSUE TITLE
Terraform azurerm backend isn't working properly

### ISSUE THREAD

**Issue by luckypolamreddy** [hashicorp/terraform-provider-azurerm#15373]
Hi,

I identified there an issue with azurerm provider , when i am trying to configure azurerm backend sometimes it is working and sometimes it not working and it varies computer to computer i mean with personal laptop it is working and with office laptops giving an error like 
Error: Error building ARM Config: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
│
│ To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
│ auth method - instructions for which can be found here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret
│
│ Alternatively you can authenticate using the Azure CLI by using a User Account.

Many times even if provided subscription id, tenant id in provider azure rm block also it is giving the same error .
the basic thing is not working, pls follow the below code

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.95.0"
    }
  }
  backend "azurerm" {
        resource_group_name  = "Chandra-Terraform-AKS"
        storage_account_name = "rearchnonprodgitops"
        container_name       = "tfstate"
        key                  = "non-prod/terraform.tfstate"
  }
}

provider "azurerm" {
}

attached the image as well

![Capture](https://user-images.githubusercontent.com/66781906/153541105-cfba6155-f85e-4e87-a39a-6c36b59a2712.PNG)

**Comment by tombuildsstuff** [comment]
hi @luckypolamreddy 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
