### ISSUE TITLE
Having trouble in azurerm_subscription_cost_management_export

### ISSUE THREAD

**Issue by SyedK1987** [hashicorp/terraform-provider-azurerm#15389]
### Terraform (and AzureRM Provider) Version

Terraform v1.1.3
on Windows x86

### Affected Resource(s)

`azurerm_subscription_cost_management_export`

### Terraform Configuration Files

`resource "azurerm_subscription_cost_management_export" "azbilling" {
name = var.bill_name
subscription_id = var.subscription_id
recurrence_type = "Weekly"
recurrence_period_start_date = local.start_date
recurrence_period_end_date = local.end_date
export_data_storage_location {
container_id = azurerm_storage_container.bill_container.resource_manager_id
root_folder_path = "/${var.recurrence_type}/costreport"
}

export_data_options {
type = "Usage"
time_frame = "TheLastWeek"
}
}`
### Expected Behaviour
Export should have created with Weekly recurrence with "Weekly export of last 7 days" option.
### Actual Behaviour

The Plan got failed with above error message.

### Steps to Reproduce

1. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @SyedK1987 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
