### ISSUE TITLE
Support for Managed Boot diagnostic Storage Account

### ISSUE THREAD

**Issue by stevanovic-milan** [hashicorp/terraform-provider-azurerm#15406]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Support to be able to set Managed Boot Diagnostic Storage Account for Virtual Machines.
This has already been implemented for **azurerm_windows_virtual_machine** and **azurerm_linux_virtual_machine**
* https://github.com/hashicorp/terraform-provider-azurerm/issues/8319

### New or Affected Resource(s)

* azurerm_virtual_machine

### Potential Terraform Configuration

```hcl
# boot_diagnostics = true #(without specifying storage_account_uri)
```

### References
* https://docs.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics#boot-diagnostics-storage-account

**Comment by tombuildsstuff** [comment]
hi @stevanovic-milan 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!
