### ISSUE TITLE
azurerm_application_gateway - identity block - type, should default to UserAssigned as it's the only allowed value

### ISSUE THREAD

**Issue by jdelforno** [hashicorp/terraform-provider-azurerm#15445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.15
* AzureRM Provider version: 2.96.0

### Terraform Configuration Files

N/A - Issue is rather straight forward.

### Description / Feedback

Default the Identity type to "UserAssigned" as it's **currently** the only type available.

Edit: Also since upgrading, I'm now constantly seeing the Application Gateway doing an in-place upgrade for the Identity block.

**Comment by tombuildsstuff** [comment]
hi @jdelforno 

We're currently working through making the `identity` block behaviourally consistent across the Provider (see https://github.com/hashicorp/terraform-provider-azurerm/issues/15187 for details) - as a part of this we're moving to be behaviourally consistent in requiring that the `identity` block is specified when a Managed Identity is assigned to a resource, so that users can be sure an identity is present.

As such in order to be behaviourally consistent across the provider, unfortunately we have no plans to make this field optional & defaulted - as this would mean a breaking change to the configuration should other Identity types (such as `SystemAssigned`, or `SystemAssigned, UserAssigned`) become available in the future.

The other issue here (the `identity` block not being set into the state) is a regression which has been previously opened in #15411 and has been fixed by https://github.com/hashicorp/terraform-provider-azurerm/pull/15412 which will ship in the next release.

Thanks!
