### ISSUE TITLE
Support for attach multiple user identities to Kubernetes nodes

### ISSUE THREAD

**Issue by flmmartins** [hashicorp/terraform-provider-azurerm#15567]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Today in azurerm_kubernetes_cluster you can assign one identity to kubelet and one identity to manage the cluster but I have a use case where we use **User Assigned Identities** for some **applications** and we need to attach those to default nodes or to other nodes in the cluster.

Example: We use external DNS so we create a user assigned identity for that and attach to the default nodes so we can use it together with pod identity.

Today we do this by invoking a script that does this by attaching the identities to the VMSS. 

```shell
echo ${IDENTITY_LIST} | \
             curl -f -s -X PATCH -d@- \
               -H "Authorization: Bearer ${TOKEN}" \
               -H Content-Type:application/json \
               -H Accept:application/json \
               https://management.azure.com/${VMSS_ID}\?api-version=2018-06-01)
```

Is it possible to do something like this for azurerm_kubernetes_cluster or azurerm_kubernetes_cluster_node_pool?

For azurerm_windows_virtual_machine_scale_set and azurerm_linux_virtual_machine_scale_set I noticed this is already possible since the identity block accepts a list but since the nodes are created as part of Kubernetes then it should have an option here as well.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster
* azurerm_kubernetes_cluster_node_pool

**Comment by tombuildsstuff** [comment]
hi @flmmartins 

Thanks for opening this issue.

The AKS API provisions a bunch of different resources behind the scenes based on the options provided (which is what Terraform passes to the Azure API) - whilst it does provision a VM Scale Set for you (when VMSS mode is used) - this functionality isn't exposed via the API and as the names etc could change it's not reliable for Terraform to update these AKS managed node pools.

As such in order for us to expose this functionality in Terraform it would need to be added to the AKS API - since this isn't available today (but as you've mentioned would likely make sense against the specific Node Pool), I'd suggest [opening an issue on the AKS Repository](https://github.com/Azure/AKS/issues) where someone from the AKS Team should be able to take a look - but since this isn't something we can support in the Azure Provider at this point in time I'm going to close this issue for the moment.

Thanks!
