### ISSUE TITLE
Support for [Configure terraform module to create an Azure Alert V2]

### ISSUE THREAD

**Issue by bhanumaddineni** [hashicorp/terraform-provider-azurerm#15588]
Hi Team,

Currently we have terraform module to create an Azure Alert V1.
Please help us to configure terraform module to create an Azure Alert V2 and see the below link for some details.  

https://cloudadministrator.net/2021/11/04/azure-monitor-log-alert-v2/

Regards,
Bhanu Maddineni
bmaddineni@avidxchange.com

**Comment by tombuildsstuff** [comment]
hi @bhanumaddineni 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by bhanumaddineni** [comment]
we're requesting to do the enhancement of using the latest API to allow it the existing module to create V2 alert
