### ISSUE TITLE
azurerm_monitor_diagnostic_categories - Unalbe to retrieve Azure Storage File Shares Diagnostic Categories

### ISSUE THREAD

**Issue by minimusgeekus** [hashicorp/terraform-provider-azurerm#15606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.1.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.98.0

### Affected Resource(s)

* `azurerm_monitor_diagnostic_categories`

### Terraform Configuration Files

```hcl
data "azurerm_storage_share" "example" {
  name                 = "myShare"
  storage_account_name = "myStorageAccount"
}


data "azurerm_monitor_diagnostic_categories" "files" {
  resource_id = data.azurerm_storage_share.example.resource_manager_id
}
```

### Expected Behaviour
Data object ```data.azurerm_monitor_diagnostic_categories.files``` should have contained a list of available log and diagnostic metrics for the resource, in this case an Azure Storage File Share. This object would then be iterated / consumed in a dynamic block to apply diagnostic settings.

### Actual Behaviour
╷
│ Error: retrieving Diagnostics Categories for Resource "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myRresourceGroup/providers/Microsoft.Storage/storageAccounts/myStorageAccount/fileServices/default/fileshares/myFileShare": insights.DiagnosticSettingsCategoryClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ResourceTypeNotSupported" Message="The resource type 'microsoft.storage/storageaccounts/fileservices/fileshares' does not support diagnostic settings."
│ 
│   with data.azurerm_monitor_diagnostic_categories.files,
│   on main.tf line 23, in data "azurerm_monitor_diagnostic_categories" "files":
│   23: data "azurerm_monitor_diagnostic_categories" "files" {
│ 
╵

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @minimusgeekus 

Thanks for opening this issue.

Based on this error message coming from the Azure API it appears that this is unsupported for this type of resource:

> The resource type 'microsoft.storage/storageaccounts/fileservices/fileshares' does not support diagnostic settings.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
