### ISSUE TITLE
Duplicate Resource Group Resources Possible

### ISSUE THREAD

**Issue by dutsmiller** [hashicorp/terraform-provider-azurerm#15633]
It seems as though the provider is allowing duplicate resource groups upon initial provisioning.  When the code below is run, it succeeds successfully with both resource groups displayed in terraform state, although with only one existing in the portal.  If you then run a targeted terraform destroy on the second resource group, all of the resources will be removed from Azure while only the second resource group is removed from terraform state.   The fact that the contents of the first resource group will be destroyed is NOT displayed anywhere in the terraform plan.  Note:  The prevent_destroy lifecycle blocks are not required to produce the bug, but rather added to demonstrate the potential magnitude of its effects.

```
provider "azurerm" {
  features {}
}

resource "random_string" "random" {
  length  = 12
  upper   = false
  special = false
}

resource azurerm_resource_group "test1" {
  name = random_string.random.result
  location = "eastus2"
  lifecycle {
    prevent_destroy = true
  }
}

resource "azurerm_storage_account" "example" {
  name                     = random_string.random.result
  resource_group_name      = azurerm_resource_group.test1.name
  location                 = azurerm_resource_group.test1.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  lifecycle {
    prevent_destroy = true
  }
}

resource azurerm_resource_group "test2" {
  name = random_string.random.result
  location = "eastus2"
}
```

It's important to note that if the second resource group block is attempted to be added after the initial apply, terraform throws an error about the resource already existing.

I did some testing with the az cli and it seems that the `az group create` command mimics the `az group update` command if the group already exists.  What that means is that you can run the same `az group create` command repeatedly and it will always return "succeeded". As such, I'm not sure this is entirely an azurerm provider bug given one would hope the Azure API would throw an error on a create command if the resource group already exists.

**Comment by tombuildsstuff** [comment]
hi @dutsmiller 

Thanks for opening this issue.

Whilst the Azure Provider does check for the presence of an existing resource during the creation of a resource to ensure that we don't unintentionally adopt it (and raise an error if one is found with a matching name/resource group etc) - that doesn't handle duplicate resources which are created in parallel. There's a feature-request on the Terraform Plugin SDK repository which is tracking support for a feature which'll make this possible - and as such I'm going to close this in favour of the upstream issue (https://github.com/hashicorp/terraform-plugin-sdk/issues/224) for the moment.

Thanks!

**Comment by dutsmiller** [comment]
@tombuildsstuff So, just to clarify, there's nothing that can be done within the provider such that this code would fail (as it absolutely SHOULD).

```
provider "azurerm" {
  features {}
}
resource "random_string" "random" {
  length  = 12
  upper   = false
  special = false
}
resource azurerm_resource_group "test1" {
  name = random_string.random.result
  location = "eastus2"
}
resource azurerm_resource_group "test2" {
  name = random_string.random.result
  location = "eastus2"
  tags = { foo = "bar" }
}
resource azurerm_resource_group "test3" {
  name = random_string.random.result
  location = "eastus2"
  tags = { bar = "baz" }
}
resource azurerm_resource_group "test4" {
  name = random_string.random.result
  location = "eastus2"
  tags = { baz = "foo" }
}
```
Currently you can run that code from scratch and subsequent applies have no complaints.  The applied tags end up being whatever ran last.

**Comment by stevehipwell** [comment]
> Whilst the Azure Provider does check for the presence of an existing resource during the creation of a resource to ensure that we don't unintentionally adopt it (and raise an error if one is found with a matching name/resource group etc) - that doesn't handle duplicate resources which are created in parallel.

@tombuildsstuff could you confirm that by parallel you mean at the same level in the graph and that if there were dependencies or `depends_on` linking these resources the creation would fail? Or do you actually mean "in the same workspace and added at the same time"?

Although https://github.com/hashicorp/terraform-plugin-sdk/issues/224 would potential solve or mitigate this specific issue it's shouldn't have to. I also don't think it wouldn't fix the resource group being adopted in another workspace?

I think this should be fixable (good enough) in the provider. Take for example the original bug with 2 resource groups called the same. With a provider backed by an actual "REST" API the easy (and correct) implementation would be that the plan defines two POST calls with the first one run returning 201 and the second one returning an error code causing a failure. Due to the way the Azure API has been "designed" (idempotency isn't a silver bullet as this issue shows) the plan creates two PUT calls, the easy (and not correct) implementation here is to allow all non error codes, which causes this issue. A slightly more correct solution is to make sure the correct code is returned and error if a 200 comes back when a resource is created, although this has side effects. A better solution would be to check for existence or the resource before creation to catch obvious errors and then check the correct code is returned. There is actually no correct solution here with the current Azure API design.
