### ISSUE TITLE
azurerm_network_security_rule - slow rule add process

### ISSUE THREAD

**Issue by jcavet** [hashicorp/terraform-provider-azurerm#15631]
It's been a thorn for quite some time now but can someone please explain why the process of adding rules to a security group is painfully slow and never improves?

Ranges from adding 5 rules to 25 rules etc. Each time it literally adds one rule at a time. Are we that limited by M$ APIs?

Is there anything in the plans to help with this process and improve performance? It's night and day between AWS & Azure.

**Comment by tombuildsstuff** [comment]
hi @jcavet 

Thanks for opening this issue.

There's two approaches to provisioning Rules within a Network Security Group - both inline within the `azurerm_network_security_group` resource and using the `azurerm_network_security_rule` resource, however since the Azure API mutates the same underlying object there's a lock in place within the provider to workaround concurrency issues within the API. In this instance this lock can be disabled using the `features` block (as shown below) - but we'd recommend defining the rules within the `azurerm_network_security_group` resource where possible since it avoids these API concurrency issues by submitting these as a single API call.

```hcl
provider "azurerm" {
  features {
    network {
      relaxed_locking = true
    }
  }
}
```

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
