### ISSUE TITLE
Support for AKS CNI mode: none

### ISSUE THREAD

**Issue by TheKangaroo** [hashicorp/terraform-provider-azurerm#15663]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS supports a new CNI mode "none" which disables Azure managed CNI and makes it easier to bring your own cni.

The CNI mode "none" is already present in the API and in the az cli (aks-preview extension).

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"
  network_plugin      = "none"          # allowed values used to be 'azure' and 'kubenet'. new option is 'none'

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }
}

```

### References

* https://github.com/Azure/AKS/issues/2092

**Comment by mattstam** [comment]
Thanks for adding this @TheKangaroo! And yes we definitely want to be explicit about needing `none` set. It *is not* the default networking option and has unique requirements for getting your clusters up and running, so we want to avoid users accidentally configuring this.

**Comment by ekarlso** [comment]
Any idea on when this will be live?

**Comment by ekarlso** [comment]
@tombuildsstuff would a PR be accepted for this or ?

**Comment by stephybun** [comment]
@TheKangaroo @mattstam, thanks for sharing your concerns.

We are gradually making the behaviour of fields across the provider consistent, hence leaving this property unset should imply `none` rather than explicitly setting the value to `none` as @tombuildsstuff already mentioned.

That being said I do agree from a UX perspective that we should not be facilitating the accidental creation of clusters that are not functional. In truth this option might be better named as `custom` since that is the intention, something which we will bring up with the AKS team.

**Comment by ekarlso** [comment]
@stephybun @tombuildsstuff could we aim to get this for 3.3.0 somehow?
