### ISSUE TITLE
Bug: azurerm_firewall_policy_rule_collection_group

### ISSUE THREAD

**Issue by omerfeldman2** [hashicorp/terraform-provider-azurerm#15682]
Editing/adding/deleting specific rule in azurerm_firewall_policy_rule_collection_group will delete and recreate all the rules in the group instead of manipulating the specific rule.

**Comment by sinbai** [comment]
@omerfeldman2 thank you for opening this issue. Could you please provide your .tf config to help repro/troubleshooting?

**Comment by manicminer** [comment]
@omerfeldman2 Thanks for raising this. Unfortunately we will need some more information in order to effectively reproduce and debug this. I'm going to close this issue for now - please could you open a new issue using our bug reporting template and provide as much info as you can (including a reproducible config as @sinbai mentioned)? Thanks!
