### ISSUE TITLE
Unable to manage containers when network is denied on storage account

### ISSUE THREAD

**Issue by gsmartvoda** [hashicorp/terraform-provider-azurerm#15683]
Unable to manage containers when network is denied on storage account. We are using TFE & a service principal which has owner access across the subscription but is unable to access the container. 

Code below. 

resource "azurerm_storage_account" "dxdssa" {
  name                     = "dxds${var.environment}sa"
  resource_group_name      = *
  location                 = data.azurerm_resource_group.dxresourcegrp.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  allow_blob_public_access	= true
  is_hns_enabled           = "true"
  
  network_rules {
    default_action = "Deny"
    ip_rules                   = ["100.0.0.1"]
  }
}

resource "azurerm_storage_container" "dxdssa" {
  name                  = "raw"
  storage_account_name  = "dxds${var.environment}sa"
  container_access_type = "private"
}

Error below:

Error retrieving Container "raw" (Account "dxdsdevsa" / Resource Group "*"): containers.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.

Any suggestions?

**Comment by tombuildsstuff** [comment]
hi @gsmartvoda 

The Azure Provider needs to be able to query the Containers Data Plane endpoint, as such it'll need access to the Storage Account.

This is required since the Data Plane and Resource Manager API's for Storage aren't currently feature-compatible - which means that we need to access both to be able to determine if there's any changes. #2977 is tracking the work required to switch to using the Resource Manager API, however unfortunately this is blocked on the Service Team making these two API's feature-compatible.

Since this is currently required and this'll be fixed by #2977, rather than having multiple issues open tracking the same thing I'm going to close this in favour of #2977 - once this is supported by the Service Team then we can take a look into switching to use the Resource Manager API for this in the future.

Thanks!
