### ISSUE TITLE
terraform create AKS use existing application gateway seem to be broken

### ISSUE THREAD

**Issue by theasphaltworld** [hashicorp/terraform-provider-azurerm#15693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.4
azurerm v2.98.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
ingress_application_gateway {
     subnet_id    = var.ingress_agic_subnet == null ? null : data.azurerm_subnet.ingress_agic_subnet[0].id  # subnet where I created App gateway
      gateway_id   = var.ingress_application_gateway_id  #existing  app gateway ID
   }
```

### Expected Behaviour

it should take the existing app gateway and configure AGIC on it

### Actual Behaviour

getting error
Error: Conflicting configuration arguments
│
│   with module.aks.azurerm_kubernetes_cluster.this,
│   on terraform-azurerm-lab3-aks\main.tf line 70, in resource "azurerm_kubernetes_cluster" "this":
│   70:       subnet_id    = var.ingress_agic_subnet == null ? null : data.azurerm_subnet.ingress_agic_subnet[0].id
│
│ "ingress_application_gateway.0.subnet_id": conflicts with ingress_application_gateway.0.gateway_id
╵
╷
│ Error: Conflicting configuration arguments
│
│   with module.aks.azurerm_kubernetes_cluster.this,
│   on terraform-azurerm-lab3-aks\main.tf line 73, in resource "azurerm_kubernetes_cluster" "this":
│   73:       gateway_id   = var.ingress_application_gateway_id
│
│ "ingress_application_gateway.0.gateway_id": conflicts with ingress_application_gateway.0.subnet_id
╵

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by stephybun** [comment]
Hi @theasphaltworld,

Thanks for raising this issue. The AKS API will create an Application Gateway for you based on the `subnet_id` or `subnet_cidr` provided, or you can BYO Application Gateway. As a result it isn't possible to specify both `subnet_id` and `gateway_id` since that would trigger conflicting behaviours in the API. Since you already have an existing Application Gateway the only property you need to set is the `gateway_id`.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment.
Thanks!
