### ISSUE TITLE
unable to use null to ignore ingress_application_gateway block

### ISSUE THREAD

**Issue by theasphaltworld** [hashicorp/terraform-provider-azurerm#15695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.4
Azurerm v.2.97.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
ingress_application_gateway{
gateway_id = var.gateway_id
subnet_id = var.subnet_id
}
```

### Expected Behaviour
i don't understand why the new verison of azurerm removed enabled switch
I thought by removing that switch, you can set, allthose variables to null, and then it won't provision that AGIC

### Actual Behaviour
if you set those variables to null
it will complain
"ingress_application_gateway.0.subnet_id": one of
│ `ingress_application_gateway.0.gateway_id,ingress_application_gateway.0.subnet_cidr,ingress_application_gateway.0.subnet_id` must be specified

does it mean if I have that ingress_application_gateway block, then I must enable application gateway AGIC? previously, you can use switch to control

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by stephybun** [comment]
Hi @theasphaltworld,

Thanks for raising this issue. Whilst blocks containing an `enabled` switch are still present in the provider today it isn't consistent with the behaviour that blocks typically have in the provider which is that if a block is absent it is equivalent to it being null i.e. disabled in this particular case.

Just to clarify, omitting the entire `ingress_application_gateway` block is equivalent to
```
addon_profile {
  ingress_application_gateway {
    enabled = false
  }
}
```
in the deprecated schema.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment.
Thanks!
