### ISSUE TITLE
azurerm_app_service_plan terraform import Azure ID is serverFarms not serverfarms

### ISSUE THREAD

**Issue by Elthas17** [hashicorp/terraform-provider-azurerm#15723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.6                                                                    
on windows_amd64                                                                    
+ provider registry.terraform.io/hashicorp/azurerm v2.98.0  
```

azurerm_app_service_plan

### Terraform Configuration Files
NA

### Debug Output
NA

### Expected Behavior

When importing an existing resource the Azure Resource ID is required in the command:
`terraform import <Terraform Resource Name>.<Resource Label> <Azure Resource ID>` 

The Azure Resource ID contains 'resourceFarms' and not 'resourcefarms' , but terraform expects it to contain 'resourcefarms' so the command  fails. when i change the ID so that it contains 'resourcefarms' it passes but this is not what Azure provides as an ID. 

### Actual Behavior
When running
`terraform import <Terraform Resource Name>.<Resource Label> <Azure Resource ID>` 
as
`terraform import azurerm_app_service_plan.<myappserviceplan> /subscriptions/<mysubscription>/resourceGroups/<myresourcegroup>/providers/Microsoft.Web/serverFarms/<myappserviceplan>`

i get the error:
` Error: parsing Resource ID "/subscriptions/<mysubscription>/resourceGroups/<myresourcegroup/serverFarms/freeserviceplan": ID was missing the 'serverfarms' element`

when i run it as 
`terraform import azurerm_app_service_plan.<myappserviceplan> /subscriptions/<mysubscription>/resourceGroups/<myresourcegroup>/providers/Microsoft.Web/serverfarms/<myappserviceplan>` 
the command succeeds but this is not the ID given by Azure in the azure web portal. 

### Steps to Reproduce
run above commands

**Comment by tombuildsstuff** [comment]
hi @Elthas17 

Thanks for opening this issue.

When importing resources into Terraform we require that the ID specified at Import time matches the casing we're expecting - and if these don't match then (as you've highlighted) we raise an error that the given segment doesn't match what we're expecting.

An example of the Resource ID (including casing) required for each Resource can be found in the `Import` section of the documentation  for each Resource, for example for an App Service Plan this can be found here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_plan#import.

Since Terraform is correctly raising here that the Resource ID doesn't match the format/casing we're expecting, I'm going to close this out as a usage question - but as mentioned above Terraform will return an error if the Resource ID doesn't match the casing that we're expecting where it's necessary, as we're parsing these based on the casing specified.

Thanks!

**Comment by Elthas17** [comment]
@tombuildsstuff  

thanks for your reply.

Azure does not allow to choose what the resource ID looks like, its decided by azure and is to be copy pasted from their webportal. So i would assume that this ID is to be treated 'as a given'  and terraform should follow the ID as provided by Azure?

So how can we match the expected casing without modifying manually what the ID is? 

kind regards
