### ISSUE TITLE
Imported azurerm_key_vault_key shall be replaced because of new attribute key_vault_id

### ISSUE THREAD

**Issue by flobeier** [hashicorp/terraform-provider-azurerm#15806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* Terraform: `1.1.3`
* azurerm: `2.99.0`

### Affected Resource(s)

* `azurerm_key_vault_key`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_key" "example" {
  name         = "rsa-${azurerm_mssql_server.example.name}"
  key_vault_id = azurerm_key_vault.example.id
  key_type     = "RSA"
  key_size     = 3072

  key_opts = [
    "unwrapKey",
    "wrapKey",
  ]

  tags = local.tags
}
```
### Expected Behaviour
Import does not lead to a resource that shall be replaced on the next `terraform apply` because the code matches the imported resource.

### Actual Behaviour
Terraform wants to replace the key because of a new attribute, key_vault_id:
```log
+ key_vault_id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-example/providers/Microsoft.KeyVault/vaults/kv-example" # forces replacement
```

### Steps to Reproduce

1. `terraform import <resource id of the key>`
2. `terraform plan`

**Comment by jackofallops** [comment]
HI @flobeier - This value can be added to your imported configuration to satisfy the diff and prevent recreation. Details on importing items into Terraform's control can be found [here on our learn site](https://learn.hashicorp.com/tutorials/terraform/state-import).   Since that attribute is being added, not changed, it suggests that it is missing from your config.

Note that if you have imported the Key Vault also the ID used for that import must match the case expectations of Terraform as per the example in the Key Vault docs. A case difference there will trigger a replacement.

Hope this helps.

**Comment by flobeier** [comment]
@jackofallops the key_vault_id attribute is missing when importing a key, sorry if I was not being clear enough. I confirmed this by having a look at the state, it is not there.

To summarize: When importing a key, Terraform wants to destroy and create it again on the next apply because the key_vault_id is not added during the import.

**Comment by ms-zhenhua** [comment]
Hi @flobeier , seems this issue is the same as [this one](https://github.com/hashicorp/terraform-provider-azurerm/issues/12357) and has been [fixed ](https://github.com/hashicorp/terraform-provider-azurerm/pull/15670) recently in [v2.99.0 of the Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.99.0/CHANGELOG.md). I have test with the latest Terraform Provider version and it works well. Could you kindly help check whether you are using the latest version (v2.99.0) ?

BTW, if you ran **import** with older Provider version and ran it again with v2.99.0, you may got the following **Error**. In this case, **key_vault_id** won't be updated. You have to manually open the **terraform.tfstate** file to update **key_vault_id** from **null** to **"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/...."**
![image](https://user-images.githubusercontent.com/76987228/158498826-a05df986-30f3-430c-91a2-cb3e72993d43.png)

Hope this helps.

**Comment by flobeier** [comment]
@ms-zhenhua thank you very much for your help! I removed the key from the state file using `terraform state rm` and imported it using azurerm v2.98.0, the key_vault_id was missing. Doing the same with v2.99.0 was successful, the key_vault_id is now in the state file. I must have imported the key using v2.98.0 instead of v2.99.0.
