### ISSUE TITLE
azurerm_kubernetes_cluster does not provide load_balancer_profile attribute block

### ISSUE THREAD

**Issue by michaelelleby** [hashicorp/terraform-provider-azurerm#15937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
output "egress_ip_addresses" {
  value = azurerm_kubernetes_cluster.mycluster.load_balancer_profile.effective_outbound_ips
}
```

### Expected Behaviour

List of load balancer IPs should be output.

### Actual Behaviour

```
│ Error: Unsupported attribute
│
│   on modules\kubernetes\output.tf line 66, in output "egress_ip_addresses":
│   66:   value = azurerm_kubernetes_cluster.mycluster.load_balancer_profile.effective_outbound_ips
│
│ This object has no argument, nested block, or exported attribute named "load_balancer_profile".
```

### Steps to Reproduce

1. `terraform validate`

### References

* [Documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#attributes-reference) states an attribute block `load_balancer_profile ` is available with the property `effective_outbound_ips`

**Comment by stephybun** [comment]
Hi @michaelelleby,

Thanks for raising this issue!

The `load_balancer_profile` block is nested under the `network_profile` block, in addition the index also needs to be specified when accessing nested attributes, so the output should be 
```
output "egress_ip_addresses" {
  value = azurerm_kubernetes_cluster.mycluster.network_profile.0.load_balancer_profile.0.effective_outbound_ips
}
```

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment.

Thanks!
