### ISSUE TITLE
Old version of AzureRM Provider installed

### ISSUE THREAD

**Issue by amarkevich** [hashicorp/terraform-provider-azurerm#15972]
### Terraform (and AzureRM Provider) Version

Terraform v1.1.7
```
  required_providers {
    azurerm = {
      version = "~>2.2"
    }
```

### Affected Resource(s)

16.03.2022
```
- Installing hashicorp/azurerm v2.99.0...
- Installed hashicorp/azurerm v2.99.0 (signed by HashiCorp)
```

23.03.2022
```
- Installing hashicorp/azurerm v2.70.0...
- Installed hashicorp/azurerm v2.70.0 (unauthenticated)
```

### Debug Output

```
│ Error: Resource instance managed by newer provider version
│ 
│ The current state of [hidden] was
│ created by a newer provider version than is currently selected. Upgrade the
│ azurerm provider to work with this state.
```

### Expected Behaviour

no provider version downgrade

### Actual Behaviour

old version selected which cause mentioned error

### Steps to Reproduce

found during this week

**Comment by tombuildsstuff** [comment]
hi @amarkevich 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by amarkevich** [comment]
I'm unable to use mentioned resource:
![image](https://user-images.githubusercontent.com/62415/159695023-ac01f7f5-09d5-456c-b8f7-22d2438e2731.png)

**Comment by amarkevich** [comment]
Solved: recently pipeline switched to private agent with old provider version installed
