### ISSUE TITLE
Invalid resource type: azurerm_function_app_function

### ISSUE THREAD

**Issue by jesskranz** [hashicorp/terraform-provider-azurerm#16015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.7

### Affected Resource(s)

* `azurerm_function_app_function`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

provider "azurerm" {
  version = "= 2.99.0"
  features {}
}

```

### Expected Behaviour

I should be able to include 'azurerm_function_app_function' in my apply, and terraform should recognise it. 

### Actual Behaviour

Error: Invalid resource type

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @jesskranz 

Thanks for opening this issue.

This new resource is coming in the 3.0 Beta, which can be enabled in v2.99 of the AzureRM Provider: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-beta.

There should be a "this resource requires the Beta" notice at the top of that page in v2.99 (as with the other Beta resources), but unfortunately that's missing from the documentation - however we're working to release v3.0 of the AzureRM Provider at the moment so this should GA later today.

Since this is going to be fixed in version 3.0 I'm going to close this issue for the moment - and assign this to the 3.0 milestone so that when version 3.0 is available a comment will be left to let you know - however it should be able to use this in the interim by enabling the Beta as linked above.

Thanks!
