### ISSUE TITLE
3.0.0 An argument named "allow_blob_public_access" is not expected here

### ISSUE THREAD

**Issue by raypet-cillco** [hashicorp/terraform-provider-azurerm#16023]
Code that worked with previous version started throwing allow_blob_public_access not expected errors.

Glancing at release-notes I don't see anything about it being deprecated/removed.

**Comment by tombuildsstuff** [comment]
hi @raypet-cillco 

Thanks for opening this issue.

As 3.0 is a major release a complete list of changes can be found [in the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - which is [linked from the changelog since this is a major version](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022).

In this case this field has been renamed to `allow_nested_items_to_be_public`, however there maybe other changes you need to make to your Terraform Configuration to be compatible with v3.0 - we'd recommend consulting the upgrade guide.

Thanks!

**Comment by raypet-cillco** [comment]
Thanks for the detailed info. Reading through the upgrade documentation, indeed it's mentioned there and I can patch the problem on my side. Apologies for not diving deep enough when this blew up in our tests.
