### ISSUE TITLE
An argument named "allow_blob_public_access" is not expected here.

### ISSUE THREAD

**Issue by ronaldmundell01** [hashicorp/terraform-provider-azurerm#16032]
PS D:\GIT\NZTA\SharedResources\azure-templates\terraform\linux-vm> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/random...
- Finding hashicorp/azurerm versions matching ">= 2.55.0"...
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/tls...
- Installing hashicorp/random v3.1.2...
- Installed hashicorp/random v3.1.2 (signed by HashiCorp)
- Installing hashicorp/azurerm v3.0.1...
- Installed hashicorp/azurerm v3.0.1 (signed by HashiCorp)
- Installing hashicorp/null v3.1.1...
- Installed hashicorp/null v3.1.1 (signed by HashiCorp)
- Installing hashicorp/tls v3.1.0...
- Installed hashicorp/tls v3.1.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
PS D:\GIT\NZTA\SharedResources\azure-templates\terraform\linux-vm> terraform plan 
╷
│ Error: Unsupported argument
│
│   on storage-account.tf line 9, in resource "azurerm_storage_account" "diagnostic-storage":
│    9:   allow_blob_public_access  = false
│
│ An argument named "allow_blob_public_access" is not expected here

esource "azurerm_storage_account" "diagnostic-storage" {
  name                      = "${var.vm_name}diagstg"
  resource_group_name       = var.target_resource_group
  location                  = var.target_location
  account_kind              = var.storage_account_kind
  account_tier              = var.storage_account_tier
  account_replication_type  = var.storage_account_replication_type
  enable_https_traffic_only = true
  allow_blob_public_access  = false
  min_tls_version           = "TLS1_2"
}

**Comment by katbyte** [comment]
Hey @ronaldmundell01,

Thanks for opening this issue.

As 3.0 is a major release a complete list of changes can be found [in the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - which is [linked from the changelog since this is a major version](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022).

In this case this field has been renamed to `allow_nested_items_to_be_public`, however there maybe other changes you need to make to your Terraform Configuration to be compatible with v3.0 - we'd recommend consulting the upgrade guide.

We'd recommend pinning the version of the Azure Provider being used, for example to pin to `3.0.0`:

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=3.0.0"
    }
  }
}
```

You can also pin to the last 2.x release temporarily as shown below, however note that any future enhancements will ship in 3.x:

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.99.0"
    }
  }
}
```

Thanks!

**Comment by ronaldmundell01** [comment]
the documentation is still reflecting the incorrect information

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account
