### ISSUE TITLE
Support for Logic Apps with consumption

### ISSUE THREAD

**Issue by luxu-ms** [hashicorp/terraform-provider-azurerm#16035]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the terraform documentation, our customer only find the provision with standard logic apps, is there option to provision the consumption logic apps?

### New or Affected Resource(s)

* azurerm_logic_app_standard

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by neil-yechenwei** [comment]
@luxu-ms , thanks for raising this issue. Seems it has been supported by [azurerm_logic_app_workflow](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_workflow).

**Comment by luxu-ms** [comment]
Thanks @neil-yechenwei. What the customer wants to do is to provision the plan type consumption
![image](https://user-images.githubusercontent.com/92287281/160060251-b72ce064-b3c3-4e18-b038-623cc7561c9e.png)

according to the existing terraform docs, it should have another resource called "azurerm_logic_app_consumption" to differentiate with "azurerm_logic_app_standard".

**Comment by neil-yechenwei** [comment]
Seems the resource with plan consumption created via azure portal is same with the resource created via tf azurerm_logic_app_workflow. If it's unexpected, could you share the rest api link for this scenario since I didn't find it? Thanks.

**Comment by tombuildsstuff** [comment]
@luxu-ms support for Logic App Consumption is available [via the `azurerm_logic_app_workflow` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_workflow) (it was previously called just `Logic App`) - whereas Logic App Standard is available [via the `azurerm_logic_app_standard` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_standard).

Since support for this is already available within Terraform I'm going to close this issue for the moment, but should those not provision what you need then please let us know and we can take another look.

Thanks!
