### ISSUE TITLE
"allow_blob_public_access" is not expected in azurerm_storage_account!

### ISSUE THREAD

**Issue by ttaher** [hashicorp/terraform-provider-azurerm#16049]
Hi All ,
Yesterday , suddenly we had an issue in terraform plan command in our pipeline which was working well before with the same code 
to create azurerm_storage_account  with allow_blob_public_access  = true 
but with anew changes the pipeline failed  i attahced the code we use and the issue 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 13.5
AzureRM: v3.0.1
### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "stgacnt" {
  name                     = var.STORAGE_ACCOUNT_NAME
  resource_group_name      = data.azurerm_resource_group.rg.name
  location                 = data.azurerm_resource_group.rg.location
  account_tier             = var.STORAGE_ACCOUNT_TIER
  account_replication_type = var.STORAGE_ACCOUNT_REPLICATION_TYPE
  allow_blob_public_access = "true"

  static_website {
    index_document = "index.html"
  }
  
}
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
### Debug Output
Providers required by configuration:
.
└── provider[registry.terraform.io/hashicorp/azurerm] >= 2.46.0

Providers required by state:

    provider[registry.terraform.io/hashicorp/azurerm]

C:\hostedtoolcache\windows\terraform\0.14.10\x64\terraform.exe plan -out=tfplan -detailed-exitcode

Error: Unsupported argument

  on main.tf line 25, in resource "azurerm_storage_account" "stgacnt":
  25:   allow_blob_public_access = "true"

An argument named "allow_blob_public_access" is not expected here.

### Expected Behaviour

storage account should be created with "allow blob public access" set to true in portal.

### Actual Behaviour
See error above

### Steps to Reproduce

1. `terraform apply`

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#argument-reference

**Comment by christophernruud** [comment]
Have you looked at the migration guide to 3.0.0 or pinned your version to the latest 2.x release?
This issue is resolved in the migration guide:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide

**Comment by stephybun** [comment]
Hey @ttaher  ,

Thanks for opening this issue.

As 3.0 is a major release a complete list of changes can be found [in the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - which is [linked from the changelog since this is a major version](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022).

In this case this field has been renamed to allow_nested_items_to_be_public, however there maybe other changes you need to make to your Terraform Configuration to be compatible with v3.0 - we'd recommend consulting the upgrade guide.

We'd recommend pinning the version of the Azure Provider being used, for example to pin to 3.0.0:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=3.0.0"
    }
  }
}
```
You can also pin to the last 2.x release temporarily as shown below, however note that any future enhancements will ship in 3.x:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.99.0"
    }
  }
}
```
Thanks!
