### ISSUE TITLE
Issue with dynamic variable in azure

### ISSUE THREAD

**Issue by Pwd9000-ML** [hashicorp/terraform-provider-azurerm#16058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```hcl
terraform {
  required_version = "~> 1.1.0"
  backend "azurerm" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0.1"
    }
  }
}
```

### Affected Resource(s)

* `azurerm_container_registry`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "APPSVC" {
  name                = var.appsvc_name
  location            = azurerm_resource_group.RG.location
  resource_group_name = azurerm_resource_group.RG.name
  service_plan_id     = azurerm_service_plan.ASP.id
  https_only          = true

  identity {
    type = "SystemAssigned"
  }

  site_config {
    container_registry_use_managed_identity = true
    ftps_state                              = "FtpsOnly"
    application_stack {
      docker_image     = "${var.acr_name}/${var.appsvc_name}"
      docker_image_tag = "latest"
    }
    vnet_route_all_enabled = var.vnet_route_all_enabled
  }

  app_settings = lookup(local.app_settings, "linux_app_settings", null)
  #app_settings = var.appsvc_settings
}

resource "azurerm_app_service_virtual_network_swift_connection" "azure_vnet_connection" {
  count          = var.vnet_integ_required == true ? 1 : 0
  app_service_id = azurerm_linux_web_app.APPSVC.id
  subnet_id      = azurerm_subnet.SUBNETS["App-Service-Integration-Subnet"].id
}

resource "azurerm_container_registry" "ACR" {
  name                = var.acr_name
  location            = azurerm_resource_group.RG.location
  resource_group_name = azurerm_resource_group.RG.name
  sku                 = var.acr_sku
  admin_enabled       = var.acr_admin_enabled

  dynamic "identity" {
    for_each = var.acr_requires_identity == true ? [1] : []
    content {
      type = "SystemAssigned"
    }
  }

  dynamic "georeplications" {
    for_each = var.acr_sku == "Premium" ? var.acr_georeplications_configuration : []
    content {
      location                = georeplications.value.location
      zone_redundancy_enabled = georeplications.value.zone_redundancy_enabled
    }
  }

  dynamic "network_rule_set" {
    for_each = local.acr_fw_rules != null ? local.acr_fw_rules : []
    content {
      default_action = network_rule_set.value.default_action
      dynamic "ip_rule" {
        for_each = network_rule_set.value["ip_rules"] != [] ? network_rule_set.value["ip_rules"] : []
        content {
          action   = ip_rule.value["action"]
          ip_range = ip_rule.value["ip_range"]
        }
      }

      dynamic "virtual_network" {
        for_each = network_rule_set.value["virtual_network_subnets"] != [] ? network_rule_set.value["virtual_network_subnets"] : []
        content {
          action    = virtual_network.value["action"]
          subnet_id = virtual_network.value["subnet_id"]
        }
      }
    }
  }

}
```

The issue is I am building an App service that is VNET integrated.
I then use a dynamic local to generate a list of possible outbound IPs to add to the ACR as whitelisted IPs.
The locals config looks like this:

```hcl
locals {

  ## ACR Firewall rules ##
  #Get all possible outbound IPs from VNET integrated App services and combine with allowed On Prem IP ranges from var.acr_custom_fw_rules
  allowed_ips = distinct(flatten(concat(azurerm_linux_web_app.APPSVC.possible_outbound_ip_address_list, var.acr_custom_fw_rules)))

  acr_fw_rules = [
    {
      default_action = "Deny"
      ip_rules = [for i in local.allowed_ips : {
        action   = "Allow"
        ip_range = i
        }
      ]
      virtual_network_subnets = [
        {
          action    = "Allow"
          subnet_id = azurerm_subnet.SUBNETS["App-Service-Integration-Subnet"].id
        }
      ]
    }
  ]

}
```

I basically get the following error on the first initial run:

![image](https://user-images.githubusercontent.com/44137582/160133789-6302bfc2-9e30-4c23-8659-035da226ed34.png)

Link to the failed initial run:
https://github.com/Pwd9000-ML/Azure-Terraform-Deployments/actions/runs/2040245742

On the second run of the same code, it works fine:

Link to the successful second run:
https://github.com/Pwd9000-ML/Azure-Terraform-Deployments/actions/runs/2040259293

I have tried setting the ACR with an explicit dependency on resource ` depends_on = [azurerm_app_service_virtual_network_swift_connection.azure_vnet_connection]`  to ensure the VNET integration is created fully before building the ACR, however this has no effect and the same error occurs on the initial run, but succeeds on subsequent runs.

**Comment by magodo** [comment]
@Pwd9000-ML Thank you for submitting this!

Looking through your config above, it appears that the local var `acr_fw_rules.ip_rules` depends on `allowed_ips`, which in turn will be expanded after the first apply: Before the first apply, the lenght of the `allowed_ips` is 1 (comes from `var.acr_custom_fw_rules`), which is then used for the `network_rule_set` of the ACR, resulting into one `network_rule_set`. But after the completion of the 1st apply, the length of `allowed_ips` is increased into 27 (26 more items from the `azurerm_linux_web_app`'s `possible_outbound_ip_address_list`). This causes Terraform detects an inconsistency between the plan and the final state, hence the panic you saw above.

One way to fix this is to split your provision into multiple stages: The first stage is to provision the resources except the ACR. The second stage is to provision the ACR, with the finalized local vars. Though I'm not sure if there is a better solution for your use case.

I'm going to close this issue for now as this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community.html).

**Comment by magodo** [comment]
The analysis [above](https://github.com/hashicorp/terraform-provider-azurerm/issues/16058#issuecomment-1080214586) is not true. In fact, it is allowed to use `unknown` value (e.g. value known after the apply) inside the dynamic block, and the provider can still be consistent between the plan and the after-apply stages.

The problem for this specific case is due to the `ip_rule` is not actually a dynamic block, but an attribute (as its ConfigMode is set to attr). As is stated in https://github.com/hashicorp/terraform/issues/22340, for the attribute-like block, it is not allowed to use dynamic block, instead use `for` expression. It appears that using dynamic block for this attribute-like block will cause terraform fail with incosnsitency plan as shown above, when the iteration contains unknown value.

I've verified this behavior with a demo provider: https://github.com/magodo/terraform-provider-demo/tree/v2, with following snippet:

```hcl
terraform {
  required_providers {
    demo = {
      source = "magodo/demo"
    }
  }
}

locals {
  countries = concat(["US", "Germany"], demo_resource_foo.test1.output_addr.*.country)
  addresses = [for addr in local.countries : {
    country = addr
  }]
}

resource "demo_resource_foo" "test1" {
  name = "abc"
  addr {
    country = "China"
  }
}

resource "demo_resource_foo" "test2" {
  name = "efg"

  /* dynamic "addr" { */
  /*   for_each = local.addresses */
  /*   content { */
  /*     country = addr.value.country */
  /*   } */
  /* } */

  addr = [
    for addr in local.addresses :
    {
      country = addr.country
      city    = null
      roads   = null
    }
  ]
}
```

**Comment by Pwd9000-ML** [comment]
@magodo 
Thanks for this test, it is a great test to validate the issue.
I will be re-working my module slightly to use `for` loops instead because of the `ConfigMode` on the `ip_rule`.

I'll include @jbardin for visibility and will post my result son the other thread [#30751](https://github.com/hashicorp/terraform/issues/30751)
