### ISSUE TITLE
r/resource_group: feature flag for only deleting when empty / no nested resources

### ISSUE THREAD

**Issue by StevenHessing** [hashicorp/terraform-provider-azurerm#1608]
When deleting resource groups created using the azurerm provider, any Azure RDFE resources created previously or afterwards under the same resource group using the Azure portal or other tooling are also deleted.

This unfortunately appears to be by-design by Azure: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-deployment-model

This causes Terraform to delete RDFE resources it never created and which it does not have in its state file. 

As solution, Terraform should check whether there are RDFE resources in the resource group it is about to delete. If there are, Terraform should reject executing its plan until the user has rectified the situation.

Terraform v0.11.7
terraform-provider-azurerm_v1.7.0_x4

**Comment by tombuildsstuff** [comment]
hi @StevenHessing 

Thanks for opening this issue :)

> This unfortunately appears to be by-design by Azure: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-deployment-model

Unfortunately as you've mentioned this is by design within Azure - whilst Terraform could check for the presence of items in a Resource Group and fail to delete it, I believe users would expect Terraform to mirror the behaviour they're seeing elsewhere. That said, we could potentially add an override flag to this (in a similar way we have for the `azurerm_virtual_machine` resource to delete the OS/Data Disks) to prevent deletion if child-resources still exist, which would allow both the existing behaviour (and this request to work simultaneously) - what do you think?

Thanks!

**Comment by dmedeiros204** [comment]
Might have saved this guy from making a "big mistake" https://www.craigstuntz.com/posts/2021-07-08-how-i-made-a-giant-mistake-with-terraform.html
