### ISSUE TITLE
r/network_security_group - the `protocol` casing change is missing from the 3.0 upgrade guide doc

### ISSUE THREAD

**Issue by labyrinthinesecurity** [hashicorp/terraform-provider-azurerm#16092]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2

### Affected Resource(s)

* `azurerm_network_security_group`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
In security_rule, my rules have protocol TCP:

protocol                                   = "TCP"

This reflects the situation in the Azure Backend, where the resource provider set the protocol to TCP in capital letters.

### Expected Behaviour

Microsoft set the protocol parameter of my network security rules to "TCP" (with capital letters).
It used to be ok until AzureRM 2.99.0 included

Since AzureARM 3.0.*, I get the following error message when running terraform plan:

terraform plan

Error: expected security_rule.1.protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP

### Actual Behaviour

AzureRM should have accepted TCP as a valid protocol since the Azure resource provider accepts 'TCP' in capital letters.

AzureRM used to work properly. Something has changed since 2.99.0

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
hey @labyrinthinesecurity, sorry that your having this issue

As part of the 3.0 upgrade we are starting to move towards the casing specified by the rest API specs (swagger) and SDK. The provider is validating against the SDK constants and should be transparently translating the API responses to casing expected by the rest API specs. 

If you use the casing expected by the validation is this still an issue?

**Comment by labyrinthinesecurity** [comment]
Hello Katbyte,

Thanks for reaching out. It is still an issue for me because the Azure RP itself doesn't respect the casing. All my NSGs have protocol set to 'TCP' in Azure backend, so I'm getting a lot of errors. On the long term, MSFT told me they were going to use a consistent casing, but no delivery date was given by them... :(

**Comment by labyrinthinesecurity** [comment]
Since I'm not the owner of the NSGs, I cannot re-create them with 'Tcp' instead of 'TCP'.

**Comment by saulobejo** [comment]
@katbyte 

I second @labyrinthinesecurity 

TCP and UDP are known standardized acronyms.

Also, it makes no sense that every time an instance is created using the UI there's an 'error' on terraform.

**Comment by mkprizzle** [comment]
Also an issue for key_permisions, key_secrets for key vault resource types. They expect title casing. This is inconsistently applied, though, as "key_opts" blocks expect camelCase for the same inputs.

**Comment by srozga** [comment]
Some more info on this. Between 2.99 and 3.0, the code very deliberately changed over a few commits to NOT ignore casing when validating inputs; note the _false_ param. That used to be _true_ a few months back. https://github.com/hashicorp/terraform-provider-azurerm/blob/0ad1931b54d7bd9bcf9d434ef3187029a6e7381e/internal/services/network/network_security_group_resource.go#L75-L82

This is causing this validation problem when running terraform plan. 

I ran the following scenario:
1. Create an nsg rule in 2.99 with code "tcp". 
2. Changed the value in the code to "Tcp" 
3. Run tf plan with 2.99. No changes. 
4. Upgrade RM to 3.8.
5. Run tf plan again with 3.8 this time. Plan wants to update resource protocol from "tcp" -> "Tcp". If you have many of these guys lying around, this issue will result in a seemingly useless huge plan.

Of note, the _direction_ and _access_ attributes do not suffer from this problem, because the tf state after creating the resource in 2.99 actually has the right casing for _direction_ and _access_, even though my code had everything in lower case. This part makes the least sense of all of this.

**Comment by RussTech** [comment]
If I view a network security group in the **azure gov** portal (environment: usgovernment) and view the JSON resources, the API shows:
`
"protocol: TCP"
`
This case matches the state file.  
 
I then checked a security group in Azure portal (environment: public) the JSON view in that environment shows
`
"protocol: Tcp"
`
In both public and gov, every API version i checked showed the same output.  including API versions: 
2022-01-01
2021-01-01
2017-04-01 

The provider 3.11.0 does update the state file to match the case of the code.  I validated that re-running the plan after applying using 3.11.0 no longer reports TCP -> Tcp changes.

**Comment by HughPrince** [comment]
Hello, is there any update or workarounds to this challenge/change as in my current scenario I can't have the NSG rules being ripped off and re added when there is no actual change to them.

From testing today with different versions up to tf 1.2.8, azurerm 3.21.1 it shows:

The Azure end will set upper case but azurerm provider => 2.99.0 is forcing a validation of init-caps Tcp.
The result is that any NSG rules which have been implemented < azurerm 2.99.0 with upper case TCP will be removed/re-added as Tcp. If the resulting rule is opened and saved via the Azure console it will be changed to upper case. I'm not suggesting manual updates of the NSG rules in the Azure console, just backing up that Azure is would appear to be working with upper case for the protocol parameter.
I've tested modifying the tf code and state to be Tcp as a work around, but the remove/add is still triggered.

Any suggestions or workarounds welcomed and if not possible can this be investigated further to see if the validation can be updated to correctly validate against what Azure is expecting.

Of if I have the wrong end of the stick on why this validation has been added/changed happy to be corrected.

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here this appears to be missing from the upgrade guide - the behaviour is correct insofar as the casing should match what's defined in the Azure Swagger rather than accepting any casing, however I believe the confusion here comes from the fact that this isn't documented in the upgrade guide, so apologies for that.

I've tagged this as a documentation bug since [the 3.0 upgrade guide needs updating to document this change](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - and once updated we can look to close this issue.

However as mentioned above since we're now using the casing defined by the Azure Swagger, this can be worked around by updating your Terraform Configuration to use the correct casing.

Thanks!

**Comment by HughPrince** [comment]
Thank you for the fast response @tombuildsstuff. Just to check my understanding, are we saying:
 
 - The Azure REST API swagger states initCAPS for the protocol option, but the API does not enforce this. 
    - This has resulted in other variations of case to be configured via older azurerm providers. 
 - The Azure console does not adhere to same case definition as the swagger and sets upper case.
 - Going forward to ensure consistency against  swagger the azurerm provider will enforce the InitCAPS.
 - To migrate to the v3.0 providers the process is to correct the case in the terraform configuration, and apply the changes.
    -  This will remove/re-add the rules

Question, probably daft one as I'm sure this would have already been done, but I'll ask anyway.

Does the Azure API support updating the case of the protocol within a rule without removing and re-adding the rule?
  - The key being to reduce the risk when updating critical environments
     -  e.g. TF apply fails half way thru, after removing the rules and failed to re add them.

Is this the Azure definition being referred to?

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2015-06-15/networkSecurityGroup.json

  "definitions": {
    "SecurityRulePropertiesFormat": {
      "properties": {
        "description": {
          "type": "string",
          "description": "A description for this rule. Restricted to 140 chars."
        },
        "**protocol**": {
          "type": "string",
          "description": "Network protocol this rule applies to. Possible values are 'Tcp', 'Udp', and '*'.",
          "enum": [
            **"Tcp",
            "Udp",
            "*"**

**Comment by engineertdog** [comment]
`Tcp` has never been the correct capitalization of the acronym. `tcp` or `TCP`. As mentioned before, Azure doesn't even use what their documentation says. Microsoft documentation, like every documented project ever, is never accurate.
