### ISSUE TITLE
azurerm_bot_channel_ms_teams calling_web_hook Should accept url without trailing forward-slash

### ISSUE THREAD

**Issue by half2me** [hashicorp/terraform-provider-azurerm#16097]
Trying to set a webhook like: `https://my-url` will be rejected, even though it is a valid URL, and works in Azure.

Error: invalid `calling_web_hook`, must start with `https://` and end with `/`

**Comment by neil-yechenwei** [comment]
@half2me , thanks for raising this issue. Even though it's a valid URL, but API always returns "https://my-url/" even if this property is set as "https://my-url" in request payload.  So seems it's a bug in rest api. Filed an issue on https://github.com/Azure/azure-rest-api-specs/issues/18511 for tacking.

**Comment by tombuildsstuff** [comment]
hey @half2me 

Thanks for opening this issue.

Since this is a bug in the Azure API rather than something specific to Terraform, I hope you don't mind but I'm going to close this in favour of the upstream issue: https://github.com/Azure/azure-rest-api-specs/issues/18511 - as once this is fixed upstream this'll automatically be fixed in Terraform.

Thanks!
