### ISSUE TITLE
azurerm: Parameter "allow_blob_public_access" will fail with Provider 3.0 and up

### ISSUE THREAD

**Issue by Gill-Bates** [hashicorp/terraform-provider-azurerm#16128]
```
Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
```

Creating a StorageAccount with azurerm lower than 3.0 will work

```
resource "azurerm_storage_account" "foobar" {
  allow_blob_public_access  = false
}
```

With Version 3 and above, Terraform will fail:

`"allow_blob_public_access not expected here"`

**Comment by zioalex** [comment]
I had the same issue. Workaround so far with version v2.99.0

**Comment by mlcooper** [comment]
This change is documented in the v3.0.0 [release notes](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022), and v3.0.0 introduces some breaking changes (major version bump in the provider):

![image](https://user-images.githubusercontent.com/9505606/160652336-3777cdff-63f7-40f8-940c-6e0a64d2e2d0.png)

**Comment by katbyte** [comment]
Hey @Gill-Bates ,

as @mlcooper mentioned 3.0 is a major release a complete list of changes can be found [in the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - which is [linked from the changelog since this is a major version](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022).

In this case this field has been renamed to `allow_nested_items_to_be_public`, however there maybe other changes you need to make to your Terraform Configuration to be compatible with v3.0 - we'd recommend consulting the upgrade guide.

We'd recommend pinning the version of the Azure Provider being used, for example to pin to 3.0.0:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=3.0.0"
    }
  }
}
```
You can also pin to the last 2.x release temporarily as shown below, however note that any future enhancements will ship in 3.x:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.99.0"
    }
  }
}
```
Thanks!

**Comment by Gill-Bates** [comment]
@mlcooper It should be noted in the Docs, not only in the Release Notes!

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account

The documentation in Terraform is meanwhile so confusing, I recommend the implementation from Microsoft

![image](https://user-images.githubusercontent.com/25774289/160801755-c8b090b2-906f-4e34-a6bb-a45ddf2aa7a2.png)
