### ISSUE TITLE
Documentation - azurerm_storage_account

### ISSUE THREAD

**Issue by mlcooper** [hashicorp/terraform-provider-azurerm#16135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v3.0.0 and higher

### Affected Resource(s)

* `azurerm_storage_account`

### Expected Behaviour

In v3.0.0+ of the provider, the `allow_blob_public_access` property has been renamed to `allow_nested_items_to_be_public`, however in the documentation it still references `allow_blob_public_access` as shown here: 

![image](https://user-images.githubusercontent.com/9505606/160650405-96628dd9-b57e-476f-8235-6122ae7e9cf4.png)

I believe this should be updated to reference `allow_nested_items_to_be_public`.
### Actual Behaviour

* #0000

**Comment by janhonenj** [comment]
Furthermore, the old, optional parameter "allow_blob_public_access" defaulted to "false" while the new replacement parameter defaults to "true".  This will, inadvertently, attempt to enable public access for lots of people that did not bother to explicitly define this parameter before.

**Comment by katbyte** [comment]
Hey @janhonenj 

Thanks for opening this issue, it does look like we missed updating the data source documentation, so i've opened #16145 to fix this!

As for the default value we have updated it to conform to the new default used by azure itself as can be seen in the discussion here: #13037

Finally for enabling public access to items, i don't think that is what this property actually does, and it was renamed due to the confusion. from #12689, what this property actually does is allow nested items within this Account [e.g. Containers Blobs etc] to opt into being public.

Apologies for any confusion, i've also updated the description in #[16145](https://github.com/hashicorp/terraform-provider-azurerm/pull/16145) to be more explicit about what this property does.
