### ISSUE TITLE
azurerm_public_ip attribute name changed from availability_zone to zones

### ISSUE THREAD

**Issue by Prost98** [hashicorp/terraform-provider-azurerm#16141]
Hi,

In the most recent version of the provider (3.0.2), the **azurerm_public_ip** resource attribute named **availability_zone** has now been changed to **zones**. Is there a reason the attribute name was changed and not left as-is for backward compatibility? This change forces code changes for anyone that references the current and future versions of the provider.

**Comment by katbyte** [comment]
Hey @vainars ,

Thanks for opening this issue.

As 3.0 is a major release there have been a number of breaking changes changes made, a complete list can be found [in the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - which is [linked from the changelog since this is a major version](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022).

In this case the change was made we have tried to align all resources around a common zones schema and design to provide a more consistent experience across the provider, and as 3.0.0 is a major version change the old property was removed.

For now you can just pin to the last 2.x release temporarily as shown below, however note that any future enhancements will ship in 3.x:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.99.0"
    }
  }
}
```
