### ISSUE TITLE
This module cannot be used above v1.44.0 as a dependency

### ISSUE THREAD

**Issue by baileye** [hashicorp/terraform-provider-azurerm#16163]
Only up to v1.44.0 (released in February 2020) can be used as a terraform module in other projects as a dependency. The module path in go.mod needs to be updated to v3 (or v4 for the upcoming release) ref: https://go.dev/doc/modules/version-numbers

> A major version update to a number higher than v1 will also have a new module path. That’s because the module path will have the major version number appended, as in the following example:
>
> `module example.com/mymodule/v2 v2.0.0`

**Comment by tombuildsstuff** [comment]
hi @baileye 

Thanks for opening this issue.

This repository hosts a plugin officially supported only for use with Terraform - as such the semantic versioning applied to this repository reflects the semantic versioning for downstream users of Terraform (e.g. Terraform users via HCL) - rather than a traditional Go Module.

Whilst we only support using this Provider via Terraform Core - you should also be able to make use of this plugin via the same underlying mechanism, [`hashicorp/go-plugin`](https://github.com/hashicorp/go-plugin), or if you're looking to use Terraform in automation you may wish to look into [`hashicorp/terraform-exec`](https://github.com/hashicorp/terraform-exec) which allows for using Terraform in an automated manner.

Alternatively you're welcome to include/make use of files from this Provider in your repository - however this use-case is unsupported and where this provider moves fairly quickly, we make no guarantees against drastically changing things without any sort of warning or notification.

As we don't officially support using the Provider in this fashion - unfortunately we have no plans to change how we version this module from using semantic versioning based on Terraform/HCL usage to based on the Go Module interpretation - and as such whilst I'd like to thank you for reaching out, I'm going to close this issue for the moment.

Thanks!
