### ISSUE TITLE
Migrate the ID format of key vault nested resources

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform-provider-azurerm#16174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/11059 (Azure KeyVault Error: Provider produced inconsistent result after apply), the root cause is that the LIST[ on the resources with a query to the key vault name might fail to get the key vault.](https://github.com/hashicorp/terraform-provider-azurerm/blob/57b41ea7ea305c956d476387d2d197aa2231bfb5/internal/services/keyvault/client/helpers.go#L117-L121), which might suffers from the [ARM caching problem](https://github.com/Azure/AKS/issues/1964#issuecomment-729150191).

My prior attempt is to remove the additional query for the key vault in the Read() of the key vault secret, in this #14047. Whilst this is closed due to there might be some DNS error returned in the Read of the key vault secret when the key vault is deleted outside of Terraform, which causes Terraform can't correctly remove the secret from its state.

How about we change the ID of the secret/key/certificate to some hyperthetic form like: `<key vault id>/secrets|keys|certificates/<name>`. In this way, we are still able to keep all the information as the current ID format, while save as to do a conversion from the key vault host URI to its resource ID, i.e. eliminate the problematic LIST API.

### New or Affected Resource(s)

* azurerm_key_vault_key
* azurerm_key_vault_secret
* azurerm_key_vault_certificate
* azurerm_key_vault_certificate_issuer
* azurerm_key_vault_managed_storage_account

**Comment by tombuildsstuff** [comment]
hi @magodo 

Thanks for opening this issue.

The Resource Manager APIs make extensive use of the Data Plane ID rather than the Resource Manager ID for Certificates, Keys and Secrets - as such given this is threaded through the provider changing this to use a different ID format at this point in time would lead to a significant number of breaking changes for users (including configuration changes). As such unfortunately due to how widely used these are this isn't a change we can make at this point in time - but should the Data Plane and Resource Manager API's become more compatible in the future, perhaps we can investigate switching over to using that.

As such whilst I'd like to thank you for opening this issue (and #16230), since this isn't something we can ship due to the scale of this change I'm going to close this issue for the moment.

Thanks!
