### ISSUE TITLE
Support for Storage Account allow_blob_public_access no longer available in azurerm v3

### ISSUE THREAD

**Issue by graff6996** [hashicorp/terraform-provider-azurerm#16245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
locals {
  virtual_network_subnet_ids = var.subnet_name == [] ? null : data.azurerm_subnet.example.*.id
}

resource "azurerm_storage_account" "example" {
  name                      = var.storage_acc_name
  resource_group_name       = var.rg_name
  location                  = var.location
  account_tier              = var.account_tier
  account_replication_type  = var.account_replication_type
  access_tier               = var.access_tier
  account_kind              = var.account_kind
  enable_https_traffic_only = var.enable_https_traffic_only
  allow_blob_public_access  = var.allow_blob_public_access
  is_hns_enabled            = var.Hierarchical_Namespace
  min_tls_version           = "TLS1_2"

  network_rules {
    default_action             = var.default_action
    ip_rules                   = var.ip_rules
    virtual_network_subnet_ids = local.virtual_network_subnet_ids
  }

  tags = var.tags

}
```

### Debug Output/Panic Output

```shell
Error: Unsupported argument
│
│   on modules\storage_accnt_creation\main.tf line 14, in resource "azurerm_storage_account" "example":
│   14:   allow_blob_public_access  = var.allow_blob_public_access
│
│ An argument named "allow_blob_public_access" is not expected here.
```

### Expected Behaviour

allow_blob_public_access can be set to true or false

### Actual Behaviour

Error: Unsupported argument
│
│   on modules\storage_accnt_creation\main.tf line 14, in resource "azurerm_storage_account" "example":
│   14:   allow_blob_public_access  = var.allow_blob_public_access
│
│ An argument named "allow_blob_public_access" is not expected here.

### Steps to Reproduce

terraform plan

### Important Factoids

NA

### References

Terraform documentation states that this argument is still supported
(https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account)

**Comment by tombuildsstuff** [comment]
hi @graff6996 

Thanks for opening this issue.

As 3.0 is a major release a complete list of changes can be found [in the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - which is [linked from the changelog since this is a major version](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022).

In this case this field has been renamed to allow_nested_items_to_be_public, however there maybe other changes you need to make to your Terraform Configuration to be compatible with v3.0 - we'd recommend consulting the upgrade guide.

We'd recommend pinning the version of the Azure Provider being used, for example to pin to 3.0.0:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=3.0.0"
    }
  }
}
```
You can also pin to the last 2.x release temporarily as shown below, however note that any future enhancements will ship in 3.x:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.99.0"
    }
  }
}
```


Thanks!
