### ISSUE TITLE
managed_disk  - where get source_resource_id when restore a disk

### ISSUE THREAD

**Issue by cuntoulishifu** [hashicorp/terraform-provider-azurerm#16274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13

### AzureRM Provider Version

2.89.0

### Affected Resource(s)/Data Source(s)

azure_managed_disk  

### Terraform Configuration Files

```hcl
resource azurerm_managed_disk RG-PROD__vm-datadisk-000 {
  name                 = "vm-datadisk-000"
  location             = "ukwest"
  resource_group_name  = "RG-PROD"
  create_option        = "Restore"
  source_resource_id   = "/subscriptions/xxxxx-xxx-xxx-xxx-xxxxx/resourceGroups/AzureBackupRG_ukwest_1/providers/Microsoft.Compute/restorePointCollections/AzureBackup_vm-02_169/restorePoints/AzureBackup_20190122_014129/disks/vm-02_disk2_4a?id=edef9810-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx"
  storage_account_type = "Premium_LRS"
  disk_size_gb         = "1023"
}
```

### Debug Output/Panic Output

```shell
where can I get the source_resource_id? I have searched my Azure env and can't see source_resource_id in that format.
```

### Expected Behaviour

can get source_resource_id in that format.

### Actual Behaviour

where can I get the source_resource_id? I have searched my Azure env and can't see source_resource_id in that format.

### Steps to Reproduce

terraform apply

**Comment by stephybun** [comment]
Hi @cuntoulishifu,

Thanks for raising this issue!

The property `source_resource_id` expects the [ID of an existing managed disk](https://registry.terraform.io/providers/hashicorp/azurerm/2.98.0/docs/resources/managed_disk#source_resource_id) which is accessible via the `id` attribute of that resource e.g. `azurerm_managed_disk.example.id`. [Here](https://registry.terraform.io/providers/hashicorp/azurerm/2.98.0/docs/resources/managed_disk#example-usage-with-create-copy) is an example in the docs of what that looks like in a copy scenario.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment.

Thanks!
