### ISSUE TITLE
azurerm_site_recovery_replicated_vm waits for synchronisation 

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#16373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_site_recovery_replicated_vm

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_replicated_vm" "protected_vm_tf" {
  count                                     = var.dr_serviceclass == "Gold" ? 1 : 0
  name                                      = local.vm_name
  resource_group_name                       = var.support_resource_group
  recovery_vault_name                       = local.recovery_vault
  recovery_replication_policy_id            = data.azurerm_site_recovery_replication_policy.policy.id
  source_vm_id                              = local.virtual_machine_id
  source_recovery_fabric_name               = data.azurerm_site_recovery_fabric.fabric.name
  source_recovery_protection_container_name = data.azurerm_site_recovery_protection_container.primary.name
  target_zone                               = local.secondary_zone ? tonumber(local.secondary_zone) : "3"
  target_resource_group_id                  = data.azurerm_resource_group.virtualmachine_asr[0].id
  target_recovery_fabric_id                 = data.azurerm_site_recovery_fabric.fabric.id
  target_recovery_protection_container_id   = data.azurerm_site_recovery_protection_container.secondary.id
  target_network_id                         = data.azurerm_resources.vnet.resources[0].id

  managed_disk {
    disk_id                    = lower(data.azurerm_managed_disk.os_disk[0].id)
    staging_storage_account_id = data.azurerm_storage_account.primary.id
    target_resource_group_id   = data.azurerm_resource_group.virtualmachine_asr[0].id
    target_disk_type           = var.disk_storage_account_type
    target_replica_disk_type   = var.disk_storage_account_type
  }

  dynamic "managed_disk" {
    for_each = module.vm_disks[*].diskid
    content {
      disk_id                    = lower(managed_disk.value)
      staging_storage_account_id = data.azurerm_storage_account.primary.id
      target_resource_group_id   = data.azurerm_resource_group.virtualmachine_asr[0].id
      target_disk_type           = var.disk_storage_account_type
      target_replica_disk_type   = var.disk_storage_account_type
    }
  }

  network_interface {
    source_network_interface_id = azurerm_network_interface.virtualmachine.id
    target_subnet_name          = data.azurerm_subnet.subnet.name
  }

  depends_on = [
    azurerm_windows_virtual_machine.virtualmachine_windows, azurerm_virtual_machine.virtualmachine_migrated,
    azurerm_linux_virtual_machine.virtualmachine_linux, azurerm_virtual_machine_extension.virtualmachine_linux, data.azurerm_site_recovery_protection_container.secondary, module.vm_disks
  ]
}
```

### Debug Output/Panic Output

```shell
None
```

### Expected Behaviour

Configuration is completed the run completes

### Actual Behaviour

Configuration is completed the run continues waiting for synchronisation this behaviour does not happen with ARM

### Steps to Reproduce

terraform apply

**Comment by myc2h6o** [comment]
Hi @mpjtaylor if the VM size is big it could take long to finish the operation. If it times out at Terraform, you can set the [timeouts](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/site_recovery_replicated_vm#timeouts) to a longer value. If you see the synchronization progress is always 0% on Azure Portal, you may need to contact the Azure support to check the replicated item.

**Comment by mpjtaylor** [comment]
yes its taking a good hour, but with ARM it does not noted on the timeout thanks !

**Comment by tombuildsstuff** [comment]
hey @mpjtaylor 

Thanks for opening this issue.

One of the core tenants of Terraform is that we wait for a resource to be fully provisioned before marking it as successfully provisioned - since this means that any resources which depend on the resource being created can rely on it being fully provisioned (for example, being able to add a DNS Record to a Load Balancer once it's finished creating, not beforehand).

This means that in this case we poll the Azure API until the Virtual Machine has finished replicating, which as @myc2h6o has mentioned varies depending on the size of the Virtual Machine (and its Data Disks etc). As @myc2h6o has mentioned you can use the `timeouts` block to extend the default timeouts for this resource if you're replicating a Virtual Machine containing a large amount of data - which'll mean that Terraform will poll until this is completed.

ARM Templates on the other hand fire-and-forget the deployment. Whilst this makes it seem like the resources have been provisioned quicker, it means you aren't entirely sure when it's finished deploying/if this eventually ends up failing. There's tradeoff's to both approaches, but ultimately since the Azure SDK exposes this as a Long Running Operation which should be polled on, we're polling on this as needed until the Azure SDK/API marks this as successfully provisioned.

Since this is a core tenant of Terraform, unfortunately we aren't planning on removing this polling, since this would mean that resources depending on this resource would no longer be able to guarantee the resource is fully replicated. As such I'm going to close this issue for the moment, however if you'd like to see the performance of the replication improved I'd suggest opening a ticket with Microsoft Support here, who should be able to redirect that Feature Request to the relevant Service Team.

Thanks!
