### ISSUE TITLE
ignore_changes for specific tags not working

### ISSUE THREAD

**Issue by Pinaki-Kundu** [hashicorp/terraform-provider-azurerm#16372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.6

### AzureRM Provider Version

3.0.1

### Affected Resource(s)/Data Source(s)

lifecycle for each resources

### Terraform Configuration Files

```hcl
lifecycle {
    ignore_changes = [
      tags["owneremail"], tags["ownername"],
    ]
  }
```

### Debug Output/Panic Output

```shell
...
...
When expanding the plan for module.keyvault.azurerm_key_vault.vault to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.tags["owneremail"]: was cty.StringVal("xxxx_xxxx@xxx.com"), but now
cty.StringVal("xxxxxxxx.xxxx@xxx.com").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
...
...
```

### Expected Behaviour

It's been expected to ignore changes related to tags "owneremail" and "ownername", which was actual behavior with 

terraform version - 0.13.2
hashicorp/azurerm version - 2.42.0

### Actual Behaviour

Instead of ignoring its checks for remote to actual state and plan as a modification in case of tag value change.

### Steps to Reproduce
Try to ignore few specific tags with ignore_changes list under lifecycle  block.

```hcl
resource "azurerm_key_vault" "vault" {
  name  = "test_vault"
...
...

  lifecycle {
    ignore_changes = [
      tags["owneremail"], tags["ownername"],
    ]
  }
}
```
### Important Factoids

This was working fine with - terraform version - 0.13.2 & hashicorp/azurerm version - 2.42.0

**Comment by pinaki-accenture** [comment]
@mbfrahry please let me know if you need more details from my side. Thanks

**Comment by pinaki-accenture** [comment]
Hello All, eagerly waiting for some update here. Thanks in advance.

**Comment by ms-zhenhua** [comment]
Hi @pinaki-accenture, thank you for reaching out.
I tried to reproduce this issue with the attached configuration, but the issue did not happen.
My steps are:
1. Run **terraform apply** with the configuration.
2. Change the value of tags[owneremail] from "xxxx_xxxx@xxx.com" to "xxxxxxxx.xxxx@xxx.com"
3. Run **terraform plan**, and I got `No changes` result

If my steps are different from yours, kindly help provide more detailed steps of yours. If possible, kindly also help provide your runnable configuration (you can remove the sensitive information) so that I can try to reproduce this issue with it and do more investigation. 

Thanks.

[main.zip](https://github.com/hashicorp/terraform-provider-azurerm/files/9459478/main.zip)

**Comment by Pinaki-Kundu** [comment]
Thanks for the notification. It's working fine with the latest versions.
