### ISSUE TITLE
azurerm_network_interface attribute: internal_domain_name_suffix not available

### ISSUE THREAD

**Issue by CarlFies** [hashicorp/terraform-provider-azurerm#16415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_network_interface

### Terraform Configuration Files

```hcl
data "azurerm_network_interface" "XXX" {
  name                = "existingNIC"
  resource_group_name = data.azurerm_resource_group.rg.name
}

data.azurerm_network_interface.XXX.internal_domain_name_suffix
```

### Debug Output/Panic Output

```shell
This object has no argument, nested block, or exported attribute named
│ "internal_domain_name_suffix".
```

### Expected Behaviour

something.ax.internal.cloudapp.net

### Actual Behaviour

Error: Unsupported attribute

### Steps to Reproduce

terraform validate

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_interface#internal_domain_name_suffix

**Comment by tombuildsstuff** [comment]
hi @CarlFies 

In the code used above, you're making use of [the `azurerm_network_interface` Data Source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/network_interface) rather than the [Resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_interface) (linked above) - and Terraform is correctly raising this as an unknown attribute since the Data Source currently doesn't expose this attribute.

Since this is a usage question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but if you're looking to make use of the `internal_domain_name_suffix` attribute within the Data Source then please feel free to open a new Feature Request and we can take a look.

Thanks!
