### ISSUE TITLE
Error: "availability_set_id": conflicts with zone

### ISSUE THREAD

**Issue by mohammadkandy** [hashicorp/terraform-provider-azurerm#16476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_windows_virtual_machine

### Terraform Configuration Files

```hcl
variable "availability_set_id" {
  type    = string
  default = "/subscriptions/<sub_id>/resourceGroups/<rgp>/providers/Microsoft.Compute/availabilitySets/<availability_sets>"
}

variable "zone" {
  type    = string
  default = null
}
```

```hcl
resource "azurerm_windows_virtual_machine" "windowsvm" {
  availability_set_id        = var.availability_set_id
  zone                       = var.zone
}

or

resource "azurerm_windows_virtual_machine" "windowsvm" {
  availability_set_id = var.availability_set_id != "" ? var.availability_set_id : null
  zone                = var.zone != "" ? var.zone : null
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Conflicting configuration arguments
│
│   with module.windows_vm.azurerm_windows_virtual_machine.windowsvm,
│   on ../../../catalog/resources/virtual-machine-windows/main.tf line 17, in resource "azurerm_windows_virtual_machine" "windowsvm":
│   17:   availability_set_id        = var.availability_set_id
│
│ "availability_set_id": conflicts with zone
╵
Releasing state lock. This may take a few moments...
ERRO[0024] 1 error occurred:
        * exit status 1
```

### Expected Behaviour

When one property is defined, there shouldn't be conflicts.

### Actual Behaviour

│ "availability_set_id": conflicts with zone

### Steps to Reproduce

Create a windows VM resource with:
availability_set_id = "/subscriptions/<sub_id>/resourceGroups/<rgp>/providers/Microsoft.Compute/availabilitySets/<availability_sets>"
zones = null

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/5482

**Comment by tombuildsstuff** [comment]
hi @mohammadkandy 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding Terraform Configuration rather than a bug in the Azure Provider (as the variable `availability_set_id` has a default value, passing `null` to a module will use this default value) - as this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
