### ISSUE TITLE
azurerm_network_security_rule inappropriate caps sensitivity

### ISSUE THREAD

**Issue by calebak404** [hashicorp/terraform-provider-azurerm#16765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_network_security_rule

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_rule" "Allow-HTTP-HTTPS" {
  name                        = "Allow-HTTP-HTTPS"
  resource_group_name         = var.resource_group_name
  network_security_group_name = var.network_security_group_name
  priority                    = 1030
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "TCP"
  source_port_range           = "*"
  destination_port_ranges     = ["80", "443"]
  source_address_prefixes = "*"
  destination_address_prefix = "*"
}
```

### Debug Output/Panic Output

```shell
expected protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP
```

### Expected Behaviour

Resource should have deployed with no error.

### Actual Behaviour

Resource failed to deploy with above error.

This error is new with provider versions 3.x, these resources deployed with no issues in provider versions 2.x

It would be expected that this argument not be sensitive to capitalization, or if it is, the values are capitalized as expected for acronyms.

I have thousands of these rules deployed across multiple projects, it would be onerous to be forced to change every one.

### Steps to Reproduce

terraform plan

**Comment by myc2h6o** [comment]
Hi @calebak404 Thanks for opening the issue! Unfortunately, the case sensitivity has been enhanced in 3.0. It is introduced by [this change](https://github.com/hashicorp/terraform-provider-azurerm/pull/15182/files#diff-6e976520a60d0a2ce1018bd0ef55278013dff6be512b0951e722578e8a86dd3cR84)
Similar issue #16076

**Comment by MitchDrage** [comment]
So is this not still a bug?
I'm hitting this now too, and the provider is forcing to use "Udp" instead of "UDP", which conflicts with what the Azure portal sets.
So when you are importing an NSG, the provider now forces an update over the top of the Azure portal resources to convert "UDP" to "Udp". That really shouldn't happen.

**Comment by tombuildsstuff** [comment]
@MitchDrage these constants are defined in the API as `Udp` rather than `UDP` - 3.0 and above requires that these match casing-wise to avoid issues within Terraform Core which requires that the planned values matches the result of the applied values, which is required since the Azure API and SDKs define these values differently.

There's an internal issue tracking updating the documentation to account for these changes (since unfortunately these were missed from the 3.0 upgrade guide) - which'll fix this from a documentation standpoint, but you'll need to update the usages in your Terraform Configuration to match the validation here.

Since this is working as intended I'm going to close this issue for the moment - however you'll need to work through and update these to match what Azure is returning here (`Udp`) since that's the defined value for these constants.

Thanks!
