### ISSUE TITLE
azurerm_container_registry retention_policy block should not be replaceable by a list of object

### ISSUE THREAD

**Issue by thllxb** [hashicorp/terraform-provider-azurerm#16860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.6.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "acr1" {
  location            = "eastus"
  name                = "my-acr1"
  resource_group_name = "my-rg"
  sku                 = "Premium"

  retention_policy = [{
    enabled = true
    days    = 7
  }]

}

resource "azurerm_container_registry" "acr2" {
  location            = "eastus"
  name                = "my-acr2"
  resource_group_name = "my-rg"
  sku                 = "Premium"

  retention_policy {
    enabled = true
    days    = 7
  }
}

resource "azurerm_storage_account" "sa1" {
  account_replication_type = "LRS"
  account_tier             = "Premium"
  account_kind             = "BlockBlobStorage"
  location                 = "eastus"
  name                     = "my-sa1"
  resource_group_name      = "my-rg"

  blob_properties = [{
    versioning_enabled       = false
    change_feed_enabled      = false
    last_access_time_enabled = false
  }]
}

resource "azurerm_storage_account" "sa2" {
  account_replication_type = "LRS"
  account_tier             = "Premium"
  account_kind             = "BlockBlobStorage"
  location                 = "eastus"
  name                     = "my-sa2"
  resource_group_name      = "my-rg"

  blob_properties {
    versioning_enabled       = false
    change_feed_enabled      = false
    last_access_time_enabled = false
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported argument
│
│   on main.tf line 20, in resource "azurerm_storage_account" "sa1":
│   20:   blob_properties = [{
│
│ An argument named "blob_properties" is not expected here. Did you mean to define a block of type "blob_properties"?
```

### Expected Behaviour

According https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_registry#retention_policy, "retention_policy" should be a sub block, which should lead to a failure when trying to create "azurerm_container_registry.acr1", just like what happens to "azurerm_storage_account.sa1".

### Actual Behaviour

"azurerm_container_registry.acr1" got created successfully.

**Comment by magodo** [comment]
@thllxb For providers that developed on top of SDK v2 (including this provider), the "nested block" indicates the syntax as you have used for `azurerm_container_registry.acr2` and `azurerm_storage_account.sa2`.

The only exception is that the schema has defined `ConfigMode: pluginsdk.SchemaConfigModeAttr`, which is a trick in the SDK v2 library, that it allows both syntax to work, where the `network_rule_set` for `azurerm_container_registry.acr1` is one of such case. Though, we still prefer using the "block" syntax rather than the "attribute" syntax in most cases. The "attribute" syntax is only used when users want to force zero it, e.g. `network_rule_set = []`.

As this is a question about the property usage, and there is nothing needs to be done in the provider. I'm gonna close this issue for now. Please feel free to reopen if you have any further question.
