### ISSUE TITLE
OpenID Connect authentication works for init but not for plan with azurerm-provider

### ISSUE THREAD

**Issue by torivara** [hashicorp/terraform-provider-azurerm#16881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.6.0

### Affected Resource(s)/Data Source(s)

azurerm_provider

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    resource_group_name  = "rgname"
    storage_account_name = "testingterraform2313"
    container_name       = "terraformstate"
    key                  = "terraformstate.tfstate"
    use_oidc             = true
    subscription_id      = "***"
    tenant_id            = "***"
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

#Create Resource Group
resource "azurerm_resource_group" "rg" {
  name     = "tf-demo-rg"
  location = "westeurope"
}
```

### Debug Output/Panic Output

```shell
[Debug log](https://gist.github.com/torivara/bacdb77821c107a9ae33e1f4e55889af)

The error message is around line 2900.
```

### Expected Behaviour

Terraform init creates the remote backend in Azure storage account.
Terraform plan should show me expected changes needed for infrastructure to match terraform files.

### Actual Behaviour

Terraform init creates the remote backend as expected, and seems to be correctly authenticated (supports OIDC).

![image](https://user-images.githubusercontent.com/16333425/169371269-30df8d22-de18-4124-9dc5-3fc78cf937eb.png)

Terraform plan gives an error saying authentication with az cli is not allowed for service principals (does not support OIDC?).

![image](https://user-images.githubusercontent.com/16333425/169370712-be385b8d-6173-41b8-b836-f9d4c6d73fa8.png)

### Steps to Reproduce

1. terraform init
2. terraform plan

### Important Factoids

I am trying to authenticate with OpenID Connect from a GitHub workflow. This feature was released in 1.2.0, and I was eager to test it out. Files can be found [here](https://github.com/torivara/oidc-starter). Used the docs from [here](https://www.terraform.io/language/settings/backends/azurerm).  As far as I can tell, the app registration has contributor access to the subscription. It does also have Storage Blob Data Owner on the storage account.

### References

Terraform maintainer pointed me here.

https://github.com/hashicorp/terraform/issues/31085#issuecomment-1132120536

**Comment by tombuildsstuff** [comment]
hi @torivara 

Whilst OIDC support for Terraform (Core) shipped in v1.2 - support for OIDC in the AzureRM Provider was only added in this weeks release (after Terraform Core had shipped support) which shipped in v3.7.0. Since you're using v3.6.0 you'll need to upgrade to v3.7.0 for this to work

Support for OIDC shipped in v3.7.0 of the AzureRM Provider, since you're using v3.6.0 this isn't supported in that version - but note that [OIDC will need to be enabled for the Provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_oidc) in addition to the AzureRM Backend (within Terraform Core) if you wish to use it for both.

Since this is going to be fixed by upgrading to the latest version of the AzureRM Provider I'm going to close this issue for the moment - but if that doesn't work for you then let us know and we can take another look.

Thanks!
