### ISSUE TITLE
[New resource] Support for `azurerm_user_assigned_identity_assignment` to enable attachment of Managed Idenities for data resources

### ISSUE THREAD

**Issue by desek** [hashicorp/terraform-provider-azurerm#16893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to have a new resource called `azurerm_user_assigned_identity_assignment` (derived from `azurerm_role_assignment`) that makes it possible to attach Managed Identities by resource Id's rather than on resource creation for VM's.

### New or Affected Resource(s)/Data Source(s)

* azurerm_user_assigned_identity
* azurerm_user_assigned_identity_assignment

### Potential Terraform Configuration

```
data "azurerm_virtual_machine" "example" {
  name                = "production"
  resource_group_name = "networking"
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_user_assigned_identity" "example" {
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  name = "search-api"
}

resource "azurerm_user_assigned_identity_assignment" "example" {
  scope                = data.azurerm_virtual_machine.example.id
  role_definition_name = "Reader"
  principal_id         = azurerm_user_assigned_identity.example.principal_id
}
```

**Comment by tombuildsstuff** [comment]
hey @desek 

Thanks for opening this issue.

There's a duplicate issue for this somewhere, but unfortunately this isn't possible due to the inconsistent behaviour of the Azure API when it comes to Identity assignment - some require that it's done via POST, others via PUT, some can be done only at creation time etc - as such the API doesn't really allow this to be done in this manner without requiring the user to know which resource this approach would be valid for.

As a general rule the Azure API defines associations between multiple resources by linking them within one of the resources, to indicate the hierarchy, by contrast other APIs tend to use "association" resources to link two resource together. This differing behaviour, plus the inconsistent behaviour of the `identity` block in general, unfortunately means that this isn't something we can really implement given the behaviour described above.

Ultimately I'd suggest raising a feature request with Microsoft here, since I'd agree that it should be possible to assign a Managed Identity outside of the resource (where said resource doesn't need it for immediate provisioning, anyway) - however since this currently isn't possible due to the design of the Azure API I'm going to close this issue for the moment.

Thanks!
