### ISSUE TITLE
Subscription not creating in the correct Tenant

### ISSUE THREAD

**Issue by RZeni** [hashicorp/terraform-provider-azurerm#16902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

2.2.2

### AzureRM Provider Version

3.4.0

### Affected Resource(s)/Data Source(s)

azurerm_subscription

### Terraform Configuration Files

```hcl
provider "azurerm" {
  # logged in via cli
  tenant_id = "########-####-####-####-############"
  features {}
}

data "azurerm_billing_mca_account_scope" "example" {
  billing_account_name="########-####-####-####-############:########-####-####-####-############_2019-05-31"
  billing_profile_name="####-####-###-###"
  invoice_section_name="####-####-###-###"
}

resource "azurerm_subscription" "example" {
  alias = "client2-sub-alias"
  subscription_name = "client2-sub"
  billing_scope_id  = data.azurerm_billing_mca_account_scope.example.id
}
```

### Debug Output/Panic Output

```shell
Resource Successfully provisioned ( Just in wrong location )
```

### Expected Behaviour

Subscription should have been created in new tenant

### Actual Behaviour

Subscription is created in default tenant

### Steps to Reproduce

Create New Azure Account.
Log into az cli
Create a new resource group (through UI or TF)
Create a new Tenant in that resource group (through UI or TF)
Attempt to Create a subscription in the new tenant with TF

In the UI, the option is available
![image](https://user-images.githubusercontent.com/16297198/169635249-d680f59d-5f6c-41d4-acc6-291819a5462a.png)

### References

"If you're looking to use Terraform across Tenants - it's possible to do this by configuring the Tenant ID field in the Provider block"
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli - TF Azure provider auth details

tenant_id is only exported on this resource so i can't specify on the resource level
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_subscription - TF create subscription

https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription - MS docs on creating subscriptions

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/aadb2c_directory - TF Azure create directory

https://github.com/hashicorp/terraform-provider-azurerm/issues/2025 - similar issue, can't make resources in tenant without subscription, while in their case new b2c provider does not need subscription, but I want to create a subscription in the tenant instead

**Comment by Brathadair** [comment]
👍

**Comment by tombuildsstuff** [comment]
hi @RZeni 

In the example above 2 of the resources are provisioned using one provider instance (the unaliased `default` provider) - and the other resource uses an aliased provider, both providers would need to be using the same Tenant ID in order for this to be provisioned in the same Tenant, else this would explain why these are provisioned in the wrong Tenant - as such we'd recommend checking that the Providers used are correctly configuring the Tenant ID.

Since this should be fixed by updating the Provider configs here, I'm going to close this issue for the moment - but if that doesn't work for you then please let us know by providing a standalone repro for this and we can take another look.

Thanks!

**Comment by RZeni** [comment]
@tombuildsstuff thank you for the quick response. 

In my example script, I only configured the default un-aliased provider and provisioned two resources with it. In your response you reference a third resource created with an aliased provider, and that the providers need to have the same tenantId. However that is not my under standing of what I wrote nor is it my intended outcome. What i am intending is this:

On a brand new azure account. Login to az cli. Create a new tenant. Create a subscription in the new tenant. Here is a more compete example. On a fresh azure account `terraform plan -out plan`   `terraform init`

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.4.0"
    }
  }
}

# setup root provider
provider "azurerm" {
    features {}
}

# setup resource group variables
variable "resource_group_name_prefix" {
  default       = "rg"
  description   = "Prefix of the resource group name that's combined with a random ID so name is unique in your Azure subscription."
}

variable "resource_group_location" {
  default = "eastus2"
  description   = "Location of the resource group."
}

# get random name
resource "random_pet" "rg-name" {
  prefix    = var.resource_group_name_prefix
}

# create resorce group
resource "azurerm_resource_group" "rg" {
  name      = random_pet.rg-name.id
  location  = var.resource_group_location
}

# create directory (Tenant) with root provider
resource "azurerm_aadb2c_directory" "example" {
  country_code            = "US"
  data_residency_location = "United States"
  display_name            = "client-z1"
  domain_name             = "clientz1.onmicrosoft.com"
  resource_group_name     = azurerm_resource_group.rg.name
  sku_name                = "PremiumP1"
}


# setup client provider pointing to the newly created directory (tenant)
provider "azurerm" {
  alias = "ClientProvider"
  tenant_id = azurerm_aadb2c_directory.example.id
  features {}
}

# billing account details in client provider (these will be unique to a new azure account, so i blanked mine out)
data "azurerm_billing_mca_account_scope" "example" {
  billing_account_name="########-####-####-####-############:########-####-####-####-############_2019-05-31"
  billing_profile_name="####-####-###-###"
  invoice_section_name="####-####-###-###" 
  provider = azurerm.ClientProvider
}

# create subscription in client provider
resource "azurerm_subscription" "example" {
  provider = azurerm.ClientProvider
  subscription_name = "client-z1-sub"
  billing_scope_id  = data.azurerm_billing_mca_account_scope.example.id
}

```

When I run `Get-AzSubscription` The output shows that the subscription is created in the tenant of the un-aliased "root provider"  instead of the newly created tenant referenced by the aliased "ClientProvider"
![image](https://user-images.githubusercontent.com/16297198/169918611-39397b9c-201f-40e1-acb7-041d8fad2d39.png)

**Comment by tombuildsstuff** [comment]
@RZeni unfortunately I think that's a Terraform Core limitation at this point, whilst the code "works" there the value within the provider block isn't being interpolated correctly since it's an Unknown value - which is interpreted as an empty string, and since the `tenant_id` is parsed from the Azure CLI, that's why this is getting the default value.

What happens if you do a multi-stage apply there? That is, commenting out the code from the `ClientProvider` Provider down, running `terraform apply` and then uncommenting/applying that code - which should allow this Unknown value to become known.

**Comment by RZeni** [comment]
Just ran it again that way as well, same outcome unfortunately, I was developing that way, one resource at a time. I also tried just hard coding the tenant Id as a string, same result.

If I change the tenant on the cli I suspect it creates the subscription in the correct tenant. However that is not going to work for my use case. I also tried using Service Principals instead of CLI auth since that lets me specify tenant, but SP's cannot create subscriptions. 

I think you are correct about the provider not supporting it right now.

I found the underlying source for creating subscriptions.
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/subscription/subscription_resource.go 

I was exploring this code and found the below reference which relates to the available struct options on line 155 - 160 in the above link (Extracted below for convenience)
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.subscription.models.putaliasrequestadditionalproperties?view=azure-dotnet 
```
	req := subscriptionAlias.PutAliasRequest{
		Properties: &subscriptionAlias.PutAliasRequestProperties{
			Workload: workload,
		},
	}
```
which is called on line 206
```
future, err := aliasClient.Create(ctx, aliasName, req)
```

With this I think updating req to the following will work
```
	req := subscriptionAlias.PutAliasRequest{
		Properties: &subscriptionAlias.PutAliasRequestProperties{
			Workload: workload,
			AdditionProperties: {
				SubscriptionTenantId: tenantId
			}
		},
	}
```

Of course the schema need to be updated as well. 
I think updating it from an output only to work like the alias field is the best option ie. optional but computed if not provided. It should be non breaking, it should still be output and it will just allow optional input now.
```

			"tenant_id": {
				Type:        pluginsdk.TypeString,
				Description: "The Tenant ID to which the subscription belongs",
				Computed:    true,
			},
```
to
```
			"tenant_id": {
				Type:        pluginsdk.TypeString,
				Description: "The Tenant ID to which the subscription belongs",
				Computed:    true,
				Optional:    true,
				ForceNew:    true
			},
```
then I should be able to access like this within the `resourceSubscriptionCreate` function
```
tenantId := meta.(*clients.Client).Subscription.TenantId
```

I am going to test this later when I have time and if it works I will submit a PR

**Comment by tombuildsstuff** [comment]
@RZeni we intentionally have a 1:1 link between the Tenant and Subscription of the Provider and the Resources within it (and there's a number of assumptions/design decisions which depend on that) - as such unfortunately we intentionally don't add `subscription_id` to resources to allow provisioning a resource in a different Subscription, and thus the same would apply to the Tenant ID here.

Whilst I appreciate that doesn't help your particular use-case here, I believe you should be able to split this up into different modules which'd allow you to apply these in steps as needed - first provisioning the subscription and then provisioning the resources within it, which'd work around this upstream issue in Terraform Core.

There's an issue tracking [depends_on in providers within the Terraform Core repository](https://github.com/hashicorp/terraform/issues/2430) which'll ultimately fix this - as such I'd recommend subscribing to that issue since I believe that'll fix this longer-term - however unfortunately we won't be able to accept a PR which adds `subscription_id` and `tenant_id` to resources as explained above.

**Comment by RZeni** [comment]
I believe the Option 2 i lined out that fits within the design parameters you define. It requires no change to the provider or the resource schema. The issue is resourceSubscriptionCreate function does not pass the tenantId field to the MS API at all as defined here https://docs.microsoft.com/en-us/azure/templates/microsoft.subscription/aliases?tabs=bicep  therefore it will never create a subscription in anything but the accounts default teantId (not the one configured in the provider) as its left up to azure to decide in this case. So if we take the tenantId already configured in the provider `d.Get("tenant_id").(string)`, this keeps it 1:1 and we can create subscriptions in the configured tenant instead of letting azure decide
