### ISSUE TITLE
The VMSS resource already exists - to be managed via Terraform this resource needs to be imported into the State

### ISSUE THREAD

**Issue by zioalex** [hashicorp/terraform-provider-azurerm#16910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.6

### AzureRM Provider Version

">= 2.97.0, ~> 2.99.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
# module.linuxVmss["MY_VMSS"].azurerm_linux_virtual_machine_scale_set.vmss["linux"] must be replaced
+/- resource "azurerm_linux_virtual_machine_scale_set" "vmss" {
      - encryption_at_host_enabled                        = false -> null
      - eviction_policy                                   = "Deallocate" -> null # forces replacement
      ~ id                                                = "/subscriptions/MY_SUBS/resourceGroups/dev-rg/providers/Microsoft.Compute/virtualMachineScaleSets/dev-vmss-ubuntu" -> (known after apply)
      ~ instances                                         = 4 -> 8
        name                                              = "MY_VMSS"
      ~ platform_fault_domain_count                       = 1 -> (known after apply)
      ~ priority                                          = "Spot" -> "Regular" # forces replacement
      - secure_boot_enabled                               = false -> null
      ~ tags                                              = {
          - "CreatedOnDate"                     = "2022-05-13T12:55:54.9487562Z" -> null
          - "Creator"                           = "The_creator" -> null
          - "Environment"                       = "DEV" -> null
          - "__AzureDevOpsElasticPool"          = "MY_POOL" -> null
          - "__AzureDevOpsElasticPoolTimeStamp" = "5/20/2022 1:57:59 PM" -> null
            # (5 unchanged elements hidden)
        }
      ~ unique_id                                         = "3e96771d-cb83-4736-b12a-0f1326d26826" -> (known after apply)
      - vtpm_enabled                                      = false -> null
        # (18 unchanged attributes hidden)
```

### Debug Output/Panic Output

```shell
module.linuxVmss["MY_VMSS"].azurerm_linux_virtual_machine_scale_set.vmss["linux"]: Creating...
╷
│ Error: A resource with the ID "/subscriptions/MY_SUBSC/resourceGroups/MY_RG/providers/Microsoft.Compute/virtualMachineScaleSets/MY_VMSS" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_linux_virtual_machine_scale_set" for more information.
│ 
│   with module.linuxVmss["MY_VMSS"].azurerm_linux_virtual_machine_scale_set.vmss["linux"],
│   on ../../local_tf_modules/my_modules/terraform/vmss_linux.tf line 8, in resource "azurerm_linux_virtual_machine_scale_set" "vmss":
│    8: resource "azurerm_linux_virtual_machine_scale_set" "vmss" {
```

### Expected Behaviour

The expected behavior is that the VMSS is replaced or the priority updated without any entire VMSS replacement.

### Actual Behaviour

Terraform breaks out complaining that the resource is not managed by itself and suggesting to re-import it.
This is very weird having Terraform recognized the change in Priority as a "forces replacement" update.

### Steps to Reproduce

Run my pipeline.

### References

Related but not the same #14423

**Comment by tombuildsstuff** [comment]
hi @zioalex 

Thanks for opening this issue.

Taking a look through here this is a configuration issue with two resources defining the same resource, note the difference in the resource label here ("linux" vs "vmss") indicating there's two resources here:

> module.linuxVmss["MY_VMSS"].azurerm_linux_virtual_machine_scale_set.vmss["linux"] must be replaced

> +/- resource "azurerm_linux_virtual_machine_scale_set" "vmss" {

> module.linuxVmss["MY_VMSS"].azurerm_linux_virtual_machine_scale_set.vmss["linux"]: Creating..

Since an existing VM exists with the same name in Azure, Terraform is correctly detecting that this already exists and must be imported into the state to avoid unintentionally adopting it, to avoid the configuration bugs present within the code - but you can fix this by using unique names for the Virtual Machines (since Azure uses the `name` and `resource_group_name` as the unique identifiers for the Virtual Machine).

As this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by zioalex** [comment]
Hi @tombuildsstuff  I do not follow you.
The difference I see it is because we are using a module called linuxVmss that is creating vmss resources.

No one created such resource manually. It was created previously by Terraform so why it doesn't recognize them?

**Comment by zioalex** [comment]
@tombuildsstuff can you clarify why did you close this one?

**Comment by zioalex** [comment]
Hi @tombuildsstuff  can you please reopen this one?

**Comment by tombuildsstuff** [comment]
@zioalex

>  It was created previously by Terraform so why it doesn't recognize them?

Presumably because the state file wasn't kept around between Terraform Applies? You'll need to use a [Terraform Backend](https://www.terraform.io/language/settings/backends) to store your Terraform Statefile.

Since this is a question specific to your environment rather than a bug in the Azure Provider I'm going to lock this issue for the moment, but if you're still having issues [please open an issue on the Community Discuss forum](https://discuss.hashicorp.com) where someone should be able to assist further.

Thanks!
