### ISSUE TITLE
Support for Firewall rules Mirroring

### ISSUE THREAD

**Issue by michelefa1988** [hashicorp/terraform-provider-azurerm#16944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Problem**

Very frequently I use the code like below to create a number of firewall rules for a number of resources (cosmos, keyvault, psql etc). 

```
resource "azurerm_postgresql_firewall_rule" "psql_firewall_rule" {
  for_each = { for x in var.allowed_ips: x.ip_address => x }

  name                = each.value.name
  resource_group_name = var.resource_group
  server_name         = azurerm_postgresql_server.postgresql_server.name
  start_ip_address    = cidrhost(each.value.ip_address, 0)
  end_ip_address      = cidrhost(each.value.ip_address, -1)

}
```
My goal is that I want to use azure infrastructure rules to mirror the rules I have written in the terraform code. Currently I see two ways of doing this but none of them seems to do mirroring perfectly.

1) Using ordered lists - this kind of does part of the work since terraform reshuffles the rules and somewhat mirrors them. However updating an IP in the middle of the list causes many firewall rules to be deleted and recreated (due to order). Of course this can cause issues/ downtime especially if terraform breaks half way end you end up with a bunch of missing rules. Sometimes terraform also tries to delete and recreate a rule too fast causing terraform to fail with the error "rule already exists"

2) Use a map (example above) - this solves the problem of many rules being deleted and recreated  since now updating one IP only updates that particular IP address and does not touch any other firewall rules. However if anybody creates a manual firewall in the portal (e.g 0.0.0.0/0) there is no way it will ever be deleted by terraform and is way harder to catch. 

Can you guys come up with a solution for fixing this?

**Possible Solutions**
1) Either terraform adds a feature which is between lists and maps - a map but any additional items not present in the code are deleted
2) Otherwise update the azurerm provider to make them similar to the way the variable aks `api_server_authorized_ip_ranges` is updated. In this case the list of resources (firewall rules), are a single resource and not a bunch of individual rules. 

### New or Affected Resource(s)/Data Source(s)

3.7.0

**Comment by magodo** [comment]
@michelefa1988 Thank you for submitting this issue :+1:

For this case, you'd better keep using the map as you've done. For tracking the unmanaged resources, this isn't something forced by Terraform, rather practioners should define some rule/policy in the internal team. If those unmanaged resources want to be managed by Terraform, you can [import](https://www.terraform.io/cli/import) them then.

For your two proposals:

1. This is beyond the scope of the provider. Personally, I don't think Terraform core will make this happen, due to the reason that Terraform is not meant to force users to manage everything via it.
2. The Terraform resource schema is defined based on its API model, as the API of the AKS has such a list, we export `api_server_authorized_ip_ranges` as an array. That's the same reason why we exported the properties as is for the PG firewall rule.

As this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community.html). I'm gonna close this issue for now.

**Comment by michelefa1988** [comment]
@magodo  Thanks for the reply. 

Do you agree the functionality I am asking for is pretty basic and there are many benefits to the product/ security if they are implemented

Personally I do not disagree with any of your points and I guessed the answer to this post would be tricky. 

However I would like to ask:
1.  Is it really is something the community needs? (does it need to be posted elsewhere)
2. If (1) is true, Who is responsible for getting it implemented? I agree it is not a terraform issue, perhaps neither an azure provider (if APIs are not available). Does this mean this is an azure api problem and the issue lies with the teams who manage these various resources? (mysql, cosmos etc)

**Comment by magodo** [comment]
@michelefa1988 I'd say it is ideal to have Azure builtin enforcement to only allow managing a set of resources via Terraform. Whilst in reality, this can cause issues. E.g. for features not supported by Terraform, people will seek other options (e.g. direct rest API). Also, Terraform is only responsible for managing the CRUD of a resource, whilst some resources have operations (e.g. start/stop a VM) that are beyond Terraform's scope, which can only be managed via other means. There is no clear boundary for differentiating the TF support/non-support operations.

Therefore, unfortunately the responsible to enforce the rules to manage only via TF lie with the practioners.
