### ISSUE TITLE
azurerm_container_group gets constantly replaced

### ISSUE THREAD

**Issue by DevSecNinja** [hashicorp/terraform-provider-azurerm#16999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_container_group

### Terraform Configuration Files

```hcl
resource "azurerm_container_group" "this" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name
  ip_address_type     = "Private"
  network_profile_id  = azurerm_network_profile.this.id
  os_type             = "Linux"

  container {
    name   = "someName"
    image  = "someImage"
    cpu    = "0.5"
    memory = "0.5"

    commands = ["some", "commands"]

    ports {
      port     = 53
      protocol = "UDP"
    }

    volume {
      mount_path = "/app/conf"
      name       = "someName"
      read_only  = true
      secret = {
        Corefile = base64encode(someContent)
      }
    }

  }

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
# module.dns_forwarder.azurerm_container_group.this must be replaced
-/+ resource "azurerm_container_group" "this" {
      ~ exposed_port        = [
          - {
              - port     = 53
              - protocol = "UDP"
            },
        ] -> (known after apply)
      + fqdn                = (known after apply)
      ~ id                  = "/subscriptions/<mySubId>/resourceGroups/<myRgName>/providers/Microsoft.ContainerInstance/containerGroups/<myContainerGroupName>" -> (known after apply)
      ~ ip_address          = "someIp" -> (known after apply)
        name                = "someName"
      - tags                = {} -> null
        # (6 unchanged attributes hidden)

      ~ container {
          - environment_variables        = {} -> null
            name                         = "someName"
          - secure_environment_variables = (sensitive value)
            # (4 unchanged attributes hidden)


          ~ volume {
                name       = "someName"
              ~ secret     = (sensitive value) # forces replacement
                # (3 unchanged attributes hidden)
            }
            # (1 unchanged block hidden)
        }
    }
```

### Expected Behaviour

Resource should not have been replaced.

### Actual Behaviour

Every time I run terraform apply, Terraform replaces this resource.

### Steps to Reproduce

1. terraform apply

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/11544

**Comment by lonegunmanb** [comment]
Hello @DevSecNinja , thanks for opening this issue. This issue is caused by `secure_environment_variables`. 

According to the [document](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-environment-variables#secure-values):

>Environment variables with secure values aren't visible in your container's properties--their values can be accessed only from within the container.

The replacement was caused by the diff between tfstate and empty results from API.

So in Terraform Provider we cannot get secure environment variables' values from API, and there is no way to update this property via API. It brings us to a dilemma: should we set `secure_environment_variables` `ForceNew` to `false`? If we do so, then the user may not be aware of that any changes to the `secure_environment_variables` won't be updated to the API, and that's not good. The current design will cause replacement every time we try to plan or apply, but the potential diff will be eliminated.

But this kind of replacement is very bad. There's a workaround:

1. Declare `ignore_changes` and include  `secure_environment_variables`
2. Add a `null_resource` and add your environment variables' values to the `triggers` so any changes would cause a replacement on the `null_resource`
3. Add [`replace_triggerd_by`](https://www.terraform.io/language/meta-arguments/lifecycle#replace_triggered_by) on the container group resource, pointed to the `null_resource`

It's not a prefect solution but it can prevent the meaningless replacement, and replace the container instance when the environment variables' value have been changed.

**Comment by lonegunmanb** [comment]
Hi @DevSecNinja , I cannot reproduce this issue by simply run the apply then plan, but I've reproduced the issue if I run the import command then plan.

The current code needs the container config in the existing tfstate, it seems like the API won't return secret. If you import the resource, the provider cannot get the secret value. If we write secret in user's code directly into the state file, then Terraform won't be able to detect the secret drift between state and service side. Since the API won't return the secret, I think we have nothing to do about this issue.

**Comment by DevSecNinja** [comment]
Hey @lonegunmanb, thanks for the swift reply. Isn't there anything I can ignore to get it resolved? It's a bit weird to get the container group recreated again and again. Thanks!

**Comment by tombuildsstuff** [comment]
@lonegunmanb we can parse the secret from the users config in the import/read functions as necessary to remove this diff here

**Comment by lonegunmanb** [comment]
@tombuildsstuff Ok, I'll try a patch, thanks for the tip.

**Comment by lonegunmanb** [comment]
Hi @DevSecNinja , I think we may have a workaround(need Terraform v1.2.0). 

1. Adding `lifecycle` block to container group:

```hcl
lifecycle {
    ignore_changes       = [container[0].volume[0].secret]
    replace_triggered_by = [null_resource.secret_trigger.id]
  }
```

2. Adding a new `null_resource` to capture the secret value:

```hcl
resource "null_resource" "secret_trigger" {
  triggers = {
    trigger = local.secret
  }
}
```

It will ignore the null value from import command, but trigger a replacement when the actual secret value has been changed.

**Comment by lonegunmanb** [comment]
@DevSecNinja Is this issue related to import command? Because when I tried apply a container group with secret volume then run plan, no diff was found.

**Comment by DevSecNinja** [comment]
> @DevSecNinja Is this issue related to import command? Because when I tried apply a container group with secret volume then run plan, no diff was found.
> 
> Have you tried my workaround yet?

Thanks for your support on this! No, it happens on a Terraform plan/apply. What kind of container image did you use? I can send you the TF file on Teams if you could ping me there?

**Comment by DevSecNinja** [comment]
Thanks for fixing this @lonegunmanb! I was using a module for this and although my main config had the up-to-date version of the provider, the module did not. Thanks!
