### ISSUE TITLE
Support for `az webapp config ssl upload`: Upload certificate to appservice directly

### ISSUE THREAD

**Issue by adamency** [hashicorp/terraform-provider-azurerm#17014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

After a lenghty research in the provider documentation, in the `examples` directory, in the issues for the project, and in google and stack overflow, there doesn't seem to be any equivalent in `terraform-provider-azurerm` for the `az` cli command:

```
az webapp config ssl upload --certificate-file $pfxPath --certificate-password $pfxPassword --name $webapp --resource-group $resourceGroup
```

which is the equivalent of going to the Azure portal, then to your appservice, then to SSL/TLS Settings and upload a PFX certificate on the appservice itself.

Methods in the provider only seem to support [importing a certificate on key vault](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/examples/app-service-certificate) then giving rights on the keyvault to the appservice or binding a certificate to a custom domain binding.

But there isn't an actual need of a keyvault nor a custom domain to assign a certificate to an appservice, as explained before.

It would greatly ease terraform configuration if we could upload a certificate directly to the appservice.

I imagine it as a simple `certificates` argument to `azurerm_linux_web_app` (and the windows one too I guess) being a list of `certificate` object providing three arguments:
- `name` (required)
- `pfx_glob` (required)
- `password` (optional)
 
to conform with [current syntax](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_certificate) and in the same way [access policies are handled in keyvaults](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault#access_policy).

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {}

  certificates =
  [
    {
      name = "mycert1"
      pfx_glob = filebase64("mycert1.pfx")
      passwrod = "mypassword"
    },
    {
      name = "mycert2"
      pfx_glob = filebase64("mycert2.pfx")
      passwrod = "mypassword"
    }
  ]
}
```

**Comment by tombuildsstuff** [comment]
hi @adamency 

Thanks for opening this issue.

Taking a look through here I believe this is already supported [via the `azurerm_app_service_certificate` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_certificate) which supports both sourcing these from a local file and KeyVault as needed - would you be able to take a look and see if that works for you?

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by adamency** [comment]
You closing the issue not even two minutes after I posted it when I specifically address the case of the resource you're talking about in the body of my post is kinda rude.

Read my post til the end, I explained how this resource needs a keyvault or a custom binding while the `az` cli method I'm talking about **does not**. It directly assigns it to the appservice itself.

**Comment by tombuildsstuff** [comment]
hi @adamency 

There's a number of resources for uploading/assigning Certificates to App Services - the `azurerm_app_service_certificate` resource doesn't require a binding to exist - however the `azurerm_app_service_certificate_binding` resource does.

Whilst your original post links to the `./examples` directory, unfortunately this directory only contains an example of the `azurerm_app_service_certificate` resource sourcing the certificate from a Key Vault Secret and doesn't cover uploading a file. This is instead covered in the Example Usage in the documentation for the `azurerm_app_service_certificate` resource, which as mentioned above I believe should solve your issue here.

The `./examples` folder in this repository contains a large number of examples but can't cover every scenario - and is primarily intended to contain more extensive/involved scenarios - which are cross-linked from the Resource documentation as appropriate.

As mentioned above, I believe the `azurerm_app_service_certificate` resource will solve this for you, since it doesn't require a binding and there's an example of uploading a certificate from a file in the Example Usage - so I'd recommend [taking a look at the example usage in the documentation here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_certificate) which I believe will solve this issue for you.

However, since this is a configuration question rather than a bug/feature enhancement in the Azure Provider - I'm going to re-close this issue. Should you have questions regarding this resource I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com) where someone should be able to assist you further.

Thanks!
