### ISSUE TITLE
Support for API Management Policy Fragments

### ISSUE THREAD

**Issue by alexwieseawe** [hashicorp/terraform-provider-azurerm#17016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for API Management Policy Fragments

Microsoft Doco: https://docs.microsoft.com/en-us/azure/api-management/policy-fragments
ARM reference: https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/policyfragments?tabs=json

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management_policy_fragment

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management_policy_fragment" "fragment" {
  api_management_id = azurerm_api_management.example.id
  xml_content       = file("example.xml")
  description       = "Reusable policy fragment that does xyz"
}
```

### References

- https://docs.microsoft.com/en-us/azure/api-management/policy-fragments
- https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/policyfragments?tabs=json

**Comment by jeanpaulsmit** [comment]
While native support is under development, you could use the AzApi provider to do the same.

```
resource "azapi_resource" "apim-fragment" {
  type      = "Microsoft.ApiManagement/service/policyFragments@2021-12-01-preview"
  name      = "test-from-tf"
  parent_id = azurerm_api_management.apim.id

  body = jsonencode({
    properties = {
      description = "test-from-tf"
      format      = "rawxml"
      value       = "<fragment><set-header name=\"Some-header\""><value>some-value</value></set-header></fragment>"
    }
    })
}
```
In the 'Potential Terraform Configuration' above, a file (xml_content) is mentioned, but currently it seems only inline fragments are supported (xml or rawxml, and not link-xml or link-rawxml).

**Comment by feberl** [comment]
Are there any plans to implement this? We use policy fragments intensively and actually want to move away from the workaround with AzApi as the plan is always dirty and lifecycle thing does not work for us.

**Comment by PrestonR** [comment]
I've been digging into this for awhile now, and I've come to the conclusion that the problem is with the fragments API. The formatting is just... strange. It's consistently inconsistent. It uses tabs in some places, spaces in other places, line breaks plus tabs and spaces and in some laces, and just line breaks in other places.

It might be worth opening an issue with Azure to have them either provide some guidance on how to format before upload, or give them a heads up that it's a real problem in IAC world.

**Comment by PrestonR** [comment]
Following up to keep this alive. I feel a bit sheepish with my previous response. I didn't realize the `rawxml` format was Razor syntax, and that `xml` format is escaped razor syntax e.g. everything inside the expressions. So it looks like the Fragments API is spitting back `xml` format if you provide it `rawxml` format. Not sure 

That said, there is no work around that I can see to avoid a constant diff.

For what it's worth, I noticed the REST documentation is not updated. It looks like the Fragments API went to general availability on 2022-08-01 - indeed, the [AzAPI documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2022-08-01/service/policyfragments?pivots=deployment-language-terraform) does show the API as generally available.

Also, to confirm my original suspicion, I do believe the AzApi provider is the culprit here. 

Here is a sample policy we submit as a `rawxml` fragment:

```
<fragment>
  <set-variable name="UserId" value="@{
    return ((Jwt)context.Variables["jwt"]).Claims.GetValueOrDefault("sub", new string[1]).First();
  }" />
  <set-body>@{
    var userId = context.Variables.GetValueOrDefault<string>("UserId", "");
    JObject inBody = context.Request.Body?.As<JObject>();
    if (inBody != null) {
      inBody.Add("user_id", userId);
    }
    return inBody.ToString();
  }</set-body>
</fragment>
```

Here is the output from the Terraform plan (after an apply):

```
<fragment>\r\n\t<set-variable name=\"UserId\" value=\"@{&#xA; return ((Jwt)context.Variables[&quot;jwt&quot;]).Claims.GetValueOrDefault(&quot;sub&quot;, new string[1]).First();&#xA; }\" />\r\n\t<set-body>@{\r\n var userId = context.Variables.GetValueOrDefault&lt;string&gt;(\"UserId\", \"\");\r\n JObject inBody = context.Request.Body?.As&lt;JObject&gt;();\r\n if (inBody != null) {\r\n inBody.Add(\"user_id\", userId);\r\n }\r\n return inBody.ToString();\r\n }</set-body>\r\n</fragment>
```

Here is the same output from a GET request directly against the REST api with properties: `https://management.azure.com/subscriptions/{{SUBSCRIPTION_ID}}/resourceGroups/{{RESOURCE_GROUP}}/providers/Microsoft.ApiManagement/service/{{SERVICE_NAME}}/policyFragments/:policyFragmentName?api-version=2022-08-01&format=rawxml` and response:

```
<fragment>\r\n\t<set-variable name=\"UserId\" value=\"@{\n    return ((Jwt)context.Variables[\"jwt\"]).Claims.GetValueOrDefault(\"sub\", new string[1]).First();\n  }\" />\r\n\t<set-body>@{\n    var userId = context.Variables.GetValueOrDefault<string>(\"UserId\", \"\");\n    JObject inBody = context.Request.Body?.As<JObject>();\n    if (inBody != null) {\n      inBody.Add(\"user_id\", userId);\n    }\n    return inBody.ToString();\n  }</set-body>\r\n</fragment>
```

and the `xml` response:

```
<fragment>\r\n\t<set-variable name=\"UserId\" value=\"@{&#xA;    return ((Jwt)context.Variables[&quot;jwt&quot;]).Claims.GetValueOrDefault(&quot;sub&quot;, new string[1]).First();&#xA;  }\" />\r\n\t<set-body>@{\r\n    var userId = context.Variables.GetValueOrDefault&lt;string&gt;(\"UserId\", \"\");\r\n    JObject inBody = context.Request.Body?.As&lt;JObject&gt;();\r\n    if (inBody != null) {\r\n      inBody.Add(\"user_id\", userId);\r\n    }\r\n    return inBody.ToString();\r\n  }</set-body>\r\n</fragment>
```

and the raw state body looks like this:

```
{\"properties\":{\"description\":\"append-userId-to-body\",\"format\":\"rawxml\",\"value\":\"\\u003cfragment\\u003e\\r\\n\\t\\u003cset-variable name=\\\"UserId\\\" value=\\\"@{\\u0026#xA;    return ((Jwt)context.Variables[\\u0026quot;jwt\\u0026quot;]).Claims.GetValueOrDefault(\\u0026quot;sub\\u0026quot;, new string[1]).First();\\u0026#xA;  }\\\" /\\u003e\\r\\n\\t\\u003cset-body\\u003e@{\\r\\n    var userId = context.Variables.GetValueOrDefault\\u0026lt;string\\u0026gt;(\\\"UserId\\\", \\\"\\\");\\r\\n    JObject inBody = context.Request.Body?.As\\u0026lt;JObject\\u0026gt;();\\r\\n    if (inBody != null) {\\r\\n      inBody.Add(\\\"user_id\\\", userId);\\r\\n    }\\r\\n    return inBody.ToString();\\r\\n  }\\u003c/set-body\\u003e\\r\\n\\u003c/fragment\\u003e\"}}
```

That looks like encoding hell. JSON, Unicode, XML, HTML and special chars? 

So, I don't know. Initially, the issue actually looks like a mismatch and a bug to me with the AzAPI provider. If you submit `rawxml` you are returned `xml` instead of `rawxml`. But, worth noting that the REST API itself does not return a JSON response. I'm not sure if the AzAPI provider uses a different API than REST - I would've thought they'd use the same.

I'll file a bug with the AzAPI provider until this gets some traction; hopefully we'll get some relief; will link the issue here after submission.

**Comment by jan-mrm** [comment]
Right now working on a pull request to implement the new resource after updated the api version.
Currently looking into the here already mentioned weird formatting and how to work with that

**Comment by sinbai** [comment]
> Right now working on a pull request to implement the new resource after updated the api version. Currently looking into the here already mentioned weird formatting and how to work with that

Hi @jan-mrm thanks for your contribution, could you please share any updates on the pull request you are working on?

**Comment by jan-mrm** [comment]
hey @sinbai, I lost track since the resource has its challenges and other things came up, but good point. I revived my branch and published it but I'm not 100% on the implementation yet. Take a look

**Comment by travisgan** [comment]
Have been tracking this since last year. Thanks @jan-mrm for the PR. Really looking forward for someone at hashicorp to review and move it forward.

**Comment by travisgan** [comment]
Can anyone from hashicorp provide update on this?
