### ISSUE TITLE
AKS should export the kublet_identity 

### ISSUE THREAD

**Issue by michelefa1988** [hashicorp/terraform-provider-azurerm#17023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently when creating an [AKS](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster) cluster the property `kubelet_identity` is not exported.  This causes issues when we need to create RBAC rules for this identity. 

This key is present and exported in the AKS [datasource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/kubernetes_cluster#kubelet_identity) 

My opinion is that if the datasource can read the resource, then the AKS resource should do the same.

A problem currently present due to this issue can be found here [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/13152) 

### New or Affected Resource(s)/Data Source(s)

all

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/13152

**Comment by sebader** [comment]
not quite sure what you mean? This principalId is already exported:

`azurerm_kubernetes_cluster.foo.kubelet_identity.0.object_id`

**Comment by michelefa1988** [comment]
@sebader , you are right it is there. Then its a problem of documentation

I expect to see this documented [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster)  (taken from [azurerm_kubernetes_cluster data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/kubernetes_cluster))

![image](https://user-images.githubusercontent.com/12183072/171139264-15930eb9-9506-4db8-84f8-fa5e5cfce817.png)

**Comment by sebader** [comment]
yeah it appears the docs dont mention this. Maybe change your issue to reflect this

**Comment by myc2h6o** [comment]
Hi @michelefa1988. For blocks, only attributes which are not configurable and auto filled by services are put under `Attributes Reference` and uses `... block exports ...`. If the property is configurable, it uses `... block supports ...`., and since it's configurable, it is also exported, and the value is same as what is being set in the config file. So you shall be able to use below properties under `kubelet_identity`
![image](https://user-images.githubusercontent.com/10579712/171175974-13c2eb9d-049a-42fa-b427-8941dd0cc825.png)


\--------------------------------------------------------------------------------------------------
And this is another example in [kubernetes_cluster](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster) for `identity` block. `type` and `identity_ids` can be configured, and also exported from the resource, the exported value is the configured value. `principal_id` and `tenant_id` is decided by service, and cannot be put in the config, so they are under `Attribute Reference` section and marked as exported.
![image](https://user-images.githubusercontent.com/10579712/171175925-c2f610d8-09dd-4a7c-aa53-ea09cc2af6ac.png)
![image](https://user-images.githubusercontent.com/10579712/171175852-ac71118e-bdfa-4e58-a4ec-30e9d1c9e875.png)

**Comment by michelefa1988** [comment]
@myc2h6o makes sense to me. Will you guys be adding it to the docs?

**Comment by michelefa1988** [comment]
@myc2h6o are you able to update the documentation to make it more clear for others? 

As far as I understand you are saying that if a block is imported (input) it is automatically exported (output). I would know this now but I guess others may find it confusing. 

Perhaps you can update the `kubelet_identity` documentation to block to `The kubelet_identity block supports and exports the following:`

**Comment by myc2h6o** [comment]
Hi @michelefa1988, although there is no keyword like `export` for `kubelet_identity`, because it is under [Argument Reference](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#argument-reference), it is considered as exported. You can find more detail about `Argument` [here](https://www.terraform.io/language/expressions/references#references-to-resource-attributes):

>The documentation for aws_instance lists all of the arguments and nested blocks supported for this resource type, and also lists a number of attributes that are exported by this resource type. All of these different resource type schema constructs are available for use in references, as follows:

>The arguments of the ebs_block_device nested blocks can be accessed using a splat expression. For example, to obtain a list of all of the device_name values, use aws_instance.example.ebs_block_device[*].device_name

Besides this, I think we do have some inconsistency in the doc, I've opened #17059 to fix it.
