### ISSUE TITLE
vague error upgrading azurerm v2.95.0 -> v3.8.0

### ISSUE THREAD

**Issue by fgarcia-cnb** [hashicorp/terraform-provider-azurerm#17049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.7

### AzureRM Provider Version

2.95.0, 3.8.0

### Affected Resource(s)/Data Source(s)

several

### Terraform Configuration Files

```hcl
Upgrading an entire module. too many resources to list
```

### Debug Output/Panic Output

```shell
│ Error: Insufficient identity blocks
│
│   on  line 0:
│   (source code not available)
│
│ At least 1 "identity" blocks are required.
```

### Expected Behaviour

module code plans just fine with azurerm 2.95.0. i expect errors moving to v3.8.0... hoping the errors help me identify sections that need to be modified to be compatible with v3.8.0. However, i am getting a very vague, useless error. Verbose logging didnt help much either.

any suggestions?

**Comment by rcskosir** [comment]
@fgarcia-cnb Thanks for taking the time to submit this issue. I am glad you were able to find the resource that needed an identity block defined. I understand that these kind of version upgrades can be frustrating and tricky to navigate. We will continue to strive to make our error messages more useful. Since you were able to resolve your issue I am going to mark this issue as closed.
