### ISSUE TITLE
dynamic validation in locals 

### ISSUE THREAD

**Issue by venrass** [hashicorp/terraform-provider-azurerm#17065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Right now i dont see an option to validate variables in locals block...is there a provision to add dynamic in locals too
for example i have a list of comma seperated container names used while storage account creation... i wanted to validate each container name... how do i do it now...
var.othercontainer_name for example is "abc,cfr,ggg,ddd" is a comma separated list of strings
 
locals {
  containers = "${var.othercontainer_name!=" " ? split(",", trimspace(var.othercontainer_name)) : [] }" 

  dynamic "validation"{
    for_each = local.containers
    content{
        condition = (
        length(containers.value) >= 3 &&
        length(containers.value) <= 24 &&
        can(regex("^[0-9a-z]+$", containers.value))
      )
      error_message = "Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only."
    }
  }
}

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

**Comment by tombuildsstuff** [comment]
hi @venrass 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
