### ISSUE TITLE
Wrong destroy order when using named values for backend credentials

### ISSUE THREAD

**Issue by radui1398** [hashicorp/terraform-provider-azurerm#17080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

2.99.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_named_value, azurerm_api_management_backend

### Terraform Configuration Files

```hcl
- 1 APIM Instance
- 1 APIM API Instance
- 1 Named value that saves credentials "appKey"
- 1 Backend that uses the named value "my-backend"
- 1 Policy on the operation that uses a backend
- 1 Operation
```

### Debug Output/Panic Output

```shell
╷
│ Error:  deleting Named Value: (Name "appKey" / Service Name "service-name" / Resource Group "rg"): apimanagement.NamedValueClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="The Api Management Property 'appKey' is used by the following entities:\r\n/backends/my-backend\r\n"
│ 
│ 
╵
```

### Expected Behaviour

The delete order should be:

- delete operation policy that uses backend
- delete backend
- delete named value

### Actual Behaviour

The actual delete order probably is:

- delete operation policy that uses backend
- delete named value
- delete backend

### Steps to Reproduce

Only a terraform apply is enough to retrieve the error.

### Important Factoids

Running in Europe West

**Comment by tombuildsstuff** [comment]
hi @radui1398 

Thanks for opening this issue.

Taking a look through here this appears to be an issue with the Terraform Configuration being used which can be solved by [using a `depends_on` to explicitly define the dependencies](https://www.terraform.io/language/meta-arguments/depends_on), which'll enforce the ordering both when provisioning and tearing these resources down - which can be used in alongside interpolation (which creates an implied resource ordering).

Since this'll be fixed by updating the Terraform Configuration being used here, I'm going to close this issue for the moment as this forum is intended to be used for feature enhancements and bugs in the Azure Provider - however should you have further questions about the Terraform Configuration I'd direct you towards [one of the Community Resources](https://www.terraform.io/community.html) where someone should be able to assist further.

Thanks!
