### ISSUE TITLE
Support for Java 17

### ISSUE THREAD

**Issue by bouncysteve** [hashicorp/terraform-provider-azurerm#17144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure App Service now supports Java 17 (https://devblogs.microsoft.com/java/java-17-and-tomcat-10-0-available-on-azure-app-service/), but site_config only allows 1.7, 1.8 and 11 for java_container_version and java_version.

### New or Affected Resource(s)/Data Source(s)

azurerm_3.9.0

**Comment by xiaxyi** [comment]
Thanks @bouncysteve for raising this feature request. I added java 17 for Linux web app in the mentioned pr. I'll check the windows and update later.

**Comment by ozen10** [comment]
Is there an update when will the java 17 be available for azurerm_windows_web_app

**Comment by peterprumbach-telekom** [comment]
We also have an urgent need for support for version 17 in our azurerm_windows_web_app!

**Comment by rcskosir** [comment]
@bouncysteve Thank you for opening this issue. I know some time and many versions have passed since you opened this issue. As stated in a comment above, azurerm_linux_web_app has Java 17. In addition, the documentation shows that Java 17 is an option for azurerm_windows_web_app as well: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app
Since Java 17 is available, I am going to close this issue.
