### ISSUE TITLE
Support for disk resize without downtime (live)

### ISSUE THREAD

**Issue by kazimierzbudzyk** [hashicorp/terraform-provider-azurerm#17240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure has a no-downtime disk resizes available in public preview. We should allow this functionality to be available when resizing disks through terraform.

Given this is still a preview feature we should make it opt-in on the relevant resources. Terraform should verify if feature is enabled if possible. We need to respect the restriction of this feature only being available for disks up to 4 TiB and only data disks (os disk no-downtime resizes are not supported).

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine, azurerm_windows_virtual_machine, azurerm_managed_disk

### References

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/expand-os-disk#resize-without-downtime-preview

**Comment by kazimierzbudzyk** [comment]
Update: Feature is now GA https://azure.microsoft.com/en-us/updates/generally-available-live-resize-for-premium-ssd-and-standard-ssd-disk-storage/

**Comment by myc2h6o** [comment]
Thanks @kazimierzbudzyk for the update! @tombuildsstuff service team said after the GA of Premium SSD and Standard SSD mentioned above by @kazimierzbudzyk, Standard HDD will be GA after a few weeks, and Ultra SSD not decided yet.

**Comment by jrca025** [comment]
@kazimierzbudzyk link cannot be found. any other alternatives?

**Comment by kazimierzbudzyk** [comment]
@jrca025 it looks like the announcement was pulled back, see discussion in https://github.com/MicrosoftDocs/azure-docs/issues/96112.

**Comment by Klaas-** [comment]
https://github.com/MicrosoftDocs/azure-docs/commit/b6737115677d0bcba130347ea9ead5e3363b74d9 https://azure.microsoft.com/en-us/updates/generally-available-live-resize-for-premium-ssd-and-standard-ssd-disk-storage/

I'd say it's now GA

**Comment by tombuildsstuff** [comment]
[](👋 hey folks

Apologies for the delayed reply here / for #17245.

I've spent a little while digging into this (and #17245) and whilst we also thought this needed to be threaded through the (Linux/Windows) Virtual Machine, (Linux / Orchestrated / Windows) Virtual Machine Scale Set and Data Disk Attachment resources, in addition to the Managed Disk resource - however digging into this it appears this is only actually needed within the Managed Disk resource (as the VM resources don't currently support inlined data disks, isn't applicable to OS Disks - and changing this for VMSS would cause the instance to be cycled using the non-orchestrated mode).

I've taken a look through #17245 and whilst it's off to a good start, based on the conditions listed for both [the Linux Virtual Machine](https://learn.microsoft.com/azure/virtual-machines/linux/expand-disks?tabs=azure-cli%2Cubuntu#expand-without-downtime) [and the Windows Virtual Machine](https://learn.microsoft.com/azure/virtual-machines/windows/expand-os-disk#expand-without-downtime) we do need to account for the state/configuration of the Virtual Machine in addition to that of the Managed Disk.

As such whilst I'd like to apologise for the delay reviewing this one, I hope you don't mind @kazimierzbudzyk but I'm going to push a couple of commits to #17245 to make those changes, add a test covering this, and rename the feature flag for this to `expand_without_downtime` (to match the GA name for this feature) - but that's otherwise looking pretty good to me 👍 .

Thanks!

**Comment by manicminer** [comment]
Closed by #17245
