### ISSUE TITLE
Support for DesktopVirtualization API version 2022-02-10-preview

### ISSUE THREAD

**Issue by amccullough84** [hashicorp/terraform-provider-azurerm#17303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for the updated desktopvirtualization API version 2022-02-10-preview has/is being added in the Go SDK, but is being added as Track2 not Track1 which is currently not supported by the provider.

The current API version used by the provider is now 4+ months out of sync with features, that can't be implemented without the new API version being supported.

Looking through commits on the Azure SDK for Go, the plan seems to be that once a service is in Track 2, the Track 1 equivalent will be deprecated, so we need to know the approach for integrating new API versions being released into Track 2 of the SDK for Go into the provider. 

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_xxxx

### References

Track 2 release: https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fresourcemanager%2Fdesktopvirtualization%2Farmdesktopvirtualization%2Fv2.0.0-beta.1

REST API Specs: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2022-02-10-preview

**Comment by tombuildsstuff** [comment]
(Apologies, unintentionally closed this through a related PR, will get a reply out later today)

**Comment by tombuildsstuff** [comment]
hey @amccullough84 

Thanks for reaching out here.

As you've mentioned, the Azure SDK (Team) are busy migrating packages from Track1 to Track2 - and whilst there's a number of changes in the Track2 SDK, this isn't something we plan to use at this point in time for a number of reasons.

Instead we're moving towards using a Terraform-specific Go SDK, based on [the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs) - which can be found [at `hashicorp/go-azure-sdk`](https://github.com/hashicorp/go-azure-sdk). This SDK includes a number of Terraform specifics which means that we can lean more heavily on the SDK and reduces the code required for each resource.

I've opened #17340 which updates the `desktopvirtualization` package to use the (same) `2021-09-03-preview` API from `hashicorp/go-azure-sdk` rather than `Azure/azure-sdk-for-go`. Once that's merged, as [the `hashicorp/go-azure-sdk` repository includes the newer `2022-02-10-preview` API version too](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/desktopvirtualization), it should be possible to update this to use the new API Version and add any new fields.

Since this is a question rather than an issue/feature request for the Azure Provider, I'm going to close this issue for the moment - but as mentioned above since an SDK is now available for this it should be possible for someone to take a look at updating this to the new API Version once #17340 has been merged.

Thanks!
