### ISSUE TITLE
azurerm_storage_share : Key based authentication is not permitted on this storage account

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#17341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_share

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "filesupport" {
  name                              = var.storage_account_name
  resource_group_name               = var.resource_group_name
  location                          = var.location
  infrastructure_encryption_enabled = var.infrastructure_encryption_enabled
  shared_access_key_enabled         = false
  account_kind                      = "StorageV2"
  account_tier                      = var.account_tier
  account_replication_type          = var.account_replication_type

  identity {
    type         = "UserAssigned"
    identity_ids = [var.user_assigned_identity_id]
  }

  network_rules {
    bypass         = ["AzureServices", "Logging", "Metrics"]
    default_action = "Allow"
  }
  tags = var.tags
}

resource "azurerm_storage_account_customer_managed_key" "filesupport" {
  storage_account_id        = azurerm_storage_account.filesupport.id
  key_vault_id              = var.key_vault_id
  key_name                  = azurerm_key_vault_key.filesupport.name
  user_assigned_identity_id = var.user_assigned_identity_id
}

resource "azurerm_key_vault_key" "filesupport" {
  name         = var.storage_account_name
  key_vault_id = var.key_vault_id
  key_type     = "RSA"
  key_size     = 3072

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

resource "azurerm_storage_share" "oraclesupport" {
  name                 = local.vm_name
  storage_account_name = data.azurerm_storage_account.oraclesupport[0].name
  quota                = var.oracle_quota
}
```

### Debug Output/Panic Output

```shell
Error: [0m[0m[1mchecking for existence of existing Storage Share "xxx" (Account "ssss" / Resource Group "rrrr"): shares.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account.
```

### Expected Behaviour

File share is created.

### Actual Behaviour

No file share created error occurs.

### Steps to Reproduce

terraform apply

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/11460

**Comment by tombuildsstuff** [comment]
hi @mpjtaylor 

Thanks for opening this issue.

Due to limitations within the Azure API the AzureRM Provider has to make use of the Data Plane API when provisioning items (Blobs, Containers, Shares etc) within a Storage Account, which by default is done using Shared Key Authentication.

For _some_ of the Items within a Storage Account it's possible to use AzureAD authentication instead, [which can be enabled using this setting](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#storage_use_azuread) - but unfortunately full support for using Resource Manager (and AzureAD authentication) for provisioning nested items within a Storage Account rather than Data Plane is blocked on the Azure Service Team at this point in time (and tracked in #2977).

This means that at this point in time you'll need to allow Shared Key access to the Storage Account if you're looking to provision Storage Shares within it - but if you're looking to do this without enabling Shared Key access, I'd recommend subscribing to #2977 (which is currently waiting on the Azure Service Team to make the Data Plane and Resource Manager APIs feature-compatible).

Since this is a configuration question I'm going to close this issue for the moment, but as mentioned above I'd recommend subscribing to #2977 here which should fix this longer-term.

Thanks!
