### ISSUE TITLE
azurerm_application_gateway wrong size limits when WAF_V2 and CRS 3.2

### ISSUE THREAD

**Issue by lukerogers** [hashicorp/terraform-provider-azurerm#17344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "network" {
  ...
  
  waf_configuration {
    enabled                   = true
    firewall_mode             = "Prevention"
    rule_set_type             = "OWASP"
    rule_set_version	        = "3.2"
    file_upload_limit_mb      = "4000"
    max_request_body_size_kb  = "2000"
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected waf_configuration.0.file_upload_limit_mb to be in the range (1 - 750), got 4000

  with azurerm_application_gateway.network,
  on agw.tf line 74, in resource "azurerm_application_gateway" "network":
  74:     file_upload_limit_mb      = "4000"


Error: expected waf_configuration.0.max_request_body_size_kb to be in the range (1 - 128), got 2000

  with azurerm_application_gateway.network,
  on agw.tf line 75, in resource "azurerm_application_gateway" "network":
  75:     max_request_body_size_kb  = "2000"
```

### Expected Behaviour

When using WAF_V2 **AND** CRS3.2 the limits should be as follows:

- 2MB request body size limit
- 4GB file upload limit

Documentation on this update is at https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/application-gateway-waf-request-size-limits

### Actual Behaviour

Error is thrown about sizes being too large

### Steps to Reproduce

Create AGW with WAF_V2 and CRS 3.2 with higher limits as indicated in the Configuration section of this issue.

**Comment by lukerogers** [comment]
I notice that the [WAF Policy](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/web_application_firewall_policy_resource.go) has the increased limits as well

"file_upload_limit_in_mb": {
	Type:         pluginsdk.TypeInt,
	Optional:     true,
	ValidateFunc: validation.IntBetween(1, 4000),
	Default:      100,
},
"max_request_body_size_in_kb": {
	Type:         pluginsdk.TypeInt,
	Optional:     true,
	ValidateFunc: validation.IntBetween(8, 2000),
	Default:      128,

But the validation logic is just that and doesn't consider the WAF and CRS Version.

**Comment by sinbai** [comment]
Hi @lukerogers,

Thank you for opening this issue here.  For the [doc]( https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/application-gateway-waf-request-size-limits) mentioned above, it corresponds the resource `azurerm_web_application_firewall_policy`  in terraform . The maximum value of [file_upload_limit_in_mb](https://github.com/hashicorp/terraform-provider-azurerm/blob/fb0d21e27f04b92d06f62622351d79f316adad59/internal/services/network/web_application_firewall_policy_resource.go#L269) is 4000 and [max_request_body_size_in_kb](https://github.com/hashicorp/terraform-provider-azurerm/blob/fb0d21e27f04b92d06f62622351d79f316adad59/internal/services/network/web_application_firewall_policy_resource.go#L275) is 2000 currently.

However, the resource `azurerm_application_gateway` could not currently support increasing the limits, because the latest version Azure API does not support FileUploadLimitInMb set to 4000 and MaxRequestBodySizeInKb  set to 2000 when the `rule_set_version` set to 3.2, the detail are as follows:

The response from [API](https://docs.microsoft.com/en-us/rest/api/application-gateway/application-gateways/create-or-update#code-try-0):

```
{
  "error": {
    "code": "ApplicationGatewayFirewallInvalidFileUploadLimitInMbForWAFv2",
    "message": "FileUploadLimitInMb '4000' is out of range for WAF v2, it should be within '1' and '750' in context 'properties.webApplicationFirewallConfiguration'.",
    "details": []
  }
}
```

```
{
  "error": {
    "code": "ApplicationGatewayFirewallInvalidMaxRequestBodySizeInKb",
    "message": "MaxRequestBodySizeInKb '2000' is out of range, it should be within '8' and '128' in context 'properties.webApplicationFirewallConfiguration'.",
    "details": []
  }
}
```

**Comment by lukerogers** [comment]
Sorry about that, I read it that the WAF itself supported the higher limits. Now I see it's just on the policies. Thanks for the clarification!
