### ISSUE TITLE
Support for azurerm_frontdoor

### ISSUE THREAD

**Issue by MATTHEWTAYLOR1995** [hashicorp/terraform-provider-azurerm#17460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello guys,

Is it possible to add the "Pricing Tier" argument into the azurerm_frontdoor resource? 

It looks like it's been added into the AzureRM provider - https://github.com/hashicorp/terraform-provider-azurerm/pull/15140

Thanks guys,
Matt

### New or Affected Resource(s)/Data Source(s)

azurerm_frontdoor

### Potential Terraform Configuration

```hcl
pricing_tier = ["Standard", "Premium", "Classic"]
```

**Comment by WodansSon** [comment]
@MATTHEWTAYLOR1995, thank you for opening this issue. The legacy Front Door `network` API does not expose support for the `pricing_tier` field, so adding this to the existing resources is not an option. The `pricing_tier` field is only exposed in the new `CDN` API version of the Front Door resources. I am sorry for the delay, and I fully understand your frustration around this. I will do what I can to expedite the release of the remaining 7 resources required for a working version of the `CDN` Front Door. That said, I am going to close this issue since there is currently no way to expose the `pricing_tier` in the legacy `azurerm_frontdoor` resource. I thank you for your patience while we work through the implementation details of the new `CDN` Front Door resources. This is currently my top priority.
