### ISSUE TITLE
“staticCommunicationServices”: expected the segment “CommunicationServices” to be “communicationServices”

### ISSUE THREAD

**Issue by Shurbeski** [hashicorp/terraform-provider-azurerm#17532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.12.0

### Affected Resource(s)/Data Source(s)

azurerm_communication_service

### Terraform Configuration Files

```hcl
const communicationService = new CommunicationService(scope, `${id} communication service`, {
    name: `${id}-communication`,
    resourceGroupName: rg.name,
    dataLocation: "United States",
  });
```

### Debug Output/Panic Output

```shell
[2022-07-06T17:40:01.917] [ERROR] default - ╷
│ Error: parsing "/subscriptions/**/resourceGroups/**rg/providers/Microsoft.Communication/CommunicationServices/-communcation": parsing segment "staticCommunicationServices": expected the segment "CommunicationServices" to be "communicationServices"
│ 
│   with azurerm_communication_service.**communicationservice,
│   on cdk.tf.json line 4401, in resource.azurerm_communication_service.**communicationservice:
│ 4401:       }
```

### Expected Behaviour

Because of the reason the Communication Service is deployed 5 months ago and we haven't done any changes there, the expected behavior is to continue deploying new and changed resources and not get stuck with this error:

### Actual Behaviour

We are using CDKTF,  once we execute the command `cdktf yarn deploy` we are getting the following error 
```
[2022-07-06T17:40:01.917] [ERROR] default - ╷
│ Error: parsing "/subscriptions/**/resourceGroups/**rg/providers/Microsoft.Communication/CommunicationServices/-communcation": parsing segment "staticCommunicationServices": expected the segment "CommunicationServices" to be "communicationServices"
│ 
│   with azurerm_communication_service.**communicationservice,
│   on cdk.tf.json line 4401, in resource.azurerm_communication_service.**communicationservice:
│ 4401:       }
```

### Steps to Reproduce

cdktf deploy

**Comment by myc2h6o** [comment]
Communication Service was initially introduced with the id segment `CommunicationServices` https://github.com/hashicorp/terraform-provider-azurerm/blob/1b6330b3d0645f4b66747771e2df55493c519397/internal/services/communication/parse/communication_service.go#L36
however it seems wrong compared to the segment name `communicationServices` in [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/f0343961168af6b19ea86dd3aa2429e2ca453db4/specification/communication/resource-manager/Microsoft.Communication/stable/2020-08-20/CommunicationService.json#L265).

[Segment](https://github.com/hashicorp/go-azure-sdk/blob/b10d07b1bd07f1962e070cb0c555b8ff87c5bdf1/resource-manager/communication/2020-08-20/communicationservice/id_communicationservice.go#L111) was updated by https://github.com/hashicorp/terraform-provider-azurerm/commit/1572cfefbcbd8add88821d59a0f77fbb005f94fc. It is the ideal segment but seems to be breaking the resource created before the change, due to the segment validation.

@tombuildsstuff in order to not break the old resource, shall we parse this ID case insensitively and parse it case sensitively in 4.0?
