### ISSUE TITLE
Set public_network_access_enabled to false on private / internal AKS

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-azurerm#17555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> public_network_access_enabled - (Optional) Whether public network access is allowed for this Kubernetes Cluster. Defaults to true. Changing this forces a new resource to be created.

This is also true for AKS that have `private_cluster_enabled = true` which means that they should not be accessible from public networks. As `public_network_access_enabled ` defaults to `true` you have to explicitly declare if for private clusters.

> [private_cluster_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#private_cluster_enabled) - (Optional) Should this Kubernetes Cluster have its API server only exposed on internal IP addresses? This provides a Private IP Address for the Kubernetes API on the Virtual Network where the Kubernetes Cluster is located. Defaults to false. Changing this forces a new resource to be created.

(for both see this docu: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster)

A private cluster with the default public_network_access_enabled would be created like the following:
![image](https://user-images.githubusercontent.com/46575727/177943350-34de847c-e59f-4422-b788-ca06c2a10114.png)

My idea would be to set `public_network_access_enabled = false` if the cluster is private.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster

**Comment by eehret** [comment]
In addition I would like to point out that if you have created a private cluster that initially had `public_network_access_enabled = true` (the default) and then subsequently try to change its value to `false` this results in Terraform indicating that destruction and recreation of the cluster is required.   This makes little sense to me, as these two configurations should be functionally identical.

**Comment by svg153** [comment]
The `public_network_access_enabled` was deprecated for AKS https://github.com/hashicorp/terraform-provider-azurerm/pull/22478

**Comment by stephybun** [comment]
Thanks for raising this issue @mkemmerz.

As pointed out in the comment above this property has been deprecated with the reason being that the property was never functional in the first place. Please see [this comment over on the AKS repo](https://github.com/Azure/AKS/issues/3690#issuecomment-1590425190) for more information. 

Since this property was introduced with the default value of `true` we've opted to keep it that way to prevent any accidental diffs for users that haven't set this property. Although setting/changing this value will have no effect on the cluster since we aren't sending this to the API anymore, you can set it to `false` now without having the cluster recreated for parity with what is set in `private_cluster_enabled` and for peace of mind.

With that in mind I'm going to close this issue, as this property has no bearing on the actual accessibility of the cluster.
