### ISSUE TITLE
Support for adding function to App Function Slot & VNet Integration

### ISSUE THREAD

**Issue by geremy42** [hashicorp/terraform-provider-azurerm#17670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Adding function to Function App Slot doesn't work as VNet Integration
`ID contained more segments than required: "/subscriptions/subId/resourceGroups/RSG-Name/providers/Microsoft.Web/sites/FUN-NAME/slots/staging", map[slots:staging]`

The same behavior has been seen for `azurerm_function_app_slot ` or `azurerm_windows_function_app_slot` 

### New or Affected Resource(s)/Data Source(s)

azurerm_function_app_function, azurerm_app_service_slot_virtual_network_swift_connection

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app_function" "test" {
  name            = "test"
  function_app_id = azurerm_function_app_slot.test.id
  config_json = jsonencode({
    "bindings": [
    {
      "type": "eventGridTrigger",
      "name": "eventGridEvent",
      "direction": "in"
    }
  ]
  })
}
resource "azurerm_app_service_slot_virtual_network_swift_connection" "test" {
  slot_name      = azurerm_function_app_slot.test.name
  app_service_id = azurerm_function_app_slot.test.id
  subnet_id      = azurerm_subnet.test.id
}
```

**Comment by bubbletroubles** [comment]
I've been looking at vNet integration for Windows/Linux Web/Function apps. I've submitted PRs for review to expose the vNet Integration directly on each resource, instead of calling the `azurerm_app_service_slot_virtual_network_swift_connection`.

This capability is documented at https://docs.microsoft.com/en-us/azure/app-service/overview-vnet-integration#permissions where the `virtualNetworkSubnetId` property can be set directly to enable vNet Integration.

I've tested that both the Function App and Slot resources both work with vNet Integration. My recommendation would be to use the direct via resource method once the PRs are approved and the next version of the AzureRM provider is published.

Pull requests:
#17576 - AzureRM Windows Web App
#17572 - AzureRM Windows Function App
#17494 - AzureRM Linux Function App
#17584 - AzureRM Linux Web App
#17731 - AzureRM Logic App

@tombuildsstuff @jackofallops @katbyte FYI

**Comment by geremy42** [comment]
Works well @bubbletroubles ! Thanks
