### ISSUE TITLE
Cannot create windows VM from third party azure image (cognosys)

### ISSUE THREAD

**Issue by fassaghir** [hashicorp/terraform-provider-azurerm#17774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.14.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
i am using below configurations to create VM from third party image on Azure market place but i am error.


resource "azurerm_virtual_machine" "vm" {
  count = 1
  name = "test-vm"
  location = "west europe"
  resource_group_name = "test_rg"
  network_interface_ids = [element(azurerm_network_interface.network_interface.*.id, count.index)]
  vm_size = var.vm_size
  

  storage_image_reference {
    publisher = "cognosys"
    offer     = "hardened-iis-on-windows-server-2012-r2"
    sku       = "hardened-iis-on-windows-ser-2012-r2"
    version   = "latest"
}
}
```

### Debug Output/Panic Output

```shell
Error: Code="VMMarketplaceInvalidInput" Message="Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request. VM
```

**Comment by tombuildsstuff** [comment]
hi @fassaghir 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 3.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!
