### ISSUE TITLE
How to increase os disk size? by default linux vm will take 30GiB using os_disk block in azurerm_windows_virtual_machine resource

### ISSUE THREAD

**Issue by gouthamkamre68** [hashicorp/terraform-provider-azurerm#17844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Hi,

I'm new to terraform and i have one requirement is to increase os disk size, as per terraform code default it's taking 30 GiB if i want to increase to 60 GiB what code need to write.

i don't want to add additional disk just want to increase os disk size.

### Description

I'm new to terraform and i have one requirement is to increase os disk size, as per terraform code default it's taking 30 GiB if i want to increase to 60 GiB what code need to write.

i don't want to add additional disk just want to increase os disk size.

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_windows_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  admin_password      = "P@$$w0rd1234!"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }
```

**Comment by tombuildsstuff** [comment]
hi @gouthamkamre68 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
