### ISSUE TITLE
azurerm_container_registry should ignore georeplications order

### ISSUE THREAD

**Issue by palmerabollo** [hashicorp/terraform-provider-azurerm#17987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13.7

### AzureRM Provider Version

3.18.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "mycontainerregistry" {
  name                = "mycontainerregistry"
  resource_group_name = "myresourcegroup"
  location            = "North Europe"
  sku                 = "Premium"
  admin_enabled       = false

  georeplications {
    location = "eastus2"
    regional_endpoint_enabled = true
  }

  georeplications {
    location = "eastus"
    regional_endpoint_enabled = true
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_container_registry.mycontainerregistry will be updated in-place
  ~ resource "azurerm_container_registry" "mycontainerregistry" {
        [...]

      ~ georeplications {
          ~ location                  = "eastus" -> "eastus2"
            regional_endpoint_enabled = true
            tags                      = {}
            zone_redundancy_enabled   = false
        }
      ~ georeplications {
          ~ location                  = "eastus2" -> "eastus"
            regional_endpoint_enabled = true
            tags                      = {}
            zone_redundancy_enabled   = false
        }
    }
```

### Expected Behaviour

No changes should be detected. The order in the georeplication regions should be ignored.

### Actual Behaviour

Terraform/azurerm detects a change in the georeplication regions, even if they are the same two regions (eastus and eastus2).

### Steps to Reproduce

terraform apply

**Comment by magodo** [comment]
@palmerabollo Thank you for submitting this!

Ideally we should make the `georeplications` a `Set` (order insensitive) rather than a `List` (order sensitive). Whilst since there is an underlying [bug](https://github.com/hashicorp/terraform-plugin-sdk/issues/160) in the SDK for type `Set`, we have to keep it as a `List`.

On the other hand, the service team is expected to keep the order of the replications as the user defined, so that the `List` type can also work as expected. Unfortunately, they didn't. As a workaround, we order the returned replications in dict order: https://github.com/hashicorp/terraform-provider-azurerm/blob/0357a5709aa5a18afbcb37d2c263acbeb2216a36/internal/services/containers/container_registry_resource.go#L662-L665

This means, users are expected to keep the same order in the config. In your example config, it simply implies that swap the two `georeplications` does the trick. I'll mention this in the document.
