### ISSUE TITLE
Support for azurerm_linux_function_app to add Source Control

### ISSUE THREAD

**Issue by ktgrondahl** [hashicorp/terraform-provider-azurerm#18032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello, I am working on setting up an azurerm_linux_function_app to create a Function App in Azure. 

The azurerm_linux_function_app does not support a source_control block, like the traditional (soon to be depracated) function_app did. 
 
Option 1: (add support for source control inside linux web app, (just like plain function app))
OR

Option 2: 
Create a new resource for adding source control to linux function app, similar to how it is done for app services with  the azurerm_app_service_source_control resource. 

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Potential Terraform Configuration

```hcl
Option 1: 
source_control {
    repo_url = "https://github.com/totallyawesomerepo"
    branch   = "main"
  }

or
Option 2: 
resource "azurerm_function_app_source_control" "example" {
 app_id   = azurerm_linux_function_app.example.id
 repo_url = "https://github.com/totallyawesomerepo"
 branch   = "main"
}
```

**Comment by kkpeterson4** [comment]
This would be a very helpful feature for my team!

**Comment by SPSCS-Simon** [comment]
It's now October 2023! so over 12 months since the last comment! There also seems to be a bunch of positive reactions - how many are needed to prioritize this! 

Per the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service):
_This resource has been deprecated in version 3.0 of the AzureRM provider and will be removed in version 4.0. Please use [azurerm_linux_web_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app) and [azurerm_windows_web_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app) resources instead._

There seems no alternate just now but revert to using the App Service, this also ties into the `cdktf` provider too!
