### ISSUE TITLE
azurerm_role_assignment does not error out if principal_id does not exist

### ISSUE THREAD

**Issue by calebak404** [hashicorp/terraform-provider-azurerm#18113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.14.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "role_assignment" {
  name                              = random_uuid.role_assignment_id.result
  scope                             = local.role_scope
  
  role_definition_id                = local.role_definition[var.role_name]
  principal_id                      = var.service_principal_id
  description                       = var.description

  skip_service_principal_aad_check  = false
}
```

### Debug Output/Panic Output

```shell
authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal <<REDACTED>> does not exist in the directory <<REDACTED>>. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype"
```

### Expected Behaviour

A principal ID that doesn't exist should have errored out immediately with a 404.

### Actual Behaviour

Run continues until timeout value is hit.

Based on the description of [skip_service_principal_aad_check](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#skip_service_principal_aad_check) I might expect this behavior if that argument was set to true.  But false is the default, and we are explicitly setting it, and still getting this behavior.

### Steps to Reproduce

Run deploy a role assignment with a principal_id that doesn't exist in azure ad.

**Comment by ms-zhenhua** [comment]
Hi @calebak404, thank you for reaching out. 
By current design, if the provider receives **PrincipalNotFound** error from Azure Cloud, it will try to recreate the azurerm_role_assignment until success or timeout value is hit. The reason is there are 2 possible scenarios that Azure Cloud may respond **PrincipalNotFound**: 
1. The principal id was not added before.
2. The principal id is newly created. It cannot be immediately returned because of [replication delay](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-template#new-service-principal).

Since the provider cannot tell apart these 2 scenarios, it has to use retry with a timeout value as a workaround to solve these scenarios.

The [skip_service_principal_aad_check](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#skip_service_principal_aad_check) can only be used for a newly created SP. It will not work for a SP which was not added before. And this property can be used only when the principal type is **Service Principal**. It does not work for other types(**User**, **Group**, etc.) of principal id.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. On review, the described behavior is as intended based on @ms-zhenhua's comment above. Therefore I am going to mark this issue as closed.
