### ISSUE TITLE
Azure CLI 2.37.0 breaks on the Microsoft Graph migration

### ISSUE THREAD

**Issue by JWDobken** [hashicorp/terraform-provider-azurerm#18179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Due to [the deprecation of Azure Active Directory (Azure AD) Graph](/graph/migrate-azure-ad-graph-overview), the underlying Active Directory Graph API will be replaced by [Microsoft Graph API](/graph/api/overview) in Azure CLI 2.37.0.

This actually breaks 
Running terraform plan gives the following error:

```cmd
│ Error: building account: getting authenticated object ID: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: AADSTS530003: Your device is required to be managed to access this resource.
│ Trace ID: XXXX-XXXX-XXXX-XXXX
│ Correlation ID: XXXX-XXXX-XXXX-XXXX
│ Timestamp: 2022-08-30 09:14:38Z
│ To re-authenticate, please run:
│ az login --scope https://graph.microsoft.com//.default
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on provider.tf line 1, in provider "azurerm":
│    1: provider "azurerm" {
```

### Terraform Version

1.2.8

### AzureRM Provider Version

3.20.0

### Affected Resource(s)/Data Source(s)

provider "azurerm"

### Terraform Configuration Files

```hcl
terraform {
  required_version = "= 1.2.8"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.20.0"
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: building account: getting authenticated object ID: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: AADSTS530003: Your device is required to be managed to access this resource.
│ Trace ID: XXXX-XXXX-XXXX-XXXX
│ Correlation ID: XXXX-XXXX-XXXX-XXXX
│ Timestamp: 2022-08-30 09:14:38Z
│ To re-authenticate, please run:
│ az login --scope https://graph.microsoft.com//.default
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on provider.tf line 1, in provider "azurerm":
│    1: provider "azurerm" {
```

### Expected Behaviour

accept the working `az login`

### Actual Behaviour

rejects the login credentials, see error output abve

### Steps to Reproduce

tf plan

**Comment by tombuildsstuff** [comment]
hi @JWDobken 

Thanks for opening this issue.

Taking a look through here this change isn't strictly related to Microsoft Graph but appears to be a change in security policy being used, namely this error is coming back from the Azure CLI: `ERROR: AADSTS530003:  Your device is required to be managed to access this resource.`.

Are you able to confirm if the command the Azure CLI is returning in the error (`az login --scope https://graph.microsoft.com//.default`) works on your machine? Based on the error message the Azure CLI is returning when executed by Terraform, this appears to be suggesting that your machine isn't enrolled in a management policy, rather than something specific to Terraform, so it'd be good to confirm that first.

Thanks!

**Comment by tombuildsstuff** [comment]
@JWDobken thanks for confirming - that's an organisational security policy, so you'd need to reach out to whoever manages your AAD environment to confirm the requirements there.

Based on the error message coming back from the Azure CLI, it's possible that your machine may not be enrolled in some security policies which are required to authenticate, whilst I can't confirm the specifics there - they should be able to confirm what's required here.

Once you're able to authenticate to the Azure CLI Terraform should work automatically, as such unfortunately there isn't much we can do in Terraform specifically to workaround this - but whoever manages your AAD environment should be able to confirm the access requirements (e.g. using a machine bound to AAD / with whatever policies applied) which'll make the Azure CLI work - and once the command above works then you should be able to use Terraform as normal.

However since this isn't something specific to the Azure Provider and is instead a question around the Azure CLI - I'm going to close this issue for the moment - but if the folks who manage your AAD environment can't confirm the requirements you [can open an issue on the Azure CLI repository](https://github.com/Azure/azure-cli/issues) where someone should be able to assist further.

Thanks!
