### ISSUE TITLE
azurerm_monitor_action_group event_hub_receiver no way to set resource_group_name

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#18322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_action_group

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_action_group" "support" {
  name                = "AlertsAction"
  resource_group_name = data.azurerm_resource_group.support.name
  short_name          = "alerts"

  event_hub_receiver {
    name                    = "s-alerts"
    event_hub_namespace     = local.management_monitor_namespace_name
    event_hub_name          = "e-alerts"
    subscription_id         = local.management_subscriptionid
    use_common_alert_schema = true
  }
  tags = local.common_tags
}
```

### Debug Output/Panic Output

```shell
Error: in event_hub_receiver, exactly one of event_hub_id or (event_hub_namespace, event_hub_name) must be set
with module.terraform-azure_support.azurerm_monitor_action_group.support
on .terraform/modules/terraform-azure_support/log_analytics_workspace.tf line 11, in resource "azurerm_monitor_action_group" "support":
```

### Steps to Reproduce

terraform apply

**Comment by teowa** [comment]
Hi @mpjtaylor , thanks for submitting this issue, seems I cannot repro the issue with given config. Could you please try the below config? As for no way to set `resource_group_name` in event_hub_receiver, it is by API design, because `event_hub_namespace` is unique, see https://github.com/hashicorp/terraform-provider-azurerm/pull/17335#issuecomment-1221810192.

<details>

<summary>TF config</summary>

```
provider "azurerm" {
  features {
  }
}

resource "azurerm_resource_group" "example" {
  name     = "test-ag"
  location = "eastus"
}

resource "azurerm_eventhub_namespace" "example" {
  name                = "aTestEventHubNamespace-123"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"
  capacity            = 1
}

resource "azurerm_eventhub" "example" {
  name                = "aTestEventHub"
  namespace_name      = azurerm_eventhub_namespace.example.name
  resource_group_name = azurerm_resource_group.example.name
  partition_count     = 1
  message_retention   = 1
}

resource "azurerm_monitor_action_group" "example" {
  name                = "testactiongroup"
  resource_group_name = azurerm_resource_group.example.name
  short_name          = "atest"
  event_hub_receiver {
    name                    = "eventhub-test-action"
    event_hub_name          = azurerm_eventhub.example.name
    event_hub_namespace     = azurerm_eventhub.example.namespace_name
    use_common_alert_schema = true
  }
}

```

</details>

**Comment by mpjtaylor** [comment]
Hi,

the action group is in a different subscription to the event hub, without using the deprecated id there is no way using the below that the connection can be made no resource group is known?

```
  event_hub_receiver {
    name                                      = "sendtoeventhub"
    event_hub_namespace          = "eventhubnamespace"
    event_hub_name                   = "eventhub1"
    subscription_id                     = "00000000-0000-0000-0000-000000000000"
    use_common_alert_schema = false
  }    
```

**Comment by teowa** [comment]
Hi @mpjtaylor , the `resource_group` is actually a redundant parameter, because we cannot create two same named eventhub namespace under one subscription. And even with the deprecated id, the resource group name is not send to the [REST API](https://github.com/Azure/azure-rest-api-specs/blob/b0f48ad950e29525d407607c336b549bcfb15333/specification/monitor/resource-manager/Microsoft.Insights/stable/2021-09-01/actionGroups_API.json#L920-L956). With `event_hub_namespace`,  `event_hub_name`, `subscription_id`, a specific eventhub can be confirmed.

**Comment by mpjtaylor** [comment]
Ok, this can be closed I was expecting to need resource group

Thanks

**Comment by tombuildsstuff** [comment]
Closing per above
