### ISSUE TITLE
azurerm_logic_app_standard is not getting forced replaced when the underlying app service plan is replaced

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform-provider-azurerm#18325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_standard

### Terraform Configuration Files

Removed some lines that were irrelevant to aid readability:

First apply used a name of ```lgpl-001``` as below.

```hcl
resource "azurerm_service_plan" "logic_app_service_plan" {
  name = "lgpl-002"
}

resource "azurerm_logic_app_standard" "logic_app" {
  name                = "logc-001"
  app_service_plan_id = azurerm_service_plan.logic_app_service_plan.id
}
```

Second apply used a name of ```lgpl-002```

### Debug Output/Panic Output

Removed some lines that were irrelevant to aid readability:

```shell

# azurerm_service_plan.logic_app_service_plan must be replaced
-/+ resource "azurerm_service_plan" "logic_app_service_plan" {
~ id = "/subscriptions/***/resourceGroups/test/providers/Microsoft.Web/serverfarms/lgpl-001" -> (known after apply)
~ name = "lgpl-001" -> "lgpl-002" # forces replacement
}

# azurerm_logic_app_standard.logic_app will be updated in-place
~ resource "azurerm_logic_app_standard" "logic_app" {
~ app_service_plan_id = subscriptions/***/resourceGroups/test/providers/Microsoft.Web/serverfarms/lgpl-001" -> (known after apply)
}
```

### Expected Behaviour

If any changes cause ```azurerm_service_plan``` to be replaced, then the ```azurerm_logic_app_standard``` that relies on it must also be replaced.

Terraform isn't recognizing it needs to replace ```azurerm_logic_app_standard``` - it thinks it can just update it.  This is not possible for Azure to do.

This has to be worked around like this in ```azurerm_logic_app_standard```

```
lifecycle {
  replace_triggered_by = [
    azurerm_service_plan.logic_app_service_plan.name
  ]
}
```

### Actual Behaviour

Terraform wants to update a resource rather than replace it.
The apply will fail, even though the plan succeeds as Azure cannot have a logic app defined without an underlying service plan.

### Steps to Reproduce

Create the above two resources, and then reapply with a ```name``` change to ```azurerm_service_plan```

### Important Factoids

The same applies to the ```azurerm_linux_function_app``` resource which also must be replaced if ```azurerm_service_plan``` is replaced.

**Comment by ziyeqf** [comment]
Hi @scott-doyland-burrows , thanks for opening the issue.

for this scenario, please try to add `create_before_destroy=true` to `azurerm_app_service_plan`block as below.
```
resource "azurerm_service_plan" "logic_app_service_plan" {
  name = "lgpl-002"

  lifecycle{
    create_before_destroy = true
  }
}
```

The reason is that `azurerm_logic_app_standard` doesn't have to be replaced beacuase of change of its `app_service_plan_id`. The apply failed beacuse it tried to delete the old `azurerm_service_plan` resource which was been using by `azurerm_logic_app_standard`. Adding this lifecycle argument helps releasing the old service plan so it can be succsefully deleted.

If it helps or any further questions, please leave comments.

**Comment by scott-doyland-burrows** [comment]
@ziyeqf Regardless of whether the above would work around the issue, there are other times that ```azurerm_service_plan``` needs to be replaced, while keeping the same ```name``` .  If I alter the following so the ```zone_balancing_enabled``` alters to ```false```, then the resource will be replaced.

It is not possible to use ```create_before_destroy``` as the ```name``` stays the same.

```
resource "azurerm_service_plan" "logic_app_service_plan" {
  name                   = "lgpl-001"
  zone_balancing_enabled = true //altering to false causes a replace
}
```

The issue is that the ```azurerm_logic_app_standard``` should have a dependency , and be replaced when ```azurerm_service_plan``` is replaced.

In the same way that ```azurerm_app_service_virtual_network_swift_connection``` will be replaced when ```azurerm_logic_app_standard``` is replaced.

```
resource "azurerm_app_service_virtual_network_swift_connection" "logic_app_virtual_network" {
  app_service_id = azurerm_logic_app_standard.logic_app.id // if this is replaced then azurerm_app_service_virtual_network_swift_connection is replaced
  subnet_id      = azurerm_subnet.pwapimgw_logic_app_subnet.id
}
```

**Comment by ziyeqf** [comment]
Hi @scott-doyland-burrows, thanks for your reply.

For this scenario, I may suggest two solutions.

1. add `replace_triggered_by` argument and use the resource as a condition rather than its property like `name`. then the `azurerm_logic_app_standard` resource will be replaced when the `azurerm_service_plan` resource be replaced.
```
resource "azurerm_service_plan" "logic_app_service_plan" {
  name = "lgpl-002"
}

resource "azurerm_logic_app_standard" "logic_app" {
  name                = "logc-001"
  app_service_plan_id = azurerm_service_plan.logic_app_service_plan.id

  lifecycle {
    replace_triggered_by = [azurerm_service_plan.logic_app_service_plan]
  }
}
```
2. add `create_before_destroy` lifecycle argument and change the `name` property of `azurerm_service_plan` meanwhile changing properties which will force a replacement of `azurerm_service_plan`. Then the `azurerm_logic_app_standard` resource could migratre to new `azurerm_service_plan` without a replacement of itself, and the old one will be deleted.
```
resource "azurerm_service_plan" "logic_app_service_plan" {
  name                   = "lgpl-001"
  zone_balancing_enabled = true
  lifecycle {
    create_before_destroy = true
  }
}

```
```
resource "azurerm_service_plan" "logic_app_service_plan" {
  name                   = "lgpl-002" #change the name meanwhile changing the zone_balancing_enabled property
  zone_balancing_enabled = false
  lifecycle {
    create_before_destroy = true
  }
}
```

Here are the reasons.
1. The dependency between `azurerm_logic_app_standard` and `azurerm_service_plan` is the property `app_service_plan_id`, it is a required property, but changing it will not force `azurerm_logic_app_standard` to be replaced, `azurerm_logic_app_standard` can migrate service plans without a replacement of itself. For example, editing the `app_service_plan_id` property of  `azurerm_logic_app_standard` from an existing one to another, it can be updated in-place rather than a replacement of itself.
2. I don't think there should be a built-in dependent relation because that, not in every scenarios `azurerm_service_plan` is managed by Terraform. It's ok to create a service plan on Portal and copy-paste the service plan id into `app_service_plan_id` property. And changing the property will not force a replacement for `azurerm_logic_app_standard` as the reason 1.
4. The reason of apply failture in this issue is during replacement of `azurerm_service_plan`, it failed to delete the service plan because it has been using by `azurerm_logic_app_standard`, and the `replace_triggered_by` argument caused `azurerm_logic_app_standard` get deleted which released `azurerm_service_plan` so it can be deleted successfully. then they were re-created.
5. adding `create_before_destroy` argument and changing the name of service plan will create a new `azurerm_service_plan` first and migrate `azurerm_logic_app_standard` from the older plan to newer one which will also release the old service plan. changing its name is because same names leads to same resource ids, which will cause the newer service plan creation fail.

Please leave comments for any further questions.

**Comment by scott-doyland-burrows** [comment]
Thanks for the reply.

What you say re the ```azurerm_logic_app_standard``` not always having to be replaced if the ```logic_app_service_plan.id``` changes makes sense.

In which case, should there be some way for the terraform plan to recognise there will be an apply failure - but maybe that is a bigger question overall - as there are many occasions when a plan will be successful, only for the apply to then fail.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @ziyeqf‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
