### ISSUE TITLE
Storage Account allow_blob_public_access no longer works in v3

### ISSUE THREAD

**Issue by skoya** [hashicorp/terraform-provider-azurerm#18397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_stroage_account

### Terraform Configuration Files

```hcl
Storage account 

allow_nested_items_to_be_public = false

if allow_blob_public_access is already set to true in the resource then the above flag is now unable to switch.
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

allow_nested_items_to_be_public = false

SHOULD set azure storage account. allow_blob_public_access = false.

### Actual Behaviour

no change to the allow_blob_public_access

### Steps to Reproduce

terraform apply on an existing or new storage account.

**Comment by ToddBowman** [comment]
This feature is documented in 3.0.1, 3.0.2 removes the documentation for the switch but still has the note it only works in the public clouds, and 3.1.0 and beyond all references to it are missing.

**Comment by magodo** [comment]
Seems duplicate to #17255, that:

>  In the v3.x.x azurerm provider `blob_public_access` has been [`renamed`](https://www.hashicorp.com/blog/terraform-azurerm-3-0-brings-enhanced-azure-function-support#:~:text=prevent_deletion_if_contains_resources%20%3D%20false\).-,Storage%3A,-The%20field%20allow_blob_public_access)

**Comment by skoya** [comment]
Nope that attribute doesn't exist in the latest version. 17255 is no longer valid.

**Comment by skoya** [comment]
Basically, we can't set it it in provider. Regardless of the documentation the code doesn't exist to set it. 

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/storage/storage_account_resource.go#L1490

**Comment by ToddBowman** [comment]
Thanks @magodo, "allow_nested_items_to_be_public" works for me.  I don't like it, it should match what the portal calls this feature but it works.  Thanks for the quick reply.

**Comment by skoya** [comment]
it works for new resources but fails for existing storage accounts where blob_public_access is set to true.

**Comment by skoya** [comment]
agree though allow_nested_items_to_be_public seems lazy rather than allowing for granular control?

**Comment by tombuildsstuff** [comment]
@skoya as @magodo has mentioned above, this field has been renamed to alleviate confusion, since the naming in the portal was leading some users to believe that this setting (which controls whether items within the storage account can opt-into being public) would make all of their content public - which it doesn't.

The setting `allow_nested_items_to_be_public` is an intentional naming choice to remove this confusion, intentionally diverging from the wording in the Portal (which can change anyway, as such we generally match naming based on the API, except for cases such as this) - whilst individual objects (containers, blobs) can opt-in using properties within those resources.

Prior to 3.0 this field was called `allow_blob_public_access` - this is now called `allow_nested_items_to_be_public` and has the same behaviour (in that it controls whether nested items are allowed to opt-into being public or not) - this is just a rename to alleviate the confusion (and [is covered in the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide)).

Since this is a question rather than an issue in the Azure Provider I'm going to close this issue for the moment, but should you have further usage questions [I'd direct you towards the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
