### ISSUE TITLE
can't add node-role.kubernetes.io/<role> label

### ISSUE THREAD

**Issue by davidkarlsen** [hashicorp/terraform-provider-azurerm#18567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
adding


 agents_labels = {
    "nodepool" : "defaultnodepool"
    "node-role.kubernetes.io/eos" : ""
  }


will fail with

Code="BadRequest" Message="For Kubernetes version greater than or equal to 1.16, node label keys in the 'kubernetes.io' or 'k8s.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io). For more information, please check https://aka.ms/aks-node-labels-116." Target="node-role.kubernetes.io/eos="
```

### Debug Output/Panic Output

```shell
Error: updating Default Node Pool Node Pool: (Agent Pool Name "nodepool" / Managed Cluster Name "aks-dts-dev-kigx" / Resource Group "rg-dts-bld-dev") containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="For Kubernetes version greater than or equal to 1.16, node label keys in the 'kubernetes.io' or 'k8s.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io). For more information, please check https://aka.ms/aks-node-labels-116." Target="node-role.kubernetes.io/eos="
```

### Expected Behaviour

should accept label, it is valid and not restricted

### Actual Behaviour

fails as described

### Steps to Reproduce

see info given

**Comment by davidkarlsen** [comment]
note that it possible to add the same label with kubectl w/o any problems

**Comment by stephybun** [comment]
Thanks for raising this issue @davidkarlsen. 

The error you're receiving is returned by the AKS API and not the provider. At a guess it looks like the label might fall under one of the [reserved prefixes specified in the MSFT docs](https://learn.microsoft.com/en-us/azure/aks/use-labels#reserved-prefixes). Adding the label using kubectl bypasses the AKS API which is what the provider sends and receives calls to. 

Since this isn't something we can fix in the provider I'm going to close this issue, I'd suggest raising an issue over on [Azure/AKS](https://github.com/Azure/AKS) for clarification and/or fixing.
