### ISSUE TITLE
Support for tagging arbitrary resources

### ISSUE THREAD

**Issue by larsmaes-sogeti** [hashicorp/terraform-provider-azurerm#18596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have this use case where Azure creates some resources outside of my terraform code. 
I would like to tag these resources with terraform.

### New or Affected Resource(s)/Data Source(s)

azurerm_resource_tags, azurerm_resource_tag

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_tags" "tags" {
   resource_id = "${var.resource_id}"
   tags = {
      tag1 = "value1"
      tag2 = "value2"
   }
}

or 

resource "azurerm_resource_tag" "tag" {
   resource_id = "${var.resource_id}"
   key = var.tag_key
   value = var.tag_value
}
```

**Comment by martenvd** [comment]
Hi Lars, I'm working on a possible solution for this at the moment. When I have updates on this I'll keep you posted.

**Comment by tombuildsstuff** [comment]
hey @larsmaes-sogeti @martenvd 

Apologies for the delayed response here, whilst the Pull Request linked above was closed it appears this issue wasn't at the same time.

Unfortunately as [mentioned in that Pull Request](https://github.com/hashicorp/terraform-provider-azurerm/pull/22105#issuecomment-1600530013) we have no plans to introduce a generic tags resource, [the details for which can be found in this comment](https://github.com/hashicorp/terraform-provider-azurerm/pull/19544#issuecomment-1340683878). Since this isn't something we plan to add to the provider whilst I'd like to thank you for opening this feature request, unfortunately I'm going to have to close this feature request due to the differing behaviours of the Azure API here.

Thanks!
