### ISSUE TITLE
azurerm_private_endpoint import fails due to 'privateendpoint' segment parsing error

### ISSUE THREAD

**Issue by soohonlee** [hashicorp/terraform-provider-azurerm#18591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.2.5

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "australiaeast"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  location            = "australiaeast"
  resource_group_name = "example-rg"
  address_space       = ["10.0.0.0/16"]

  subnet {
    name           = "subnet1"
    address_prefix = "10.0.1.0/24"
  }
}

resource "azurerm_private_endpoint" "pe" {
  name                = "pe-example"
  location            = "australiaeast"
  resource_group_name = "example-rg"
  subnet_id           = azurerm_virtual_network.example.subnet["subnet1"].id

  private_service_connection {
    name                           = "psc-pe-example"
    private_connection_resource_id = var.resource_id
    is_manual_connection           = false
    subresource_names              = ["vault"]
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: parsing Resource ID "/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/example-rg/providers/microsoft.network/privateendpoints/pe-example": ID was missing the `privateEndpoints` element
│ 
│ 
╵
```

### Expected Behaviour

The import should have succeeded.

I tried again after replacing the privateendpoints segment in the resource Id with privateEndpoints and the import succeeded.

The Azure Portal provided the resource id in the format **"/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/example-rg/providers/microsoft.network/privateendpoints/pe-example"**

The Azure resource ID is case inconsistent so the import function should be case insensitive to account for this.

P.S. The config and the resource names were hypothetical configs as my actual config is too complex and I can't share it.

### Actual Behaviour

The import failed when it should have succeeded.

### Steps to Reproduce

terraform import "azurerm_private_endpoint.pe" "/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/example-rg/providers/microsoft.network/privateendpoints/pe-example"

### References

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/private_endpoint_resource.go
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/vendor/github.com/hashicorp/go-azure-helpers/resourcemanager/resourceids/ids.go#L46
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/parse/private_endpoint.go#L60
https://learn.microsoft.com/en-us/rest/api/virtualnetwork/private-endpoints/get?tabs=HTTP

**Comment by soohonlee** [comment]
I looked at the code in the file **internal/services/network/parse/private_endpoint.go**

The below code in lines 60-62 looks like it is causing the issue. 

``` go
if resourceId.Name, err = id.PopSegment("privateEndpoints"); err != nil {
  return nil, err
}
```

Looking at the function ParseAzureResourceID in **vendor/github.com/hashicorp/go-azure-helpers/resourcemanager/resourceids/ids.go#L45**

``` go 
componentMap := make(map[string]string, len(components)/2)
  for current := 0; current < len(components); current += 2 {
    key := components[current]
    value := components[current+1]
```

it looks like the issue is that the segment parser is case sensitive. Should the parser be converting all the segment keys to lower or upper case to deal with Azure's case inconsistency?

**Comment by tombuildsstuff** [comment]
hi @soohonlee 

Thanks for opening this issue.

Whilst the Azure API Specification states that some components of the Resource ID's are Case Insensitive (specifically, the `values` for each `key`, e.g. `pe-example` for `privateEndpoints` in your example above), the ARM spec defines that each of the `key` segments must be `camelCased`. Unfortunately this behaviour is inconsistent across the different Azure API's, with some treating these as case-sensitive and others treating these as case-insensitive when parsing - which is a frequent source of subtle bugs (with some resources subtly failing to deploy).

The Azure Portal itself tends to change the casing on the Resource ID being returned from time to time too, depending on how the Resource ID is constructed and which portal blade is active. Ultimately this means that we use the Azure API Specifications as the source of truth for Resource IDs, which states that these segments should be camelCased.

These inconsistencies mean that we're forced to treat Resource ID's (and thus the components which comprise them) as case-sensitive, meaning that when importing resources into Terraform we validate that the casing matches what we're expecting so that we can avoid these subtle issues - and as such this validation is intentionally case-sensitive and we aren't planning on making this case-insensitive (this behaviour also mirrors other Terraform Providers, which are case sensitive fwiw).

Instead when documenting resources we highlight the Resource ID format (and casing) which should be used in the `import` section of the documentation for each resource [for example in the case of Private Endpoint](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint#import) which matches the format we're expecting internally to be able to parse each Resource ID.

Since this behaviour is intentional, whilst I'd like to thank you for reaching out, I'm going to close this issue for the moment - however as you've mentioned above you should be able to import the Private Endpoint resource by using the Resource ID format defined [in the `import` section of this resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint#import).

Thanks!
