### ISSUE TITLE
`azurerm_cdn_frontdoor_profile_custom_domain` must allowed to be associated with multiple routes

### ISSUE THREAD

**Issue by sebader** [hashicorp/terraform-provider-azurerm#18613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.25.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_profile_custom_domain, azurerm_cdn_frontdoor_route

### Terraform Configuration Files

```hcl
-
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

With the release of `azurerm_cdn_frontdoor_profile_custom_domain` and `azurerm_cdn_frontdoor_route` it is not possible to use one custom domain on multiple (many) routes. This must be enabled.

currently `associate_with_cdn_frontdoor_route_id` on `azurerm_cdn_frontdoor_profile_custom_domain` is a string, it should be a slice. However, it would be a lot more logical to me, if the association is set on a route, like you would do through the portal: When you create a new route, you can select all the custom domains (plus the default endpoint) to enable this route for.

@WodansSon

**Comment by aluchs-hpg** [comment]
I believe this is a clone of https://github.com/hashicorp/terraform-provider-azurerm/issues/18598. PR #18600 has been raised to resolve the issue.

**Comment by WodansSon** [comment]
@sebader, thank you for opening this issue. I was not aware that you could have multiple custom domains associated with a single route, my bad. The reason I decided to do it this way is because of the requirement to disassociate the custom domain with the route in order to delete the custom domain. Because of this requirement it broke the single apply rule for Terraform and I had to make the custom domain self aware that it was associated with the route so on delete it would know to remove the association before it actually deleted itself... I am sure there are prolly other ways to go about this but that was the one I came up with. 🤔
