### ISSUE TITLE
Support for BackendPool Objects: Virtual Machine, VMSS and App Services

### ISSUE THREAD

**Issue by mfiebelkorn** [hashicorp/terraform-provider-azurerm#18657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the backend_address_pool block in the azurerm_application_gateway supports:

- Name
- FQDN
- ip_addresses

This does not allow for the backend pool to support the application gateway options: Virtual Machine, Virtual Machine Scale Set, nor App Services

Currently, these options are only available when configuring the backend pool in the Azure Portal.

### New or Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Potential Terraform Configuration

```hcl
A backend_address_pool block supports the following:

name - (Required) The name of the Backend Address Pool.
fqdns - (Optional) A list of FQDN's which should be part of the Backend Address Pool.
ip_addresses - (Optional) A list of IP Addresses which should be part of the Backend Address Pool.
virtual_machine - (Optional) A list of Virtual Machines which should be part of the Backend Address Pool.
VMSS - (Optional) A list of Virtual Machine Scale Sets which should be part of the Backend Address Pool.
```

### References

https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-components#backend-pools

**Comment by tombuildsstuff** [comment]
hi @mfiebelkorn 

Thanks for opening this issue.

Taking a look through here, unfortunately this is a bit of a misleading Azure Portal feature, which exposes this as a bi-directional relationship rather than the one-way relationship as this is defined within the API (insofar as the VMSS's Network Profile block defines which Application Gateway it's related to).

Since the Azure API doesn't expose this feature in this manner, unfortunately we're unable to expose this as a bi-directional relationship without making this a perpetual diff in both resources/introducing a circular reference to fix this. As such whilst I'd like to thank you for opening this issue, since this isn't something that's possible at this point in time - but can be achieved within the VMSS resource (as the API is exposing this) - I'm going to close this issue for the moment.

Thanks!
