### ISSUE TITLE
Support for source_image_id property in documentation on https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine

### ISSUE THREAD

**Issue by jriekse5555** [hashicorp/terraform-provider-azurerm#18752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The property source_image_id is not documented and the existing documentation on the property id points to the deprecated generic vm resource:

See the note on the id property on https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine

### New or Affected Resource(s)/Data Source(s)

n/a

**Comment by myc2h6o** [comment]
Hi @jriekse5555 thanks for opening the issue! `azurerm_virtual_machine` is in a feature frozen status so we are not adding/updating the properties there. Instead, please find `source_image_id` in [`azurerm_linux_virtual_machine`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#source_image_id) and [`azurerm_windows_virtual_machine`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#source_image_id)

**Comment by tombuildsstuff** [comment]
hi @jriekse5555 

Taking a look through here as @myc2h6o has mentioned the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 3.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!

**Comment by jriekse5555** [comment]
There appears to be confusion on the issue. The issue is that the documentation on the current azurerm_windows_virtual_machine resource lists id as the custom image property when it is source_image_id. Updating the document with this change and removing the reference just below it to an example that is no longer up to date will allow proper use of the documentation using the current azurerm_windows_virtual_machine resource.

**Comment by myc2h6o** [comment]
@jriekse5555 The document link `./examples/virtual-machines/virtual_machine/managed-disks/from-custom-image` mentioned under the `storage_image_reference.id` property is used to illustrate the usage of the property of this resource especially, since it is still supported by `azurerm_virtual_machine`. As for the suppression message to use the new resources, it is put at the top of the resource in the [disclaimers](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#disclaimers).

**Comment by myc2h6o** [comment]
@jriekse5555 it may be a little bit confusing. There are three resources here. The old one `azurerm_virtual_machine` and two new ones: `azurerm_windows_virtual_machine` and `azurerm_linux_virtual_machine`.
The old resource `azurerm_virtual_machine` can be used to create either a Windows VM or a Linux VM. And it only supports `storage_image_reference.id` but not `source_image_id`.
And starting from provider version 2.0, we introduced two new resources `azurerm_windows_virtual_machine` and `azurerm_linux_virtual_machine` to support Windows/Linux VM better because there are many differences between these two kinds of Virtual Machines. And these two new resources support `source_image_id`.

**Comment by jriekse5555** [comment]
Thanks. I see it is now listed.

**Comment by jriekse5555** [comment]
Just wanted to thank you both for your patience. Yeah, was looking at the wrong article at the beginning.
