### ISSUE TITLE
data  "azurerm_resource_group" provider fails to reference its values

### ISSUE THREAD

**Issue by julbrunner** [hashicorp/terraform-provider-azurerm#18975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3 

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
################ project.tf ################
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.4"
    }
  }
  backend "azurerm" {}
}

# Configure azure provider
provider "azurerm" {
  skip_provider_registration = true 
  subscription_id            = xxxxxxxxxxxxxxxxxxxxx
  features {

    resource_group {
      prevent_deletion_if_contains_resources = true
    }

    key_vault {
      purge_soft_delete_on_destroy               = false
      purge_soft_deleted_certificates_on_destroy = false
      purge_soft_deleted_keys_on_destroy         = false
      purge_soft_deleted_secrets_on_destroy      = false
    }
  }

module "rgTest" {
  source                          = "./modules/rgTest"
  resource_group_name             = var.resource_group_name
}

output "locationTest"{
  value = module.rgTest.location
}

################ MODULE rgTest ################
#### file main.tf ####

# INPUT variables from project.tf
variable "resource_group_name" {
  type = string 
}

# Get data for resource group
data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

#### file output.tf ####
output "location" {
  value = data.azurerm_resource_group.rg.location
}

########################## 
# There's a bigger landscape behind this deployment e.g. with an Application GW, PostgreSQL flex server etc. #
```

### Debug Output/Panic Output

```shell
########## On Github Action Output #################
+ location = (known after apply)

########## On tf_log=TRACE ##############
{"id":"/subscriptions/***/resourceGroups/xxx","name":"xxx","type":"Microsoft.Resources/resourceGroups","location":"westeurope","properties":{"provisioningState":"Succeeded"}}

# Further down, I can see the following INFO and DEBUG message for the deployment of Postgre SQL flex server
[INFO]  ReferenceTransformer: reference not found: "var.resource_group_name"
[DEBUG] ReferenceTransformer: "module.postgreSQL_flex.data.azurerm_resource_group.rg" references: [] 

# As a result I it will give the following message to the graph
[TRACE] planDataSource: module.postgreSQL_flex.data.azurerm_resource_group.rg configuration is fully known, at least one dependency has changes pending
```

### Expected Behaviour

The backend configuration field of resource group location should match the fetched data from the data provider "azurerm_resource_group".

### Actual Behaviour

The reference and retrieved values for this specific data provider gets lost **but only in one (DEV) out of three stages (SAND + PROD)!**
For sandbox and productive environment this is no issue.
Therefore terraform forces a replacement of all resources within this resource group!

### Steps to Reproduce

I couldn't reproduce the error in a clean setup. 

Therefore, also other issues could lead to this problem aside from the actual provider (e.g. corrupt state file?). It's odd that there have been no changes in the repository or setup after the last (successful) deployment.

**Comment by manicminer** [comment]
Hi @julbrunner, thanks for reporting this. From the example configuration you provided, it looks like this is a graph dependency problem. You will need to tell Terraform that the data source depends on the module that creates the resource group. You can do this by referencing an output value/attribute from the module, or by using the `depends_on` meta argument.

This is more of a Terraform usage question, I recommend following [this tutorial](https://developer.hashicorp.com/terraform/tutorials/configuration-language/dependencies) on resource dependencies. It's also worth noting that dependency gaps can manifest inconsistently depending on the timing of the apply operation.

We use GitHub issues for tracking feature requests and bugs in the Azure provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html). Accordingly, since as mentioned this is a Terraform usage question, I'm going to close this issue, but I believe you should be able to get an answer on the community discussion portal.
