### ISSUE TITLE
Terraform output.tf for the AKS Cluster deployed

### ISSUE THREAD

**Issue by syedyakoobali** [hashicorp/terraform-provider-azurerm#19000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I have an output.tf file containing the following code.
output "kube_config" {
  value     = azurerm_kubernetes_cluster.aks[0].kube_config_raw
  sensitive = true
}

output "host" {
  value = azurerm_kubernetes_cluster.aks[0].kube_config.0.host
}

### Terraform Version

1.1.7

### AzureRM Provider Version

2.91.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
When the pipeline is executed it shows for the above part of code the error.
```

### Debug Output/Panic Output

```shell
Error: Invalid index
│ 
│   on output.tf line 21, in output "host":
│   21:   value = azurerm_kubernetes_cluster.aks[0].kube_config.0.host
│     ├────────────────
│     │ azurerm_kubernetes_cluster.aks[0].kube_config is empty list of object
│ 
│ The given key does not identify an element in this collection value: the
│ collection has no elements.
╵
```

### Expected Behaviour

Terraform pipeline should get executed and the resources get deployed

### Actual Behaviour

The pipeline fails with error pointing to the output.tf file

### Steps to Reproduce

The pipeline fails with error pointing to the output.tf file

### Important Factoids

a

### References

Please provide your generous inputs.

**Comment by tombuildsstuff** [comment]
hi @syedyakoobali 

Thanks for opening this issue.

Taking a look through here this appears to be a configuration question - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
