### ISSUE TITLE
Azure Data Factory managed_virtual_network_enabled not working as expected

### ISSUE THREAD

**Issue by RHooijer** [hashicorp/terraform-provider-azurerm#19099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_data_factory

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory" "this" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name

  managed_virtual_network_enabled = true
  public_network_enabled = false

 lifecycle {
    ignore_changes = [
      # Ignore changes to tags, external policy is setting them
      tags,
        ]
    }
```

### Debug Output/Panic Output

```shell
Deployment is successful
```

### Expected Behaviour

I expect the managed_virtual_network_enabled = true option to set the AutoResolveIntegrationRuntime to Managed virtual network, however. It created the AutoResolveIntegrationRuntime with a public connection. 

### Actual Behaviour

I expect the managed_virtual_network_enabled = true option to set the AutoResolveIntegrationRuntime to Managed virtual network, however.

**Comment by Amier3** [comment]
Hey @RHooijer 

The provider has a separate resource for integration runtime,[ azurerm_data_factory_integration_runtime_azure](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_integration_runtime_azure) . There's a variable to configure a managed network in that resource. 

I'm going to close this for now since it's not a provider bug, but let me know if you have any questions.

**Comment by jvanenckevort** [comment]
@Amier3 

This is clearly a bug, so please reopen it. When you deploy synapse analytics with the AutoResolveIntegrationRuntime runtime and set public_network_enabled = false, the AutoResolveIntegrationRuntime is of type Managed Virtual Network. For data factory that does not work as the OP describes, and I think it should work the same way since under the hood those two services are the same. This means that the `managed_virtual_network_enabled` options does not work!
