### ISSUE TITLE
Importing log analytics workspace - parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

### ISSUE THREAD

**Issue by articice** [hashicorp/terraform-provider-azurerm#19100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "poc"
  location = "North Europe"
}

resource "azurerm_log_analytics_workspace" "workspace" {
  name                = "workspace"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: parsing Resource ID "/subscriptions/<redacted>/resourcegroups/<redacted>/providers/microsoft.operationalinsights/workspaces/<redacted>": parsing "/subscriptions/<redacted>/resourcegroups/<redacted>/providers/microsoft.operationalinsights/workspaces/<redacted>": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"
│ 
│ 
╵
```

### Expected Behaviour

Resource should import successfully.

### Actual Behaviour

Resource doesn't import.

### Steps to Reproduce

1. Create a Log Analytics Workspace manually.
2. terraform import azurerm_log_analytics_workspace.services_log_workspace <resourceID>

### References

Similar issues exist for other resources:
#17532 & #17537 “staticCommunicationServices”: expected the segment “CommunicationServices” to be “communicationServices” for azurerm_communication_service

**Comment by tombuildsstuff** [comment]
hey @articice 

Thanks for opening this issue.

As the error message is showing during import here, you'll need to ensure that the casing for the Resource ID matches what Terraform is expecting, which can be found in the `import` section of the documentation - in the case of [`azurerm_log_analytics_workspace` that can be found here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace#import).

If you update the Resource ID being provided to match what's in the documentation then this should import correctly:

> terraform import azurerm_log_analytics_workspace.workspace1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.OperationalInsights/workspaces/workspace1

Whereas the Resource ID being provided uses a different casing:

> /subscriptions/<redacted>/resourcegroups/<redacted>/providers/microsoft.operationalinsights/workspaces/<redacted>

As such you'll need to update `resourcegroups` -> `resourceGroups` and `microsoft.operationalinsights` to `Microsoft.OperationalInsights`, since this is how the Resource ID is defined within the Azure API (unfortunately the Portal can recase things and changes it's casing from time to time).

Since this'll be fixed by updating the casing on the Resource ID to match the casing expected by Terraform here I'm going to close this issue for the moment, but if you're still facing an issue when updating the casing to what Terraform's requiring then please let us know and we'll take another look.

Thanks!
