### ISSUE TITLE
Conflict Error When Modifying Existing Security Group Rule Priorities

### ISSUE THREAD

**Issue by khan-belal** [hashicorp/terraform-provider-azurerm#19202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.30.0

### Affected Resource(s)/Data Source(s)

azurerm_network_security_rule

### Terraform Configuration Files

```hcl
locals {
  my-serv-sg-ports ={
    "ssh"                   = { port = "22", proto = "Tcp" }
    "http-80"               = { port = "80", proto = "Tcp" }


resource "azurerm_network_security_rule" "my-serv-inbound-traffic" {

  for_each = local.my-serv-sg-ports

  name                                       = each.key
  priority                                   = 1000 + index(keys(local.my-serv-sg-ports), each.key)
  direction                                  = "Inbound"
  access                                     = "Allow"
  protocol                                   = each.value.proto
  source_port_range                          = "*"
  destination_port_range                     = each.value.port
  source_address_prefix                      = azurerm_virtual_network.my-vnet.address_space[0]
  destination_application_security_group_ids = ["${azurerm_application_security_group.my-serv-sg-ports.id}"]
  resource_group_name                        = azurerm_resource_group.my-rg.name
  network_security_group_name                = azurerm_network_security_group.my-priv-sub-sg.name
}

locals {
  my-other-serv-sg-ports ={

   "my-other-serv-https" = {-}
}


resource "azurerm_network_security_rule" "my-other-serv-inbound-traffic" {
  for_each = local.my-other-serv-sg-ports

  -
  -
  -
}
```

### Debug Output/Panic Output

```shell
Error: creating/updating Security Rule: (Name "ssh" / Network Security Group Name "my-priv-sub-sg" / Resource Group "my-rg"): network.SecurityRulesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original 
Error: Code="SecurityRuleConflict" Message="Security rule my-other-server-https conflicts with rule ssh. Rules cannot have the same Priority and Direction. To learn more, see aka.ms/nsgrules." Details=[]
│
│   with azurerm_network_security_rule.my-serv-inbound-traffic["ssh"],
│   on sg-config-ws.tf line 35, in resource "azurerm_network_security_rule" "my-serv-inbound-traffic":
│   35: resource "azurerm_network_security_rule" "my-serv-inbound-traffic" {
│
╵
```

### Expected Behaviour

Terraform should modify rules in an order where there are no conflicts with existing resources. This occurs when modifying the priority of rules that are already created.

I have to run a terraform apply multiple times before the conflicts in priority are cleared up.

### Actual Behaviour

Terraform throws an error that there is a conflict in priority. Multiple "apply" runs are required to clear up the error.

### Steps to Reproduce

run a Terraform apply to create sg rules. 

Change priorities of rules and execute a subsequent apply.

### References

There was a similar issue in the past, but it has been marked as resolved.

https://github.com/hashicorp/terraform-provider-azurerm/issues/293

**Comment by magodo** [comment]
@khan-belal Thank you for submitting this! Unfortunately, due to how Terraform works, different resource instances can not orchestrate by the provider.

When updating multiple `azurerm_network_security_rules`, they are updated in sequential, which might causes conflicts as you have seen, unless you have added explicit dependencies across them to ensure each update of the NSR won't cause conflict. E.g. say you are updating NSR1 from 100->200, and NSR2 from 200->300. If you have specified the dependency that NSR1 depends on NSR2, then NSR2 will be updated first, which might mitigate the issue.

Another less trivial way to workaround this issue is to update all the NSRs within a NSG at once. This means:

1. Remove the NSRs from your terraform state `terraform state rm`
2. Fill in the `security_rule` blocks for the affected NSGs
3. Make sure a `terraform plan` tells no diff
4. Change the priorities within the NSG resources
5. `terraform apply`
6. [Recover] Remove the `security_rule` blocks from the NSGs
7. [Recover] Import back the NSRs and fill in the config manually, or by the help of tools like `aztfy`.

**Comment by khan-belal** [comment]
@magodo thanks for the reply. 

Luckily this isn't a common task that I will have to perform on my side. I only had to change the priority based on a previous mistake when standing up the NSG. I will go ahead and try the dependency trick to see if that will resolve this for future reference.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
