### ISSUE TITLE
parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

### ISSUE THREAD

**Issue by esener303** [hashicorp/terraform-provider-azurerm#19416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.32.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Terraform Configuration Files

```hcl
terraform {
    required_providers {
    local = {
      source = "hashicorp/local"
    
    }

  }

  # Do not use var.value here
  backend "azurerm" {
    resource_group_name   = "rg-terraform-westeurope-001"
    storage_account_name  = "xyz"
    container_name        = "xyz-tfstate" ### <<<<<<<<< If not exsist create first
    key                   = "xyz-contoso.tfstate"
    subscription_id       = "123"
    tenant_id             = "456"
    
  }

  required_version = ">= 1.3.5"
  

}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }

  subscription_id = var.sub_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  tenant_id       = var.tnt_id

}


locals {
  dns_servers = [
    var.dns_forwarder_ip_address
                // Internal Azure DNS Server
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: parsing "/subscriptions/ guid /resourcegroups/rg-contoso-dev-eastus2-001/providers/microsoft.operationalinsights/workspaces/law-contoso-dev-eastus2-001": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"
```

### Expected Behaviour

terraform plan succeed

### Actual Behaviour

│ Error: parsing "/subscriptions/ guid /resourcegroups/rg-contoso-dev-eastus2-001/providers/microsoft.operationalinsights/workspaces/law-contoso-dev-eastus2-001": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

### Important Factoids

issue occurred after the upgrade to the latest version

**Comment by eohlde** [comment]
I am also experiencing this issue. Possibly related to #17720

**Comment by tombuildsstuff** [comment]
hi @esener303 @eohlde 

Thanks for opening this issue.

As mentioned in the error message here:

> expected the segment "resourcegroups" to be "resourceGroups"

.. Terraform's expecting the Resource ID to match a given format but a different casing is being specified, taking a looking through here the Resource ID being specified:

> /subscriptions/guid/resourcegroups/rg-contoso-dev-eastus2-001/providers/microsoft.operationalinsights/workspaces/law-contoso-dev-eastus2-001

versus the Resource ID ([from the `import` documentation for `azurerm_log_analytics_workspace`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace#import)) we're expecting the format:

> /subscriptions/guid/resourceGroups/rg-contoso-dev-eastus2-001/providers/Microsoft.OperationalInsights/workspaces/law-contoso-dev-eastus2-001

As such it should be possible to fix this by updating the casing on the Resource ID value being specified (that is `resourcegroups` -> `resourceGroups` and `microsoft.operationinsights` -> `Microsoft.OperationalInsights`) - which'll fix this.

The behaviour of the Azure API is inconsistent insofar as Resource IDs are supposed to be case-insensitive during Requests and case-sensitive during Responses. Unfortunately, a number of API's don't behave in this manner and silently fail (in really subtle ways) when the casing doesn't match what the API is expecting. As such we're ultimately moving towards validating Resource IDs match the casing that's expected, which'll allow us (in the medium-term) to workaround these API/casing issues. However (as in this case) some user input may need updating to ensure the casing matches.

Whilst that's unfortunate that's affected you in this case, as mentioned above it should be possible to workaround this by updating the casing here, which'll allow `terraform plan` to succeed - would you be able to take a look?

Since this should be fixed by updating the casing being used here, I'm going to close this issue for the moment however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by esener303** [comment]
> hi @esener303 @eohlde
> 
> Thanks for opening this issue.
> 
> As mentioned in the error message here:
> 
> > expected the segment "resourcegroups" to be "resourceGroups"
> 
> .. Terraform's expecting the Resource ID to match a given format but a different casing is being specified, taking a looking through here the Resource ID being specified:
> 
> > /subscriptions/guid/resourcegroups/rg-contoso-dev-eastus2-001/providers/microsoft.operationalinsights/workspaces/law-contoso-dev-eastus2-001
> 
> versus the Resource ID ([from the `import` documentation for `azurerm_log_analytics_workspace`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace#import)) we're expecting the format:
> 
> > /subscriptions/guid/resourceGroups/rg-contoso-dev-eastus2-001/providers/Microsoft.OperationalInsights/workspaces/law-contoso-dev-eastus2-001
> 
> As such it should be possible to fix this by updating the casing on the Resource ID value being specified (that is `resourcegroups` -> `resourceGroups` and `microsoft.operationinsights` -> `Microsoft.OperationalInsights`) - which'll fix this.
> 
> The behaviour of the Azure API is inconsistent insofar as Resource IDs are supposed to be case-insensitive during Requests and case-sensitive during Responses. Unfortunately, a number of API's don't behave in this manner and silently fail (in really subtle ways) when the casing doesn't match what the API is expecting. As such we're ultimately moving towards validating Resource IDs match the casing that's expected, which'll allow us (in the medium-term) to workaround these API/casing issues. However (as in this case) some user input may need updating to ensure the casing matches.
> 
> Whilst that's unfortunate that's affected you in this case, as mentioned above it should be possible to workaround this by updating the casing here, which'll allow `terraform plan` to succeed - would you be able to take a look?
> 
> Since this should be fixed by updating the casing being used here, I'm going to close this issue for the moment however please let us know if that doesn't work for you and we'll take another look.
> 
> Thanks!

Indeed It works. removed object from state list and imported as you suggest and works fine now on.
Thanks lot.
