### ISSUE TITLE
Azure Kubernetes Cluster with Microsoft Defender Log Analytics Workspace ID Case Sensitivity

### ISSUE THREAD

**Issue by ehonsey** [hashicorp/terraform-provider-azurerm#19488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.1

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.3.1"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.28.0"
    }
  }
}

resource "azurerm_kubernetes_cluster" "k8s" {
  location            = "centralus"
  name                = "my_cluster"
  resource_group_name = "my_resource_group"
  default_node_pool {
    name    = "nodepool1"
    vm_size = "Standard_D3_V2"
  }

  azure_policy_enabled = true
  microsoft_defender {
    log_analytics_workspace_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/DefaultResourceGroup-CUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-00000000-0000-0000-0000-000000000000-CUS"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: parsing "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/DefaultResourceGroup-CUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-00000000-0000-0000-0000-000000000000-CUS": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"
│
│   with module.aks_cluster.azurerm_kubernetes_cluster.k8s_cluster,
│   on ../../../../../../modules/azure/aks/cluster/aks-cluster.tf line 64, in resource "azurerm_kubernetes_cluster" "k8s_cluster":
│   64:     log_analytics_workspace_id = "/subscriptions/${var.subscription_id}/resourcegroups/DefaultResourceGroup-CUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-${var.subscription_id}-CUS"
│
```

### Expected Behaviour

The `azure_policy_enabled` and `microsoft_defender` variables exist to retain [Microsoft Defender for Containers](https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-containers-enable?tabs=aks-deploy-portal%2Ck8s-deploy-asc%2Ck8s-verify-asc%2Ck8s-remove-arc%2Caks-removeprofile-api&pivots=defender-for-container-aks) security solution. These values are automatically generated by Azure for subscriptions with the Defender for containers policy enabled. They are explicitly stated so that plan/apply actions do not alter the resource state.

With these variables in place a `terraform plan` should show "No Changes."

### Actual Behaviour

Due to existing resource API case sensitivity issues (see "References" section) the state of the resource lists `/resourcegroups/` in the resource path after the subscriptions ID. For example:

`/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/DefaultResourceGroup-CUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-00000000-0000-0000-0000-000000000000-CUS`

A `terraform plan` will show a resource update on the AKS cluster and update/replace for downstream resources from this dependency. It should indicate "No Changes."

Conversely, when synchronizing the Terraform configuration to use the lowercase `/resourcegroups/` path, a `terraform plan` will generate a parse error as `resourceGroups` is case sensitive in the configuration:

`Error: parsing "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/DefaultResourceGroup-CUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-00000000-0000-0000-0000-000000000000-CUS": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"`

Please remove the case sensitivity issue so that planning / apply commands do not indicate changes.

### Steps to Reproduce

;; `/resourceGroups` in log_analytics_workspace_id
terraform plan

;; `/resourcegroups` in log_analytics_workspace_id
terraform plan

### References

[18235](https://github.com/hashicorp/terraform-provider-azurerm/issues/18235)
[18244](https://github.com/hashicorp/terraform-provider-azurerm/issues/18244)
[18291](https://github.com/hashicorp/terraform-provider-azurerm/pull/18291)

**Comment by KlemenDanfoss** [comment]
Same issue here.

Terraform Version
1.2.9

AzureRM Provider Version
3.28.0

**Comment by KlemenDanfoss** [comment]
For a quick fix you can use ignore_changes

**Comment by tombuildsstuff** [comment]
hi @ehonsey 

Thanks for opening this issue.

As mentioned in the error message here:

> expected the segment "resourcegroups" to be "resourceGroups"

.. Terraform's expecting the Resource ID to match a given format but a different casing is being specified, taking a looking through here the Resource ID being specified:

> /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/DefaultResourceGroup-CUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-00000000-0000-0000-0000-000000000000-CUS

versus the Resource ID ([from the `import` documentation for `XXX`](XXX#import)) we're expecting the format:

> /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/DefaultResourceGroup-CUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-00000000-0000-0000-0000-000000000000-CUS

As such it should be possible to fix this by updating the casing on the Resource ID value being specified (that is `resourcegroups` -> `resourceGroups`) - which'll fix this.

The behaviour of the Azure API is inconsistent insofar as Resource IDs are supposed to be case-insensitive during Requests and case-sensitive during Responses. Unfortunately, a number of API's don't behave in this manner and silently fail (in really subtle ways) when the casing doesn't match what the API is expecting. As such we're ultimately moving towards validating Resource IDs match the casing that's expected, which'll allow us (in the medium-term) to workaround these API/casing issues. However (as in this case) some user input may need updating to ensure the casing matches.

Whilst that's unfortunate that's affected you in this case, as mentioned above it should be possible to workaround this by updating the casing here, which'll allow `terraform plan` to succeed - would you be able to take a look?

Since this should be fixed by updating the casing being used here, I'm going to close this issue for the moment however please let us know if that doesn't work for you and we'll take another look.

Thanks!
