### ISSUE TITLE
Unable to import azurerm_virtual_machine - expected the segment "resourcegroups" to be "resourceGroups"

### ISSUE THREAD

**Issue by timbuchinger** [hashicorp/terraform-provider-azurerm#19510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "this" {
  name                         = "server"
  resource_group_name          = "resource-group"
  location                     = "canadacentral"
  vm_size                      = "Standard_D8s_v4"
  primary_network_interface_id = azurerm_network_interface.this.id
  network_interface_ids        = [azurerm_network_interface.this.id]

  storage_os_disk {
    name              = "server-dev-OSDisk"
    create_option     = "Attach"
    caching           = "ReadWrite"
    disk_size_gb      = 127
    os_type           = "Windows"
    managed_disk_id   = azurerm_managed_disk.this.id
    managed_disk_type = "StandardSSD_LRS"
  }
}
```

### Debug Output/Panic Output

```shell
Error: flattening `storage_os_disk`: &errors.errorString{s:"parsing Disk ID \"/subscriptions/[redacted]/resourcegroups/[redacted]/providers/Microsoft.Compute/disks/[redacted]\": parsing \"/subscriptions/[redacted]/resourcegroups/[redacted]/providers/Microsoft.Compute/disks/[redacted]\": parsing segment \"staticResourceGroups\": expected the segment \"resourcegroups\" to be \"resourceGroups\""}
```

### Expected Behaviour

I expect the Virtual Machine to be imported to state successfully.

### Actual Behaviour

The import fails.

### Steps to Reproduce

Run `terraform import` against this particular VM. I have imported many other VMs successfully.

**Comment by tombuildsstuff** [comment]
hi @timbuchinger 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 3.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!

**Comment by tazjin** [comment]
@tombuildsstuff I'm sure you're aware of this, but the new resources are not at feature-parity with the old one, meaning that at this point some resource configurations are essentially dropped on the floor and can not be managed with Terraform anymore.
