### ISSUE TITLE
Support for setting an alternate subscriptionId as a resource parameter

### ISSUE THREAD

**Issue by emerzon** [hashicorp/terraform-provider-azurerm#19539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently in order to support multiple subscriptions, one needs to specify multiple aliases as different providers, since currently the azurerm provider has a 1-to-1 relationship between the authentication credentials and subscriptions.

However, from an Azure API perspective, the relationship between authentication credentials and subscriptions is actually a 1-to-N.

The main drawback of the current method used by azurerm is that the subscriptionIds must be known beforehand (to be declared); therefore it's not possible to work with multiple dynamic subscriptions, at least not without the usage of an external helper to declare them as provider aliases directly in the TF files.

My proposal is to allow any resource to specify an alternative subscriptionId (different from the one specified within the provider block) as part of the resource parameters.

This way, subscriptions can be created/updated/destroyed dynamically, and their values could be reused to populate such this resource parameter.

### New or Affected Resource(s)/Data Source(s)

azurerm_*

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  client_id       = "nono"
  client_secret   = "nono"
  subscription_id = "XXX" 
  tenant_id       = "nono"
}

# Sample resource using the default subscription (coming from provider block)
resource "azurerm_private_dns_zone" "zoneXXX" {
  name                = "XXX.domain"
  resource_group_name = azurerm_resource_group.xxx.name
}

# Sample resource using the custom subscription 
resource "azurerm_private_dns_zone" "zoneYYY" {
  name                = "YYY.domain"
  subscription_id = "YYY"
  resource_group_name = azurerm_resource_group.yyy.name
}
```

**Comment by ms-zhenhua** [comment]
Hi @emerzon, thank you for reaching out.
This problem is similar with [this common issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/19520#issuecomment-1334698607). We will try to address it after the whole provider is migrated to use [Hashicorp Azure SDK](https://github.com/hashicorp/go-azure-sdk).

**Comment by tombuildsstuff** [comment]
hey @emerzon

Apologies thought I'd already replied to this one, I guess I wrote the comment but forgot to hit submit 😅

Internally the Provider has a number of expectations/requirements where a Provider Instance has a 1:1 relationship with a Subscription - as such whilst this has come up a few times over the years, unfortunately this isn't something we plan to implement at this point in time.

That said I totally understand the use-case here, and there's a feature request on Terraform Core which I think will solve this for you in a different manner - as such whilst this isn't something we plan to support at the Provider level, I'd encourage you to comment on/subscribe to [this upstream issue tracking support for Dynamic Providers](https://github.com/hashicorp/terraform/issues/19932), since once support for this is implemented there then this should be usable with every Provider rather than just being tied to AzureRM.

Whilst I appreciate that's probably not the answer you're looking for, since this isn't something we plan to implement within the Provider I'm going to close this issue for the moment - but when this functionality is supported in Terraform (Core) then this should be usable across all Providers, which'll fix this in a different manner.

Thanks!
