### ISSUE TITLE
ID was missing the `serverfarms` element

### ISSUE THREAD

**Issue by JeremyMcConnell** [hashicorp/terraform-provider-azurerm#19600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.34.0

### Affected Resource(s)/Data Source(s)

azurerm_resources, azurerm_linux_web_app

### Terraform Configuration Files

```hcl
# Find an existing app service plan
data "azurerm_resources" "asp" {
  type = "microsoft.Web/serverFarms"
}

# Add app deployment
resource "azurerm_linux_web_app" "webapp" {
  name                = "webapp"
  resource_group_name = azurerm_resource_group.rg.name
  location            = data.azurerm_resources.asp.resources[0].location
  service_plan_id     = data.azurerm_resources.asp.resources[0].id

  site_config {}
}
```

### Debug Output/Panic Output

```shell
{
   "@level":"error",
   "@message":"Error: ID was missing the `serverfarms` element",
   "@module":"terraform.ui",
   "@timestamp":"2022-12-07T03:53:23.263382Z",
   "diagnostic":{
      "severity":"error",
      "summary":"ID was missing the `serverfarms` element",
      "detail":"",
      "address": <OMITTED>,
      "range": <OMITTED>,
      "snippet": <OMITTED>
   },
   "type":"diagnostic"
}

Operation failed: failed running terraform plan (exit 1)
```

### Expected Behaviour

The App Service Plan ID retrieved via `azurerm_resources` should be considered valid and the `azurerm_linux_web_app` resource successfully created.

### Actual Behaviour

Terraform throws the error `ID was missing the 'serverfarms' element`

This seems to be caused by the ID containing `serverFarm` while Terraform is expecting `serverfarm` (all lower case). Since this ID is generated and provided by Azure, it should probably be considered valid without needing to manipulate it.

I was able to temporarily solve this issue using [replace](https://developer.hashicorp.com/terraform/language/functions/replace). For example: `replace(<appPlanID>, "serverFarms", "serverfarms")`

### Steps to Reproduce

1. Have an existing app service plan
2. terraform plan

### References

These issues seem to be caused by the same bug, with a different effect:
- https://github.com/hashicorp/terraform-provider-azurerm/issues/15723
- https://github.com/hashicorp/terraform-provider-azurerm/issues/5787

**Comment by tombuildsstuff** [comment]
hey @JeremyMcConnell 

Thanks for opening this issue.

Unfortunately the casing used by the Azure Portal and Azure APIs differs (and changes over time) as such the Azure APIs are the canonical reference for Resource ID segments. Since Resource IDs are predictable within Azure, we now define these within Terraform based on a point-in-time reference of the Resource ID, unfortunately at the point-in-time when this Resource ID was created we were using the segment `serverfarms` (as the Azure API was doing so) - however at this point in time the ARM Team within Azure has required that segments move towards using camelCasing for segment names, as such this should ultimately become `serverFarms`.

The Azure API's are supposed to be case-insensitive during reads and case-sensitive during responses with particular values - however both the Azure API's and the Azure Portal can and do change these casings as Service Teams desire. Unfortunately other Azure API's (and downstream tooling) can end up parsing these case-sensitively, which we've seen historically has caused a number of knock-on issues - namely where resources provision successfully but are unusable (for example a cluster you can't log into).

To workaround this we're moving towards validating that the Resource ID casing matches what we're expecting, which is the source of this error - but ultimately means that the Resource ID being provided in Terraform shouldn't change casing as/when the Azure API opts to change this casing.

As you've mentioned it should be possible to achieve this with the `azurerm_resources` data source by using a `replace` to workaround this, but we'd generally recommend using [the `azurerm_service_plan` data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/service_plan) which outputs the Resource ID we're expecting for the App Service Plan resource - whilst the `azurerm_resources` data source is available, we'd recommend using the more specific Data Source where possible.

Thanks!

**Comment by tombuildsstuff** [comment]
@JeremyMcConnell 👍 - purely out of interest, any chance you could elaborate on why you can't use the specialised data source there, I'm wondering if we're missing a data source?

**Comment by JeremyMcConnell** [comment]
@tombuildsstuff For sure. It's not a limitation of the ARM provider or Terraform. 

The `azurerm_service_plan` requires the plan `name`, which just isn't known. The app service plan is generated from a different repo/workspace, among other shared resources, and we locate it using agreed upon tagging structure.

This is an exploratory attempt to save costs in staging/test across multiple services without having to map the names of all the shared resources. So still finding all the pros and cons.
