### ISSUE TITLE
Azure Federated credential wildcards

### ISSUE THREAD

**Issue by fmgjw2** [hashicorp/terraform-provider-azurerm#19642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are using the new feature for the Azurerm with  Workload Identify.
We have multiple workspaces using the same Service Principle and to use Workload Identify we need to add 2 Federated credentials per workspace, this causes 3 issues.

1) The maximum amount of Federated credentials that can be associated to 1 Service Principle is 20, as we have more than 10 (remembering each workspace requires 2)  workspace in multiple workstreams that have more than 10 workspaces using the same Service Principle, hence we are having to create extra service Principles in Azure, this requires manual intervention due out IaC/risk profiles and elevated accounts. 

2) Along the same lines as the elevated question above, when a new workspace is required 2 new Federated credentials are required as the Subject Identifier is a one-to-one to a workspace. As we need to create 2 new Federated credentials this requires manual intervention due out IaC/risk profiles and elevated accounts.

3) Deployment of Workflow code to generate a new workspace in Terraform, this is now on hold as this Workflow can no longer perform the Azure requirements to link a workspace to a service Principle

4) Renaming of workspaces, up to now renaming a workspace was in TF Cloud and the code, now we find we also need to locate the correct Service principle in Azure and also alter the Federated Credentials

We have spent a lot of time migrating over from Client Secrets to Workload Identify but now feeling the pain, it is on the Road map to allow wildcards in the Subject Identifier and if it is, do you have an estimated Qualter time frame for this?

### New or Affected Resource(s)/Data Source(s)

AZURERM 1.35

**Comment by haytham0123** [comment]
Any updates here?

**Comment by dheerajbsomaraj** [comment]
Any updates on this?

**Comment by manicminer** [comment]
Hi @fmgjw2, thanks for opening this issue and apologies for the delayed reply. Unfortunately, Azure only supports exact matches with using federated credentials for OIDC, so due to this limitation the Terraform Cloud team is unable to improve efficiency here. We suggest reaching out to your Azure account team about this, to inform them about the challenges you are/were facing and to ask if they have plans to raise the limits here, or improve the claims matching to accommodate your workflow with fewer credentials.

Since this is a platform limitation with Azure, I'm going to close out this issue for now, but we will be happy to revisit this in future if/when these platform limitations are addressed on the Azure side.
