### ISSUE TITLE
azurerm has screwed my subscription

### ISSUE THREAD

**Issue by AgSync-Aaron** [hashicorp/terraform-provider-azurerm#19706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.3.2

### AzureRM Provider Version

v3.36.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "container_registry" {
  name                       = "logs-metrics"
  log_analytics_workspace_id = var.log_analytics_workspace_id
  target_resource_id         = azurerm_container_registry.default.id

  metric {
    category = "AllMetrics"
    retention_policy {
      enabled = false
    }
  }

  log {
    category_group = "allLogs"
    enabled        = true
    retention_policy {
      enabled = false
      days    = 0
    }
  }

  log {
    category_group = "audit"
    enabled        = false
    retention_policy {
      enabled = false
      days    = 0
    }
  }
}
```

### Debug Output/Panic Output

```shell
A resource with the ID "/subscriptions/[sub_id]/resourcegroups/rg-name/providers/microsoft.containerregistry/registries/foo-bar-baz/providers/microsoft.insights/diagnosticSettings/logs-metrics" already exists
```

### Expected Behaviour

You should properly delete my resources when I destroy them

### Actual Behaviour

I now have many abandoned resources and I cannot delete them.

I cannot even use the Azure API to delete the abandoned resources.

If I have purged my resource group I get the error...
```json
{"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}
```

If I attempt to apply my infrastructure as much as I can, then delete with the API I get
```json
{
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'northcentralus' and API version '2021-04-01' for type 'diagnosticSettings'. The supported api-versions are '2015-07-01, 2016-09-01, 2017-05-01-preview, 2021-05-01-preview, 2020-01-01-preview'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, southcentralus, eastus2, centralus, australiaeast, australiasoutheast, brazilsouth, uksouth, ukwest, southindia, centralindia, westindia, canadaeast, canadacentral, westcentralus, westus2, koreasouth, koreacentral, australiacentral, australiacentral2, francecentral, francesouth, , southafricanorth, uaecentral, uaenorth, switzerlandnorth, switzerlandwest, germanynorth, germanywestcentral, norwayeast, norwaywest, westus3, jioindiawest, swedencentral, qatarcentral'."
  }
}
```

### Steps to Reproduce

Use the azurerm terraform provider.

**Comment by AgSync-Aaron** [comment]
I have found a workaround. If I create a counter for the name, I can keep generating new resources...
```
resource "azurerm_monitor_diagnostic_setting" "container_registry" {
  name                       = "logs-metrics${var.azurerm_fuck_up_counter}"
  log_analytics_workspace_id = var.log_analytics_workspace_id
  target_resource_id         = azurerm_container_registry.default.id

  metric {
    category = "AllMetrics"
    retention_policy {
      enabled = false
    }
  }

  log {
    category_group = "allLogs"
    enabled        = true
    retention_policy {
      enabled = false
      days    = 0
    }
  }

  log {
    category_group = "audit"
    enabled        = false
    retention_policy {
      enabled = false
      days    = 0
    }
  }
}
```

**Comment by AgSync-Aaron** [comment]
I take it all back. My work around does not work
```
╷
│ Error: creating Monitor Diagnostics Setting "logs-metrics1" for Resource "/subscriptions/xxxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.ContainerRegistry/registries/agsyncengi": diagnosticsettings.DiagnosticSettingsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
│
│   with module.aks.azurerm_monitor_diagnostic_setting.container_registry,
│   on modules\aks\logging.tf line 1, in resource "azurerm_monitor_diagnostic_setting" "container_registry":
│    1: resource "azurerm_monitor_diagnostic_setting" "container_registry" {
│
╵
```

**Comment by AgSync-Aaron** [comment]
Once I got rid of all references to `azurerm_monitor_diagnostic_setting` everything is peachy. 
![image](https://user-images.githubusercontent.com/43680940/208052904-c0f8577d-5c17-4fb2-881d-71182ba9510b.png)

**Comment by AgSync-Aaron** [comment]
OMFG!

I deleted everything. and I mean EVERYTHING  I could and removed all references to the `azurerm_monitor_diagnostic_setting` and opened up my vnet diagnostic settings to find this... 
![image](https://user-images.githubusercontent.com/43680940/208059416-d01e7372-6b63-4ef8-a55e-330bb5c17ec7.png)

As I suspected, the resource is untouchable.

**Comment by tombuildsstuff** [comment]
hi @AgSync-Aaron 

Taking a look through here as you've mentioned unfortunately the way that Diagnostic Settings are handled within Azure is that they're created and deleted outside of the scope of a given Resource Group. This means that whilst other items (for example a Network/VM) would be deleted when the Resource Group is deleted, Diagnostic Settings kick around unless explicitly deleted (either via `terraform destroy` or deleting them via the CLI).

The error messages that Terraform's returning here are the "requires import" checks we do, since the Azure API's are upserts, we need to ensure when creating a resource that we're not unintentionally adopting an existing one - as such we're prompting that this resource needs to be imported (so that we can correctly flag the items which can/can't be updated without recreating the resource).

In this particular instance as you've mentioned the Diagnostic Setting outlives the Resource Group and so needs to be cleaned up, either via Terraform (if it's managed there) or via the Azure CLI - last time I dug into this the Azure Portal doesn't surface Diagnostic Settings unless there's a Resource Group (or whichever other item it's scoped to) associated with it, which gives the false impression that this has been deleted.

Unfortunately there's not enough information about to determine how the Container Registry and it's related resources are being removed (via Terraform or an external intervention such as the Azure CLI) - based on the description above I have a feeling this is being done manually, however since this thread has focused on the design of the Diagnostic Settings resource rather than a bug specific to Terraform I'm going to close this issue for the moment. That said, if you're seeing that the Monitor Diagnostic Setting isn't being removed, please feel free to open a new issue attaching the debug logs (`TF_LOG=1 TF_LOG_PATH=somepath terraform apply`) and we'll take a look.

Thanks!

**Comment by AgSync-Aaron** [comment]
I just found this comment here with basically the same issue as I was having that I just found. https://github.com/hashicorp/terraform-provider-azurerm/issues/11076#issuecomment-963092635
I attempted to delete the resource directly with the API, but I could not.

_This clearly is not_ an azurerm provider issue. Thanks for responding.
