### ISSUE TITLE
Support for Windows 365/CloudPC api's

### ISSUE THREAD

**Issue by ZipMartyHyland** [hashicorp/terraform-provider-azurerm#19767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi all please add support for CloudPC/Windows 365 api's as documented here.
https://learn.microsoft.com/en-us/graph/api/resources/cloudpc-api-overview?view=graph-rest-beta

Would be most useful for:
https://learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta

Allowing terraform to create provisioning policies that use other resources created by terraform, currently terraform can only be used to create the networking resources and the provisioning policies must be created with ClickOps or via GraphAPI

### New or Affected Resource(s)/Data Source(s)

azurerm_cloudpc

### References

https://learn.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta

**Comment by mybayern1974** [comment]
@ZipMartyHyland thank you for opening this issue. May I assume this feature belongs to [Terraform Azure AD Provider](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs) (its repo is [here](https://github.com/hashicorp/terraform-provider-azuread/)) that focuses on supporting MS Graph features in Terraform by leveraging MS Graph API, rather than this repo?

If so I may suggest to close this issue here and file this issue to the Terraform AAD repo, or feel free to raise different opinions.

**Comment by ZipMartyHyland** [comment]
Thanks for letting me know, I'll raise it there.
