### ISSUE TITLE
azurerm_storage_account block customer_managed_key does not support system-assigned managed identity

### ISSUE THREAD

**Issue by sanderrhorst** [hashicorp/terraform-provider-azurerm#19807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.37.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "***" {
  name                             = "***"
  resource_group_name              = azurerm_resource_group.***.name
  location                         = azurerm_resource_group.***.location
  account_tier                     = "Standard"
  account_replication_type         = "LRS"
  allow_nested_items_to_be_public  = "false"
  cross_tenant_replication_enabled = true
  min_tls_version                  = "TLS1_2"
  access_tier                      = "Cool"

  customer_managed_key {
    key_vault_key_id = azurerm_key_vault_key.***.id
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Missing required argument
│ 
│   on Storage.tf line 48, in resource "azurerm_storage_account" "***":
│   48:   customer_managed_key {
│ 
│ The argument "user_assigned_identity_id" is required, but no definition was
│ found.
```

### Expected Behaviour

I expect this customer_managed_key block to have an option to use the system-assigned identity of the storage account as this is supported when you configure this trough the portal. This forces us to keep using azurerm_storage_account_customer_managed_key while it would be much better to have everything in the same place. 

### Actual Behaviour

Plan failed

**Comment by magodo** [comment]
@sanderrhorst This error message indicates that you didn't specify the `customer_managed_key.user_assigned_identity_id`, which is a required property to set.

**Comment by sanderrhorst** [comment]
> @sanderrhorst This error message indicates that you didn't specify the `customer_managed_key.user_assigned_identity_id`, which is a required property to set.

Yes I know, but it is not possible to add the value referring the system assigned managed identity there. And that is what I want. This block just does not support usage of the system assigned managed identity which I would like to see added to this block:)

**Comment by magodo** [comment]
@sanderrhorst You told that *This forces us to keep using azurerm_storage_account_customer_managed_key*, could you please share how do you specify a system assigned identity via `azurerm_storage_account_customer_managed_key` given it also only supports `user_assigned_identity_id`?

**Comment by sanderrhorst** [comment]
@magodo, in the azurerm_storage_account_customer_managed_key we left the user_assigned_identity_id parameter empty, so it defaults uses the managed identity of the storage account which is supplied under storage_account_id. Example:

resource "azurerm_storage_account_customer_managed_key" "***" {
  storage_account_id = azurerm_storage_account.***.id
  key_vault_id       = azurerm_key_vault.***.id
  key_name           = azurerm_key_vault_key.***.name
}

With above code, I see the configured settings in the portal set to the Identity type: System-assigned and the System-assigned identity: ID of the System Assigned managed Identity of the storage account

**Comment by tombuildsstuff** [comment]
@sanderrhorst apologies for the delayed reply to this one.

When using a System Assigned Identity you'll need to use the separate `azurerm_storage_account_customer_managed_key` resource rather than the `customer_managed_key` block within the `azurerm_storage_account` resource. This is because you'll need to grant the System Assigned identity associated with the Storage Account access to the Key Vault in question in order for it to be able to access it (else provisioning will fail), which can't be done until the Storage Account and it's associated System assigned identity is created.

I vaguely recall from a previous discussion with @magodo that the Service Team were discouraging the use of a System Assigned identity for this purpose (due to this circular reference) - and instead were recommending customers use a User Assigned identity to workaround this (since the permissions can be defined in advance), as such the two options here are:

1. Use the separate `azurerm_storage_account_customer_managed_key` resource with a System Assigned identity.
2. Use a User Assigned identity and the `customer_managed_key` block within the `azurerm_storage_account` resource.

As such whilst I'd like to thank you for opening this issue, since this is ultimately a configuration/design question I'm going to close this issue for the moment - but as outlined above this limitation comes from the fact that the System Assigned identity won't exist until after it's created, and so can't have permissions assigned in advance - and without those the Storage Account fails to provision.

Thanks!
