### ISSUE TITLE
Provider produces inconsistent plan for principal ID value on azurerm_role_assignment

### ISSUE THREAD

**Issue by landalex** [hashicorp/terraform-provider-azurerm#19857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "function_app_keyvault" {
  scope                = azurerm_key_vault.key_vault.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_windows_function_app.function_app.identity.0.principal_id
}
```

### Debug Output/Panic Output

```shell
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.thecycle_azure.azurerm_role_assignment.function_app_keyvault[0] to include new
│ values learned so far during apply, provider "registry.terraform.io/hashicorp/azurerm" produced an invalid new value
│ for .principal_id: was cty.StringVal("bf817af4-fc6b-448c-9a7b-2a36c8f27e7f"), but now
│ cty.StringVal("54f40e7a-399f-4227-85d2-717e01615649").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behaviour

When applying an azurerm_role_assignment resource, the resource is successfully created/modified.

### Actual Behaviour

The Terraform apply operation fails due to the plan being inconsistent. Even after creating the role assignment successfully in the portal, the provider creates a plan that includes creating a new role assignment and fails with this error when applying.

### Steps to Reproduce

1. terraform apply

### References

This issue appears to be similar to #8318 but does not fix itself when re-applying.

**Comment by liuwuliuyun** [comment]
Hi @landalex, thanks for raising this issue. From the error msg I think it could be azurerm_windows_function_app.function_app.identity.0.principal_id somehow got changed. I notice you created the role assignment successfully in the portal, so is it before you see this error msg or after?

**Comment by landalex** [comment]
I ran the Terraform apply operation and it failed with this error, so I tried to create it in the portal manually and it worked. I then re-ran the apply operation and it still failed with the same error (including planning to create the resource, which I had just manually created), so it seems like there may be an issue with how the plan gets created. I would expect that if a resource is manually created in the portal and then Terraform apply is run, that resource is found by Terraform and it asks me to import it, but this didn't happen.

**Comment by landalex** [comment]
I've just imported the resource into my Terraform state, and when running another apply operation Terraform plans to replace the resource because it believes the principal ID has changed, which once again fails to create the new resource with the same error as reported above. So even after importing there's still an issue where the provider is somehow getting the wrong principal ID.

**Comment by liuwuliuyun** [comment]
Hi @landalex, to reproduce your issue here, I might need your your config file (*.tf) and state file (*.tfstate). If it is a large project, the minimum info I need will be the config and state for resource `azurerm_windows_function_app` and `azurerm_role_assignment`. You could upload to https://gist.github.com/ or any other website of your choice. Be sure to remove any sensitive information in both files if you do.

**Comment by landalex** [comment]
Here is the state: https://gist.github.com/landalex/681d4e95045496ce5eac8256015c8976
Note that I manually extracted this from a much larger state file and removed some information.

Here is the main.tf: https://gist.github.com/landalex/8df18ca5e990c0b4484959137357636f
Again, removed irrelevant variables and removed some information.

As I said, the Terraform plan operation attempts to create the role assignment because it doesn't think one already exists (despite manually creating one in the portal), so there is no `azurerm_role_assignment` in the Terraform state for this function app.

**Comment by liuwuliuyun** [comment]
Thanks for the update. I have checked the state and the principle_id in state is 54f40e7a-399f-4227-85d2-717e01615649. By your description, you only encounter this when trying to create an azurerm_role_assignment and failed with promoted error. 

So, I would suggest to do following test 1. delete the azurerm_role_assignment resource from *.tf file. 2. rerun terraform plan. If everything works fine, it should generate a successful plan. Be sure to make backup before your test.  

If you failed in above tests, it means something is wrong with principle_id config in *tfstate and we will deal with it then.

If we are lucky and above test succeeds without error, you could run apply to adjust your other configuration. Since you already have assignment in portal, you could try 1. Delete the assignment from portal 2. create azurerm_role_assignment in *.tf and apply.

**Comment by landalex** [comment]
Update: I spoke to Azure support because I got suspicious that it might not be specific to Terraform, and after some back and forth the issue was caused by the system assigned identity of the Function App (accessible by going to the Function App and opening the Identity blade). For some reason the system assigned identity principal ID for the Function App was the same as the principal ID of the deployment slot of the Function App, which was causing the problem. I disabled the system managed identity and re-enabled it, which created a new identity object and principal ID, and from there I was able to create role assignments again via Terraform successfully.
