### ISSUE TITLE
Support for mssql_managed_instance to include the AzureAD admin enabled block

### ISSUE THREAD

**Issue by mukundbajaj** [hashicorp/terraform-provider-azurerm#19877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the mssql_managed_instance after creation has to use azurerm_mssql_managed_instance_active_directory_administrator to enable the AAD login for administrators.

Can we include this block as a part of the same mssql_managed_instance, so that the SQL MI gets created without the local login and password? This enables us to ensure that the AAD user from the beginning is the admin and we can mitigate the risk of storing the credentials in a state file.

The Azure Portal by default allows this behavior.

### New or Affected Resource(s)/Data Source(s)

mssql_managed_instance

**Comment by sinbai** [comment]
@mukundbajaj thanks for opening this issue. Unfortunately, Terraform could not do it because it creates mssql_managed_instance resource based on Azure API. API requires `administrator_login` and `administrator_login_password` when creating mssql_managed_instance. In addition, if "the risk of storing the credentials in a state file" means saving the `administrator_login_password` to state file, in fact, terraform does not write sensitive data `administrator_login_password` into it.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is not something that we are able to add as noted above.
Whilst I'd like to thank you for opening this issue as we have no plans to support this functionality I'm going to close this issue for the moment.
