### ISSUE TITLE
Support for setting provider wise timeout settings

### ISSUE THREAD

**Issue by cusspvz** [hashicorp/terraform-provider-azurerm#19922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Seems like the current default timeout settings for all resources are not enough for setups with a lot of Azure resources. From what I've seen, as part of the terraform default resource parameters, each resource can define its own API call timeouts.

I'm currently experiencing `context deadline exceeded` errors when attempting to refresh the state, from random resources. I was wondering if there's a way to setup the default timelines for the specific provider instead of having AzureRM defaulting based on the terraform's plugin sdk timeout defaults.

### New or Affected Resource(s)/Data Source(s)

azurerm_*

**Comment by magodo** [comment]
@cusspvz You can customize the resource timeout values per [this](https://developer.hashicorp.com/terraform/language/resources/syntax#operation-timeouts). Note that you have to [do an apply to make the updated timeout take effect](https://github.com/hashicorp/terraform/issues/31023). Or, you can manually edit the state file (but please do that with cautions).

**Comment by cusspvz** [comment]
@magodo correct, what I'm requesting is the ability to set defaults within the provide configuration, so the defaults on all resources get loaded from the provider defaults if these exist instead of the Terraform plugin SDK defaults.

**Comment by magodo** [comment]
There is no Terraform plugin SDK defaults, but there are default timeouts for each resource, which is defined by the provider, e.g. https://github.com/hashicorp/terraform-provider-azurerm/blob/4340d639946ce6aa6e187b944dfd1371465e8a99/internal/services/batch/batch_account_resource.go#L36-L39

I don't think it is very helpful for a provider level timeout override that applies to every resource since different resources take very different time span for each operation.

**Comment by manicminer** [comment]
Thanks for requesting this @cusspvz. I agree with @magodo that a provider-wide timeout override would be impractical as some resources take very little time, whereas others may take several minutes or even hours (plural). You can override timeouts for individual resources where the default timeout is problematic for your use case. Accordingly, since it's unlikely that we'll incorporate this functionality due the aforementioned impracticality, I'm going to close this issue for now. Thanks again for requesting this and please open further issues if you have any other feature requests.
