### ISSUE TITLE
Additional Information On ratelimit_enabled Flag

### ISSUE THREAD

**Issue by dancarltonigt** [hashicorp/terraform-provider-azurerm#19946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am looking for additional documentation on the ratelimit_enabled flag. I cannot find any informtion on this on the Azure documentation or azurerm_vpn_gateway_connection  documentation besides the "ratelimit_enabled - (Optional) Should the rate limit be enabled? Defaults to false." comment on the page.

Can someone please provide additional information on this. I am looking for how this interacts with the VPN tunnel, and what is the target rate limit.

### New or Affected Resource(s)/Data Source(s)

azurerm_vpn_gateway_connection

### Potential Terraform Configuration

```hcl
n/a
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
