### ISSUE TITLE
Support for azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by roiSH120** [hashicorp/terraform-provider-azurerm#19965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_kubernetes_cluster resource doesn't output all resources that created under node_resource_group:
internal load balancer
agentpool-nsg
and more

There is no option to get the id of the internal load balancer that is created.

Thank you!

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by stephybun** [comment]
Thanks for raising this issue @roiSH120.

Unfortunately the AKS API doesn't expose the IDs of the resources created in the managed node resource group, as a result it isn't something that we can support in the resource today.

However it should still be possible to get the IDs of these resources through the use of data sources. Taking the load balancer resource as an example, below is one suggestion on how you could extract the resource ID:

```
data "azurerm_resources" "lb" {
  resource_group_name = azurerm_kubernetes_cluster.test.node_resource_group
  type = "Microsoft.Network/loadBalancers"
}

output "id" {
  value = {
    aks_loadbalancer = data.lb.spokes.resources[0].id
  }
}
```

Since this is achievable through the use of data sources I'm going to close this issue. For further configuration questions I'd suggest raising them over on our [Community Discuss forum](https://discuss.hashicorp.com/).
