### ISSUE TITLE
Deprovisioning azurerm_servicebus_namespace resource fails due to it changing Public access to "All Networks" prior to Destroy

### ISSUE THREAD

**Issue by jomitch1** [hashicorp/terraform-provider-azurerm#20072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13.7

### AzureRM Provider Version

3.36

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

upon a destroy (changing the count, commenting out the code), the azurerm_servicebus_namespace resource should destroy

### Actual Behaviour

An Azure Policy scoped to this Resource prevented the destroy; the Policy is as follows:

    "policyRule": {

      "if": {

        "allOf": [

          {

            "field": "type",

            "equals": "Microsoft.ServiceBus/namespaces/networkRuleSets"

          },

          {

            "field": "Microsoft.ServiceBus/namespaces/networkrulesets/default.defaultAction",

            "equals": "allow"

          }

        ]

      },

      "then": {

        "effect": "deny"

### Steps to Reproduce

prerequisite:  create Azure Policy preventing ServiceBus Namespace from having the "networkRuleSet" defined to "Allow"

### References

Deprovisioning azurerm_servicebus_namespace resource fails due to it changing Public access to "[All Networks](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/servicebus/servicebus_namespace_network_rule_set_resource.go#L237)" prior to Destroy; the issue is that we have an Azure Policy preventing the "All Network" Public access setting on Azure resources (a recommended security practice), so upon the deprovision of this Resource via Terraform Enterprise, the Destroy fails; currently in order to successfully destroy the azurerm_servicebus_namespace, we must first create an exception in the Azure Policy governing this setting for this resource; Optimally, the azurerm_servicebus_namespace resource would be destroyed as is, rather than editing it to a new configuration prior to its deletion

**Comment by xiaxyi** [comment]
@jomitch1 Thanks for raising this issue. From your description, I suspect this is a restriction from the api side, in order to confirm whether this is a TF provider issue, can you either share the deletion error message you got or try to deleting the resource via PowerShell/ CLI/ calling API to see if the namespace can be deleted?

**Comment by redshiftz** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/servicebus/servicebus_namespace_network_rule_set_resource.go
I think Line 237 is the culprit in 'func resourceServiceBusNamespaceNetworkRuleSetDelete'
defaultAction := namespaces.DefaultActionAllow

**Comment by manicminer** [comment]
Thanks for reporting this @jomitch1, and for the additional info @redshiftz. It looks like the deletion here is not a true deletion but instead relaxes the rule to effectively disable it. This is a limitation of the service, and is the best approach we have here. In the case of having a policy preventing this, there is unfortunately not much we can do to help here. You may need to simply change the rule to conform with your policy, rather than deleting it, or alternatively manually remove it from your state if you wish for Terraform to no longer manage it.

As I believe there isn't anything for us to change here, I'm going to close this issue for now. If you believe I have misunderstood, or if there is a potential solution I did not notice, please feel free to comment and we'll be happy to take another look. Thanks!
