### ISSUE TITLE
3.39.1 azurerm_postgresql_flexible_server zone is not updated 

### ISSUE THREAD

**Issue by omerfsen** [hashicorp/terraform-provider-azurerm#20084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.3.9.1

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "flexible_server" {
   count               = var.single_server ? 0 : 1
   name                = var.server_name
   location            = var.location
   resource_group_name = var.resource_group_name
 
   sku_name = var.sku_name
 
   storage_mb            = var.storage_mb
   backup_retention_days = var.backup_retention_days
 
   administrator_login    = data.vault_generic_secret.administrator_creds.data.administrator_login
   administrator_password = data.vault_generic_secret.administrator_creds.data.administrator_password
   version                = var.server_version
 
   delegated_subnet_id = var.delegated_subnet_id
   private_dns_zone_id = var.private_dns_zone_id
 
   dynamic "high_availability" {
     for_each = var.create_replica_instance ? [1] : []
     content {
       mode = "ZoneRedundant"
     }
   }

 }
```

### Debug Output/Panic Output

```shell
│ Error: `zone` can only be changed when exchanged with the zone specified in `high_availability.0.standby_availability_zone`
│ 
│   with module.psql["yyyyy"].azurerm_postgresql_flexible_server.flexible_server[0],
│   on ../cpp-module-terraform-azurerm-postgresql/flexible_server.tf line 1, in resource "azurerm_postgresql_flexible_server" "flexible_server":
│    1: resource "azurerm_postgresql_flexible_server" "flexible_server" {
│ 
╵
╷
│ Error: `zone` can only be changed when exchanged with the zone specified in `high_availability.0.standby_availability_zone`
│ 
│   with module.psql["xxx"].azurerm_postgresql_flexible_server.flexible_server[0],
│   on ../cpp-module-terraform-azurerm-postgresql/flexible_server.tf line 1, in resource "azurerm_postgresql_flexible_server" "flexible_server":
│    1: resource "azurerm_postgresql_flexible_server" "flexible_server" {
```

### Expected Behaviour

I expect (as previous versions are already doing it) zone field automatically propogated when running apply. If not next terraform runs try to empty zone field which results above error.

For example:

 terraform state show azurerm_postgresql_flexible_server.flexible_server[0]
# azurerm_postgresql_flexible_server.flexible_server[0]:
resource "azurerm_postgresql_flexible_server" "flexible_server" {
    administrator_login           = (sensitive value)
    administrator_password        = (sensitive value)
    backup_retention_days         = 30
    delegated_subnet_id           = ""
    fqdn                          = "xxxX"
    geo_redundant_backup_enabled  = false
    id                            = "/subscriptions/e..."
    location                      = "uksouth"
    name                          = "YYYY"
    private_dns_zone_id           = ""
    public_network_access_enabled = true
    resource_group_name           = "XXXXX"
    sku_name                      = "MO_Standard_E2s_v3"
    storage_mb                    = 32768
    version                       = "11"
    zone                          = ""     <<<!!!!!!!!!!!!!!!!!!!!!!!! _WAS Set to 3 by Azure but terraform fails to update it on first apply
    authentication {
        active_directory_auth_enabled = false
        password_auth_enabled         = true
    }
} 

### Actual Behaviour

I expect (as previous versions are already doing it) zone field automatically propogated when running apply. If not next terraform runs try to empty zone field which results above error.

### Steps to Reproduce

2. terraform apply again

if you omit to add zone then next run fails.

### References

none

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume it's by TF design. Though `zone` and `high_availability.0.standby_availability_zone` aren't set, but service API would randomly set them at service side. So Terraform doesn't know the value of them at first apply. After first apply, I assume you would encounter tf difference using `tf plan`. And you have to handle them before second apply. There are two ways to resolve it. They could be to use ignore_changes or explicitly set them in tf config. See more details from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server#zone.

**Comment by omerfsen** [comment]
But old azurerm provider catches and updates it on first apply(azurerm 2.79.1 for example)

**Comment by jeicob22** [comment]
Same situation happens with **azurerm_mysql_flexible_server**

`# azurerm_mysql_flexible_server.my_server["a_server"] will be updated in-place
  ~ resource "azurerm_mysql_flexible_server" "my_server" {
        id                            = "/subscriptions/..."
        name                          = "transfer-development-server"
        tags                          = {}
      - zone                          = "2" -> null
        # (14 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
`

**Comment by tombuildsstuff** [comment]
hey @omerfsen 

Thanks for opening this issue.

As @neil-yechenwei has mentioned, if an Availability Zone isn't specified then the Azure API will pick one by default - whilst previous versions of the Azure Provider didn't surface the value of the `zone` field, we're intentionally doing so in v3.0 as part of [some behavioural changes, which are documented in 3.0 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#behavioural-updates).

Whilst the Azure API automatically selecting an Availability Zone for this resource is convenient, doing so means it's easier to unintentionally distribute resources within a single zone, since resources may be provisioned in the same Availability Zone by the API - which could cause issues should a particular Availability Zone have issues.

To ensure that we're surfacing this information and users to make an informed choice about the deployment of resources, as of v3.0 the `zone` field is no longer marked as computed, meaning that if a user hasn't specified this value they'll need to make use of `ignore_changes` to say they're happy for Azure to pick an Availability Zone for them. This allows either for users to define the Availability Zone they wish to deploy the resource into - or have Azure auto-select the Zone for them (and not define this within the config).

As such, it should be possible to remove the diff from the plan here either to specify the Availability Zone which should be used, or using `ignore_changes` to ignore changes to the `zone` field (saying that you'd like Azure to pick an Availability Zone when provisioning the resource, and use that).

Since this is a configuration question rather than a bug in the Azure Provider, I'm going to close this issue for the moment - but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Comment by omerfsen** [comment]
Ok. Now it is clear for us. Thank you
