### ISSUE TITLE
Support for Conditional access names location for AKS clusters

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#20123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful if there was terraform support to restrict Azure Regions by using Conditional Access Named Locations to allow access to Azure Kubernetes Service (AKS) clusters from only specific logical groupings of IP address ranges or countries/regions. 

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "Production"
  }

  conditional_access{
    named_location = “String”
  }
}
```

**Comment by stephybun** [comment]
Thanks for raising this issue @ramyaradhakrishnan108.

I'm not sure this is supported by the AKS API at this point in time since I'm unable to find any references to it in the REST API spec and haven't found any documentation on it either. Could you provide some more information on how you would currently do this either via the Portal or with the Azure CLI? 

We cannot support what isn't available to us in the API so you would need to raise an issue over on https://github.com/Azure/AKS to get this added before we can look into this.

**Comment by stephybun** [comment]
Closing since we haven't heard back and no linked feature request has been opened on the AKS repo. When support for this becomes available in the AKS API feel free to reach out and we can reopen this. Thanks!
