### ISSUE TITLE
Error: in event_hub_receiver, exactly one of event_hub_id or (event_hub_namespace, event_hub_name) must be set

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#20146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_action_group

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_action_group" "support" {
  name                = "AlertsAction"
  resource_group_name = data.azurerm_resource_group.support.name
  short_name          = "alerts"

  event_hub_receiver {
    name                    = "s-alerts"
    event_hub_namespace     = local.management_monitor_namespace_name
    event_hub_name          = "e-alerts"
    subscription_id         = local.management_subscriptionid
    use_common_alert_schema = true
  }
  tags = local.common_tags
}
```

### Debug Output/Panic Output

```shell
Error: in event_hub_receiver, exactly one of event_hub_id or (event_hub_namespace, event_hub_name) must be set
with module.terraform-azure_support.azurerm_monitor_action_group.support
on .terraform/modules/terraform-azure_support/log_analytics_workspace.tf line 11, in resource "azurerm_monitor_action_group" "support":
```

### Expected Behaviour

Plan and apply should not change anything nor fail this seems to be random issue, sometimes i need to delete the azurerm_monitor_action_group in the portal and then let it recreate.

### Actual Behaviour

Error: in event_hub_receiver, exactly one of event_hub_id or (event_hub_namespace, event_hub_name) must be set

### Steps to Reproduce

terraform plan
terraform apply
terraform plan
terraform apply

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/18322

**Comment by nlighten** [comment]
We consistently get this issue as soon as we change something to an `azurerm_monitor_action_group` that contains an `event_hub_receiver`. The initial create works but any update fails with 

```
Error: in event_hub_receiver, exactly one of event_hub_id or (event_hub_namespace, event_hub_name) must be set ....
```

The bug seems to be related to the following change:

https://github.com/hashicorp/terraform-provider-azurerm/pull/17335/files

In the `flattenMonitorActionGroupEventHubReceiver` function the `event_hub_id` is always added when the FourPointOhBeta feature toggle equals false. So `event_hub_id`, `event_hub_namespace`,  `event_hub_name` and `subscription_id` are all returned:

https://github.com/hashicorp/terraform-provider-azurerm/blob/a478a88388a7125dd5dabf6073bb5d1de3df175e/internal/services/monitor/monitor_action_group_resource.go#L1106-L1108

But the `expandMonitorActionGroupEventHubReceiver` throws the error we see when the FourPointOhBeta feature toggle equals false and all four items exist:

https://github.com/hashicorp/terraform-provider-azurerm/blob/a478a88388a7125dd5dabf6073bb5d1de3df175e/internal/services/monitor/monitor_action_group_resource.go#L851-L860


At a first glance it seems that adding the `event_hub_id` in `flattenMonitorActionGroupEventHubReceiver`  can be removed from function `flattenMonitorActionGroupEventHubReceiver` but I am not sure.

@teowa I am not sure if you remember the change. If you do, I would appreciate your thoughts on the above.

**Comment by teowa** [comment]
Hi @mpjtaylor @nlighten, thanks for raising this, I have sent PR to fix this issue.

**Comment by DevopsMercenary** [comment]
any work around in the mean time ?

**Comment by mpjtaylor** [comment]
Delete it and let it be recreated.
