### ISSUE TITLE
Not able to set Resource access configuration to keyvault

### ISSUE THREAD

**Issue by gyuvaraj10** [hashicorp/terraform-provider-azurerm#20395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are no attributes to set the following options to the azure keyvault via terraform
![image](https://user-images.githubusercontent.com/8053219/217826255-83d58e8c-e545-46d2-b4fc-b65346860d81.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_key_vault

**Comment by tombuildsstuff** [comment]
hey @gyuvaraj10 

Support for this is available as the `enabled_for_deployment`, `enabled_for_disk_encryption` and `enabled_for_template_deployment` fields in the `azurerm_key_vault` resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault#enabled_for_deployment

Since this is a configuration question rather than an issue in the Azure Provider I'm going to close this issue for the moment, but should you have further configuration questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
