### ISSUE TITLE
Update azurerm_container_app_environment resource to enable configuration of daprAIInstrumentationKey property

### ISSUE THREAD

**Issue by faheemgani** [hashicorp/terraform-provider-azurerm#20404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I noticed that the wait is now over and we have support for deploying Container Apps and Container App environments through Terraform. :tada: Thanks for all the hard work that went into making that happen.

When I was looking at the `azurerm_container_app_environment` resource, I noticed the following property was missing - `daprAIInstrumentationKey` 

If using ARM or the az CLI this property can be set when deploying the container app environment:

https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=arm-template

I believe it allows Dapr to log its metrics against an Application Insights instance.

Just wanted to check if there was a plan to add this in the future or if this needs to be set elsewhere.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Potential Terraform Configuration

```hcl
resource "azurerm_application_insights" "example" {
  name                = "tf-test-appinsights"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "web"
}

resource "azurerm_container_app_environment" "example" {
  name                        = "my-environment"
  location                    = azurerm_resource_group.example.location
  resource_group_name         = azurerm_resource_group.example.name
  log_analytics_workspace_id  = azurerm_log_analytics_workspace.example.id
  dapr_ai_instrumentation_key = azurerm_application_insights.example.instrumentation_key
}

```
```


### References

https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=arm-template

https://learn.microsoft.com/en-us/cli/azure/containerapp/env?view=azure-cli-latest#az-containerapp-env-create

**Comment by crookm** [comment]
The usefulness of this feature is not as high as instrumenting application insights within the application. Dapr does kinda hide cross-service calls because of its proxy, but app insights does still join telemetry together across buckets and apps, so you still get full distributed tracing (I guess only for service invocations though).

I still think this feature should be added, because without it the application map is useless (only showing one localhost server, the proxy). My guess is that it would help with tracing pubsub etc as well, but I'm not sure as my app doesn't use it.

As a temporary solution until this can be added to the provider, I managed to set this value with the [AzAPI provider](https://registry.terraform.io/providers/Azure/azapi/latest/docs) (I used the connection string value instead of the instrumentation key).

```terraform
resource "azapi_update_resource" "ai_dapr" {
  type        = "Microsoft.App/managedEnvironments@2022-10-01"
  resource_id = azurerm_container_app_environment.env.id

  body = jsonencode({
    properties = {
      daprAIConnectionString = azurerm_application_insights.ai.connection_string
    }
  })
}
```

There's some [details here](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2022-10-01/managedenvironments?pivots=deployment-language-terraform) about the structure of the body for this resource, if you want to change other things as well.

The `daprAIConnectionString` property doesn't seem to like being updated, I found. If you change app insights buckets, it won't direct logging to the new bucket.
