### ISSUE TITLE
Terraform Import : provider/azurerm: Network Security Group - facing issues on protocol casing at Import time TCP Tcp

### ISSUE THREAD

**Issue by priyapriyapriya3** [hashicorp/terraform-provider-azurerm#20402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform 1.3.7

### AzureRM Provider Version

 v3.0.0

### Affected Resource(s)/Data Source(s)

NSG

### Terraform Configuration Files

```hcl
protocol                                   = "TCP"

Terraform Import : provider/azurerm: Network Security Group - facing issues on protocol casing at Import time TCP Tcp
error expected .protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP
```

### Debug Output/Panic Output

```shell
error expected .protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP
```

### Expected Behaviour

It should be either accepting the with out case sensitive, or import should be done as acceptable by Terraform

### Steps to Reproduce

Terraform init
Terraform validate/terraform plan

### References

#32650
I have raised the same issue with terraform where they said to raise in this forum

**Comment by tombuildsstuff** [comment]
hi @priyapriyapriya3 

Per the error message being returned here, we're expecting the values for this field to be `*`, `Tcp`, `Udp`, `Icmp`, `Ah` or `Esp`] - however you're specifying `TCP` which doesn't match the casing here.

We use the casings defined in [the Azure API Specifications](https://github.com/Azure/azure-rest-api-specs) which are the canonical casings for this field from the Service Team - as such we require (and normalize back to) these values - as such you can fix this configuration error by updating the casing of the value being specified from `TCP` to `Tcp`.

Since this is a configuration question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
