### ISSUE TITLE
azurerm_sql_managed_instance_failover_group in failover groups configuration can not set up sql server license failover group rights

### ISSUE THREAD

**Issue by kenzjq** [hashicorp/terraform-provider-azurerm#20401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the current azurerm resource azurerm_sql_managed_instance_failover_group , it seems missing the  sql server license failover group rights selection in failover groups configuration, please find the screenshot of the existing SQL failover group. 
![failover](https://user-images.githubusercontent.com/67395422/217907329-2e950db6-44fd-4b81-a85c-66a278f8d5a4.PNG)

### New or Affected Resource(s)/Data Source(s)

azurerm_sql_managed_instance_failover_group

### Potential Terraform Configuration

```hcl
there should be an argument in azurerm_sql_managed_instance_failover_group to allow sql server license failover group rights selection.
```

### References

https://techcommunity.microsoft.com/t5/azure-sql-blog/what-is-the-failover-rights-benefit-for-geodr/ba-p/3676999

**Comment by sinbai** [comment]
@kenzjq  thanks for opening this issue. Per the above screen shot, it seems that the terraform resource should be `azurerm_mssql_managed_instance_failover_group` rather than `azurerm_mssql_failover_group`, right? If yes, I've checked that  the [latest Azure API](https://github.com/Azure/azure-rest-api-specs/blob/f1180941e238bc99ac71f9535ecd126bb8b77d8f/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/InstanceFailoverGroups.json#L119) does not seem to support this feature yet. Since Terraform depends on the Azure rest API implementation, it is currently could not be supported. If you find that an Azure API property supports this feature, please let us know and we would support it based on the priority.

**Comment by sb185296** [comment]
i am also try to find a way to enable it under azurerm_mssql_managed_instance_failover_group
and not really found , only with GUI via portal :\

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
