### ISSUE TITLE
compute isolation

### ISSUE THREAD

**Issue by komaldeyton** [hashicorp/terraform-provider-azurerm#20506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I am unable to find more documentation on this.

### Description

Using compute isolation block and specifying sku="Standard". Is still pulling up Basic sku for public IPs and Load balancers. Please advise. Thanks

### New or Affected Resource(s)/Data Source(s)

azurerm_hdinsight_kafka_cluster

**Comment by tombuildsstuff** [comment]
hi @komaldeyton 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding the Terraform Configuration being used rather than a bug in the Azure Provider, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
