### ISSUE TITLE
Advice on tagging outputs "cluster_endpoint" and "cluster_certificate_authority_data" as sensitive in kubernetes resource

### ISSUE THREAD

**Issue by nikuljain** [hashicorp/terraform-provider-azurerm#20602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

need guidance on should we have below as sensitive ?

when we try to create an AKS cluster using terragrunt, we see the following errors complaining about the sensitive outputs.
Error: Output refers to sensitive values

on outputs.tf line 11:
11: output "cluster_endpoint" {

To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm your intent.

If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
sensitive = true

Error: Output refers to sensitive values

on outputs.tf line 16:
16: output "cluster_certificate_authority_data" 

output referred are below :
azurerm_kubernetes_cluster.default.kube_config[0].host
azurerm_kubernetes_cluster.default.kube_config[0].cluster_ca_certificate

### Terraform Version

1.3.3

### AzureRM Provider Version

3.x.x

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
guidance needed
```

### Debug Output/Panic Output

```shell
guidance needed
```

**Comment by tombuildsstuff** [comment]
hi @nikuljain 

Thanks for opening this issue.

Taking a look through here this appears to be a configuration question rather than a bug in the Azure Provider, specifically [the documentation for `terraform outputs` highlights how you can mark these as sensitive](https://developer.hashicorp.com/terraform/language/values/outputs#optional-arguments).

Since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
