### ISSUE TITLE
azurerm_cdn_frontdoor_rule does not allow leading slash in match_values even though azure portal allows it

### ISSUE THREAD

**Issue by ameykarandikar1** [hashicorp/terraform-provider-azurerm#20652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_rule" "rule" {
  name                      = "rule"
  cdn_frontdoor_rule_set_id = azurerm_cdn_frontdoor_rule_set.ruleset.id

  order                     = 1
  actions {
    url_rewrite_action {
      destination             = "/static_content"
      preserve_unmatched_path = true
      source_pattern          = "/"
    }
  }

  conditions {
    url_path_condition {
      match_values = ["/static/"]
      operator     = "BeginsWith"
    }
    url_path_condition {
      match_values     = ["/static/homepage/"]
      negate_condition = true
      operator         = "BeginsWith"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: "conditions.0.url_path_condition.0.match_values.0" must not begin with the URLs leading slash(e.g. /), got "/static/"
```

### Expected Behaviour

Azure portal allows leading slashes in the match values but terraform provider is erroring out. A screenshot from azure portal with the values saved is included.

<img width="744" alt="screenshot" src="https://user-images.githubusercontent.com/77250635/221302484-23521445-f2ac-4315-b2cb-434706a3c177.png">

### Actual Behaviour

terraform provider errored out

**Comment by WodansSon** [comment]
@ameykarandikar1, thank you for opening this issue. The Terraform provider and the Portal UI will not always match 1 to 1. In this case, the Portal UI, allows the leading slash in the text box for visual purposes only. When the portal persists the value to the service the leading slashes are stripped from the value. The [Microsoft documentation](https://learn.microsoft.com/en-us/azure/frontdoor/rules-match-conditions?pivots=front-door-standard-premium&tabs=json#request-path) also mentions that `...if you specify a leading slash, it's ignored...`. This might seem a tad bit confusing but what the Terraform provider is currently doing is the correct behavior, the Portal is just allowing them in the UI, but not the actual value for that it sends to the service. Since this isn't actually a bug I will be closing this issue. Thanks again for opening this issue and have a great day. 🚀
