### ISSUE TITLE
Please reopen #20525, since Azure Front Door Classic is not deprecated

### ISSUE THREAD

**Issue by GurliGebis** [hashicorp/terraform-provider-azurerm#20692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

#20525 has been closed with a commit that changes the text to mention that Azure Front Door Classic has been deprecated.

Can you please link to where this is mentioned from Microsoft?
From what I can see, nowhere do they mention it being deprecated - they have just released a migration tool for people who wants to use the more advanced features of Standard and Premium.

There are still use cases for using Classic, so removing it from the provider is going to be making it impossible to use this going forward for people with those use cases.

If you could please provide links to where the deprecation is mentioned, so we can use that in our planning on how to move forward.

### New or Affected Resource(s)/Data Source(s)

azurerm_frontdoor

### References

This is the migration guide - nowhere does it mention Classic being deprecated: https://learn.microsoft.com/en-us/azure/frontdoor/tier-migration

**Comment by WodansSon** [comment]
@GurliGebis, thank you for opening this issue. The Terraform Front Door Classic resources are not going to be deprecated from the Terraform provider in v4.0 as originally stated, which is why the note in the documentation was updated. The resources will remain within the provider without any engineering effort(e.g. `deprecated`), save for security issue and framework fixes. I cannot comment beyond that publicly at this point. Thank you again for opening this issue and bringing it to my attention. 🚀
