### ISSUE TITLE
azurerm_container_app_environment should not require a log_analytics_workspace_id

### ISSUE THREAD

**Issue by zioproto** [hashicorp/terraform-provider-azurerm#20748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

v3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "tf-aca-rg"
  location = "eastus"
}

resource "azurerm_container_app_environment" "example" {
  name                       = "mytfaca"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
}

resource "azurerm_container_app" "example" {
  name                         = "example-app"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"

  template {
    container {
      name   = "examplecontainerapp"
      image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Missing required argument
│
│   on main.tf line 6, in resource "azurerm_container_app_environment" "example":
│    6: resource "azurerm_container_app_environment" "example" {
│
│ The argument "log_analytics_workspace_id" is required, but no definition was found.
```

### Expected Behaviour

The `log_analytics_workspace_id` should not be required. With the CLI it is possible to create a container app with `--logs-destination none` in case the logs are handled manually in the application by a third party solution:

Example:
```
az containerapp env create --name nologsmyaca -g aca --location eastus --logs-destination none
```

With Terraform is not possible to create a Container App with this equivalent configuration

### Actual Behaviour

`log_analytics_workspace_id` is required forcing the creation of the Log Analytics Workspace.

### Steps to Reproduce

`terraform plan`

**Comment by zioproto** [comment]
I intercepted the `PUT` method with `mitmproxy` when I create the containerapp  env using az-cli.

Running this command:
```
az containerapp env create --name nologsmyaca -g aca --location eastus --logs-destination none
```

Results in this:
```
{
    "location": "eastus",
    "properties": {
        "appLogsConfiguration": {
            "destination": null,
            "logAnalyticsConfiguration": null
        },
        "customDomainConfiguration": null,
        "daprAIInstrumentationKey": null,
        "internalLoadBalancerEnabled": null,
        "vnetConfiguration": null,
        "zoneRedundant": false
    },
    "sku": {
        "name": "Consumption"
    },
    "tags": null
}
```

**Comment by zioproto** [comment]
In addition, we should make sure that changing `log_analytics_workspace_id` does not trigger the destroy and recreate of the resource. The customer should be able to point to a different log analytics workspace id during operations.

**Comment by leandroscardua** [comment]
Hi There,

Do we have any update on it?

**Comment by leandroscardua** [comment]
Hi There,

Do we have any update on it?

**Comment by ctnoz** [comment]
Any update on this bug?

When deploying container apps environment in the portal, I can choose one of the following logging options:
1) log analytics
2) azure monitor (diagnostic settings)
3) none

But in terraform, I cannot choose a logging option other than log analytics. This is because [`log_analytics_workspace_id` is a required argument for `azurerm_container_app_environment` and cannot be set to null](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_app_environment#log_analytics_workspace_id). This prevents me from enabling diagnostic settings instead of log analytics.

I can still define diagnostic settings alongside log analytics with no conflicts in terraform, but log analytics takes precedence during deployment. Therefore, after deploying with terraform, I have to manually switch logging options from log analytics to azure monitor (diagnostic settings) in the portal. Only then does it disable log analytics and enable diagnostic settings with the details (metrics, storage account, eventhub, etc.) I defined in the terraform code.

**Comment by Sefriol** [comment]
Agreed. Terraform config should match possible logging options in Azure Portal.
