### ISSUE TITLE
azurerm_kubernetes_cluster: automatic_channel_upgrade name is wrong

### ISSUE THREAD

**Issue by orgads** [hashicorp/terraform-provider-azurerm#20792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.37.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  # ...
  automatic_channel_upgrade = "rapid"
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

The name should be automatic_upgrade_channel, as it is named in the ARM template: `autoUpgradeProfile.upgradeChannel`.

### Actual Behaviour

The words are swapped.

**Comment by xyq175com** [comment]
I can work on this and drop a PR later

**Comment by stephybun** [comment]
Thanks for opening this issue @orgads.

There are many instances where we do not map property names 1:1 from the API or from ARM templates and choose to follow naming conventions specific to the azurerm provider in order to keep these consistent. This is in part because feature or property names can differ across Azure, i.e. a feature could have a different name in the portal and/or the CLI as to what's defined in the API or ARM templates. 

Renaming a field is a breaking change and involves setting behaviours on the new and old field that could cause issues in users configurations. Since it's specified in the documentation that this controls the upgrade channel of the cluster and was released in the provider over 2 years ago, we will not be renaming this field.

Since this is neither a feature request nor a bug I'm going to close this issue If you have any further questions regarding usage I'd direct you towards the [Community Discuss forum](https://discuss.hashicorp.com/).

Thanks!

**Comment by orgads** [comment]
Sure, I knew this is a breaking change, but thought that it can be renamed, while keeping the old name as a deprecated field. Anyway, this is not that important. The name just appeared a bit strange to me.
