### ISSUE TITLE
Not able to create new Subscription using Terraform

### ISSUE THREAD

**Issue by pawan-debug** [hashicorp/terraform-provider-azurerm#20857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.6

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

Installed hashicorp/azurerm v3.46.0 (signed by HashiCorp)

### Terraform Configuration Files

```hcl
data "azurerm_billing_enrollment_account_scope" "example" {
  billing_account_name    = "1234567890"
  enrollment_account_name = "0123456"
}

resource "azurerm_subscription" "example" {
  subscription_name = "My Example EA Subscription"
  billing_scope_id  = data.azurerm_billing_enrollment_account_scope.example.id
}
```

### Debug Output/Panic Output

```shell
Error: creating new Subscription (Alias "*******************"): subscription.AliasClient#Create: Failure sending request: StatusCode=401 -- Original Error: Code="UserNotAuthorized" Message="User is not authorized to create subscriptions on this enrollment account"
│
```

### Steps to Reproduce

Error: creating new Subscription (Alias "*******************"): subscription.AliasClient#Create: Failure sending request: StatusCode=401 -- Original Error: Code="UserNotAuthorized" Message="User is not authorized to create subscriptions on this enrollment account"

### References

I also refers below docs
[https://discuss.hashicorp.com/t/creating-new-subscriptions-through-terraform/29545]
[https://github.com/Azure/azure-rest-api-specs/issues/14093](mailto:https://github.com/Azure/azure-rest-api-specs/issues/14093)
https://stackoverflow.com/questions/71725712/issue-on-creating-azure-subscription-using-terraform-with-github-actions

**Comment by pawan-debug** [comment]
with CLI, I am able to create but using Terraform its giving me error. Please let me know if any additional role need to assign or missing something.

**Comment by manicminer** [comment]
@pawan-debug Thanks for raising this issue. It seems like the error you are getting from the API is due to missing permissions - I would recommend double checking your role assignments. Unfortunately there is nothing that Terraform can do to help as the correct permissions must be assigned in order to allow the operation.

We use GitHub issues for tracking feature requests and bugs in the Azure provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community). Accordingly I'm going to close this issue, but I believe you should be able to get an answer on the community discussion portal.
