### ISSUE TITLE
data azurerm_storage_account does not seem to work as expected regarding listKeys

### ISSUE THREAD

**Issue by shaneholder** [hashicorp/terraform-provider-azurerm#20902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I've read several issues and the PR around listKeys when using the data provider for azurerm_storage_account but the provider does not appear to work as described.  If a user is granted "Storage Blob Data Reader" access to a storage account.  

The above TF when executed against a storage account with "Storage Blob Data Reader" outputs the following error during a terraform plan.  My reading of the issues seems to indicate that it should fail gracefully.  

My end goal is to create a private endpoint using the workflow method with the `is_manual_connection=true`

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
terraform {

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.46.0"
    }
  }

  required_version = ">= 1.3.0"
}

provider "azurerm" {
  features {}
}

# For storage account access
# Where Requested account has: 

data "azurerm_storage_account" "repo" {
  name                = "ro-storageaccount"
  resource_group_name = "myrg"
}

output "id" {
  value = data.azurerm_storage_account.repo.id
}
```

### Debug Output/Panic Output

```shell
Error: listing Keys for Storage Account: (Name "redacted" / Resource Group "redacted"): storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'redacted' with object id redacted' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Storage/storageAccounts/redacted' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

### Expected Behaviour

The ID of the storage account should display in the output.

### Actual Behaviour

Error message above and terraform exits.

### Steps to Reproduce

1. terraform init
2. terraform plan

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/4248/files#diff-c8d648ff0856d05b08585a7774924629039f97d215e1d95715d8fd6433fce34a

This [comment ](https://github.com/hashicorp/terraform-provider-azurerm/issues/20188#issuecomment-1406533087) indicates that it should work using the data source.

**Comment by magodo** [comment]
@shaneholder The reason that the provider list the key is by default it uses SharedKey to access data plane API during:
https://github.com/hashicorp/terraform-provider-azurerm/blob/18500fe92468db28bbd5577c672b4b2d4503b460/internal/services/storage/storage_account_resource.go#L2185-L2199

Since the SharedKey is necessary here, where we can't do something as:
https://github.com/hashicorp/terraform-provider-azurerm/blob/18500fe92468db28bbd5577c672b4b2d4503b460/internal/services/storage/storage_account_resource.go#L1953-L1968

Though, you can workaround this by setting [`storage_use_azuread = true`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#storage_use_azuread).

**Comment by tombuildsstuff** [comment]
@magodo this is about the Data Source rather than the Resource? As such, the Data Source should work with limited permissions - [see this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/20188#issuecomment-1406533087) for more info.

**Comment by magodo** [comment]
@tombuildsstuff No, the API that returned error (403) is towards the mgmt plane per the error message *does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Storage/storageAccounts/redacted' or the scope is invalid*. While this key being listed is crutial to build the SharedKey for the follow up data plane API call, which targets to the queue service.

**Comment by shaneholder** [comment]
I just tried setting:
(powershell)
$env:ARM_STORAGE_USE_AZUREAD="true"

and running my test and it fails with the same error.

Additionally I tried setting:
```
provider "azurerm" {
  features {
  }
  storage_use_azuread = true
}
```
with the same resulting error.

**Comment by magodo** [comment]
@tombuildsstuff Sorry that my previous comment is about the managed resource rather than the data source. In my test, it appears to be that the listKey tolerance in data source is a bit different than the one in the resource:

https://github.com/hashicorp/terraform-provider-azurerm/blob/a234a9a103a1e02244ddfae2c5923bafe22c4284/internal/services/storage/storage_account_data_source.go#L368-L373

https://github.com/hashicorp/terraform-provider-azurerm/blob/a234a9a103a1e02244ddfae2c5923bafe22c4284/internal/services/storage/storage_account_resource.go#L1958-L1963

(The resource 403 handling is added in https://github.com/hashicorp/terraform-provider-azurerm/commit/cfd940bf5395ae02816b6ff90fe8e70815302e6f)

So the fix is as simple as make the data source to be the same as the resource does. I've verified that a SP with subscription level `Reader` and `Storage Blob Data Reader` (presumably not necessary) can then read the data source successfully.

Furthermore, as you indicated, *The Resource should be validating that we have access to the ListKeys API*. The origin of this change is introduced in https://github.com/hashicorp/terraform-provider-azurerm/pull/4248, and changing this might break some existing users who have more finer grained role definitions. So I'm hesitating to do so.
