### ISSUE TITLE
Argument missing | azurerm_bot_channel_email_v3.33.0 module

### ISSUE THREAD

**Issue by Hitesh-Kariya** [hashicorp/terraform-provider-azurerm#20982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_bot_channel_email_v.3.33.0

### Terraform Configuration Files

```hcl
Module - azurerm_bot_channel_email_v3.33.0

Argument missing - "Authentication Type"
```

### Debug Output/Panic Output

```shell
NA
```

### Expected Behaviour

Argument - "Authentication Type" - must be there.

1. Modern Authentication (OAUTH)
2. Basic Authentication (disabling Oct'22)

### Actual Behaviour

No Argument "Authentication Type"

**Comment by manicminer** [comment]
@Hitesh-Kariya Thanks for opening this issue. Does this relate to a Terraform module rather than the AzureRM provider? If this is a provider issue, please confirm and provide more information about the exact error you are seeing and your configuration to reproduce it. Thanks!

**Comment by HiteshKKariya** [comment]
The issue is from Terraform module side. 
Ref link : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bot_channel_email

![image](https://user-images.githubusercontent.com/111073477/225822996-0abc28ee-8a12-4216-94a5-03a25228fe0b.png)

Here, there is no argument for "Authentication Type" where as when we deploy in portal there are two authentication methods:
1. Modern authentication (OAUTH)
2. Basic authentication (disabling Oct'22)

![bot_channel_email](https://user-images.githubusercontent.com/111073477/225823594-c690f9d0-7e43-4b0a-875e-7957c322f2f8.JPG)

I think terraform by default goes with Basic authentication.

**Comment by Hitesh-Kariya** [comment]
The issue is from Terraform module side.
Ref link : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bot_channel_email

Here, there is no argument for "Authentication Type".
![image](https://user-images.githubusercontent.com/118470453/225824105-85fccbf6-1335-4730-9bfd-fc42218e2e39.png)

Where as when we deploy in portal there are two authentication methods:

. Modern authentication (OAUTH)
. Basic authentication (disabling Oct'22)

![bot_channel_email](https://user-images.githubusercontent.com/118470453/225824170-a00ddda0-6f87-4553-a065-c11929221f0f.JPG)

I think terraform by default goes with Basic authentication.
