### ISSUE TITLE
the possibility of creating an os_disk from an existing managed disk for the resource azurerm_linux_virtual_machine/azurerm_windows_virtual_machine

### ISSUE THREAD

**Issue by ebobant** [hashicorp/terraform-provider-azurerm#21074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, on the **azurerm_virtual_machine** resource, we can create an os disk (storage_os_disk) from an existing managed disk through the option **storage_os_disk->create_option->Attach(managed disks only).**

Given that the **azurerm_virtual_machine** resource is only available through 2.x releases, and will be completely replaced with the **azurerm_windows_virtual_machine/azurerm_linux_virtual_machine** resources, I am interested in when it will be possible to create an os disk using managed disk on these resources.

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine/azurerm_windows_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_windows_virtual_machine" "example"
.
.
.
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    create_option        = "Attach"
    managed_disk_id      = azurerm_managed_disk.source.id #or use data resource
  }
```

**Comment by tombuildsstuff** [comment]
hey @ebobant 

> Given that the azurerm_virtual_machine resource is only available through 2.x releases, and will be completely replaced with the azurerm_windows_virtual_machine/azurerm_linux_virtual_machine resources, I am interested in when it will be possible to create an os disk using managed disk on these resources.

To clarify, the legacy `azurerm_virtual_machine` resource continues to be available in 3.x - however we recommend upgrading to the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources - but the legacy resource will be removed _at some point_ in the future.

Support for attaching an existing Managed Disk as an OS Disk is being tracked in #8195, as such rather than having multiple issues open tracking the same thing, I'm going to close this issue in favour of #8195 - would you mind subscribing to that issue for updates?

Thanks!
