### ISSUE TITLE
Some attributes are marked as sensitive for no reason

### ISSUE THREAD

**Issue by orgads** [hashicorp/terraform-provider-azurerm#21130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.49.0

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_topic and more

### Terraform Configuration Files

```hcl
servicebus/servicebus.tf:
resource "azurerm_servicebus_namespace" "servicebus" {
  name = "example-servicebus"
  location = "West US 2"
  resource_group_name = "example-rg"
  sku = "Standard"
}

output "servicebus" {
  value = azurerm_servicebus_namespace.servicebus
}

main.tf:
provider "azurerm" {
  features {}
}

module "servicebus" {
  source = "./servicebus"
}

resource "azurerm_servicebus_topic" "test" {
  name         = "test"
  namespace_id = module.servicebus.servicebus.id
}
```

### Debug Output/Panic Output

```shell
# azurerm_servicebus_topic.test will be updated in-place
  ~ resource "azurerm_servicebus_topic" "test" {
        id                                      = "/subscriptions/.../resourceGroups/example-rg/providers/Microsoft.ServiceBus/namespaces/example-servicebus/topics/test"
        name                                    = "test"
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change. The value is unchanged.
      ~ namespace_id                            = (sensitive value)
        # (11 unchanged attributes hidden)
    }
```

### Expected Behaviour

It is not sensitive, and should not be considered as sensitive at any point

### Actual Behaviour

It is stored as sensitive, and the following warning appears on each apply:
```
Warning: this attribute value will no longer be marked as sensitive
```

### Steps to Reproduce

1. terraform apply
2. terraform apply

### References

I'm not sure if this issue relates to the provider or to terraform core, but it appeared recently after upgrading both.

**Comment by tombuildsstuff** [comment]
hi @orgads 

Taking a look through here [neither of these fields are marked as Sensitive in the Provider (and hasn't been in the past)](https://github.com/hashicorp/terraform-provider-azurerm/blob/0b8158e55289776b19098cf70864b59b53ba8fff/internal/services/servicebus/servicebus_topic_resource.go#L46-L59) as such I have a feeling the Module may have previously defined this output as `Sensitive: true`, but is no longer doing so?

Whilst I can't speak for if there's a bug in the latest version of Terraform Core, from what I can see above (specifically, the `Warning: this attribute value will no longer be marked as sensitive after applying this change. The value is unchanged.`) suggests that this module may have previously defined this output as a `sensitive: true` field, as such it'd be good to confirm if that's the case here.

However since the Provider itself isn't marking these fields as Sensitive, I believe this is either a change in the module (where this was previously defined as `sensitive: true` and it's now not) or an issue with Terraform Core - so whilst I'm going to close this issue for the moment, I'd encourage you to first check the module history and then (should the output not previously be being defined as sensitive), open an issue on the Terraform Core repository where someone from that team should be able to take a look into that.

Thanks!
