### ISSUE TITLE
azurerm_network_interface dns_servers not updated when changing from defined IPs to null

### ISSUE THREAD

**Issue by Wiston999** [hashicorp/terraform-provider-azurerm#21225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_network_interface

### Terraform Configuration Files

```hcl
resource "azurerm_network_interface" "nic" {
  name                = "test-interface"
  location            = "northeurope"
  resource_group_name = "[REDACTED]"

  dns_servers = ["8.8.8.8", "9.9.9.9"]


  ip_configuration {
    name                          = "test"
    subnet_id                     = "[REDACTED]"
    private_ip_address_allocation = "Dynamic"
  }
}
```

### Debug Output/Panic Output

1
```shell

→ terraform apply
azurerm_network_interface.nic: Refreshing state... [id=/subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Network/networkInterfaces/test-interface]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

2
```
sed -i 's/dns_servers/# dns_servers/' iface.tf
```

3
```
→ terraform apply
azurerm_network_interface.nic: Refreshing state... [id=/subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Network/networkInterfaces/test-interface]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Expected Behaviour

`dns_servers` attribute value should be updated when its value is modified.

### Actual Behaviour

Modifying `dns_servers` attribute from a list of IPs to `null` produces no changes in `terraform apply`

### Steps to Reproduce

1. `terraform apply` provided example configuration file filling `[REDACTED]` values to real values.
2. Comment `dns_servers` attribute in provided configuration file
3. `terraform apply` again, noticing that terraform reports `No changes. Your infrastructure matches the configuration.`

**Comment by myc2h6o** [comment]
Hi @Wiston999 thanks for raising the issue! The reason of this behavior is because `dns_servers` is `Optional`+`Computed` in the schema:https://github.com/hashicorp/terraform-provider-azurerm/blob/57d8ac737d2f6f12a31bd5816adc56a30e3d7973/internal/services/network/network_interface_resource.go#L124-L127
when removed from config, `dns_servers` will take the value from the service and doesn't output a diff because of the `Computed` flag. I guess this is introduced at first because different default value returned from service with different input. We'll be looking into this further to see if we will be removing the `Computed` flag for this `Optional` field. And as a mitigation, you could clean up the value by specifying `dns_servers = []` in the config

**Comment by Wiston999** [comment]
Hi @myc2h6o , thanks for your answer. 
We will be using `dns_servers = []` in the meanwhile.
