### ISSUE TITLE
azurerm_key_vault_certificate: feature for re-issue certificates.

### ISSUE THREAD

**Issue by Vijayalakshmi-Yolbhavi** [hashicorp/terraform-provider-azurerm#21257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,
We have configured keyvault to create/renew digicert certificates. We are able to create/import certificate with the terraform module azurerm_key_vault_certificate. However, we dont see a module to re-issue certificate. We can re-issue certificate(manually) from the portal with the "New version" feature available.  
Please let us know if there is already a terraform module available or going to be available in future for re-issuing certificates.

Thanks!

### New or Affected Resource(s)/Data Source(s)

azurerm_key_vault_certificate

**Comment by teowa** [comment]
Hi @Vijayalakshmi-Yolbhavi , thanks for submitting this issue!

By checking the docs and source code, currently there is no way in azurerm to create multiple versions of (or re-issue) the certificate, the `azurerm_key_vault_certificate` can only create one version in one certificate and it always tracks the latest version of the certificate. 

It remains some issue to manage multi versions of certificate at the same time in Terraform, because currently the service does not support for deleting single version of certificate but can only delete all versions within one certificate at one time with the [method](https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/delete-certificate/delete-certificate?tabs=HTTP). Which makes a single version certificate non-idempotent.

**Comment by Vijayalakshmi-Yolbhavi** [comment]
Hi @teowa ,
Ok.. Thanks for the information!

**Comment by harouny** [comment]
Hi @Vijayalakshmi-Yolbhavi @teowa ,

Maybe some behaviour have changed since April. I noticed the following:

- If in-place update is possible; a new version of the certificate will be created which is the behaviour we want for rotation to work properly.
- Only when in-place update isn't possible is where things get tricky. In my case I searched [documentation ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_certificate)for this text `Changing this forces a new resource to be created` to know which properties can cause in-place update to be **not** possible and will avoid changing them in future if possible, the good thing is none of them change when an action rotation happen.

**Comment by teowa** [comment]
@harouny yes, I have submitted PR to change the [doc](https://github.com/hashicorp/terraform-provider-azurerm/pull/23135/files#diff-3278e28e4fb04207631a646673beb328ccc1a9eef3772e6a600b7c0a42386be7). Update `certificate` or `certificate_policy` will create a new version of certificate.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #23135. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
