### ISSUE TITLE
Provisioning fails when deploying VM Extension

### ISSUE THREAD

**Issue by cshea15** [hashicorp/terraform-provider-azurerm#21289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "mma_agent" {
  name                       = "mma_agent"
  virtual_machine_id         = azurerm_windows_virtual_machine.vm.id
  publisher                  = "Microsoft.EnterpriseCloud.Monitoring"
  type                       = "MicrosoftMonitoringAgent"
  type_handler_version       = "1.0"
  auto_upgrade_minor_version = true
  settings                   = <<SETTINGS
  {
    "workspaceId": "${var.law_id}"
  }
    SETTINGS
  protected_settings         = <<PROTECTED_SETTINGS
    {
        "workspaceKey": "${var.law_key}"
        }
    PROTECTED_SETTINGS

  depends_on = [
    azurerm_virtual_machine_extension.aad_join,
    var.law_id,
    var.law_key
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'mma_agent'. Error message: \"Failed to apply configuration to Microsoft Monitoring Agent.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionMMAWindowsTroubleshoot "
│
│   with module.vm.azurerm_virtual_machine_extension.mma_agent,
│   on Modules\vm\extensions.tf line 14, in resource "azurerm_virtual_machine_extension" "mma_agent":
│   14: resource "azurerm_virtual_machine_extension" "mma_agent" {
```

### Expected Behaviour

Provisioning should not fail. 

### Actual Behaviour

│ Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'mma_agent'. Error message: \"Failed to apply configuration to Microsoft Monitoring Agent.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionMMAWindowsTroubleshoot "
│
│   with module.vm.azurerm_virtual_machine_extension.mma_agent,
│   on Modules\vm\extensions.tf line 14, in resource "azurerm_virtual_machine_extension" "mma_agent":
│   14: resource "azurerm_virtual_machine_extension" "mma_agent" {

I am able to deploy with Powershell and GUI successfully but it fails with Terraform. 

### Steps to Reproduce

Terraform init
Terraform plan
terraform apply

**Comment by cshea15** [comment]
[tf.log](https://github.com/hashicorp/terraform-provider-azurerm/files/11153432/tf.log)

adding bug file

**Comment by tombuildsstuff** [comment]
hi @cshea15 

Taking a look through here this appears to be a configuration question related to the VM Extension itself rather than a bug in Terraform, since this error message is coming from the VM Extension itself. As mentioned in the error message above, additional troubleshooting information for this Virtual Machine Extension can be found at https://aka.ms/VMExtensionMMAWindowsTroubleshoot

Unfortunately the configuration of a VM Extension can be particularly finicky, since each type of VM Extension has it's own payloads, error conditions and debugging models. I'd recommend following the troubleshooting steps above which should assist in debugging this - I've previously found that the logs for the VM Extension Logs to contain enough information to debug the VM Extension in question.

Since this is an issue with the configuration of the VM Extension, unfortunately the Terraform side of this is working and as such I'm going to have to close this issue for the moment, but as mentioned above the logs/troubleshooting information linked above should allows you to debug what's going on here.

Thanks!

**Comment by cshea15** [comment]
hey @tombuildsstuff - Yeah I was taking a shot to see if it was terraform because I tested by deploying out my VM and Log Analytics Workspace with Terraform then deploying the extension via Powershell after the vm and law were deployed and it worked. but couldn't get it to work with Terraform. 

When I deployed the VM, LAW, and Extension via Terraform and i got the Failure Provisioning, I RDP'd to the VM and saw that the LAW Key and ID were blank so I thought there was something that the Terraform wasn't pushing to the VM. 

I also tested the AMA extension with the same VM and LAW via Terraform and that worked just fine. It seems that its just the MMA extension with Terraform that errors out.
