### ISSUE TITLE
Cannot perform credential operations for ACR

### ISSUE THREAD

**Issue by wortner** [hashicorp/terraform-provider-azurerm#21440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.52.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry_token_password

### Terraform Configuration Files

```hcl
data "azurerm_container_registry" "acr" {
  name                = local.acr_name
  resource_group_name = data.azurerm_resource_group.acr_rg.name
}

data "azurerm_container_registry_scope_map" "scope_map" {
  name                    = "_repositories_pull"
  container_registry_name = data.azurerm_container_registry.acr.name
  resource_group_name     = data.azurerm_resource_group.acr_rg.name
}


resource "azurerm_container_registry_token" "helm_registry_token" {
  name                    = "akspulluser"
  container_registry_name = data.azurerm_container_registry.acr.name
  resource_group_name     = data.azurerm_resource_group.acr_rg.name
  scope_map_id            = data.azurerm_container_registry_scope_map.scope_map.id
}

resource "azurerm_container_registry_token_password" "helm_registry_token_password" {
  container_registry_token_id = azurerm_container_registry_token.helm_registry_token.id
  password1 {

  }
}
```

### Debug Output/Panic Output

```shell
unexpected status 400 with error: UnAuthorizedForCredentialOperations: Cannot perform credential operations for /subscriptions/REDACTED/resourceGroups/rg/providers/Microsoft.ContainerRegistry/registries/REDACTED as admin user is disabled. Kindly enable admin user as per docs: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account
```

### Expected Behaviour

I should be able to do this operation. I already using this in another project with following difference
- working with resource ACR not DATA resource
- I'm creating the ACR in the other project when creating the password works
- In the working project I store the pass to KV, here I am referencing it from kubernetes provider's helm_release resource, but I expect that I am not yet so far

### Actual Behaviour

I'am getting "Cannot perform credential operations  <> │ as admin user is disabled. Kindly enable admin user as per docs"

**Comment by wortner** [comment]
The problem is with call to REST api of /listCredentials which results in "UnAuthorizedForCredentialOperations". 

`2023-04-18T07:50:57.4032008Z 2023-04-18T07:50:57.135Z [DEBUG] provider.terraform-provider-azurerm_v3.52.0_x5: AzureRM Response for https://management.azure.com/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerRegistry/registries/REDACTED/listCredentials?api-version=2021-08-01-preview: 
2023-04-18T07:50:57.4033604Z HTTP/2.0 400 Bad Request`

The generate password call works. But somehow passing the value to the KV doesn't require /listCredentials call, this is the reason why it is failing. But why do I need such code is it because the value is used in another provider resource  

```
resource "helm_release" "keda_release" {
  name                = "keda"
  repository          = "oci://${data.azurerm_container_registry.acr.login_server}/helm"
  repository_username = azurerm_container_registry_token.helm_registry_token.name
  repository_password = azurerm_container_registry_token_password.helm_registry_token_password.password1[0].value
```

The listCredentials call causes the password to be tainted

`azurerm_container_registry_token_password.helm_registry_token_password encountered an error during creation, so it is now marked as tainted`

**Comment by wortner** [comment]
The issue is bound to this [commit](https://github.com/hashicorp/terraform-provider-azurerm/commit/68ba9917be405fa73058e9e241dcc7a365b6a226#diff-38bf82b781aecef1a8f24219d58ef436d055ac8f36ef062fbcd010a6770bcac3) where container_registry_data source is now calling listCredentials! This is for us breaking change as admin access will be always disabled. Solution so far is revert back to 3.51.0

**Comment by magodo** [comment]
@stephybun Would you mind take a look at this?

**Comment by tombuildsstuff** [comment]
@magodo calling the `ListCredentials` API here should be fine, however it appears that we need to conditionally do this based on whether the admin user is enabled?

The `Generate Credentials` endpoint will cycle the credentials, thus isn't safe to use within either the Read function or the Data Source (hence why this is set in the Create and Update methods) - and whilst we can read the result of the LRO, ARM states that these should be listable via another endpoint, so we should be safe to use the `List` endpoint here.

So rather than switching the Resource to use the Generate endpoint instead, it sounds like the secondary bug is that we should be updating the Data Source to gracefully degrade when we don't have permissions to that endpoint and/or the `admin user` isn't enabled?

**Comment by magodo** [comment]
@tombuildsstuff No, the `listCredentials` gives you the admin password if it is enabled, rather than the user token's password. The user token's password is only accessable in the LRO operation's return (Also see https://github.com/hashicorp/terraform-provider-azurerm/issues/21497)

> updating the Data Source to gracefully degrade when we don't have permissions to that endpoint and/or the admin user isn't enabled

This is already the behavior in earlier and current implementation (for both the acr resource and the data source).

Regarding *recycling the credentials*, since the `generatePassword()` is only invoked in the `Create` and `Update` functions of the `azurerm_container_registry_token_password` resource, so I'm not sure what do you mean by *recycling* here. Also this was the same behavior in v3.51.0.

**Comment by magodo** [comment]
@wortner Can you please paste the full error message, especially want to know the context of: `unexpected status 400 with error: UnAuthorizedForCredentialOperations: Cannot perform credential operations for /subscriptions/REDACTED/resourceGroups/rg/providers/Microsoft.ContainerRegistry/registries/REDACTED as admin user is disabled. Kindly enable admin user as per docs: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account
`, i.e. in which TF resource's which operation.
