### ISSUE TITLE
Support for azurerm_kubernetes_fleet_manager - member

### ISSUE THREAD

**Issue by sn0rlaxlife** [hashicorp/terraform-provider-azurerm#21468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_fleet_manager

Is it possible to have memberid added to attributes so i can provision aks fleet manager with members joined via tf as provisioned? It doesn't appear a option available outside of manually using CLI after creation (bash script)

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_fleet_manager

### Potential Terraform Configuration

```hcl
memberId = azurerm_aks.member_id
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_fleet_manager

**Comment by tillig** [comment]
I'd also buy a new resource like `azurerm_kubernetes_fleet_member` so it can be defined _outside_ of the actual Fleet Manager entity, similar to how you can define subnets for a vnet either _inside_ the vnet or as separate entities. That way I can parameterize the number of workload clusters and have the membership dynamically update rather than having to know up front the number of clusters and embed the membership objects directly.

**Comment by zioproto** [comment]
When this feature was released in preview, Microsoft published examples for the Terraform azapi provider:

* https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/fleets?pivots=deployment-language-terraform
* https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/fleets/members?pivots=deployment-language-terraform

This suggested a future development in a `azurerm_kubernetes_fleet_manager` resource and a `azurerm_kubernetes_fleet_member` resource.

The `azurerm_kubernetes_fleet_manager` was implemented in https://github.com/hashicorp/terraform-provider-azurerm/pull/19111 and it is available since version 3.30.0 of the provider.

The `azurerm_kubernetes_fleet_member` is still missing.

**Comment by dghubble** [comment]
It does seem unusual you can't define members through Terraform and have to use the UI. A member resource could be quite useful and might look like: 

```tf
resource "azurerm_kubernetes_fleet_manager" "example" {
  location            = azurerm_resource_group.example.location
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_kubernetes_fleet_member" "cluster" {
  fleet_manager_id = azurerm_kubernetes_fleet_manager.example.id

  name        = "mycluster"
  aks_cluster = azurerm_kubernetes_cluster.mycluster.id
  ...
}
```

**Comment by stephybun** [comment]
Closed by https://github.com/hashicorp/terraform-provider-azurerm/pull/24792
