### ISSUE TITLE
Cannot create private api management with no virtual network type

### ISSUE THREAD

**Issue by zadigus** [hashicorp/terraform-provider-azurerm#21506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

None

### Terraform Version

1.4.0

### AzureRM Provider Version

3.53.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "apim" {
  name                          = local.apim_name
  location                      = var.location
  resource_group_name           = var.resource_group_name
  publisher_name                = var.publisher_name
  publisher_email               = var.publisher_email
  sku_name                      = var.pricing_tier
  tags                          = var.apim_tags
  public_network_access_enabled = false
  virtual_network_type          = "None"
}
```

### Debug Output/Panic Output

```shell
Error: creating/updating Api Management: (Service Name "<my-service-name>" / Resource Group "<my-resource-group>"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NotSupported" Message="Blocking all public network access by setting property `publicNetworkAccess` of API Management service /subscriptions/<my-subscription-id>/resourceGroups/<my-resource-group>/providers/Microsoft.ApiManagement/service/<my-service-name> is not enabled during service creation."
```

### Expected Behaviour

No error.

Or at least I'd expect another terraform resource that would depend on the one I used to disable the public network access.

### Actual Behaviour

Error: creating/updating Api Management: (Service Name "<my-service-name>" / Resource Group "<my-resource-group>"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NotSupported" Message="Blocking all public network access by setting property `publicNetworkAccess` of API Management service /subscriptions/<my-subscription-id>/resourceGroups/<my-resource-group>/providers/Microsoft.ApiManagement/service/<my-service-name> is not enabled during service creation."

### Steps to Reproduce

```
terraform apply
```

**Comment by zadigus** [comment]
With azure cli, I can create the resource like this:

```
az apim create --name "vbprivateapim" \
  --publisher-email "<my-email>" \
  --publisher-name "<my-name>" \
  --resource-group "<my-resource-group-name>" \
  --location "<my-location>" \
  --sku-name Developer \ 
  --public-network-access false \ 
  --virtual-network None
```

I get no error.

**Comment by sinbai** [comment]
@zadigus thanks for opening this issue. Per the error description, I assume that it is caused by setting `public_network_access_enabled ` to `false`. Also, the error is returned by Azure API instead of Terraform. Could you please set `public_network_access_enabled ` to `true` and try again?

Besides, for the cli above, we could see that the actual value of `publicNetworkAccess` (aka. public_network_access_enabled in Terraform ) is `Enabled`  after creation in the portal, even though `public-network-access` is set to false.
![image](https://user-images.githubusercontent.com/39109137/233824646-a300fd69-5d38-43e3-8cc4-21f2688cd326.png)

![image](https://user-images.githubusercontent.com/39109137/233821530-d949de7f-be5f-4b91-b92a-6f4104eaf0c8.png)

If you are still confused about this, you could contact Microsoft to file an issue in [Azure API repo](https://github.com/Azure/azure-rest-api-specs/issues) for support.

**Comment by zadigus** [comment]
That's true, I did not pay attention to that. Thank you, I'll raise that to the Azure Support.

**Comment by zadigus** [comment]
I opened the following github issue too: https://github.com/Azure/azure-rest-api-specs/issues/23683
