### ISSUE TITLE
Support for azurerm_kubernetes_cluster_addon

### ISSUE THREAD

**Issue by darklight147** [hashicorp/terraform-provider-azurerm#21552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Missing the equivalent of the command:

`az aks enable-addons --addons azure-keyvault-secrets-provider --name myAKSCluster --resource-group myResourceGroup` using terraform

### New or Affected Resource(s)/Data Source(s)

3.52.0

**Comment by stephybun** [comment]
Hi @darklight147,

This is actually already available in the provider under the [`key_vault_secrets_provider`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#key_vault_secrets_provider) block.

Whilst I'd like to thank you for opening this feature request I'm going to close this issue since it is already available.

Thanks!
