### ISSUE TITLE
Unable to import azurerm_virtual_machine - expected the segment "resourcegroups" to be "resourceGroups"

### ISSUE THREAD

**Issue by lukasz-jakubiak** [hashicorp/terraform-provider-azurerm#21605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "SMTPRD-vm" {
    name = var.SMTPRD_vmName
    resource_group_name = data.azurerm_resource_group.prdRG5.name
    location = var.locationPrimary
    vm_size = var.SMTPRD_vmSize
    license_type = "Windows_Server"
    storage_image_reference {
        publisher = "MicrosoftWindowsServer"
        offer = "WindowsServer"
        sku = "2019-Datacenter"
        version = "latest"
    }
    storage_os_disk {
        name = "${var.SMTPRD_vmName}-os"
        caching = "ReadWrite"
        create_option = "Attach"
        managed_disk_id = "/subscriptions/${var.subscription_id}/resourceGroups/${lower(data.azurerm_resource_group.prdRG5.name)}/providers/Microsoft.Compute/disks/${var.SMTPRD_vmName}-os"
        managed_disk_type = "StandardSSD_LRS"
    }
    os_profile {
        computer_name = var.SMTPRD_vmName
        admin_username = "azadmin"
        admin_password = "Pa$$w0rd1234!"
    }
    network_interface_ids = [
        module.SMTPRD-nic.id
    ]
    os_profile_windows_config {
    }
}
```

### Debug Output/Panic Output

```shell
Error: flattening `storage_os_disk`: &errors.errorString{s:"parsing Disk ID \"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/prod/providers/microsoft.compute/disks/vmname-os\": parsing \"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/prod/providers/microsoft.compute/disks/vmname-os\": parsing segment \"staticResourceGroups\": expected the segment \"resourcegroups\" to be \"resourceGroups\""}
```

### Expected Behaviour

VM sholud import

### Steps to Reproduce

terraform import azurerm_virtual_machine.SMTPRD-vm /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/PROD/providers/Microsoft.Compute/virtualMachines/vmname

### References

Similar to issue #19510

**Comment by tombuildsstuff** [comment]
hi @lukasz-jakubiak 

As mentioned in the error message, Terraform is expecting the segment `resourcegroups` to be `resourceGroups`, as such you'll need to update the value for this segment to be able to import this resource. In the documentation for each Resource we have an example of the casing needed to import a given resource, which [in this case can be found here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine).

It's worth calling out that the `azurerm_virtual_machine` resource has been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources and as such is feature-frozen and will be deprecated in a future version of the Provider - so we'd recommend using the Linux/Windows Virtual Machine resource(s) instead.

Since this is a configuration question rather than a bug in the Provider I'm going to close this issue for the moment, but as mentioned above you can fix this by updating the segment value.

Thanks!

**Comment by lukasz-jakubiak** [comment]
Hi @tombuildsstuff 

In resource azurerm_windows_virtual_machine there is no option to "Attach" os-disk, so I need to use azurerm_virtual_machine.
I've checked the configuraion of the disk and there is no section with resourcegroups.
I will review the code once again and try to find the section with this problem.

Thanks!

**Comment by tombuildsstuff** [comment]
hey @lukasz-jakubiak 

Apologies for the confusion on my part here, re-reading the Github issue after submitting my original response I realised this is a Provider issue in the Read function, rather than just an import time issue (which is why I'd deleted my comment/reopened this, rather than marking this as off-topic) - and I've opened #21606 to fix this bug in the Read function, which'll parse the Disk ID case-insensitively in the API response.

Thanks!
