### ISSUE TITLE
azurerm_kubernetes_cluster_extension: The configuration_protected_settings is not created in the release_namespace 

### ISSUE THREAD

**Issue by HannesHil** [hashicorp/terraform-provider-azurerm#21610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.54.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_extension

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_extension" "flux" {
  name           = "gitops-flux"
  cluster_id     = azurerm_kubernetes_cluster.this.id
  extension_type = "microsoft.flux"

  release_namespace = "flux-system"
  configuration_settings = {
    "multiTenancy.enforce" = "false"
  }
  version = "1.7.3"

  configuration_protected_settings = {
    test = "test"
  }
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

The configuration_protected_settings kubernetes secret "protected-ext-parameters-gitops-flux" should be created in the release_namespace "flux-system"

### Actual Behaviour

The configuration_protected_settings kubernetes secret "protected-ext-parameters-gitops-flux"  is created in the "kube-system" namespace

**Comment by HannesHil** [comment]
furthermore the created secret is not deleted if the `configuration_protected_settings` is deleted via terraform

**Comment by stephybun** [comment]
Thanks for raising this issue @HannesHil.

I've taken a look into this and this behaviour appears to stem from the AKS API. The provider isn't specifying which namespace to create the secret in and although one might assume specifying the `target_namespace` or `release_namespace` should influence where it is created, the [MSFT documentation](https://learn.microsoft.com/en-us/azure/aks/deploy-extensions-az-cli#optional-parameters) doesn't explicitly state where the user supplied secrets or configuration are supposed to be created. Furthermore creating and deleting the extension using the Azure CLI with the same configuration yields the same behaviour.

Since this isn't something we can fix in the provider I'm going to close this issue and recommend opening one over on the [AKS repo](https://github.com/Azure/AKS) for clarification and/or fixing.
