### ISSUE TITLE
Queue properties should not be queried while creating a storage account

### ISSUE THREAD

**Issue by sl3dg3hamm3r** [hashicorp/terraform-provider-azurerm#21650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.53.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example" {
  name                = "stmystorageaccountexample"
  resource_group_name = "my-rg"

  location                 = "northeurope"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  access_tier = "Hot"
  account_kind = "StorageV2"
}
```

### Debug Output/Panic Output

```shell
# When there is a DNS entry (private IP) in place for queues (same does not apply for shares/blob), like e.g. in /etc/hosts (or in any company DNS resolver):  
# 192.168.0.0 stmystorageaccountexample.queue.core.windows.net


Error: reading queue properties for AzureRM Storage Account "stmystorageaccountexample": queues.Client#GetServiceProperties: Failure sending request: StatusCode=0 -- Original Error: context canceled
```

### Expected Behaviour

The Storage Account should be created, independent from any private DNS entry for the storage queues.

The idea is
- Create storage queue
- Create private endpoint with IP according to DNS entry, connected with queues
- Create queue

### Actual Behaviour

The Storage Account can't be created when there is a DNS entry for storage queues, due to timeout. Fun fact: The Storage Account is actually created and can be queried in the portal, but Terraform quits with error like described in Debug Output/Panic Output.

### Steps to Reproduce

Make an entry in /etc/hosts: 192.168.0.0 stmystorageaccountexample.queue.core.windows.net

terraform init
terraform apply

**Comment by tombuildsstuff** [comment]
hi @sl3dg3hamm3r 

Thanks for opening this issue.

Unfortunately in order to track changes to the properties supported by the fields on the `azurerm_storage_account` resource, we require that we retrieve these properties from the Data Plane API since this is the only location where all of these can be obtained - else we'd be unable to detect when changes have occurred to these fields, which is a core Terraform feature.

#2977 is tracking a feature request to query the Resource Manager API for this information, however unfortunately it's blocked on the Storage Service Team since the Resource Manager API doesn't expose all of the information needed.

Since this feature request is being tracked in #2977, rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #2977, but would you mind subscribing to that issue for updates?

Thanks!
