### ISSUE TITLE
Support for changing VM Size on node pool

### ISSUE THREAD

**Issue by SOFSPEEL** [hashicorp/terraform-provider-azurerm#21859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to be able to resize vm's on **azurerm_kubernetes_cluster_node_pool** https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool using the same **temporary_name_for_rotation** technique  to the way they are resized on the Default Node Pool here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#temporary_name_for_rotation

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "aks" {
  lifecycle {
    ignore_changes = [
      node_count
    ]
  }
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks.id
  name                  = "appspool1"
  node_count            = module.settings.aks_agent_count
  vm_size               = module.settings.aks_apps_pool_vm_size
  temporary_name_for_rotation = "temppool"
  os_disk_size_gb       = module.settings.aks_agent_os_disk_size
  vnet_subnet_id        = data.azurerm_subnet.subnet.id
  enable_auto_scaling   = module.settings.aks_agent_auto_scaling_enable
  min_count             = module.settings.aks_agent_min_count
  max_count             = module.settings.aks_agent_max_count
  node_labels = {
    "nodepool-type" = "user"
    "nodepoolos"    = "linux"
    "app"           = "aspnetcore"
  }
}
```

**Comment by ms-henglu** [comment]
Hi @SOFSPEEL ,

Thank you for taking time to open this issue.

Unfortunately, the ` temporary_name_for_rotation` technique is not applicable in the node pool resizing. Because when default node pool's vmsize changes, azurerm provider creates a temporary default node pool, then delete the old default node pool, then create the new default node pool with new vm size, and remove the temporary node pool. It seems that the behavior is very similar to what happens when node pool's vm size changes and forces it to re-create.

I'm not sure whether this `create_before_destroy = true` meta-argument can help in this case: https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#create_before_destroy
Because it changes this behavior so that new replacement object is created first, and the prior object is destroyed after the replacement is created.

**Comment by stephybun** [comment]
Thanks for raising this issue @SOFSPEEL - another request for this just came in with a more generic title. So that we don't have multiple issues tracking the same thing I'm going to close this issue in favour of #22265. Please subscribe to #22265 for updates.
