### ISSUE TITLE
Migrate from azurerm_app_service to azurerm_windows_web_app

### ISSUE THREAD

**Issue by DimitarSotirov7** [hashicorp/terraform-provider-azurerm#22127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I have an existing App Service in Azure which is created from Terraform single file script using 'azurerm_app_service' type. I am starting using modules and want to import the app service in the modules script file in the 'azurerm_windows_web_app' type. However, in the state file there's no instance created.

### Description

I have an existing App Service in Azure which is created from Terraform single file script using 'azurerm_app_service' type. I am starting using modules and want to import the app service in the modules script file in the 'azurerm_windows_web_app' type. However, in the state file there's no instance created.

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
