### ISSUE TITLE
Microsoft.Insights │ The parsed Resource ID was missing a value for the segment at position 5 | parsing segment "staticMicrosoftInsights": expected the segment "microsoft.insights" to be "Microsoft.Insights

### ISSUE THREAD

**Issue by sunkaris** [hashicorp/terraform-provider-azurerm#22138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.0

### AzureRM Provider Version

3.60.0

### Affected Resource(s)/Data Source(s)

azurerm_application_insights_standard_web_test

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights_standard_web_test" "avail_test" {
  name                    = "availxxxx"
  location                = "northeurope"
  resource_group_name     = azurerm_resource_group.app.name
  application_insights_id = azurerm_application_insights.appi.id
  retry_enabled           = true
  timeout                 = 120
  frequency               = 600
  enabled                 = true
 
  # Locations obtained here: https://learn.microsoft.com/en-us/previous-versions/azure/azure-monitor/app/monitor-web-app-availability#location-population-tags
  geo_locations = [
    "emea-ru-msa-edge",
    "emea-nl-ams-azr",
    "emea-se-sto-edge",
    "emea-gb-db3-azr",
    "emea-fr-pra-edge",
  ]
 
  request {
    url = each.value
    http_verb = "GET"
    parse_dependent_requests_enabled = true
    follow_redirects_enabled = true
  }
 
  validation_rules {
    expected_status_code        = 200
    ssl_cert_remaining_lifetime = 30
    ssl_check_enabled           = true
  }

 }
```

### Debug Output/Panic Output

```shell
│ Expected a Component ID that matched:
│
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Insights/components/componentValue


 However, this value was provided:

│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/----microsoft.insights---(ignore ----)/components/componentValue
```

### Expected Behaviour

│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Insights/components/componentValue

### Actual Behaviour

parsing segment "staticMicrosoftInsights": expected the segment "microsoft.insights" to be "Microsoft.Insights"

### Steps to Reproduce

terraform apply  -target='azurerm_application_insights_standard_web_test.avail_test'

### References

Looks like this issue is addressed in 3.56.0. I still see the same error with 3.56.0  and 3.60.0
https://github.com/hashicorp/terraform-provider-azurerm/pull/21725

**Comment by tombuildsstuff** [comment]
hi @sunkaris 

Thanks for opening this issue - taking a look at the error message being returned here:

```
│ Expected a Component ID that matched:
│
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Insights/components/componentValue


 However, this value was provided:

│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/----microsoft.insights---(ignore ----)/components/componentValue
```

It appears that the Resource ID used for the Application Insights resource uses the incorrect casing for the `microsoft.insights` segment which is the problem here, whilst previously this resource wasn't validating this at import time, this has been defined in the `import` section of the documentation for this resource - as such we're expecting that the Resource ID for this resource matches the format defined above.

As for how this happened, I'd wager that the Application Insights resource was imported into Terraform, and whilst we weren't previously validating that this Resource ID segment matched exactly, we're now doing so (and validating where we expect an Application Insights Resource ID that one is being specified) to avoid this type of issue going forwards.

In this case it should be possible to workaround this by updating the Resource ID used for the Application Insights resource by removing it from the Terraform State (`terraform state rm azurerm_application_insights.example`) and then re-importing it (`terraform import azurerm_application_insights.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Insights/components/instance1`) - would you be able to take a look and see if that works for you?

Since this will be fixed by updating the Resource ID of the parent Application Insights resource, I'm going to close this issue for the moment - however if that doesn't work for you then please let us know and we can take another look.

Thanks!

**Comment by sunkaris** [comment]
Thanks @tombuildsstuff this worked for me.
