### ISSUE TITLE
Transition to Azure Load Testing GA API versions 

### ISSUE THREAD

**Issue by JamesDLD** [hashicorp/terraform-provider-azurerm#22172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Load Testing preview API versions will be retired on 10 September 2023 – transition to Azure Load Testing GA API versions.

As of 1 February 2023, Azure Load Testing is generally available. We’ve updated Azure Load Testing API versions, which are now generally available.

The preview versions of the Azure Load Testing APIs will be retired on 10 September 2023:

    Resource Manager 2021-12-01-preview
    Resource Manager 2022-04-15-preview
    Data Plane 2022-06-01-preview
    Data Plane 2021-07-01-preview

To avoid potential service disruptions, you’ll need to update your templates, tools, scripts, and programs, to use a newer API version. The following are the generally available versions of API:

    Resource Manager 2022-12-01
    Data Plane 2022-11-01

The GO client seems concerned because it uses API version 2022-12-01 (check [client_gen.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/loadtestservice/client/client_gen.go))
```
import (
	"github.com/Azure/go-autorest/autorest"
	loadtestserviceV20221201 "github.com/hashicorp/go-azure-sdk/resource-manager/loadtestservice/2022-12-01"
	"github.com/hashicorp/terraform-provider-azurerm/internal/common"
)
```

Any API calls still using the older versions after 10 September 2023 will stop working until you've updated them. For more information, please refer to the REST API documentation [here](https://learn.microsoft.com/en-us/rest/api/loadtesting/?WT.mc_id=DOP-MVP-5003548).

### New or Affected Resource(s)/Data Source(s)

azurerm_load_test

### References

- [client_gen.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/loadtestservice/client/client_gen.go)

**Comment by tombuildsstuff** [comment]
hey @JamesDLD 

Thanks for opening this issue.

The Azure Provider's recently updated to use the latest stable API Version (`2022-12-01`) from the older Preview API version [as of version `3.60.0` of the Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#3600-june-08-2023) - as such you'll need to update to `v3.60.0` of the Azure Provider or above to make use of this API version.

Since this functionality is already supported and can be used by updating to the latest version of the Azure Provider, I'm going to close this issue for the moment - but that should be all that's needed here 👍 

Thanks!
