### ISSUE TITLE
Support for Managed Grafana dashboard provisioning in azurerm_dashboard_grafana

### ISSUE THREAD

**Issue by xiaopeng163** [hashicorp/terraform-provider-azurerm#22206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

could we support dashboard provisioning when create managed grafana instance with Terraform?

 https://grafana.com/docs/grafana/latest/administration/provisioning/

### New or Affected Resource(s)/Data Source(s)

azurerm_dashboard_grafana

**Comment by jiaweitao001** [comment]
Hi @xiaopeng163 , thanks for opening this issue. Terraform resource is created based on the API provided by the owner team of the service, unfortunately provisioning is not part of the API provided. Moreover, Terraform is supposed to be used to manage the resource itself instead of its status. We will not support dashboard provisioning for now. Thank you.
