### ISSUE TITLE
I can't find an argument to enable encryption for azure virtual network 

### ISSUE THREAD

**Issue by vi-malii** [hashicorp/terraform-provider-azurerm#22235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, I have to enable encryption in my azure virtual network. 
I go through a documentation (https://registry.terraform.io/providers/hashicorp/azurerm/3.61.0/docs/resources/virtual_network) and I see there's not any argument that I can use for this case. 
Is it possible to enable it somehow or maybe I do something wrong ?
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/33558148/e1f8a2d7-3d0f-4d78-afc9-b91f7d7941af)

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_network

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network" "virtual_network" {
  ...
  encryption_enabled = true
}
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
