### ISSUE TITLE
Support for specifying subscription id for azurerm_cost_anomaly_alert resource

### ISSUE THREAD

**Issue by fleetwoodstack** [hashicorp/terraform-provider-azurerm#22357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the scope can't be specified when creating an azurerm_cost_anomaly_alert resource and it defaults to the current subscription id (metadata.Client.Account.SubscriptionId).

This makes this useless for users with multiple subscriptions in Azure who want to monitor cost anomolies across their subscriptions.

Since cost anomolies are restricted to subscriptions, it would be great to add a field such as subscriptionid so we can add these for multiple subscriptions.  

### New or Affected Resource(s)/Data Source(s)

azurerm_cost_anomaly_alert

### Potential Terraform Configuration

```hcl
resource "azurerm_cost_anomaly_alert" "example" {
  name            = "alertname"
  display_name    = "Alert DisplayName"
  email_subject   = "My Test Anomaly Alert"
  email_addresses = ["example@test.net"]
  subscription_id = "0a5512e7-ca60-4bde-97e3-514207f4e659"
}
```

**Comment by tombuildsstuff** [comment]
hi @fleetwoodstack 

Thanks for opening this issue.

The architecture of the Terraform Provider assumes a 1:1 mapping between a Provider Instance and a Subscription - as such unfortunately we aren't planning to support configuring the `subscription_id` against individual resources since this would break this assumption.

However Terraform offers native support for [Provider Aliases which are designed for this purpose](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations), which would allow you to achieve this in a slightly different manner - for example:

```hcl
provider "azurerm" {
  alias  = "first"
  subscription_id = "00000000-0000-0000-0000-000000000000"
}
provider "azurerm" {
  alias  = "second"
  subscription_id = "11111111-1111-1111-1111-111111111111"
}

resource "azurerm_cost_anomaly_alert" "first" {
  name            = "alertname"
  display_name    = "Alert DisplayName"
  email_subject   = "My Test Anomaly Alert"
  email_addresses = ["example@test.net"]
  provider        = azurerm.first
}

resource "azurerm_cost_anomaly_alert" "second" {
  name            = "alertname"
  display_name    = "Alert DisplayName"
  email_subject   = "My Test Anomaly Alert"
  email_addresses = ["example@test.net"]
  provider        = azurerm.second
}
```

Since we don't plan to support configuring the `subscription_id` against individual Resources, whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment - however as mentioned above I believe you should be able to achieve this (albeit in a slightly different manner) using Provider Aliases.

Thanks!

**Comment by fleetwoodstack** [comment]
I see thanks for the response. That's a damn shame as this forces users of this resource to duplicate code unnecessarily - when a for_each would be much more manageable.
