### ISSUE TITLE
azurerm_virtual_machine ordering of identity_ids changes every plan and forces modifications

### ISSUE THREAD

**Issue by nrjohnstone** [hashicorp/terraform-provider-azurerm#22481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.2

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
Create 3 user managed identities.

Create a simple virtual machine and assign the three identities in the identity_ids array block.

Run the apply, then run a plan.

Most (but not all !) of the time you will still see that the order of the identity ids has changed and it needs more changes !
```

### Debug Output/Panic Output

```shell
No debug output
```

### Expected Behaviour

The order of the identity_ids should either be preserved (hard to do, since I assume its the Azure API responsible here) or the comparison in the plan should be smarter to not care about the order and only check that the content is the same.

### Actual Behaviour

The order appears to be randomly swapped after an apply. Even if you update the terraform code to match the same order, there is no guarantee that the next plan will not have a different order again !!

**Comment by donpeone** [comment]
I have similar issue. Terraform v1.5.2, azurerm v 3.64

**Comment by tombuildsstuff** [comment]
hi @nrjohnstone 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 3.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but you should be able to fix this issue by migrating to the replacement [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources.

Thanks!

**Comment by nrjohnstone** [comment]
I'll give it a try @tombuildsstuff but from memory there was an issue with the way the disks and tagging worked last time I tried to migrate, but that was a few months ago now
