### ISSUE TITLE
Unable destroy the resources in azure 

### ISSUE THREAD

**Issue by Dora-hema** [hashicorp/terraform-provider-azurerm#22514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.5

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

PCAF_Aggregation_Calculation_Global

### Terraform Configuration Files

```hcl
NA
```

### Debug Output/Panic Output

```shell
Error: deleting Data Flow: (Name "PCAF_Aggregation_Calculation_Global" / Factory Name "testsai2DataFactory" / Resource Group "ADF_testsai2"): datafactory.DataFlowsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The document cannot be deleted since it is referenced by PCAF_Calculation." Target="/subscriptions/71fa8945-b1cc-4942-bcac-7c3a1523113c/resourceGroups/ADF_testsai2/providers/M
```

**Comment by mybayern1974** [comment]
@Dora-hema thank you for opening this issue. Could you please provide more details otherwise it's hard to troubleshoot in terms of trying to repro first. As one important part of required contexts, please provide your Terraform config files that include Azure resources managed by Terraform AzureRM provider.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately, we need the configuration details in order to troubleshoot this issue. I am going to close this issue, since time has already passed without a response, please update this issue with a more complete configuration so that we are able to work on reproducing this and we can reopen the issue.
