### ISSUE TITLE
azurerm_mysql_flexible_server zone flag is not optional like the documentation state

### ISSUE THREAD

**Issue by maisyk** [hashicorp/terraform-provider-azurerm#22529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.2

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "foo"
  location = "eastus"
}

resource "azurerm_mysql_flexible_server" "mysql" {
  name                   = "foomysql"
  resource_group_name    = azurerm_resource_group.rg.name
  location               = azurerm_resource_group.rg.location
  version                = "8.0.21"
  sku_name               = "B_Standard_B1ms"
  administrator_login    = "foo"
  administrator_password = "bar"
  tags                   = var.tags
}
```

### Debug Output/Panic Output

```shell
# azurerm_mysql_flexible_server.mysql_server will be updated in-place
~ resource "azurerm_mysql_flexible_server" "mysql_server" {
    id                            = "/subscriptions/XXXXX/resourceGroups/XXXX/providers/Microsoft.DBforMySQL/flexibleServers/XXX"
    name                          = "XXXXX"
    tags                          = {
        "created_by" = "terraform"
        ...
    }
  - zone                          = "3" -> null
    # (14 unchanged attributes hidden)

    # (1 unchanged block hidden)
}
```

### Expected Behaviour

According to the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server), the zone attribute of the _azurerm_mysql_flexible_server_ resource is optional. When not explicitly set in the Terraform configuration, it should retain its default value of 3 (based on my experimentation). Therefore, when re-running `terraform apply` without any modifications to the _azurerm_mysql_flexible_server_ resource, the zone attribute should remain unchanged and retain the default value of 3.

### Actual Behaviour

Upon running terraform apply without any modifications to the _azurerm_mysql_flexible_server resource_, the `zone` attribute is unexpectedly being updated to `null` instead of retaining the default value of `3`. 

This behavior contradicts the documentation, which states that the zone attribute is optional. The issue leads to inconsistent behavior and unexpected changes during subsequent Terraform runs, even when no modifications are made to the resource.

### Steps to Reproduce

Simply create a azurerm_mysql_flexible_server resource without specifying the `zone` property

```
provider "azurerm" {
  features {}
}

resource "azurerm_mysql_flexible_server" "mysql_dbs" {
  name                   = "mydbs"
  resource_group_name    = "foo"
  location               = "bar"
  version                = "8.0.21"
  sku_name               = "B_Standard_B1ms"
  administrator_login    = "foo"
  administrator_password = "bar"
  tags                   = var.tags
}
```

Then simply re-run `terraform apply` once the resource has been created. You should see something like this in your terminal:

```
# azurerm_mysql_flexible_server.mysql_server will be updated in-place
~ resource "azurerm_mysql_flexible_server" "mysql_server" {
    id                            = "/subscriptions/XXXXX/resourceGroups/XXXX/providers/Microsoft.DBforMySQL/flexibleServers/XXX"
    name                          = "XXXXX"
    tags                          = {
        "created_by" = "terraform"
        ...
    }
  - zone                          = "3" -> null
    # (14 unchanged attributes hidden)

    # (1 unchanged block hidden)
}
```

**Comment by tombuildsstuff** [comment]
hey @maisyk 

Thanks for opening this issue.

This field is marked as `Optional` since it's possible to use this in one of 2 ways:

1. Specify this field, to deploy this Flexible Server into the specified Availability Zone
2. Omit this field and allow the Azure API to determine which Availability Zone this should be deployed into.

Whilst we'd typically recommend the first approach there (since it means you're aware of which Availability Zone the given resource is being deployed into) - the second approach allows for more flexibility, however will flag as a diff (as you're seeing) when the field isn't ignored via the `ignore_changes` feature (which will use the Azure provided value, and not mark this as a change).

Taking a look through here, it appears that whilst this is called out in the documentation for the PostgreSQL Flexible Server resource, it's not called out for the MySQL Flexible Server resource - as such I've opened #22531 which'll fix this, but as mentioned above you should be able to work around this by using [Terraform's `ignore_changes` feature](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) to ignore the change to the `zone` and `standby_availability_zone`, which'll use the Azure provided values.

Thanks!
