### ISSUE TITLE
azurerm_key_vault_access_policy should accept "All" for certificate/key/secret permissions

### ISSUE THREAD

**Issue by mwalser** [hashicorp/terraform-provider-azurerm#22533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The `azurerm_key_vault_access_policy` resource currently does not accept `all` for certificates, keys, secrets and storage permissions:

> Error: expected key_permissions.0 to be one of [Backup Create Decrypt Delete Encrypt Get Import List Purge Recover Restore Sign UnwrapKey Update Verify WrapKey Release Rotate GetRotationPolicy SetRotationPolicy], got **all**

According to the [Azure Documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults/accesspolicies?pivots=deployment-language-bicep#permissions) its a valid value.

This makes writing an access policy that enables every permission cumbersome. Also, it leads to existing access policies that use the `all` permission being destroyed on import because a change is detected.

### New or Affected Resource(s)/Data Source(s)

azurerm_key_vault_access_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_access_policy" "admin" {
  key_vault_id = azurerm_key_vault.keyvault.id
  tenant_id    = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  object_id    = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

  certificate_permissions = ["All"]
  key_permissions = ["All"]
  secret_permissions = ["All"]
  storage_permissions = ["All"]
}
```

### References

* https://learn.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults/accesspolicies?pivots=deployment-language-bicep#permissions

**Comment by tombuildsstuff** [comment]
hi @mwalser 

Thanks for opening this issue.

Unfortunately the behaviour of the Azure API is inconsistent here, whilst it has historically supported sending the value `all`, this is transformed into a list of permissions once the Access Policy is created/updated - which causes a diff when the value `All` is used within Terraform.

From memory, we reached out to the Service Team about this previously and were informed that the `all` value is deprecated (since it's recommended to use more limited permissions) and was subject to removal in the future - which coupled with the behaviour above is why we don't expose this value at this time.

Instead, the Provider offers [the `azurerm_key_vault_access_policy` data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_access_policy which'll provide the default permissions for each block as defined in the Portal - which should reduce the configuration lines needed here. Would you be able to take a look and see if that works for you instead?

Thanks!

**Comment by mwalser** [comment]
Hi @tombuildsstuff, thanks for the explanation. It "all" is deprecated it makes sense not to implement it. The `azurerm_key_vault_access_policy` data source is really neat, thanks for pointing that out.

I'll go ahead and close the issue. Once again, thanks for your quick answer, I really appreciate it!
