### ISSUE TITLE
Allow a Service Principal with no subscription

### ISSUE THREAD

**Issue by g13013** [hashicorp/terraform-provider-azurerm#22847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.68.0

### Affected Resource(s)/Data Source(s)

azurerm_management_group

### Terraform Configuration Files

```hcl
provider "azurerm" {
    features {}

    client_id       = "XXXX"
    client_secret   = "XXXX"
    tenant_id       = "XXXX"
    skip_provider_registration = true
}
```

### Debug Output/Panic Output

```shell
Error: building account: unable to configure ResourceManagerAccount: subscription ID could not be determined and was not specified
```

### Expected Behaviour

I expect azurerm to allow the use of a Service Principal that has minimum permissions to create the management groups. When using `az login --allow-no-subscription  --service-principal` with the service principal and then apply terraform it works as expected, but using the same service principal with terraform directly without az login, it issues an error even with the use of `skip_provider_registration`

### Actual Behaviour

`skip_provider_registration` is ignored when using a service principle that has no permissions on any subscription.

### References

We are working on the provisioning of an entire structure on Azure starting with the creation of management groups, assigning subscriptions and then deploying resources. The problem is that the Service Principal we are using might not have any permission on any existing subscription or even a tenant without any subscription.

**Comment by tombuildsstuff** [comment]
hey @g13013 

Thanks for opening this issue.

Whilst the AzureAD Provider supports authenticating without specifying a Subscription ID - the AzureRM Provider has a 1:1 relationship between a provider instance and a subscription, which forms the basis of a number of assumptions within the provider (for example around caching) and is used in virtually all resources at this point in time (to build the Resource ID for the Resource).

This means that the `subscription_id` field is pretty heavily relied on across the Provider (and is becoming more so over time, rather than less so) - as such unfortunately I think it's unlikely that we'd look to make this field optional rather than required at this point in time, due to the volume of changes needed to make that happen.

Since this isn't something we plan to support at this point in time, whilst I'd like to thank you for opening this feature request, I'm going to close this feature request for the moment. That said, using a bootstrap script to create the prerequisites (e.g. to generate the Service Principal/creds and an empty Subscription [which comes by default with most types of EA's/Microsoft Accounts etc) would probably be the next best thing here?

Thanks!

**Comment by g13013** [comment]
@tombuildsstuff Thank you for the response. Even though I am not convinced this is the right thing, because we still don't need the subscription with certain resources and API calls `skip_provider_registration` should take precedence over the `subscription_id`. 

Nonetheless I was able to find a solution myself by providing an invalid zeroed subscription id `00000000-0000-0000-0000-000000000000` along with   `skip_provider_registration` which is odd and not "very clean".

Thank you anyway for taking the time.

**Comment by g13013** [comment]
> as such unfortunately I think it's unlikely that we'd look to make this field optional rather than required at this point in time, due to the volume of changes needed to make that happen.

With my solution above, introducing a simple param `allow_no_subscription` in contrast to the cli option `--allow-no-subscription` and then checking 

```go
// somewhere in the init code, sorry I don't have any experience with terraform native plugins internals.
if (options.allow_no_subscription) {
    options.subscription_id = "00000000-0000-0000-0000-000000000000"
    options.skip_provider_registration = true
}
```
This solution will allow the provider to support all scenarios without any side effect on the existing implementation while allowing covering edge cases especially where permissions are lacking. Please reconsider.
