### ISSUE TITLE
The parsed Resource ID was missing a value for the segment at position 2 │ (which should be the literal value "resourceGroups").

### ISSUE THREAD

**Issue by sylvain-n8n** [hashicorp/terraform-provider-azurerm#22881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.15.5

### AzureRM Provider Version

3.68.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "<PoolValue>" {
  name                  = "<agentPoolValue>"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.<cluster-name>.id
  vm_size               = "Standard_E2s_v4"
  node_count            = 15
  max_pods              = 110
  os_disk_size_gb       = 32
  enable_auto_scaling   = false
  vnet_subnet_id        = module.vnet.vnet_subnets[3]
  node_labels = {
    nodetype = "<PoolValue>"
  }
  node_taints          = ["dedicated=<PoolValue>:NoSchedule"]
  orchestrator_version = "1.26.3"
  upgrade_settings {
    max_surge = 1
  }

  tags = local.common_tags
}
```

### Debug Output/Panic Output

```shell
│ Error: parsing "/subscriptions/<subscription-id>/resourcegroups/<resource-group>/providers/Microsoft.ContainerService/managedClusters/<managedClusterValue>/agentPools/<agentPoolValue>": parsing segment "staticResourceGroups": parsing the AgentPool ID: the segment at position 2 didn't match
│
│ Expected a AgentPool ID that matched:
│
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.ContainerService/managedClusters/managedClusterValue/agentPools/agentPoolValue
│
│ However this value was provided:
│
│ > /subscriptions/<subscription-id>/resourcegroups/<resource-group>/providers/Microsoft.ContainerService/managedClusters/<managedClusterValue>/agentPools/<agentPoolValue>
│
│ The parsed Resource ID was missing a value for the segment at position 2
│ (which should be the literal value "resourceGroups").
│
│
│
│   with azurerm_kubernetes_cluster_node_pool.<PoolValue>,
│   on aks.tf line 93, in resource "azurerm_kubernetes_cluster_node_pool" "<PoolValue>":
│   93: resource "azurerm_kubernetes_cluster_node_pool" "<PoolValue>" {
│
╵
```

### Expected Behaviour

The provider should accept  `resourcegroups` and `resourceGroups` on the generated resource id. Since Azure can have both.

### Actual Behaviour

If Azure has a resource ID generated with this resource group like so: `resourcegroups` it fails to continue as it only accepts `resourceGroups` .

I can only confirm that this was not an issue in v2.97.

### Steps to Reproduce

Hard to reproduce since you would need azure to have that issue. (I assume it comes from an old resource)

### References

It looks like the issue was discussed here, but I am not sure what happened to the resolution of it. It's not working in the latest version.

https://github.com/hashicorp/terraform-provider-azurerm/issues/18210

**Comment by tombuildsstuff** [comment]
hey @sylvain-n8n 

Thanks for opening this issue.

The Resource ID for a resource within Terraform and the Resource ID for a Resource within the Azure API can differ slightly - as such we define the Resource ID format that we're expecting [in the `import` section of the documentation for the associated resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool#import).

Based on the issue description above, it appears this resource was previously imported into Terraform but used the incorrect casing for the `resourceGroups` segment - whilst older versions of the Provider unintentionally accounted for this, newer versions now validate that all of the Static segments within the Resource ID match the casing we're expecting.

Unfortunately the casing of Resource IDs within Azure is an extremely complex topic, with differing sets of guidance - however the ARM Specification states that the Keys within the Resource ID (e.g. `subscriptions` and `resourceGroups` [etc] for `/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Example/things/{}`) should be case-sensitive but the values should be compared insensitively. Equally the ARM Specification states that Azure API's should be case-insensitive in requests but case-sensitive in responses - which is inconsistently implemented across the API.

This is part of why Terraform is moving towards defining it's own Resource IDs (as outlined above) which use the canonical casing for each Resource (the ARM Specification also states that keys should be `camelCased`, for example) - which is why we're validating these match as we expect when parsing.

In this case you should be able to resolve this by removing this from your state using `terraform state rm azurerm_kubernetes_cluster_node_pool.<PoolValue>` and then re-importing it using `terraform import azurerm_kubernetes_cluster_node_pool.<PoolValue> [updated id with resourceGroups]` - would you be able to take a look and see if that works for you?

Thanks!

**Comment by sylvain-n8n** [comment]
@tombuildsstuff I see, I did try this but it showed cluster re-creation. I assumed that was the wrong approach. 

But the cluster re-creation comes with another settings that defaults to true (rbac) when I update. 

So, what you mention here worked.

Thank  a lot !

**Comment by nighthawk4life24** [comment]
I'm also getting the same error relating to case sensitive " resource group " but with the azurerm_kubernetes_cluster resource. Using latest TF , provider and tf 1.5 import block. 

Is there a fix for this.
