### ISSUE TITLE
Support for annotating resources with git sha

### ISSUE THREAD

**Issue by gzur** [hashicorp/terraform-provider-azurerm#22880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Background:
For organisations and teams using Terraform and Git for infrastructure-as-code (IaC), it is crucial to trace back which specific git commit made modifications to a given resource. This aids in debugging, auditing, and improves overall transparency.

### Goal: 
Provide a clear reference between cloud resources and the `git sha` that provisioned or modified it.

### Problem Statement:
Currently, there's no out-of-the-box way in the AzureRM Terraform Provider to link a cloud resource to the specific git commit that caused its creation or modification.

### Proposed Solutions:

1. **Azure Resource Tags**:
    - Use [Azure resource tags](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources) to store the `git sha`.
    - Challenge: Not all resources support tags, making this solution not universally applicable.

2. **State File Annotation**:
    - Embed the `git sha` in the Terraform state file for each resource.
    - This approach may be more opaque, but it ensures every resource can be traced back to a git commit.

### Additional Notes:
- This feature should be opt-in since there's no assurance that the runtime environment provisioning the infrastructure has access to the `git` repo storing the Terraform manifests.

### New or Affected Resource(s)/Data Source(s)

`provider`

### Potential Terraform Configuration

```hcl
## Potential Terraform Configuration


provider "azurerm" {
  features {}
  annotate_with_git_sha = true  # opt-in flag to enable the git sha feature
}

resource "azurerm_virtual_machine" "example" {
  # ... other config ...
  # No need to mention git_sha here as it's handled at the provider level
}

}
```

**Comment by tombuildsstuff** [comment]
hey @gzur 

Thanks for opening this issue.

Whilst `git` is a popular SCM system, unfortunately it isn't ubiquitous and every organisation has slightly different requirements (including some being explicit about _which_ tag keys are allowed to be configured via an Azure Policy or otherwise) - in addition some Azure API's have similar constraints, limit the number of tags and in cases the casing too.

As such unfortunately this isn't something we'd be able to add as a tag to different resources, and due to the way the Terraform Protocol works the Provider itself doesn't have the means of setting this type of field in the state - as such this isn't something we could feasibly do at this point in time (even if there were a means of making this work across all organisations).

In addition the source revision also doesn't necessarily contain the full information needed there, due to the way the Azure API works (for example, provisioning an HDInsights or AKS Cluster provisions those resources using an ARM Template on the backend from a given point-in-time) - as such it's also down to the individual API being used too.

As such whilst I'd like to thank you for opening this feature request, unfortunately this isn't something we'd be able to implement within the Provider itself and as such I'm going to close this feature request for the moment - however I'd suggest that this type of information could be surfaced through Terraform Cloud, as such I'd recommend reaching out to Terraform Cloud support who should be able to point you in the right direction here.

Thanks!

**Comment by gzur** [comment]
Thanks for taking the time to answer. 

---

> due to the way the Terraform Protocol works the Provider itself doesn't have the means of setting this type of field in the state 

I was wondering about exactly this. Thanks for clearing it up.
