### ISSUE TITLE
Support for [encryption of state files]

### ISSUE THREAD

**Issue by MichalKoziorowski-TomTom** [hashicorp/terraform-provider-azurerm#23184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I would like to be able to encrypt terraform state files. Something similar is possible by gcs backend: https://developer.hashicorp.com/terraform/language/settings/backends/gcs#encryption

Terraform state files often contain plain text passwords

### New or Affected Resource(s)/Data Source(s)

azurerm_backend

### References

https://developer.hashicorp.com/terraform/language/settings/backends/gcs#encryption

**Comment by rcskosir** [comment]
@MichalKoziorowski-TomTom Thank you for taking the time to open this issue. We organize issues relating to the azurerm backend in the [Terraform Core Repo](https://github.com/hashicorp/terraform) since that is where the code resides. As such I am going to mark this issue as closed. 
There are some related already existing issues and PRs over in that repo [here](https://github.com/hashicorp/terraform/pull/29289). I encourage you to take a look through that PR and the other issues and PRs linked on it to see if that covers your support request. If not, feel free to open this support request in the [Terraform Core Repo](https://github.com/hashicorp/terraform).
