### ISSUE TITLE
Support for using an oauth token without the client secret and id

### ISSUE THREAD

**Issue by stolo** [hashicorp/terraform-provider-azurerm#23215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Requesting support to use an Oauth token in a system without the client secret and id.  This would allow a separate service to handle the secret and retrieve tokens for the terraform module to use.  The terraform would not have access to the secret in this scenario.  This would be similar to the OIDC configuration but instead of an OIDC token, the provider would use an OAUTH Client Credentials token.  Thanks for considering this :) 

### New or Affected Resource(s)/Data Source(s)

azurerm_*

### Potential Terraform Configuration

```hcl
export ARM_OAUTH_TOKEN=<token>

or

provider "azurerm" {
  features {}

  oauth_token = var.oauth_token
}
```

**Comment by gbordier** [comment]
This would be really useful and would also solve another scenario where azapi provider which relies on azurerm will fail when triggered after a long terraform resource creation (> 10 min) with azdevops since it will try to re-acquire a  bearer token from the original OIDC token which has now expired.

**Comment by tombuildsstuff** [comment]
hey @stolo @gbordier 

Whilst we support OIDC we require the ability to refresh the token given that it's possible for a deployment to take longer than a refresh is valid for - and as such unfortunately we have no plans to introduce support for passing in a token with an expiration assigned to it. It's worth noting that we need access tokens both for the Resource Manager API (that is `management.azure.com`, by default) and any data-plane APIs too (keyvault, storage, etc) - all of which come with their own expiry time - and in the future we'd like to consider reducing the scope of those tokens where possible - which wouldn't be possible given this scenario.

The Azure DevOps scenario described by @gbordier is ultimately a product limitation of Azure DevOps rather than something the Provider can workaround - as such I'd suggest raising a feature request with the Azure DevOps folks and/or switching to use a different authentication mechanism to workaround that, since resource provisioning can take a varied amount of time (and exceed 10 minutes).

However unfortunately since we've got no plans to support providing a client credentials token, whilst I'd like to thank you for opening this issue - I'm going to close this issue for the moment.

Thanks!

**Comment by gbordier** [comment]
thanks, it looks like the auth provider for the go azure sdk has this capability https://github.com/hashicorp/go-azure-sdk/blob/2fc034009010ae90461a4154866683ab2d40b605/sdk/client/client.go
