### ISSUE TITLE
Terraform resource for creating routing policies and routing intent in azure virtual Hub

### ISSUE THREAD

**Issue by selvanayaki678** [hashicorp/terraform-provider-azurerm#23222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Is any terraform resource available for creating routing intent and routing policies for Azure virtual hub 

I couldn't any resource that is available for this feature. 

https://learn.microsoft.com/en-us/azure/virtual-wan/how-to-routing-policies. I know We can do using the portal ,az cli and PowerShell commands. 

Kindly anyone please help on me this

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_hub

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
