### ISSUE TITLE
Error while creating azurerm_monitor_autoscale_setting in app service plan through terraform azurerm provider version 2.72

### ISSUE THREAD

**Issue by sid1206** [hashicorp/terraform-provider-azurerm#23439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0

### AzureRM Provider Version

2.72

### Affected Resource(s)/Data Source(s)

azurerm_monitor_autoscale_setting

### Terraform Configuration Files

```hcl
We are getting below issue while creating auto scale setting on azure app service plan. It was working fine and suddenly while creating a new environment we are getting this issue
```

### Debug Output/Panic Output

```shell
Insight.AutoscaleSettingsClient#CreateorUpdate: Failure responding to request: StatusCode=400 —- Original Error: autorest/azure:Service returned an error .Status=400 code=“ResourceNotSupported” Message =“ The target resource id is not supported
```

### Expected Behaviour

The auto sale setting gets created in azure through terraform

### Actual Behaviour

Facing the error while creating the resource with terraform azure ram provider version 2.72

Insight.AutoscaleSettingsClient#CreateorUpdate: Failure responding to request: StatusCode=400 —- Original Error: autorest/azure:Service returned an error .Status=400 code=“ResourceNotSupported” Message =“ The target resource id is not supported

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). Additionally, 2.x version of the provider is no longer actively maintained. With that in mind, I'm going to close this issue.
If you are able to upgrade to the 3.x version of the provider and find you are still experiencing this issue and believe it is a bug, we will need the TF configuration and the Debug output in order for a contributor to attempt to reproduce the bug. Thanks!
