### ISSUE TITLE
azurerm_redis_cache - output redis_primary_connection_string ssl=false but port is 6380

### ISSUE THREAD

**Issue by Poil** [hashicorp/terraform-provider-azurerm#23490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

# NOTE: the Name used for Redis needs to be globally unique
resource "azurerm_redis_cache" "example" {
  name                = "example-cache"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  capacity            = 2
  family              = "C"
  sku_name            = "Standard"
  enable_non_ssl_port = true
  minimum_tls_version = "1.2"

  redis_configuration {
  }
}
```

### Debug Output/Panic Output

```shell
.
```

### Expected Behaviour

```
example.redis.cache.windows.net:6380,password=xxxxxxxxxxxx=,ssl=True,abortConnect=False
```

### Actual Behaviour

```
example.redis.cache.windows.net:6380,password=xxxxxxxxxxxx=,ssl=false,abortConnect=False
```

**Comment by sinbai** [comment]
Hi @Poil thanks for opening this issue here. Unfortunately, I could not reproduce this issue using the above terraform configuration. After applying the above tf configuration, the result on Azure portal is as follows, could you please double check and provide more details?
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/39109137/38495321-aa33-4c33-b3c8-a2a2beae8346)

**Comment by Poil** [comment]
Sorry, it's the output of Terraform that is wrong not in the portal !

**Comment by sinbai** [comment]
Hi @Poil , thank you very much for your explanation. Per [terraform code](https://github.com/hashicorp/terraform-provider-azurerm/blob/e8c755aec84b99be56e3363ac579cd0c9c1efc35/internal/services/redis/redis_cache_resource.go#L723C15-L723C15), the ssl value of `redis_primary_connection_string` depends on the `enable_non_ssl_port ` property. Because `enable_non_ssl_port ` is set to true, which means ssl port is disabled, I assume it makes sense for ssl to be set to false in terraform, correct?

**Comment by sinbai** [comment]
Hi @Poil ,thanks for your explanation. I have submitted [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/23575) to fix it. Could you please follow it for more updates?
