### ISSUE TITLE
DCE/DCR not configured for Prometheus logging

### ISSUE THREAD

**Issue by jaywithersbrewin** [hashicorp/terraform-provider-azurerm#23623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.8

### AzureRM Provider Version

3.74.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "aks-lz-npd-weu-platform"
  location            = azurerm_resource_group.platform.location
  resource_group_name = azurerm_resource_group.platform.name
  dns_prefix          = "aks"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  monitor_metrics {}

  tags = {
    Environment = "Production"
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

MA_mon-lz-npd-weu-aks_westeurope_managed resource group created with Data Collection Endpoint (DCE) and Data Collection Rule (DCR) which are fully configured.

### Actual Behaviour

The DCE and DCR don't have resources configured.

**Comment by stephybun** [comment]
Thanks for raising this issue @jaywithersbrewin.

Looking over the MSFT documentation, in order to configure Prometheus metrics on an AKS cluster the Azure Monitor Workspace (which creates the MA_* resource group, as well as the DCE and DCR) needs to be created beforehand. The Rest API does not handle the automatic creation of it just from enabling it.

For guidance on how to setup Prometheus logging on your cluster the MSFT docs have a [great guide with example Terraform modules](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/kubernetes-monitoring-enable?tabs=terraform#enable-prometheus-and-grafana).

I'm going to close this issue since there aren't any changes we can make to the resource for this. The linked guide should provide clarity on how to setup Prometheus logging and for any further configuration questions the [Community Discuss forum](https://discuss.hashicorp.com/) is a good place to look through.

**Comment by jaywithersbrewin** [comment]
Thanks, @stephybun
