### ISSUE TITLE
Support for tag resource

### ISSUE THREAD

**Issue by Satak** [hashicorp/terraform-provider-azurerm#23658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Add simple resource to add tags to existing resources, e.g. subscriptions. This would be handy for tagging subscriptions and other resources that are not in the state or are not created (or can't created at all) with Terraform.

I know I can use `azapi` provider to add tags via the REST API, but that can't remove tag keys or modify keys, only set keys once and edit values. So it starts to drift very quickly.

```tf
resource "azapi_update_resource" "subscription_tags" {
  for_each = var.tags

  type      = "Microsoft.Resources/tags@2022-09-01"
  parent_id = each.value.id
  name      = "default"

  body = jsonencode({
    properties = {
      tags = each.value.tags
    }
  })
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_subscription

### Potential Terraform Configuration

```hcl
resource "azurerm_tag" "tag"  {
  resource_id = var.subscription_id
  tags        = var.tags
}
```

**Comment by mybayern1974** [comment]
@Satak thank you for raising this feature suggest. With leaving expectations to AzureRM tracked here, as for the tag limitation you mentioned to azapi, you could file that issue to the TF AzAPI repo in case owners there could either raise feedbacks or put expectations to AzAPI feature backlog.

**Comment by Satak** [comment]
I have rised the issue also at azapi issues. I just think the azapi is a bit hacky and would be really nice to have native tag resource at azurerm

**Comment by Satak** [comment]
Here is a somewhat good workaround: https://github.com/Azure/terraform-provider-azapi/issues/365

**Comment by tombuildsstuff** [comment]
hi @Satak 

Thanks for opening this issue.

Support for a generic tags resource has come up a few times over the years, our most recent investigation into this issue can be [found in this comment](https://github.com/hashicorp/terraform-provider-azurerm/pull/19544#issuecomment-1340683878) - in short we aren't planning on introducing a generic tags resource into the Provider at this point in time, however this may be something we can re-evaluate in the future should the behaviour of Tags become more consistent.

It's worth noting that for the Subscriptions scenario outlined above, it's possible to manage the Subscription within Terraform and use [the `prevent_cancellation_on_destroy` flag within the  `features` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#prevent_cancellation_on_destroy) to ensure the Subscription isn't cancelled during a destroy, for example:

```hcl
provider "azurerm" {
  features {
    subscription {
      prevent_cancellation_on_destroy = true
    }
  }
}
```

Whilst that's solving this issue in a different manner to the feature request above, having these resources managed by Terraform means that we're able to use the appropriate update method for Tags for the resource in question.

However since we're not planning to introduce a generic tags resource to the Provider for the foreseeable future, whilst I'd like to thank you for opening this feature request - I'm going to close this issue for the moment.

Thanks!

**Comment by andaryjo** [comment]
> having these resources managed by Terraform means that we're able to use the appropriate update method for Tags for the resource in question.

This is unfortunately not working when you are a customer of a CSP and not a direct customer of Azure and for some reason cannot use the PUT API for subscriptions.
