### ISSUE TITLE
`azurerm_kubernetes_cluster` default node pool taint for BYOCNI use cases

### ISSUE THREAD

**Issue by jusdor** [hashicorp/terraform-provider-azurerm#23957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hi everyone,

in reference to https://github.com/hashicorp/terraform-provider-azurerm/issues/10490 and https://github.com/hashicorp/terraform-provider-azurerm/issues/9183 I would like to ask if the behavior of not allowing taints on the default node pool can be changed.

I am creating clusters without CNI and installing Cilium, so the following taint would be quite useful for the nodes 
until the installation is finished and Cilium removes the taint: `node.cilium.io/agent-not-ready=true:NoExecute` 

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
default_node_pool {
        name                = "defaultpool"
        node_count          = 3
        vm_size             = "Standard_B2s"
        vnet_subnet_id      = azurerm_subnet.akssubnet.id
        node_taints = [
         "node.cilium.io/agent-not-ready=true:NoExecute"]
    }
```

### References

[Cilium docs on taints](https://docs.cilium.io/en/stable/installation/taints/)

**Comment by rcskosir** [comment]
Thank you for taking the time to open this feature request!

**Comment by stephybun** [comment]
Thanks for raising this issue @jusdor.

Adding taints to the default node pool has been a popular ask, and although I can see the value in supporting additional taints such as this one, the [AKS API doesn't allow taints other than `CriticalAddonsOnly=true:NoSchedule`](https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli#system-and-user-node-pools) on the system node pool (the default node pool in azurerm).

I'm unaware of any plans to extend support for other node taints but I'd recommend looking over on the [AKS repo](https://github.com/Azure/AKS) and potentially raising a feature request there.

I'm going to close this issue since this isn't something we can support today. When support for this becomes available in the AKS API we'll be happy to reopen this.
