### ISSUE TITLE
Refresh state stops working after adding private endpoint to storage account

### ISSUE THREAD

**Issue by Stolz** [hashicorp/terraform-provider-azurerm#24193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.84.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.84.0"
    }
  }

  required_version = ">= v1.5.7"
}

provider "azurerm" {
  subscription_id = "redacted"
  tenant_id       = "redacted"
  features {}
}

resource "azurerm_resource_group" "example" {
  location = "eastasia"
  name     = "example-rg"
}

resource "azurerm_virtual_network" "example" {
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  name                = "example-vnet"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  for_each = {
    web = {
      prefixes          = ["10.0.2.0/24"]
      service_endpoints = ["Microsoft.Web", "Microsoft.Storage"]
    }
    storage = {
      prefixes          = ["10.0.3.0/24"]
      service_endpoints = ["Microsoft.Storage"]
    }
  }

  address_prefixes     = each.value.prefixes
  name                 = format("%s-snet", each.key)
  resource_group_name  = azurerm_resource_group.example.name
  service_endpoints    = each.value.service_endpoints
  virtual_network_name = azurerm_virtual_network.example.name
}

data "http" "my_public_ip" {
  url = "http://ipecho.net/plain"
}

resource "azurerm_storage_account" "example" {
  account_replication_type        = "LRS"
  account_tier                    = "Standard"
  allow_nested_items_to_be_public = false
  location                        = azurerm_resource_group.example.location
  name                            = "examplerandomname"
  public_network_access_enabled   = true
  resource_group_name             = azurerm_resource_group.example.name

  network_rules {
    bypass                     = ["AzureServices", "Logging", "Metrics"]
    default_action             = "Deny"
    ip_rules                   = [data.http.my_public_ip.response_body]
    virtual_network_subnet_ids = [azurerm_subnet.example["web"].id]
  }
}

# This block breaks `terraform refresh` and `terraform plan`
resource "azurerm_private_endpoint" "example" {
  for_each                      = toset(["blob"])
  custom_network_interface_name = format("example-%s-pep-nic", each.value)
  location                      = azurerm_resource_group.example.location
  name                          = format("example-%s-pep", each.value)
  resource_group_name           = azurerm_resource_group.example.name
  subnet_id                     = azurerm_subnet.example["storage"].id

  private_service_connection {
    is_manual_connection           = false
    name                           = format("example-%s-pep", each.value)
    private_connection_resource_id = azurerm_storage_account.example.id
    subresource_names              = [each.value] # Storage Account only supports one subresource at a time
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/Stolz/bc4d7ace1ee46f600fcc8e85070421c0
```

### Expected Behaviour

I should be able to refresh Terraform state when my configuration contains a private endpoint

### Actual Behaviour

Terraform refresh stops working after adding the private endpoint. Once the private endpoint is removed Terraform refresh starts working again.

### Steps to Reproduce

1. Remove last block (azurerm_private_endpoint) from the config.
2. Run `terraform apply` (it works as expected).
3. Add back the removed block.
4. Run either `terraform refresh` or `terraform apply` (none of them work).

**Comment by magodo** [comment]
This is because when PE is enabled, the DNS resolving will change, even for public accessable storage account, e.g.:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/7970698/201b0c5a-72df-4271-b86f-1480740cd29f)

(see: https://learn.microsoft.com/en-us/azure/storage/common/storage-private-endpoints#dns-changes-for-private-endpoints)

There might be some network issues in your runner, that failed to resolve one of the domain name. E.g. I have the exact same issue when I connect with my corp VPN, and I don't know why.. The error from the provider actually indicates DNS lookup failure, and it continously retry, and due to the timeout of read is 5min (default), the retry timesout. You can manually increase the read timeout to see the actual error message, which I assume would be something like "dial: lookup ... failed".

**Comment by magodo** [comment]
@Stolz 

For the reason why the error message doesn't change after you update the timeouts is because it was still using the old value (i.e. 5min). You'll have to temporarily remove the PE block, do a dummy & successful `terraform apply` so that to update the timeout values for read. After this, you can add back the PE block and try again, in which case you'll see the error message.

However, as you have already tried to `nslookup` from your runner machine, it does reveal the exact error. It SHOULD be possible to access the storage account from OUTSIDE of the vnet as the document above stated. But it can fail for some reasons:

- Network configuration issue, as I've mentioned
- The storage account is recreated shortly after it is deleted, with the same name. For this case, you can try pick another new storage account name and retry. If you insist on continue using the same name, there will be a DNS propagation delay (to invalidate the TTL of NS).

**Comment by Stolz** [comment]
Hi @magodo , thanks again for your help. I have tried with a new name and higher timeout and indeed the message has now changed as you mentioned:

    dial tcp: lookup example2randomname.blob.core.windows.net: no such host

Since you mentioned it should be possible to do what I want (manage a SA with private endpoint with Terrafrom running from outside the vnet) that means the only cause of error left is network configuration. My goal is for the SA account to be only accessible from a small set of public IPs, and from the private IPs of certain given subnets. To accomplish that I have used this configuration

```terraform
  network_rules {
    bypass                     = ["AzureServices", "Logging", "Metrics"]
    default_action             = "Deny"
    ip_rules                   = ["1.2.3.4"] # Fake public IP, in reality I use my own public IP
    virtual_network_subnet_ids = [azurerm_subnet.example["web"].id]
  }
```

This configuration works fine for private endpoints of other Azure services I use, such as Redis, PostgreSQL or Key Vault. Terraform can refresh those resources and their private endpoints successfully so I'm not sure why Storage Accounts require a different configuration.

I have tried deleting the `network_rules` block entirely so there are no network restrictions in place, yet I get the exact same error when I run `terraform refresh`.

If my scenario should be possible, could you please suggest which network configuration is required for terraform to be able to refresh from outside a vnet an storage account configured with network restrictions?

**Comment by Stolz** [comment]
Nevermind. After adding to `/etc/hosts` file the PUBLIC IP of `example2randomname.privatelink.blob.core.windows.net, terraform refresh works fine. That means the issue is the DNS server of my ISP.

I appreciate the help.

**Comment by magodo** [comment]
The issue you are hitting now is at DNS resolving stage, which is prior to the `network_rules` to take effect. In fact, if an access to your SA from an IP not listed in your networ rule, it will cause 403 error code, as long as the DNS resolve succeeds.

I've tried your above configuration (no change except the names) locally, and all work (i.e. `terraform apply` then `terraform plan` all succeed). Whilst when I connect my corp VPN and run `terraform plan` again, it failed with the same error.
