### ISSUE TITLE
Support for NSG association during aks node pool creation 

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform-provider-azurerm#24319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Thanks for this provider, it has been working super well. Nice work you all! 

One thing we are wondering about. There doesn't seem to be a way for us to associate platform-level Network Security Groups with AKS node pools. AKS creates 1 NSG and associates it to *all* the node pools, which seems convenient. However, we would like to do network segmentation between different node pools. We know we can add some rules through k8s services but we hope not to have to rely on k8s services if we only want to do networking filtering. 

Is the general recommendation to always rely on k8s network policies? 

### New or Affected Resource(s)/Data Source(s)

zurerm_kubernetes_cluster

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
