### ISSUE TITLE
Support for enabling server logs in `azurerm_postgresql_flexible_server`

### ISSUE THREAD

**Issue by jarpoole** [hashicorp/terraform-provider-azurerm#24471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure managed Postgres now includes the ability to easily store and download server logs with a configurable retention period. It would be great to be able to enable this from Terraform.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/43940867/88817691-8c47-496c-91ca-b67774437825)

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server" "example" {
   server_logs = {
      enabled = true
      retention_days = 3
   }
}
```

### References

In the portal: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-server-logs-portal
In the CLI: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-server-logs-cli

**Comment by tombuildsstuff** [comment]
hey @jarpoole 

Checking the API Definitions for this whilst there's endpoints to download the log files - there doesn't appear to be a new API in order to configure that - however taking a look through [this article](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-server-logs-portal) it appears this functionality is configured using a Server Parameter:

> You can configure your server logs in the same way as above using the [Server Parameters](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/howto-configure-server-parameters-using-portal), setting the appropriate values for these parameters: logfiles.download_enable to ON to enable this feature, and logfiles.retention_days to define retention in days.

Server Parameters can be configured [using the `azurerm_postgresql_flexible_server_configuration` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server_configuration) - as such I believe this functionality should be possible using that resource, would you be able to take a look and see if that works for you here?

Thanks!

**Comment by jarpoole** [comment]
@tombuildsstuff works like a charm! I feel a little stupid for wasting everyone's time when the answer was right in the article I linked so many apologies. Hopefully this issue at least helps someone else trying to get the same thing working in the future!
