### ISSUE TITLE
why tags argument in azurerm_private_dns_a_record resource?

### ISSUE THREAD

**Issue by marcoboffi** [hashicorp/terraform-provider-azurerm#24487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I think presence of _tags_ argument in `azurerm_private_dns_a_record resource` resource is a typo.

[api-spec](https://learn.microsoft.com/en-us/rest/api/dns/privatedns/private-zones/create-or-update?view=rest-dns-privatedns-2018-09-01&tabs=HTTP) doesn't contain tags field in body specification (Neither create and nor get methods) .
[az cli] (https://learn.microsoft.com/en-us/cli/azure/network/private-dns/record-set/a?view=azure-cli-latest#az-network-private-dns-record-set-a-add-record) doesn't permit to set tags value.

[go-sdk](https://github.com/Azure/azure-sdk-for-go/blob/463de81ffe69a90652745c66c570a2489c620d45/sdk/resourcemanager/privatedns/armprivatedns/models.go#L151) include s a generic Metadata attribute  but it's not the same of tags attribute present in the other resources.

And how could record-A tags be different from private_zone resource tags ? 

If you agree, please remove tags argument from input interface of resource.

### Terraform Version

1.4.0

### AzureRM Provider Version

3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_private_dns_a_record resource

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_zone" "example" {
  name                = "mydomain.com"
  resource_group_name = azurerm_resource_group.example.name
    tags = {
        zone = "X"
  }
}

resource "azurerm_private_dns_a_record" "example" {
  name                = "test"
  zone_name           = azurerm_private_dns_zone.example.name
  resource_group_name = azurerm_resource_group.example.name
  ttl                 = 300
  records             = ["10.0.180.17"]
    tags = {
        zone = "Y"
  }
}
```

### Debug Output/Panic Output

```shell
data "azurerm_private_dns_a_record" "example" {
  name                = "test"
  zone_name           = "test-zone"
  resource_group_name = "test-rg"
}

output "private_dns_a_record_tags" {
  value = data.azurerm_private_dns_a_record.example.tags
}
```

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. In azurerm_private_dns_a_record, the Metadata is called tags since it's used to add tags for this resource. I assume it's different than the Metadata in other resources.

**Comment by marcoboffi** [comment]
In addition, I would like to point out that from the documentation, the resource does not support tags.  
https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support#microsoftnetwork  
(resource `privateDnsZones / A`)

**Comment by tombuildsstuff** [comment]
@marcoboffi the field is called `metadata` in the API but is ultimately used to store tags - as such for consistency within Terraform we normalise this into `tags` - since that's what this field is called in every other resource.

We're intentionally normalising the value of certain fields (e.g. `identity`, `location`, `tags`, `zones` etc) across different resources, so that these behave consistently - and so users don't need to account for breaking behavioural changes in the API when moving from one version of the API to another (for example where one API version may require the value for `type` within the `identity` block be set to `SystemAssigned,UserAssigned` but the next version requires `SystemAssigned, UserAssigned` (note the space) - these are normalised in Terraform into `SystemAssigned, UserAssigned`.

However since this is a question rather than an issue/feature request in the provider, whilst I'd like to thank you for opening this issue, I'm going to close this issue for the moment - but should you have further questions I'd direct you towards [the Community Discuss Forum](https://discuss.hashicorp.com).

Thanks!
