### ISSUE TITLE
Need changes in Azure Machine Learning Workspace code as :Classic Application Insights is deprecated and will be retired in February 2024

### ISSUE THREAD

**Issue by sudheeshkj** [hashicorp/terraform-provider-azurerm#24677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure Classic Application Insights is deprecated and will be retired in February 2024. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/machine_learning_workspace using application_insights_id as one of the required argument, So please change the code to remove app insight from machine learning

### New or Affected Resource(s)/Data Source(s)

azurerm_machine_learning_workspace

**Comment by sudheeshkj** [comment]
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/101182308/ca7cb7b4-d092-4ed3-84ab-b25a1025ab78)

**Comment by tombuildsstuff** [comment]
hi @sudheeshkj 

It's currently possible to provision Application Insights using one of two different pricing models, either Classic or Workspace - with Classic being deprecated.

The warning being shown above relates to the type of Application Insights being used - rather than the deprecation of Application Insights support within Machine Learning Workspaces -  as such specifying the `application_insights_id` when provisioning a Machine Learning Workspace remains required, however it must be using a Workspace pricing model going forwards. Instead [customers using the Classic pricing model can migrate to the Workspace pricing model](https://learn.microsoft.com/en-us/azure/azure-monitor/app/convert-classic-resource), which should remove this warning.

As such I don't believe there's any changes needed within the Provider to support this, and as such I'm going to close this issue for the moment - but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
