### ISSUE TITLE
azurerm_postgresql_flexible_server should allow public_network_access_enabled argument as input

### ISSUE THREAD

**Issue by nlighten** [hashicorp/terraform-provider-azurerm#24708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Private endpoints for `azurerm_postgresql_flexible_server` are currently in preview (GA expected in a month or so). The absence of a `public_network_access_enabled` input argument prevents the creation of instances with public access disabled in combination with privat eendpoints.. 

This is due to that fact that value of `public_network_access_enabled` is computed based on whether or not  `delegated_subnet_id` is passed as input argument. 

We would like to propose adding `public_network_access_enabled` as optional input argument with the current computed value as default for backward compatibility. 

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server" "example" {
  name                   = "example-psqlflexibleserver"
  resource_group_name           = azurerm_resource_group.example.name
  location                      = azurerm_resource_group.example.location
  version                       = "12"
  delegated_subnet_id           = azurerm_subnet.example.id
  private_dns_zone_id           = azurerm_private_dns_zone.example.id
  administrator_login           = "psqladmin"
  administrator_password        = "H@Sh1CoR3!"
  zone                          = "1"
  public_network_access_enabled = false

  storage_mb = 32768

  sku_name   = "GP_Standard_D4s_v3"
  depends_on = [azurerm_private_dns_zone_virtual_network_link.example]

}
```

### References

https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-networking-private-link

**Comment by nlighten** [comment]
@rcskosir Private Endpoints for Postgresql Flexible Server is now GA. Can we remove the preview label?

**Comment by joachimsmits** [comment]
Plz more prio, this is also possible in Bicep right now!

**Comment by joachimsmits** [comment]
We see in TF code:    
                       if network := props.Network; network != nil {
        publicNetworkAccess := false
        if network.PublicNetworkAccess != nil {
          publicNetworkAccess = *network.PublicNetworkAccess == servers.ServerPublicNetworkAccessStateEnabled
        }
        d.Set("public_network_access_enabled", publicNetworkAccess)
        d.Set("delegated_subnet_id", network.DelegatedSubnetResourceId)
        d.Set("private_dns_zone_id", network.PrivateDnsZoneArmResourceId)
      }

So plz, bring this argument to the front instead of dependent from vent injection.

**Comment by PeterNienaber** [comment]
For us the public_network_access_enabled input argument is very important to be able to rollout flexible server with Terraform and public access denied because of Azure policies of our company. We have a lot of PostgreSQL Single servers to migrate to flexible servers and we have to start soon. We are now looking to use Bicep instead although Terraform is our preferred tool.

**Comment by nlighten** [comment]
@PeterNienaber you can consider using `azapi` Terraform provider. This allows you to do more or less the same as in Bicep but then using Terraform. We are starting to use it more and more in our own modules to avoid the sometimes huge delay in new feature availability in `azurerm`

**Comment by vakaobr** [comment]
@nlighten that would be a option to be considered (use `azapi`) to cover something new, but since Microsoft is already with a date set to remove the single servers, honestly I can't see a reason to a feature so important like disable public access to the databases are not being prioritised on the AzureRM provider.

As stated by @joachimsmits before, the code is already in place (https://github.com/hashicorp/terraform-provider-azurerm/issues/24708#issuecomment-2033975674), we just need to have the argument available to be used.

This is a issue opened since January, and since March 1st we had 3.94.0/3.95.0/3.96.0/3.97.0/3.97.1 and 3.98.0 versions released. How big would be this change to not being considered as part of any of those releases ?

**Comment by NathanDunning** [comment]
Agree with the gist of this issue, we are experiencing the same issues in trying to deploy a PFS but require no public network access due to policies set by the company. Would like to have this field configurable as this field is configurable directly via the API: https://learn.microsoft.com/en-us/rest/api/postgresql/flexibleserver/servers/create?view=rest-postgresql-flexibleserver-2022-12-01&tabs=HTTP#network
