### ISSUE TITLE
Data Lake Store Identity

### ISSUE THREAD

**Issue by bg2132332** [hashicorp/terraform-provider-azurerm#2473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We require an identity for a new data lake store.  While user-assigned encryption doesn't work (i.e. can't bring my own key from a key vault to encrypt), one way to implement our own encryption is to create a new key, grant data lake's identity key vault access, and then encrypt via an ARM template (at least that's the process that I followed with a regular storage account).  The only thing is missing for this is a system-assigned identity block with data lake.  If not possible to implement identity, please prioritize data lake encryption with a user key.

### New or Affected Resource(s)

* azurerm_data_lake_store

### Potential Terraform Configuration

identity = {
  type="SystemAssigned"
}

**Comment by tombuildsstuff** [comment]
hey @bg2132332 

Thanks for opening this issue :)

Taking a quick look into this it appears this isn't available in the API version we're using (`2016-11-01`) - and there doesn't currently appear to be support for a newer API version in either [the Azure SDK for Go repository](https://github.com/Azure/azure-sdk-for-go/tree/master/services/datalake/store) or the [Azure Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/datalake-store/resource-manager/Microsoft.DataLakeStore) which is where the SDK is generated from.

Out of interest do you know which API version adds support for the Identity block? In either case we'll need to [open an issue on the Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs/issues) requesting that a Swagger document for this API version is added, so that we can add this

Thanks!

**Comment by bg2132332** [comment]
Hi Tom!  Thanks for responding so quickly.  

It seems to be there in Go SDK -- check out this line that validates "parameters.Identity".  
https://github.com/Azure/azure-sdk-for-go/blob/c1014269bb414e236cc84cfe4ff457305b668990/services/datalake/store/mgmt/2016-11-01/account/accounts.go#L148

Here is an examples of Azure Rest API (2016-11-01) that shows identity.  Seems like it's worth a try.. 
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datalake-store/resource-manager/Microsoft.DataLakeStore/stable/2016-11-01/examples/Accounts_Create.json

Another wishlist item would be support of virtual network rules :)

**Comment by tcz001** [comment]
any update on this feature?
