### ISSUE TITLE
azurerm version > 3.89.0 is breaking For loop parsing

### ISSUE THREAD

**Issue by BigFrog-coding** [hashicorp/terraform-provider-azurerm#24935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.92

### Affected Resource(s)/Data Source(s)

azurerm_pim_eligible_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_pim_eligible_role_assignment" "pim_sub_eligible_assignment" {
  for_each = {
    for role in local.roles : "${role.scope}${role.role_definition_id}" => role
  }
  scope              = each.value.scope
  role_definition_id = each.key
  principal_id       = each.value.principal_id

  schedule {
    start_date_time = time_static.static_time.rfc3339
    expiration {
      duration_days = 364
    }
  }

}

example entry of local.roles =
  {
    "principal_id" = "id here"
    "role_definition_id" = "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
    "scope" = "/subscriptions/id here"
  },
```

### Debug Output/Panic Output

```shell
The debug shows too much PII and is irrelevant
```

### Expected Behaviour

The role key should have been created using the scope and role_definition_id in the for loop. TF plans

### Actual Behaviour

│ Error: Duplicate object key
│
│   on pim.tf line 24, in resource "azurerm_pim_eligible_role_assignment" "pim_sub_eligible_assignment":
│   23:   for_each = toset({
│   24:     for role in local.roles : "${role.scope}${role.role_definition_id}" => role
│   25:   })
│     ├────────────────
│     │ role.role_definition_id is "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
│     │ role.scope is ""
│
│ Two different items produced the key "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c" in this 'for' expression. If duplicates are expected, use the ellipsis (...) after the value expression to enable grouping by key.
╵

scope is empty
This works great in all previous versions of azurerm provider

### Steps to Reproduce

Terraform plan

**Comment by xuzhang3** [comment]
@BigFrog-coding  you have duplicate role in the `roles` which should be unique

**Comment by BigFrog-coding** [comment]
no I dont, the role key is created with the for loop.  The issue is it is not reading the scope attribute in the object.  In version 3.89.0 and previous versions it works fine

**Comment by BigFrog-coding** [comment]
@xuzhang3 Can you take another look please? I am surprised no one else is seeing this issue.

**Comment by xuzhang3** [comment]
@BigFrog-coding Can you check the roles in the local vals? Where is the roles from, the loop is build the role from it and it have duplicate values. 
You can reproduce this error by :
```local
locals {
  roles = {
    roles1 = {
      scope : "scope1"
      role_definition_id : "def1"
      principal_id : "principal_id1"
    },
    roles2 = {
      scope : "scope1"
      role_definition_id : "def1"
      principal_id : "principal_id2"
    }
  }
}
```

**Comment by xuzhang3** [comment]
@BigFrog-coding  I ran the code, the error message  is generated by Terraform and was thrown by the `for` expression.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/57888764/fb387a87-842c-4991-b33c-4af7d62abd98)

**Comment by BigFrog-coding** [comment]
Yes, you are correct, but it is directly related to the Azurerm provider version, not Terraform itself.  As it works in all versions prior to 3.89.

**Comment by xuzhang3** [comment]
@BigFrog-coding  the key issue here is the role has duplicated values, how do you get the roles?

**Comment by BigFrog-coding** [comment]
As stated, many times now, it is constructed/concatenated by the for loop using scope and role_id to create unique values.  This works fine in 3.89 or lower, but broken with any 3.9 or higher azurerm provider version.

**Comment by ABCodeMonkey** [comment]
Greetings

I have peer reviewed @BigFrog-coding results on my end.

3.99
```
Initializing provider plugins...
- Finding latest version of hashicorp/time...
- Finding latest version of hashicorp/azuread...
- Finding hashicorp/azurerm versions matching "3.99.0"...
- Using previously-installed hashicorp/time v0.11.1
- Using previously-installed hashicorp/azuread v2.48.0
- Installing hashicorp/azurerm v3.99.0...
- Installed hashicorp/azurerm v3.99.0 (signed by HashiCorp)

`Plan: 90 to add, 0 to change, 0 to destroy.`
```


Plan at 3.89
```
Initializing provider plugins...
- Finding latest version of hashicorp/azuread...
- Finding hashicorp/azurerm versions matching "3.89.0"...
- Finding latest version of hashicorp/time...
- Using previously-installed hashicorp/time v0.11.1
- Using previously-installed hashicorp/azuread v2.48.0
- Using previously-installed hashicorp/azurerm v3.89.0

Plan: 206 to add, 0 to change, 0 to destroy.
```


We are creating pim roles for Owner and Contributor
2 group creations
2 pim assignments

We have a data call to gather subscriptions
```
data "azurerm_subscriptions" "available" {
}

```
We filter in our locals:

```
  enabled_subs = { for i, sub in data.azurerm_subscriptions.available.subscriptions : replace(sub.display_name, " ", "") => sub
    if((sub.state == "Enabled")
      && (length(regexall("(?i).*Visual Studio.*", sub.display_name))) == 0
      && (length(regexall("(?i).*AVAILABLE.*", sub.display_name))) == 0
      && (length(regexall("(?i).*Access to.*", sub.display_name))) == 0
      && (length(regexall("(?i).*Azure subscr.*", sub.display_name))) == 0
      && (length(regexall("(?i).*Rebecca.*", sub.display_name))) == 0
      && (length(regexall("(?i).*Azure NCE.*", sub.display_name))) == 0
      && (length(regexall("(?i).*devtest-tf-01*", sub.display_name))) == 0
      && (length(regexall("(?i).*Test-ResourceProviders*", sub.display_name))) == 0
      && (length(regexall("(?i).*Reservations*", sub.display_name))) == 0
      && (length(regexall("(?i).*PROD-Reservations*", sub.display_name))) == 0
      && (length(regexall("(?i).*Archive*", sub.display_name))) == 0
    )
  }
```

We create groups based on the local keys (2 resources, just showing the one)


```
resource "azuread_group" "pim_groups_owner" {
  for_each     = local.enabled_subs
  display_name = "a_${each.key}_pim_owner"
  description  = "Used to PIM into the owner role for break glass needs"
  members      = ["fff-fff-fff-fff-fff","fff-fff-fff-fff-fff"] 
  owners       = ["fff-fff-fff-fff-fff", "fff-fff-47c3-b5dd-94ef849905f3"]    
  security_enabled = true         
  prevent_duplicate_names = true
}
```

Then assign pim for these groups: with a lookup

```

resource "azurerm_pim_eligible_role_assignment" "pim_sub_eligible_assignment_owner" {
  for_each           = azuread_group.pim_groups_owner
  scope              = local.enabled_subs[each.key].id #key is the sub, poorly named foreach :)
  role_definition_id = data.azurerm_role_definition.owner.id
  principal_id       = each.value.object_id

  schedule {
    start_date_time = time_static.static_time.rfc3339
    expiration {
      duration_days = 364
    }
  }
}

```

There is a clear discrepancy between the two versions using the same terraform

Plan: 90 to add, 0 to change, 0 to destroy.
Plan: 206 to add, 0 to change, 0 to destroy.

**Comment by ABCodeMonkey** [comment]
Just a quick followup,
The local.enabled_subs contains 37 subs in each azurerm version
```
> length(local.enabled_subs)
37
```

**Comment by BigFrog-coding** [comment]
@tombuildsstuff Why did you close this issue? This is 100% not a configuration issue. Why would it work fine with Azurerm 3.89 and not work with any version greater than that? Please stop saying it is configuration issue when it clearly is not. I must insist you re-open this bug or I will recreate it until everyday until someone actually adresses the issue

**Comment by tombuildsstuff** [comment]
@BigFrog-coding both the error message in your original description:

```
Actual Behaviour

│ Error: Duplicate object key
│
│ on pim.tf line 24, in resource "azurerm_pim_eligible_role_assignment" "pim_sub_eligible_assignment":
│ 23: for_each = toset({
│ 24: for role in local.roles : "${role.scope}${role.role_definition_id}" => role
│ 25: })
│ ├────────────────
│ │ role.role_definition_id is "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
│ │ role.scope is ""
│
│ Two different items produced the key "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c" in this 'for' expression. If duplicates are expected, use the ellipsis (...) after the value expression to enable grouping by key.
╵
```

and the associated repro by @xuzhang3:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/57888764/fb387a87-842c-4991-b33c-4af7d62abd98)

both show a configuration issue with the value being provided.

Note that in the error message being output there's only a Role Definition shown, not a Scope - therefore the Scope must be an empty string (see `role.scope is "" in the error message) - which is likely the source of this conflict.

As mentioned above, please double-check the source data being provided here, based on the error messages being returned - this isn't a bug in the Provider but an issue with the value being provided in the Configuration - and as such you'll need to check the source data being provided to diagnose this one.

Whilst it's possible that there _could_ be an issue with a Terraform Resource if that value is interpolated, unfortunately without validating the source data contains no duplicate values - which is what Terraform Core is highlighting is the source of the problem here - it's not possible to know which resource needs further investigation, but since Terraform Core is stating the problem is the source data, that's where I would start digging into this problem.

**Comment by BigFrog-coding** [comment]
@tombuildsstuff No it does not show a configuration issue, that is our point. You are seeing something that looks like configuration issue when in reality it is an issue with the Azurerm.  The source data is a data call to pull a subscriptions and then the for loop creates dynamically a key for the loop based on the subscriptions. There is not any data that we are wrongly supplying. I assure you 100% there is not one duplicate value. 

I am happy to get into a call and talk it out if you like.  Again, I request you re-open this bug or I will just keep submitting until I get some traction.

**Comment by tombuildsstuff** [comment]
@BigFrog-coding

Whilst I can understand you’re frustrated that this issue has been closed, please refrain from re-opening duplicates for this issue. Any duplicates will need to be closed in favour of this issue, and this work ultimately distracts maintainers from working on PRs and issues.

As mentioned above: based on _the Terraform Configuration provided in the issue description_ which returns the error “Two different items produced the key” - this is a configuration issue.

Now - as you’ve alluded to in your last comment, there may well be another issue at play here - but the error message being returned here is only returned from Terraform Core when a map contains multiple keys with the same name, since a map must contain unique keys.

In order for us to diagnose any separate issue, we’d need a reproducible Terraform Configuration (and ideally, debug logs) - so if you can provide that then we’re happy to take another look.

However without that additional information we’re unable to ascertain if there’s another issue at play here, and we’re instead left with the error message being returned from Terraform Core:

```
Two different items produced the key "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c" in this 'for' expression. If duplicates are expected, use the ellipsis (...) after the value expression to enable grouping by key.
```

As such whilst I appreciate that you’re frustrated here, without a reproducible Terraform Configuration showing the issue coming from another Data Source/Resource - and/or without any debug logs, there isn’t much more we can do but look at the error message coming back from Terraform Core here.
