### ISSUE TITLE
Broken Link: Terraform Registry Documentation (azurerm_orchestrated_virtual_machine_scale_set)

### ISSUE THREAD

**Issue by chris-zenfolio** [hashicorp/terraform-provider-azurerm#25176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

N/A

### AzureRM Provider Version

N/A

### Affected Resource(s)/Data Source(s)

azurerm_orchestrated_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

On the Terraform Registry documentation page for [azurerm_orchestrated_virtual_machine_scale_set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/orchestrated_virtual_machine_scale_set#platform_fault_domain_count), there is a NOTE section 
 for the `platform_fault_domain_count` parameter that is supposed to show a list of fault domains and regions, but the link is broken.

The NOTE text:
> The number of Fault Domains varies depending on which Azure Region you're using - a list can be found [here](https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/managed-disks-common-fault-domain-region-list.md).

### Actual Behaviour

Clicking on the link in the NOTE section for the `platform_fault_domain_count` parameter link returns a 404 response from Github.

Broken Link URL (returns 404): https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/managed-disks-common-fault-domain-region-list.md

### Steps to Reproduce

1. Navigate to https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/orchestrated_virtual_machine_scale_set#platform_fault_domain_count
2. Click on the link in the NOTE section of this parameter (NOTE text above)
3. See the 404 message appear.

### Important Factoids

N/A

**Comment by rcskosir** [comment]
@chris-zenfolio Thank you for taking the time to open this issue! Presumably that document moved at some point. I have looked around [MicrosoftDocs/azure-docs](https://github.com/MicrosoftDocs/azure-docs) to see if I could find where it moved and I have not been able to. It might be worth you opening an issue on that repo to find where that list has moved to, so that we can update our link on our side. 

In the meantime I did find an issue related to managed disk fault domains that links to some documentation that includes a command that can be used to get the list of fault domains per regions. [MicrosoftDocs/azure-docs/issues/81390](https://github.com/MicrosoftDocs/azure-docs/issues/81390),
https://learn.microsoft.com/en-us/azure/virtual-machines/availability-set-overview

> `az vm list-skus --resource-type availabilitySets --query '[?name==`Aligned`].{Location:locationInfo[0].location, MaximumFaultDomainCount:capabilities[0].value}' -o Table`

**Comment by chris-zenfolio** [comment]
Hi @rcskosir,

I thought this documentation was maintained by Microsoft, hence the bug report.  It's just as easy to remove the link and add your command as a workaround.  I only opened it as a courtesy, not because I actually needed the functionality.
