### ISSUE TITLE
Option `skip_nodes_with_local_storage` default value wrongly documented

### ISSUE THREAD

**Issue by thibaultserti** [hashicorp/terraform-provider-azurerm#25229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.95

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Expected Behaviour

[Microsoft documentation](https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler?tabs=azure-cli#cluster-autoscaler-profile-settings)

**Comment by tombuildsstuff** [comment]
The Terraform Provider itself is defaulting to `true` ([as mentioned in this comment](https://github.com/hashicorp/terraform-provider-azurerm/pull/25230#issuecomment-1994418945)) but the API appears to be forcing this to `false` by default - since we're expecting the default value to be `true` here, this is a bug where we should be ensuring the value is set to `true` by default until the default value for this changes in 4.0 - as such I'm going to tag this as a bug for now.

**Comment by stephybun** [comment]
Closing since this has been completed by #22935
