### ISSUE TITLE
Support for a resource block that can add additional tags outside of resource block

### ISSUE THREAD

**Issue by anwarnk** [hashicorp/terraform-provider-azurerm#25234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

See issue: https://stackoverflow.com/questions/77119777/how-to-update-azure-subscription-tags-with-terraform

We have created some subscriptions outside of our terraform, and would like to create tags for those subscriptions, but this could be for any resource.

### New or Affected Resource(s)/Data Source(s)

azurerm_tags

### Potential Terraform Configuration

```hcl
data "azurerm_subscription" "current" {
}

resource "azurerm_tags" "example" {

  scope = data.azurerm_subscription.current
  tags = {
    Tag1   = example1
    Tag2  = example2
    Tag3 = example3

  }
}
```

**Comment by tombuildsstuff** [comment]
hey @anwarnk 

Thanks for opening this issue.

This has been raised a number of times over the years and unfortunately [for the reasons outlined in this comment](https://github.com/hashicorp/terraform-provider-azurerm/pull/22105#issuecomment-1600530013) we have no plans to introduce a generic tags resource in the provider. Whilst that mostly focused on Resources within a Subscription, it's worth noting that Subscriptions, Management Groups and Tenants behave quite differently to other Resource Manager resources, so it's quite possible that these require the use of a different endpoint to update these, rather than using the generic UpdateTags endpoint.

Since unfortunately we have no plans to support this in the Provider, whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment - but in this instance you should be able to manage the tags for these Subscriptions by importing the Subscription into Terraform and then using the `tags` field to manage these.

Thanks!
