### ISSUE TITLE
New dns_endpoint_type property may delete storage accounts

### ISSUE THREAD

**Issue by oletolshaveics** [hashicorp/terraform-provider-azurerm#25364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.97.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
# No reproduction yet - issue seems potentially dangerous, so I wanted to get this in anyway
```

### Debug Output/Panic Output

```shell
# module.env.azurerm_storage_account.mainstorage must be replaced
-/+ resource "azurerm_storage_account" "mainstorage" {
      + dns_endpoint_type                  = "Standard" # forces replacement
```

### Expected Behaviour

I would expect no changes to the Azure resources, since no changes were made (expect upgrading to 3.97.0)

### Actual Behaviour

A storage account was deleted (forced replacement).

### Steps to Reproduce

I have not tested this reproduction.
1. Create a storage account using azurerm_storage_account (without mentioning "dns_endpoint_type") using AzureRM 3.96.
2. Upgrade to AzureRM 3.97.
3. Run "terraform plan" - the plan should show the storage account being "forced replaced" due to the "dns_endpoint_type".

My apologies for the less than perfect bug report, but I feat this could lead to data loss for people, so I wanted to raise this issue as soon as possible.

The account affected was in a test environment here, so no big deal, but others might not be as lucky.

**Comment by oletolshaveics** [comment]
Got a reproduction working now. Terraform config:
`terraform {
  required_version = ">=0.12"
  
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      
	  # Start out using this version
	  version = "3.96"
	  
	  # After createing the initial resource, comment out the version above and comment in this line
	  #version = "3.97"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "random_string" "ident" {
  length        = 8
  special       = false
  upper			= false
}

resource "azurerm_resource_group" "rg" {
  name     = "AzureRMTest"
  location = "West Europe"
}

resource "azurerm_storage_account" "storage" {
  name                     = format("tf%ssa", random_string.ident.result)
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}`

Steps to reproduce:
1. terraform init
2. terraform apply
3. (Modify the file to not use version 3.96 but 3.97 instead).
4. terraform init -upgrade
5. terraform plan

Last plan (step 5) shows the storage account will be replaced. No changes were exepected.

**Comment by mikazka** [comment]
Same thing on this side and setting it to either value in 3.97 does the same

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/75730081/63cfeadb-f6a2-42b2-a5d8-c5e3b34dbc4b)


![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/75730081/22dbe83a-08b4-45cf-9fb0-6cbe23deb00d)

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/75730081/11935a2f-1be9-4b34-ab6e-a256f1f1503a)

**Comment by PatrickSpies** [comment]
Same here, needs to be fixed quickly..

**Comment by btbaetwork** [comment]
This is what i also observed. The storage accounts that were created with the "old" version of the provider have this property set to "null" (visible when doing az storage account show: 

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/125264860/b080a13b-5d39-41e3-ad65-fff08274d59c)

From my POV it would be necessary to revert that change ASAP to avoid widespread data loss!

**Comment by tombuildsstuff** [comment]
hey @oletolshaveics @PatrickSpies @mikazka @btbaetwork 

Thanks for reporting this issue.

I've taken a look through and have opened #25367 which will fix this issue - we'll look to ship this fix in a patch release once it's been reviewed, however it should be possible to pin to the previous version of the provider (`v3.96.0`) to workaround this in the interim until this is released.

Thanks!

**Comment by SebastianBalle** [comment]
@tombuildsstuff I see the #25367 has been approved. Any idea on when the `v3.97.1` will be released?

**Comment by tombuildsstuff** [comment]
@SebastianBalle the acceptance tests are running atm, once that's done we can trigger the release - should be sometime in the next hour or so

**Comment by tombuildsstuff** [comment]
I've tagged a release for `v3.97.1` (which [is currently running through](https://github.com/hashicorp/terraform-provider-azurerm/actions/runs/8387884515)) - the message above is a little premature but the binaries should be out fairly soon.

**Comment by SebastianBalle** [comment]
@tombuildsstuff  I see you are only building milestone releases for minor versions. Is it intentional that patches are manually released?

**Comment by tombuildsstuff** [comment]
@SebastianBalle it's the standard (automated) release process, I just closed the milestone by hand this time around (hence the comment above being out of order)

**Comment by tombuildsstuff** [comment]
The release is now available - double-checking the `v3.97.1` release (having created this resource on `v3.96.0`) this looks fixed to me:

```
$ terraform plan
╷
azurerm_resource_group.example: Refreshing state... [id=/subscriptions/XXX/resourceGroups/tharvey-devrg9373]
azurerm_storage_account.example: Refreshing state... [id=/subscriptions/XXX/resourceGroups/tharvey-devrg9373/providers/Microsoft.Storage/storageAccounts/tomdevsa726262]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

**Comment by oletolshaveics** [comment]
Same result ("No changes.") for me using 3.97.1. Thank you for getting this resolved quickly!

**Comment by marcindulak** [comment]
> @SebastianBalle the acceptance tests are running atm, once that's done we can trigger the release - should be sometime in the next hour or so

@tombuildsstuff to prevent such problems, would it help if acceptance tests on new azurerm releases were run also against the resources created using the oldest supported azurerm release? Do you expect, or witnessed a problem with terraform removing or changing resources due to changes in resources on Azure side, without any terraform code changes?
I know those are probably unsolvable problems, but would having some kind of tested azurerm compatibility matrix help?

**Comment by tombuildsstuff** [comment]
@marcindulak see [this comment for more details](https://github.com/hashicorp/terraform-provider-azurerm/pull/25367#issuecomment-2014621725) but unfortunately that wouldn't necessarily help.

As alluded to in that comment, ultimately the Storage API not returning the default/implied value when the field isn't configured means that each application needs to know what the default value for that field should be, which crucially can change over time and in each Azure Environment and Region. This means that _any_ application (including the Provider) needs to know internal details about the behaviour of the Storage API - and to keep track of that information over time.

Arguably it _could_ be helpful to do more upgrade testing here, but to be honest that's only patching around the problem - IMO to fix this the Azure API should be returning the value for a field if it's got an implied default value - because otherwise each application (including Azure internal plus any third-party tooling/scripts) is having to make assumptions about the state of the resource without it.

To be honest getting this onto `hashicorp/go-azure-sdk` would be the most useful thing in the short-term, which is what I'm looking into at the moment - since that would have correctly identified this field as optional/nilable rather than implying there's a default value. It wouldn't solve the issue of the API returning a default value of `null`, but it would have allowed us to determine this more easily during PR review - which I believe would have let us caught this otherwise.

**Comment by marcindulak** [comment]
@tombuildsstuff I opened a meta issue https://github.com/hashicorp/terraform-provider-azurerm/issues/25394 to collect possibilities to improve this situation.
