### ISSUE TITLE
Support for async_execution in azurerm_virtual_machine_run_command

### ISSUE THREAD

**Issue by gburkecw** [hashicorp/terraform-provider-azurerm#25487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

For long running VM setup commands, AzureRM supports setting the async_execution property to true. However, the resource azurerm_virtual_machine_run_command defaults this to false and does not allow that configuration to be changed. 

In order to use this resource, I would need to be able to set async_execution to true because my setup takes many hours to restore backups.

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_run_command

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_machine_run_command" "run-setup-sqlvm" {
  virtual_machine_id = azurerm_windows_virtual_machine.vm.id
  name               = "setup-sqlvm"
  location           = var.location
  async_execution   = true

  source {
    script_uri = data.azurerm_storage_blob.setup-sqlvm.url

    script_uri_managed_identity {
      client_id = data.azurerm_user_assigned_identity.sqlvm-setup-identity.client_id
    }
  }
  ...
}
```

**Comment by gburkecw** [comment]
I see that @teowa recently updated this resource, is this something that can be changed easily?

**Comment by tombuildsstuff** [comment]
hey @gburkecw 

As mentioned [in this comment you've commented on](https://github.com/hashicorp/terraform-provider-azurerm/pull/23377#discussion_r1405860250), unfortunately this isn't a behaviour that we're planning to support on this resource.

A design principal of Terraform is that a Resource isn't marked as completed until it's fully provisioned (which in this case would mean that we'd wait for the execution to complete) - as else we'd be tracking a resource which isn't necessarily completed (and thus any dependent resources wouldn't be able to rely on this resource being created).

Whilst you could argue that we could introduce it _in just this one place_, unfortunately as soon as we do it becomes a precedent for usages in other places - where this is far more problematic. It's worth noting that some folks have requested that behaviour in the past which we've similarly opted not to implement, because of the user confusion (and support tickets) it causes.

Ultimately [the question that I raised in that PR (that went unresolved)](https://github.com/hashicorp/terraform-provider-azurerm/pull/23377#pullrequestreview-1749973893) is whether we _should_ support this Resource in Terraform - which I think is still a valid question - this is an API you'd use interactively as your scenario describes - and ultimately Terraform isn't really designed to be used in this manner.

Whilst I appreciate that doesn't help your use-case, you can use any tool for any scenario, but some tools are easier than others - in this case Terraform's guarantees are that a Resource will be marked as provisioned when it returns, as such we need to align with that. In this instance that means that unfortunately we wouldn't introduce a flag to control the asynchronous mode on this Resource - and as such unfortunately I'm going to have to close this feature request for the moment.

Thanks!
