### ISSUE TITLE
Postgresql flexible server gets updated with zone everytime we update our config. Getting the error " `zone` can only be changed when exchanged with the zone specified in `high_availability.0.standby_availability_zone`"

### ISSUE THREAD

**Issue by souravkarmohapatra** [hashicorp/terraform-provider-azurerm#25538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.8

### AzureRM Provider Version

3.56.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "postgresql_flexible_server" {
  name                          = var.name
  resource_group_name           = var.resource_group_name
  location                      = var.region
  version                       = var.server_version
  sku_name                      = var.sku_name
  backup_retention_days         = var.backup_retention_days
  geo_redundant_backup_enabled  = var.geo_redundant_backup_enabled
  authentication {
    active_directory_auth_enabled = true
    password_auth_enabled         = false
  }
  
  dynamic "high_availability" {
    for_each = var.ha_enabled  == true ? toset([1]) : toset([])
    content {
    mode = var.availability
  }
  }

  storage_mb                    = var.storage_mb
  
}
```

### Debug Output/Panic Output

```shell
Error: `zone` can only be changed when exchanged with the zone specified in `high_availability.0.standby_availability_zone`
```

### Actual Behaviour

Whenever we try to add a new flexible server in our terraform config files, the existing server tend to modify during terraform plan. During the actual apply we are getting the error mentioned above.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. It's by TF design since zone and standby_availability_zone would be automatically set at the backend service when they aren't specified. So it has to use ignore_changes or set it explicitly in tf config.

Note: Suggest to use latest azurerm provider. Thanks.

**Comment by tombuildsstuff** [comment]
@souravkarmohapatra as @neil-yechenwei has mentioned this behaviour is intentional, [as per this note in the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server#zone):

> Azure will automatically assign an Availability Zone if one is not specified. If the PostgreSQL Flexible Server fails-over to the Standby Availability Zone, the zone will be updated to reflect the current Primary Availability Zone. You can use Terraform's ignore_changes functionality to ignore changes to the zone and high_availability[0].standby_availability_zone fields should you wish for Terraform to not migrate the PostgreSQL Flexible Server back to it's primary Availability Zone after a fail-over.

As such you'll either need to explicitly set a value for the `zone` and `standby_availability_zone` fields - or if you'd like to use the Azure specified Zone then you'll need to use `ignore_changes` on these fields - else these'll be flagged as a diff/for removal, as is happening here.

Since this is a configuration question which'll be fixed by updating the config as per above rather than a bug in the Azure Provider, I'm going to close this issue for the moment - but should you have further configuration questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
