### ISSUE TITLE
Can not deploy Azure resources to Spain Central region

### ISSUE THREAD

**Issue by JoelCanteroGCO** [hashicorp/terraform-provider-azurerm#25817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

last

### AzureRM Provider Version

last

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "mlw-rg" {
  name = "rg-${local.project_name}-mlw-${local.environment}"
  location = "spaincentral"
}

resource "azurerm_machine_learning_workspace" "example" {
  name                    = local.machine_learning_workspace_name
  location                = azurerm_resource_group.mlw_rg.location
  resource_group_name     = azurerm_resource_group.mlw_rg.name
  application_insights_id = azurerm_application_insights.this.id
  key_vault_id            = azurerm_key_vault.this.id
  storage_account_id      = azurerm_storage_account.this.id
  container_registry_id   = azurerm_container_registry.this.id
  public_network_access_enabled = local.public_network_access_enabled

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Resource Group "rg-gen008-mlw-dev": resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LocationNotAvailableForResourceGroup" Message="The provided location 'spaincentral' is not available for resource group. List of available regions is 'eastasia,southeastasia,australiaeast,australiasoutheast,brazilsouth,canadacentral,canadaeast,switzerlandnorth,germanywestcentral,eastus2,eastus,centralus,northcentralus,francecentral,uksouth,ukwest,centralindia,southindia,jioindiawest,italynorth,japaneast,japanwest,koreacentral,koreasouth,mexicocentral,northeurope,norwayeast,polandcentral,qatarcentral,swedencentral,uaenorth,westcentralus,westeurope,westus2,westus,southcentralus,westus3,southafricanorth,australiacentral,australiacentral2,israelcentral,westindia'."
│ 
│   with module.azure-machine-learning.azurerm_resource_group.mlw_rg,
│   on .terraform/modules/azure-machine-learning/modules/azure-machine-learning/main.tf line 59, in resource "azurerm_resource_group" "mlw_rg":
│   59: resource "azurerm_resource_group" "mlw_rg" {
```

### Expected Behaviour

Deploy resources to Spain Central region

### Actual Behaviour

It does not happen

### Steps to Reproduce

Our tenant is able to deploy resources to Spain Central but when I assign location to "spaincentral" in a resource group with Terraform, as it refers to another resource group that we have deployed in this region, it is not allowed.

**Comment by JoelCanteroGCO** [comment]
Hello @rcskosir, any news about this?

Thank you

**Comment by tombuildsstuff** [comment]
hi @JoelCanteroGCO 

Per [the Azure documentation](https://azure.microsoft.com/en-us/explore/global-infrastructure/geographies/#geographies) the `Spain Central` region is still "coming soon" and so doesn't appear to be generally available yet:

![Screenshot 2024-05-21 at 17 40 05](https://github.com/hashicorp/terraform-provider-azurerm/assets/666005/c024de12-744e-45d2-a4d4-d64059247cb6)

Whilst you may have access to/resources deployed within this Region, until it's generally available there may be some additional configuration required for the Service Principal/User Account in question, so I'd suggest reaching out to Azure Support who should be able to provide further information. The error message that you've quoted above is being returned from the Azure API, so whilst Terraform has support for this region, ultimately Azure Support (or your contact who granted access to this "coming soon" region) should be able to provide further information here.

Note that if you're using the Azure CLI to authenticate to Terraform, if you don't specify the `subscription_id` then we'll use the default Subscription ID from the Azure CLI, which could be a potential source of this issue - if one subscription has access to this region but another doesn't? You should be able to confirm this by checking the `subscription_id` being returned from [the `azurerm_client_config` data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/client_config).

However since the AzureRM Provider has support for this region and this error is coming from the Azure API, I'm going to close this issue for the moment - but as mentioned above Azure Support should be able to clarify what's going on here since this error message is coming from the Azure API.

Thanks!
