### ISSUE TITLE
Bug #17930 was closed without solution by bot: virtual_network_subnet_id is always reset when connecting to virtual network using azurerm_app_service_virtual_network_swift_connection

### ISSUE THREAD

**Issue by arne21a** [hashicorp/terraform-provider-azurerm#25974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.4.6 on linux_arm64

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_virtual_network_swift_connection

### Terraform Configuration Files

```hcl
See: [virtual_network_subnet_id is always reset when connecting to virtual network using azurerm_app_service_virtual_network_swift_connection](https://github.com/hashicorp/terraform-provider-azurerm/issues/17930)
```

### Debug Output/Panic Output

```shell
See: [virtual_network_subnet_id is always reset when connecting to virtual network using azurerm_app_service_virtual_network_swift_connection](https://github.com/hashicorp/terraform-provider-azurerm/issues/17930)
```

### Expected Behaviour

The bug [virtual_network_subnet_id is always reset when connecting to virtual network using azurerm_app_service_virtual_network_swift_connection](https://github.com/hashicorp/terraform-provider-azurerm/issues/17930) was closed by a bot without a solution. 
This issue persists and has many upvotes. Please reopen.

**Comment by tombuildsstuff** [comment]
@arne21a as explained [in this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/17930#issuecomment-2040031482) there isn't a bug here - you need to use `ignore_changes` to ignore this field when using the separate `azurerm_app_service_virtual_network_swift_connection` resource.

Since this is a configuration question rather than a bug in the Provider I'm going to close this issue - but as mentioned in the linked comment above, and [in the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app#virtual_network_subnet_id) - you need to either define this field inline and not use the `azurerm_app_service_virtual_network_swift_connection` resource - or use `ignore_changes` on this field when using the `azurerm_app_service_virtual_network_swift_connection` resource.

Thanks!

**Comment by arne21a** [comment]
Thanks for your quick answer, but i fear that I feel similar to the reactions on the suggested answer. The current behaviour was an issue for multiple people and continues to be one.

The current implementation of the CAF supermodule by microsoft is also affected.
See: https://github.com/aztfmod/terraform-azurerm-caf/issues/1975
Adding a lifecycle policy prevents us from removing or changing the value after creation.

To me this issue looks similar to this one: https://github.com/hashicorp/terraform-provider-azurerm/issues/24681

If there are attributes which can be managed from somewhere else like azure policy or other terraform resources, there needs to be an option to **conditionally** ignore changes. Not being able to do this will result in issues when terraform is part of a bigger solution.
