### ISSUE TITLE
Breaking changes in minor releases e.g. 3.105.0 

### ISSUE THREAD

**Issue by RolfMoleman** [hashicorp/terraform-provider-azurerm#26101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

1.5.0

### Affected Resource(s)/Data Source(s)

Azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
N/a
```

### Debug Output/Panic Output

```shell
N/a
```

### Expected Behaviour

A major release

### Actual Behaviour

A minor release with breaking changes

### References

[Semver.org](https://www.semver.org)

Surely the changes in 3.105.0 should have become 4.0.0?

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this. We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions or discussions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
