### ISSUE TITLE
Import Azure FrontDoor endpoints 

### ISSUE THREAD

**Issue by Lars-Kolsaker** [hashicorp/terraform-provider-azurerm#26423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

3.108.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_endpoint

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    storage_account_name = "stadpstatestorage"
      container_name = "terraform-state"
      key = "frontdoor.state"
  }
 required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.108.0"
    }
  }
}

import {
  to = azurerm_cdn_frontdoor_endpoint.b2cfrontdoor_migrated
  id = "/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/rg-adpb2c-westeurope-dev/providers/Microsoft.Cdn/profiles/avonova-b2c-frontdoor-endpoint-dev-migrated/afEndpoints/avonova-b2c-frontdoor-endpoint-dev"
}
```

### Debug Output/Panic Output

```shell
Error: ID was missing the `afdEndpoints` element
```

### Actual Behaviour

Trying to import a Azure FrontDoor service that has been migrated from Classic to Standard, but struggling with importing endpoints.
As far as can see the id is in accordance with the documentation https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_endpoint#import

**Comment by tombuildsstuff** [comment]
hey @Lars-Kolsaker 

Taking a look at this, this is happening because the incorrect segment is being specified, you're specifying (just the relevant segment):

> /afEndpoints/

whereas we're expecting:

> /afdEndpoints/

And as such the Import is failing since we can't find this segment - so you should be able to fix this by adding the missing `d` to the segment:

> "/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/rg-adpb2c-westeurope-dev/providers/Microsoft.Cdn/profiles/avonova-b2c-frontdoor-endpoint-dev-migrated/afdEndpoints/avonova-b2c-frontdoor-endpoint-dev"

Would you be able to take a look and see if that works for you here? Since this should be resolved by updating the segment being specified, I'm going to close this issue for the moment - but if that doesn't work for you then please let us know and we'll take another look.

Thanks!

**Comment by Lars-Kolsaker** [comment]
Thanks. See that now 😳
