### ISSUE TITLE
subnet - private_endpoint_network_policies wrong default value

### ISSUE THREAD

**Issue by agyss** [hashicorp/terraform-provider-azurerm#26967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

The key `private_endpoint_network_policies` on a subnet is described as having default value `Disabled`. However, that's not true and it defaults to 'Enabled'. This is not only different from the described behavior, but also different from default behavior in the protal UI. 

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.3

### AzureRM Provider Version

3.114.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "spoke" {
  name = "my-snet"
  resource_group_name  = "myrg"
  virtual_network_name = "myvnet"
  address_prefixes     = ["10.2.3.4/24"]
  # private_endpoint_network_policies = "Disabled" # Uncomment and see after first apply how it changes
}
```

### Debug Output/Panic Output

```shell
private_endpoint_network_policies              = "Enabled" -> "Disabled"
```

### Expected Behaviour

No changes

### Actual Behaviour

private_endpoint_network_policies              = "Enabled" -> "Disabled"

### Steps to Reproduce

1. terraform apply
2. uncomment code
3. terraform plan

**Comment by stephybun** [comment]
Thanks for opening this issue @agyss. 

Changing the default value of a property is considered a breaking change in Terraform so this change would need to be done in a major version. Looking at the code it seems this has already been done and  thedefault value for `private_endpoint_network_policies` will become `Disabled` in the version 4.0 of the provider. 

https://github.com/hashicorp/terraform-provider-azurerm/blob/139b27f749f92e05b4683586bfcc329557a27594/internal/services/network/subnet_resource.go#L215-L220

I'm going to close this since this will be resolved when the next major release goes out.

**Comment by agyss** [comment]
@stephybun Thanks for the fast confirmation. Wouldn't it make sense to:
 - list it in the release notes for the beta of v4? https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.114.0
 - At least adapt the documentation for v3... as it is obviously wrong? And highlight that it derives from described default behavior in https://learn.microsoft.com/en-us/azure/private-link/disable-private-endpoint-network-policy?tabs=network-policy-portal? The very first sentence there is **By default, network policies are disabled for a subnet in a virtual network**

**Comment by stephybun** [comment]
Appreciate the suggestions @agyss!

> list it in the release notes for the beta of v4?

We follow a certain process that has developed over the previous major releases the provider has done. All breaking changes for a major release, are detailed in the [upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide) (as it stands this one is actually missing at the moment but we will do another sweep and add that before the release goes out). The release notes should really only contain changes that will affect users when upgrading to that particular release. In addition some weeks, particularly in the lead up to a major version, there are simply too many breaking changes added that it would seem unnecessarily noisy to point them all out in the release notes and risk obscuring information that is actually relevant at that point in time.

> At least adapt the documentation for v3

The default specified for the property in the docs should not have gone out yet since as you've correctly pointed out it's wrong at the moment. Unfortunately these mistakes do slip through. We will happily accept PRs to correct this, just bearing in mind that the next major release is targeted for mid to end August, so it would need to updated back to the way it is now to reflect the correct behaviour.

**Comment by agyss** [comment]
Thanks for the detailed description!

I understand the point release not wise, breaking changes in the upgrade guide are definitely the better place 👍 

> The default specified for the property in the docs should not have gone out yet since as you've correctly pointed out it's wrong at the moment. Unfortunately these mistakes do slip through.
That's normal - too easy to miss such a thing, nobody to blame there. 

I'm not very familiar with how documentation and code for releases match here. I would have expected it's rather easy to adapt the documentation even for old versions and add a note there saying (something like):
`# Attention - default value for private_endpoint_network_policies is **enabled**. Will be brought inline with official documentation and default behavior on other tools (portal, cli) in v4.0. Specify explicitly until then.`

Anyhow, seems it's a bigger thing to adapt the documentation for the older versions/releases or maybe not possible at all if they are linked. 🤞 that everybody who uses `azurerm_subnet` is able to upgrade to v4 in the next weeks/months and does not loose much time with it.
