### ISSUE TITLE
`azurerm_cosmosdb_sql_container` documentation lists `partition_key_paths` as required but still references `partition_key_path`

### ISSUE THREAD

**Issue by samanthawalter** [hashicorp/terraform-provider-azurerm#27028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates"; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Documentation for `azurerm_cosmosdb_sql_container` lists `partition_key_paths` as required but still uses `partition_key_path` in the example and in the `autoscale_settings` description.

* Since `partition_key_path` is valid until version 4, it should still be documented but with details about the `partition_key_paths` superseding it. Or, at the least, acknowledge the deprecation of `partition_key_path` in the description of `partition_key_paths`.
* `partition_key_path` should be replaced with `partition_key_paths` in the existing example. https://github.com/hashicorp/terraform-provider-azurerm/blob/6a2cf743e482c3d8ad715a584135acf7948aec07/website/docs/r/cosmosdb_sql_container.html.markdown?plain=1#L32
* The `autoscale_settings` description should be updated to reference `partition_key_paths` in addition to `partition_key_path`. https://github.com/hashicorp/terraform-provider-azurerm/blob/6a2cf743e482c3d8ad715a584135acf7948aec07/website/docs/r/cosmosdb_sql_container.html.markdown?plain=1#L80

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_sql_container

### References

This would prevent issues like: https://github.com/hashicorp/terraform-provider-azurerm/issues/26961

Documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_sql_container

**Comment by stephybun** [comment]
Thanks for raising this issue @samanthawalter.

Our process for deprecating properties is to return a deprecation message to the user when running Terraform if their config contains a deprecated property, typically with details as to whether it has been superseded by another property. We also remove the deprecated property from the documentation to discourage use of them. 

We do not add notes or specify the deprecation of properties in the docs since this is usually redundant at this point and in some cases, such as for complicated resources like Kubernetes, App Service, VMSS etc. it tends to unnecessarily bloat the documentation which is already large and can be difficult to navigate.

You're right in that the deprecated property should have been replaced in the example as well but these are sometimes overlooked when doing the deprecation and reviewing. 

We usually do a final sweep cleaning up/replacing/removing/renaming properties in the documentation and examples in the week before a major release (at this point we're targeting for next week) so this will be fixed soon. We are happy to accept PRs correcting this now though!
