### ISSUE TITLE
azurerm_dns_zone registration_virtual_network_id should be a string?

### ISSUE THREAD

**Issue by pixelicous** [hashicorp/terraform-provider-azurerm#2926]
Hi,

From the following link:
https://docs.microsoft.com/en-us/azure/dns/private-dns-overview

It seems like its only possible to attach one vnet as registration vnet:
Only one registration virtual network is allowed per private zone.

But according to azurerm_dns_zone documentation this attribute should be a list. Shouldn' this be changed??
registration_virtual_network_ids - (Optional) A list of Virtual Network ID's that register hostnames in this DNS zone. This field can only be set when zone_type is set to Private.

**Comment by tombuildsstuff** [comment]
hi @pixelicous 

Thanks for opening this issue :)

Whilst in this instance this is currently limited to 1, the Azure API takes a list of these ID's (presumably for future development once the Preview's done, I'm unsure) - as such whilst we could adapt this to take a string I don't believe that'd be the best approach here.

Instead we could investigate only allowing a single element in this list at this time, until more items are supported at which point we could revert this - which I feel like ultimately is the better approach here (since this matches the API) - WDYT?

Thanks!

**Comment by pixelicous** [comment]
@tombuildsstuff Hey, sorry it took time to get back to you on this one.. i agree with your approach, and with the underlying infrastructure and how they built it, i also believe they won't change it anytime soon

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
