### ISSUE TITLE
Add Node.JS Language Support in azurerm_app_service

### ISSUE THREAD

**Issue by opticyclic** [hashicorp/terraform-provider-azurerm#4144]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There doesn't seem to be a way of adding a NodeJS App Service as there is no mention of NodeJS on the terraform documentation.

[This PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2973) added an example by adding:

      site_config {
        linux_fx_version = "NODE|10.14"
      }

However, there is no mention of it on the [documentation](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#linux_fx_version).

Furthermore, if I want to add Node 8.10 web app from the Azure portal the only option available to me is a Windows O/S so specifying linux_fx_version doesn't make any sense.

### New or Affected Resource(s)

* azurerm_app_service

### References

* #2183
* https://github.com/terraform-providers/terraform-provider-azurerm/pull/2973

**Comment by opticyclic** [comment]
FYI: If you use the Free/F1 SKU, the [example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/app-service/linux-nodejs/main.tf) fails with 

> Error: Error creating App Service "terraform-dev-app" (Resource Group "terraform-dev_rg"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

It succeeds if you use the Standard/S1 sku in the example.

However, if you try to deploy a different version of nodejs it succeeds but with the wrong version of nodejs deployed:

      site_config {
        linux_fx_version = "NODE|8.10"
      }

SSH greets you with:

      _____
      /  _  \ __________ _________   ____
     /  /_\  \___   /  |  \_  __ \_/ __ \
    /    |    \/    /|  |  /|  | \/\  ___/
    \____|__  /_____ \____/ |__|    \___  >
            \/      \/                  \/
    A P P   S E R V I C E   O N   L I N U X
    
    Documentation: http://aka.ms/webapp-linux
    NodeJS quickstart: https://aka.ms/node-qs
    NodeJS Version : v10.14.2
    
    root@fa46c997d6aa:/home/site/wwwroot#

**Comment by opticyclic** [comment]
It took me all day, but there is an unintuitive way of getting Node running as in the portal.

    resource "azurerm_app_service_plan" "app-plan" {
      name                = "${var.prefix}-app-plan"
      resource_group_name = var.resource_group_name
      location            = var.resource_group_location
    
      sku {
        tier = "Free"
        size = "F1"
      }
    }
    
    resource "azurerm_app_service" "app-service" {
      name                = "${var.prefix}-app"
      resource_group_name = var.resource_group_name
      location            = var.resource_group_location
      app_service_plan_id = azurerm_app_service_plan.app-plan.id
    
      app_settings = {
        #The portal and az cli list "8.10" as the supported version.
        #"8.10" doesn't work here!
        #"8.10.0" is the version installed in D:\Program Files (x86)\nodejs
        "WEBSITE_NODE_DEFAULT_VERSION" = "8.10.0"
      }
    }

Note how the version is not the same as the supported version in the portal or the az cli.

Also note that when you export the template from the portal you see the node version as a property:

                "netFrameworkVersion": "v4.0",
                "phpVersion": "5.6",
                "pythonVersion": "",
                "nodeVersion": "8.10.0",
                "linuxFxVersion": "",

Which highlights even more the need to have node as an option in terraform.

**Comment by Reddy1990** [comment]
Hi , I'm thinking of building Linux app service with Node Js , Does Terraform support this? Is this feature available now?

**Comment by ericis** [comment]
This is an interesting thread. I could use some help testing a few scenarios as I develop this tutorial:
https://github.com/ourchitecture/patterns-and-tutorials/tree/main/src/tutorials/node/azure#readme

Windows vs. Linux. Standard vs. Free. Sounds like there could definitely be better docs directly from `azurerm` teams too.

**Comment by simonbrady** [comment]
Terraform does support this, but the Azure docs and platform behaviour are a confusing mess. Key insight from [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/47749) is that the list of available runtime versions is limited and subject to change, so you need to use `az webapp list-runtimes` or `az webapp list-runtimes --linux` to see what's available. Terraform doesn't validate the runtime version string, so if you specify an unsupported version [demons may fly out your nose](http://catb.org/jargon/html/N/nasal-demons.html).

[This code](https://gist.github.com/simonbrady/ca39e44f15f09f03778dc88fc2f86b72) demonstrates creating Node.js App Service instances on both Windows and Linux, and has been tested with the [quickstart](https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs) from the App Service docs.

Linux-hosted runtimes seem to behave reasonably as long as you specify a supported `linux_fx_version`. After the App Service is created the portal will show the right Node runtime under Configuration -> General Settings -> Stack Settings, although you'll need to use `az webapp ssh` or have your app output the value of `process.version` to find exactly which point release you have. When I tested it I got:
|`linux_fx_version`|Actual runtime|
|---|---|
|NODE\|10.1|10.1.0|
|NODE\|10.6|10.23.0 (not a typo)|
|NODE\|10.14|10.14.2|
|NODE\|10-lts|10.23.0|
|NODE\|12-lts|12.19.0|
|NODE\|14-lts|14.15.1|

I don't know why 10.6 gives you a 10.23 runtime, but otherwise it makes sense.

Windows-hosted runtimes are more confusing, so unless you need one or enjoy pain I'd suggest going with Linux. As well as a supported value of `windows_fx_version` you need to specify the right value for the `WEBSITE_NODE_DEFAULT_VERSION` app setting (if you leave it out, you'll get a 6.9.1 runtime regardless of what you asked for). The only way I've found to determine the right value is to first create an App Service with `az webapp create -r` and pass the runtime string you plan to use (e.g. `az webapp create -r "node|10.14" ...`). You can then look in the portal under Configuration -> Application Settings to see what value the CLI sets, and include that in your Terraform code.

The values I've seen make sense except for 10.10:
|`windows_fx_version`|`WEBSITE_NODE_DEFAULT_VERSION`|Actual runtime|
|---|---|---|
|node\|10.6|10.6.0|10.6.0|
|node\|10.10|10.0.0|10.14.1|
|node\|10.14|10.14.1|10.14.1|
|node\|12-lts|12.13.0|12.13.0|

Again I can't explain the anomaly with 10.10, so you may as well specify 10.14 since that's what you'll get anyway. Another weird thing with Windows runtimes is that the portal doesn't show a Node runtime under General Settings, let alone the version. Creating the App Service with Terraform gives a .NET runtime in the portal, and creating it with the CLI gives you a blank.

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
