### ISSUE TITLE
Web Apps - Virtual Network Connection

### ISSUE THREAD

**Issue by mybayern1974** [hashicorp/terraform-provider-azurerm#4332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Source service api: [https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdatevnetconnection](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdatevnetconnection)

### New or Affected Resource(s)

* azurerm_app_service_virtual_network_connection

### Potential Terraform Configuration

to be designed

**Comment by njuCZ** [comment]
since the Virtual Network Connnction API and Virtual Network Connection Gateway API [#4333](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4333) need to work together to provide the function: gateway required virtual network connection integration, please refer to this PR [](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4458)

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
