### ISSUE TITLE
azurerm_template_deployment Object Output support

### ISSUE THREAD

**Issue by JustinGrote** [hashicorp/terraform-provider-azurerm#4565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Now that 0.12 natively supports objects, the output attribute of the azurerm_template_deployment should support them too. It can just take the json object output and do a jsondecode on it to make it a terraform object.

### New or Affected Resource(s)

* azurerm_template_deployment

**Comment by tombuildsstuff** [comment]
hi @JustinGrote 

Thanks for opening this issue.

Whilst Terraform Core now exposes functionality for "objects" within Terraform Configuration - unfortunately Terraform Core's Schema is defined statically ahead of time - (whilst we could use a Key-Value Pair the Values all need to be of the same type - currently a String).

That said - since we're exposing this information as a String it should be possible to serialize the values as JSON if they're not a string/int (which we cast to a string today) - which would allow users to use the `jsondecode` function to decode them as required, which I believe should solve this - WDYT?

Thanks!

**Comment by JustinGrote** [comment]
I'd be totally fine with that, if an "object" of ARM is output to a string
output: entry, then it should send the json representation so it can be
jsondecoded or "rehydrated" into terraform to work with. It would simplify
pulling multiple attributes from a created output rather than having to
create an explicit output for every individual property.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
