### ISSUE TITLE
azure datalake gen2 networking 

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-azurerm#4644]
_This issue was originally opened by @wsf11 as hashicorp/terraform#23109. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
### Terraform Version
```
Terraform v0.12.10
```

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "this" {
  name     = "exampleresourcegroup"
  location = "West US"
}
resource "azurerm_virtual_network" "this" {
  name                = "${azurerm_resource_group.this.name}-basevnet"
  location            = "${azurerm_resouce_group.this.location}"
  resource_group_name = "${azurerm_resource_group.this.name}"
  address_space       = ["10.7.29.0/29"]
}

resource "azurerm_subnet" "this" {
  name                 = "${azurerm_resource_group.this.name}-base"
  resource_group_name  = "${azurerm_resource_group.this.name}"
  virtual_network_name = "${azurerm_virtual_network.this.name}"
  address_prefix       = "10.7.29.0/29"
  service_endpoints    = [ "Microsoft.Storage"]
}
resource "azurerm_storage_account" "this" {
  name                     = "examplestorageaccount"
  resource_group_name      = "${azurerm_resource_group.this.name}"
  location                 = "${azurerm_resouce_group.this.location}"
  account_kind             = "StorageV2"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  is_hns_enabled           = "true"

  # Associates SA under VNet
  network_rules {
    default_action             = "Deny"
    bypass                     = ["AzureServices"]
    virtual_network_subnet_ids = ["${azurerm_subnet.this.id}"]
  }
}

resource "azurerm_storage_data_lake_gen2_filesystem" "this" {
  name               = "${azurerm_resource_group.this.name}"
  storage_account_id = azurerm_storage_account.this.id
}
```

### Expected Behavior
The storage data lake gen2 account should be created under the storage account in the specified VNet. 

### Actual Behavior
Since we are denying traffic to the Storage Account, and the resources are run sequentially, we are denied `PUT` access to the Storage Account. 

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. Copy & paste into a .tf file
2. `terraform init`
2. `terraform apply`

**Comment by r0bnet** [comment]
Hey @wsf11, this looks like a chicken-egg problem. In other words we have a circular dependency here which is blocking you from doing what you want to achieve.

One solution could be to extract the network rules into an own resource. Then this resource could depend on the filesystem and will be created only after it's "initialized". Since the rules are not an own resource this isn't possible right now but could be implemented.

A workaround could be (and that's what we are doing in my company) to add the subnet where the deployment is run. In our case we add the subnet where our CI/CD system is running which then has the required access to the account.
Another solution might be to add your IP address from where you are running the deployment and remove it afterwards manually (add and `ignore_changes` to avoid that TF wants to change it back).

Is any of the above workarounds a viable option for you?

**Comment by wsf11** [comment]
Hey @r0bnet , 

The network rule being extracted into its own resource sounds like a good idea. My initial thoughts were to put a VNet resource rule inside ADLS, as seen with [SQL VNet rules](https://www.terraform.io/docs/providers/azurerm/r/sql_virtual_network_rule.html. But if the network rule was extracted, this would save implementation for specific resource vnet rules having to be implemented for each resource. 

This TF script in particular is being used for local dev environments, so allowing access for just the IP where it is being run seems to be the best option. However, I still feel like there should be either a better way such as creating a VNet Network Rule resource

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
