### ISSUE TITLE
Feature Request: In DevTest Lab, add the possibility to use custom image for VM's creation

### ISSUE THREAD

**Issue by matsvei-rahachou** [hashicorp/terraform-provider-azurerm#5146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For now, during creation VM in Azure DevTest Lab, it's possible to use only the official gallery images. 

The **gallery_image_reference** block supports the next fields: _offer_, _publisher_, _sku_ and _version_. If these fields will be filled by information from custom image (in Azure, it's possible to create and attach shared gallery with custom images to DevTest Lab, and use such images for VM's creation in this Lab), for example:

```hcl
gallery_image_reference {
     offer = "CustomServer"
     publisher = "MatveyRogachev"
     sku = "2016"
     version = "latest"
 }
```

during _terraform apply_ command, it will return the next error:

```hcl
Error: Error creating/updating DevTest Windows Virtual Machine "TRF-TEST-VM" (Lab "TRF-lab" / Resource Group "TRF-labRG"): dtl.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PolicyViolated" Message="Requested gallery image is not authorized for this lab.."
```

The VM could be successfully created with the help of specified image via Azure Portal, or Azure ARM templates. 

It would be nice to have the possibility to use _id_ field in **gallery_image_reference** block for selecting the custom image, like it's working in **azurerm_virtual_machine**, or just fix the ability to use existing fields for custom images.  

### New or Affected Resource(s)

* azurerm_dev_test_windows_virtual_machine

### Potential Terraform Configuration

```hcl
gallery_image_reference {
    id = /subscriptions/subscription_id/resourcegroups/trf-lbrg/providers/microsoft.devtestlab/labs/trf-lab/sharedgalleries/trfimagegallery/sharedimages/trf-custom-image 
  }
```

### References

- https://www.terraform.io/docs/providers/azurerm/r/dev_test_windows_virtual_machine.html
- https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html

**Comment by Peleke** [comment]
Seconding this request. I need this feature for my current project, and I presume this would be supremely useful for anyone else working with DevTest Labs through Azure.

I have a few questions as to how this could be implemented. If this is something the core team thinks is worth the effort and can provide some feedback on my notes, I'd love to help develop a fix.

### Azure API

In particular, I took a look at some of the Azure docs, the source for this provider, and the [dtl package](https://github.com/Azure/azure-sdk-for-go/tree/master/services/devtestlabs/mgmt/2016-05-15/dtl) used to interface with the API.


It seems like we'd have to
- [Enable a DevTest Lab to source base images from a shared image gallery (SIG)](https://docs.microsoft.com/en-us/azure/lab-services/configure-shared-image-gallery)
- Link the DevTest Lab lab to an existing SIG
- From there, select lab VMs by specifying the shared image ID, presumably from the SIG.

I say "presumably" because the documentation doesn't clarify whether the shared image ID must correspond only to machines on the marketplace or in the linked SIG, but I can't imagine that this isn't the constraint.

Enabling a DevTest Lab to source images from a SIG and specifying the gallery to link it to can be achieved with a [`PUT` request to `Microsoft.Compute/labs/{labName}/sharedgalleries/{galleryName}`](https://docs.microsoft.com/en-us/azure/lab-services/configure-shared-image-gallery) with the following contents:

```javascript
"properties": {
  // Snip...
  "galleryId": "XXXX",
  "allowAllImages": "Enabled"
}
```

The documentation isn't explicit about how to specify a custom image ID to add to the lab, but the bottom of [this reference](https://docs.microsoft.com/en-us/azure/lab-services/add-vm-use-shared-image) seems to explain that you can do this via `PUT` to `Microsoft.Compute/galleries/{galleryID}/virtualmachines/{vm-name}`, but it doesn't name this endpoint explicitly. The payload would contain:

```javascript
"properties": {
  // Snip...
  "SharedImageId": "XXXXX"
}
```

### Implementing in Terraform
It looks like `func resourceArmDevTestLabCreateUpdate` in `terraform-provider-azurerm/azurerm/internal/services/devtestlabs/resource_arm_dev_test_lab.go` is responsible for generating the `PUT` request to `Microsoft.Compute/labs/{labName}`. It defines the following request parameters:

```go
	parameters := dtl.Lab{
		Location: utils.String(location),
		Tags:     tags.Expand(t),
		LabProperties: &dtl.LabProperties{
			LabStorageType: dtl.StorageType(storageType),
		},
	}
```

...I presume something like the following would have the effect of enabling the specified SIG:

```go
	parameters := dtl.Lab{
		Location: utils.String(location),
		Tags:     tags.Expand(t),
		LabProperties: &dtl.LabProperties{
			LabStorageType: dtl.StorageType(storageType),
			GalleryId: imageId,
			AllowAllImages: true,
		},
	}
```

In `azure-sdk-for-go`, `devtestlabs/mgmt/2016-05-15/dtl/models.go` contains types like `LabProperties`, LabPropertiesFragment`, `LabResourcesCostProperties`, etc.

Creating a new such properties type feels like a natural extension of this pattern:

```go
type SharedImageGalleryProperties struct {
	// AllowAlImages - Whether to enable this lab to deploy images from a shared image galler
       AllowAlImages boolean `json:"allowAllImages,omitempty"`
       // GalleryID - Resource ID of the SIG to link this lab to. Must be supplied if `AllowAllImages` is true.
      GalleryID int `json:"galleryId,omitempty"`
}
```

...But I suppose these could also be injected into `LabProperties` if they don't warrant their own type.

That should allow us to start using custom images in the DevTest Lab. It looks like the important change here would be updating `dtl.LabVirtualMachineProperties` to include a `SharedImageID` field. We'd also have to update code somewhere else to enforce specifying either the `gallery_image_reference` block _or_ a `SharedImageId`.

We would then update `resource_arm_dev_test_linux_virtual_machine` and `resource_arm_dev_test_windows_virtual_machine` to pass the user-specified `SharedImageID` when passing parameters:

```go
// AND: `func resourceArmDevTestWindowsVirtualMachineCreateUpdate(d *schema.ResourceData, meta interface{}) error`...
func resourceArmDevTestLinuxVirtualMachineCreateUpdate(d *schema.ResourceData, meta interface{}) error {
        // Snip...
	parameters := dtl.LabVirtualMachine{
		Location: utils.String(location),
		LabVirtualMachineProperties: &dtl.LabVirtualMachineProperties{
                 // Snip...
                  SharedImageID: utils.String(sharedImageID)
                }
```

Again — I'd appreciate feedback as to whether this seems legitimate, or if I'm aiming in entirely the wrong direction. If this seems right, though, I'm happy to implement the fix.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
