### ISSUE TITLE
Support for something like required_resource_access in azurerm_user_assigned_identity

### ISSUE THREAD

**Issue by amasover** [hashicorp/terraform-provider-azurerm#5234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I don't know if this is something that's possible to fix in the azurerm provider. It might be that it's a kind of thing that needs to be supported in Azure first. So I apologize in advance if this issue is misplaced.

On most resources in the `azuread` provider, there is the following note:

> NOTE: If you're authenticating using a Service Principal then it must have permissions to both `Read and write owned by applications` and `Sign in and read user profile` within the `Windows Azure Active Directory API`.

If you want to use Terraform to set up an application that has those permissions, it's pretty straightforward using the `required_resource_access` block in the `azuread_application` resource. However, if you want to authenticate to the `azuread` provider using a service principal that belongs to a Managed Identity, things get very tricky. The only way that I found to set up those permissions is to:

1. Create a managed identity and get its service principal id
2. Run the `New-AzureADServiceAppRoleAssignment` powershell cmdlet to add the `Application.ReadWrite.All` permission, referencing the principal id from step 1
3. In the Azure AD Microsoft Graph API, send a POST to oauth2PermissionGrants, referencing the principal id from step 1

Of course it would be much easier to do all of this in Terraform.

I think this might be impossible though, because:
* When you create an Application through the Azure Portal, you get a bunch of options for API access. It seems this is what correlates to the `required_resource_access` block in `azuread_application`.
* When you create a Managed Identity through the Azure Portal, there's nowhere to specify any sort of Microsoft Graph API permissions. It seems this isn't something that the Azure Resource Manager really supports...
* There's a role in Azure AD called `Application Administrator` that I think should allow users to add Microsoft Graph permissions to Applications. However, when I was trying to add permissions directly to a Managed Identity's service principal, I pretty much needed Global Administrator (at least needed Privileged Role Administrator). So I think `Application Administrator` might only apply to applications, not to service principals.

I'm mostly creating this issue because I'm curious if my hunch is correct that this is a pain point coming from upstream.

### New or Affected Resource(s)

* azurerm_user_assigned_identity

### Potential Terraform Configuration

```hcl
resource "azurerm_user_assigned_identity" "managed_identity" {
  name = "example"

  required_resource_access {
    # the Azure AD Graph
    resource_app_id = "00000002-0000-0000-c000-000000000000"

    # The "Sign in and read user profile" permission. Get ID from:
    # az ad sp show --id 00000002-0000-0000-c000-000000000000 --query "oauth2Permissions[?value=='User.Read']"
    resource_access {
      id = "311a71cc-e848-46a1-bdf8-97ff7156d8e6"
      type = "Scope"
    }

    # The "Read and write all applications" permission. Get ID from:
    # az ad sp show --id 00000002-0000-0000-c000-000000000000 --query "appRoles[?value=='Application.ReadWrite.All']"
    resource_access {
      id = "1cda74f2-2616-4834-b122-5cb1b07f8a59"
      type = "Role"
    }
  }
}
```

### References

* [AzureAD #35](https://github.com/terraform-providers/terraform-provider-azuread/issues/35)
* [azuread_application documentation](https://www.terraform.io/docs/providers/azuread/r/application.html)

**Comment by yuri-tieto** [comment]
@amasover where you ever able to use your Managed Identity with added Graph API permissions to manage AD resources? For me it work only if I am using Administrative roles and not granting Graph API permissions. My thought is this can be because Terraform is using Azure AD Graph API (legacy API) instead of new and recommended Microsoft Graph API and when you provide API permissions through Microsoft Graph API, Terraform is unable to use those permissions utilising legacy AAD Graph API to manage AD resource.

I am constantly getting `Insufficient privileges to complete the operation` error and the only way to fix this is to add corresponding Administrative role.

**Comment by amasover** [comment]
@yuri-tieto 

> My thought is that this can be because Terraform is using Azure AD Graph API (legacy API) instead of new and recommended Microsoft Graph API

It's been a few months since I've looked at this. I think azuread currently using the legacy Azure AD Graph API probably doesn't help (I *think* you don't need quite so elevated permissions on your personal account in order to set up these permissions if you're using Microsoft Graph...could be wrong). But it seems we also need a way to set up `required_resource_access` on a managed identity.

> were you ever able to use your Managed Identity with added Graph API permissions to manage AD resources?

I was not able to do so through Terraform, but I was able to set it up manually...

*Note*: Your account must have at least Privileged Role Administrator permission to set up all permissions, might also need at least Managed Identity Operator permission. I ended up running these commands as a Global Administrator.

**OAuth Permission Grant**

1. Login to Graph Explorer https://graphexplorer.azurewebsites.net/

2. POST to the following URL:
https://graph.windows.net/${tenant-id}/oauth2PermissionGrants

```json
{
    "odata.type": "Microsoft.DirectoryServices.OAuth2PermissionGrant",
    "clientId": "The service principal of the MSI you want to assign permissions to",
    "consentType": "AllPrincipals",
    "principalId": null,
    "resourceId": "The object ID of the graph api in your subscription",
    "scope": "User.Read",
    "startTime": "0001-01-01T00:00:00",
    "expiryTime": "9000-01-01T00:00:00"
}
```

3. Check assignment via GET on the following URL:

https://graph.windows.net/myorganization/servicePrincipals/${service-principal-client-id-of-msi}/appRoleAssignments

**App role assignments**

Powershell script (run from my local machine):

```powershell
$msiName = "${name-of-your-msi}"
$tenantId = "${your-tenant-id}"

Import-Module AzureAD.Standard.Preview
Connect-AzureAd -TenantId $tenantId
Connect-AzAccount -TenantId $tenantId

$graph = Get-AzureADServicePrincipal -Filter "AppId eq '00000002-0000-0000-c000-000000000000'" # Azure AD Graph API

$appReadWrite = $graph.AppRoles `
  | where Value -Like "Application.ReadWrite.All" `
  | Select-Object -First 1

$directoryRead = $graph.AppRoles `
  | where Value -Like "Directory.Read.All" `
  | Select-Object -First 1

$msi = Get-AzADServicePrincipal -DisplayName $msiName

New-AzureADServiceAppRoleAssignment `
  -Id $appReadWrite.Id `
  -PrincipalId $msi.Id `
  -ObjectId $msi.Id `
  -ResourceId $graph.ObjectId

New-AzureADServiceAppRoleAssignment `
  -Id $directoryRead.Id `
  -PrincipalId $msi.Id `
  -ObjectId $msi.Id `
  -ResourceId $graph.ObjectId
```
---

The above two methods are pretty nasty to work with compared to Terraform, imho.

**Comment by akingscote** [comment]
Damn didnt work for me :/
Im using a User Assigned Identity which might be the difference.

**Comment by amasover** [comment]
My identity is user assigned as well. What error do you get @akingscote?

**Comment by akingscote** [comment]
So i was trying to give my user assigned identity permissions so that it can at least read app-registrations client ids.

I tried assigning `Applicaiton.ReadWrite.All` using your powershell scripts, to both:
```
00000002-0000-0000-c000-000000000000		= Windows Azure Active Directory
00000003-0000-0000-c000-000000000000		= Microsoft Graph
```
The script works and i can see that the user assigned identity has a number of permissions assinged to it with:
```
Get-AzureADServiceAppRoleAssignedTo -ObjectId <user managed id here> | fl
```

However when i tried to run `az app list` (or similar) from the identity i still get the permission denied message.

Its not a big deal, i was able to manually assign the Azure AD `Application Administrator` role to the managed identity via the portal to get the issue unblocked.
Even using the Powershell, its still moving away from terraform which isnt ideal. Its a shame the mechanism isnt possible via the AzureCLI as i could then run a local-exec on my VM and have an automated workaround from my Linux deployment machine.

I may look at writing a tool which can interact with the Azure Graph RestAPI, but what would be ideal is if terraform pick this up.

Thanks for putting your script on here, it was very interesting.

**Comment by yuri-tieto** [comment]
Same for me - when assigning managed identity some administrative role, all works fine and terraform is able to create AD resources using managed identity. But when assigning those Graph API permissions, I constantly get `Insufficient privileges ...` error. As @amasover pointed out the problem can be in Terraform using legacy Azure AD Graph API instead of new Microsoft Graph API, so permissions are not read correctly. Most probably this feature of `required_resource_access` will be possible to implement only when Terraform switches to new Microsoft Graph API which will be possible only after new Go SDK comes out for Microsoft Graph API :(.

**Comment by akingscote** [comment]
@yuri-tieto or they could use the Microsoft Graph Rest API in their terraform go libraries

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
