### ISSUE TITLE
Unexpected recreate of Application Insights application_type = "Web" -> "web" when upgrading to 2.0.0

### ISSUE THREAD

**Issue by kendaleiv** [hashicorp/terraform-provider-azurerm#5902]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.12.21
Provider: 2.0.0

### Affected Resource(s)

* `azurerm_application_insights`

### Expected Behavior

No redeploy of Application Insights 

### Actual Behavior

Unexpected replacement of item:

```
~ application_type                      = "Web" -> "web" # forces replacement
```

### Steps to Reproduce

Upgrade from 1.x to 2.0.0 with an `azurerm_application_insights` item created with `application_type = "Web"` from 1.x.

**Comment by StefanSchoof** [comment]
I think this is a intented change, see https://github.com/terraform-providers/terraform-provider-azurerm/commit/2bca57e3eaf85dfa95852f0a958759789a7b833e

**Comment by spettifer** [comment]
That's pretty destructive. We now cannot upgrade to v2 of the provider without losing our production logs. We even tried amending the tfstate file but that didn't work either as there still appeared to be a copy of the old tfstate file in the tar file. Intended change it may be, but it seems to have unintended consequences that are leaving us scratching our heads.

**Comment by spettifer** [comment]
After some experimentation we are no further forward because (perhaps not surprisingly) there seems to be no way to change the `Application_Type` property in app insights once it's set, which I expect is why this becomes a destructive problem in TF. Although it's not clear because we are only using the default `web` variety anyway, the case doesn't seem to cause Application Insights itself any problems and I cannot find any reference to that situation changing (I'm sure if it did then a lot of people would suddenly find their app insights instances not working which would be pretty bad for all concerned). With that in mind, would it not be possible to have TF make a case insensitive equality with the existing value so that anything created with v1 will not need to be recreated just for the sake of the casing on the value?

**Comment by StefanSchoof** [comment]
It is possible to make a workaround with lifecycle ignore_changes https://www.terraform.io/docs/configuration/resources.html#ignore_changes

**Comment by spettifer** [comment]
Ah OK, I'll give that a go - might do what we want which would be great, cheers

**Comment by spettifer** [comment]
Did exactly what we wanted, thank you. Didn't know about that resource behaviour customisation ability previously but it will be useful as I'm certain we have more instances of AI where the `Application_Type` is improperly cased.

For anyone following on, [here's a gist showing an example of this for application insights](https://gist.github.com/spettifer/55dc46bad2f002f1c7def76814ccbd42)

**Comment by restfulhead** [comment]
Faced the same issue and the lifecycle ignore_changes helped. I think it would be good to add this information to https://www.terraform.io/docs/providers/azurerm/guides/2.0-upgrade-guide.html

**Comment by dagus** [comment]
This is still an issue that forces a workaround, when can we expect to have this resolved?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
