### ISSUE TITLE
Support for Private Link in azurerm_container_registry

### ISSUE THREAD

**Issue by haroldwongms** [hashicorp/terraform-provider-azurerm#6223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like support for Private Links in the azurerm_container_registry provider.  This is currently a Preview feature and am working on testing deployments now but this is not possible with the provider today.

### New or Affected Resource(s)

Existing resource
* azurerm_container_registry

### References

Private Link configuration for Azure Container Registry
* https://docs.microsoft.com/en-us/azure/container-registry/container-registry-private-link

What is a Private Link
* https://docs.microsoft.com/en-us/azure/private-link/private-link-overview

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

As an addition, private links/endpoints are a separate resource, so building those into the resource itself doesn't seem feasible really.
