### ISSUE TITLE
AzureRM version and Azure API

### ISSUE THREAD

**Issue by iamsoorya** [hashicorp/terraform-provider-azurerm#6680]
We are using AzureRM 1.44.0 I understsand that we need to update to AzureRM 2.x. However, is there is different version of Azure API that you use behind the scene? For example, If I use 1.44 to create AKS , is the same underlying Azure API used by 2.6 version also?

We are struggling to solve the state issue with 2.x version. Once we solve that we will move to 2.x version.

**Comment by mybayern1974** [comment]
@iamsoorya, thank you for opening this issue. There have been always backend API version upgrading, which is not brought in by TF 1.x to 2.x but motivated by feature requirements. In theory state things should be consistent within a major version, say between v1.a and v1.b, or between v2.c and v2.d. However that's not guaranteed across major versions say between v1.x and v2.y, since there were lots of [UI/Behavior breaking changes](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.0.0) which is on purpose during the major version upgrading.

If the above does not answer your question, may I suggest you could share an concrete example here to tell what state-diff you saw?  

Meanwhile as for the AKS case you mentioned here, there was a [breaking change](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.5.0) from TF 2.4 to 2.5, which was not common to happen within the same major version but had to happen for there being a significant change in the Azure service api behavior. You can get more detail in the release notes linked above to tell whether this is exactly your case, or you may wanna share another example you are running into.

**Comment by molinch** [comment]
If we want to move lets say from azurerm 1.40 to 2.0 there are tons of breaking changes, some require to alter the state file...
Do you provide a tool that would help in this transition? It's very easy to make mistakes

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
