### ISSUE TITLE
data.azurerm_shared_image_version: how to get the actual image version if I use "latest" as image name?

### ISSUE THREAD

**Issue by miiitch** [hashicorp/terraform-provider-azurerm#6750]
I'd like to add the actual image version as tag on my VMs.

**Comment by ArcturusZhang** [comment]
Hi @miiitch thanks for this issue.
How about this [data source `azurerm_shared_image_versions`](https://www.terraform.io/docs/providers/azurerm/d/shared_image_versions.html), which allows you to specify a `tags_filter` and return all the matched `shared_image_version`s.

**Comment by miiitch** [comment]
Hi, It is not what I want to achieve. I want to specify "latest" as image version and and use this version on the VM tags so when I look at the VM I know which image version I used. 

For this block:
```hcl

data "azurerm_shared_image_version" "image" {
...
  version = "latest"
...
}
```
`data.azurerm_shared_image_version.image.version` contains the actual latest version, something like "1.2.8" for example.

**Comment by ArcturusZhang** [comment]
Based on how the `azurerm_shared_image_version` is implemented, it will always return the latest version with the actual version number. (You will get troubles if you just want some specific version rather than the latest one)
Therefore I suppose, if my understanding is right, assigning `data.azurerm_shared_image_version.image.version` to a tag of VM should be exactly what you want? Or maybe I did not get the point here...

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
