### ISSUE TITLE
Support for KeyVault object versioning

### ISSUE THREAD

**Issue by OK-UNDP** [hashicorp/terraform-provider-azurerm#6915]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The latest version of `azurerm` (2.9.0) does not allow to create a new version of the same certificate object in the Azure KeyVault for imported PFX. As explained in the documentation for the `certificate.contents` parameter: 
> The base64-encoded certificate contents. Changing this forces a new resource to be created. 

It seems that the same situation is with KeyVault secrets. It would be great if `azurerm` or `azurerm_key_vault_certificate` and `azurerm_key_vault_secret` could handle versioning and instead of showing the latest version would have a list of versions.

### New or Affected Resource(s)

* `azurerm_key_vault_certificate`
* `azurerm_key_vault_secret`

* #0000

**Comment by cmielke** [comment]
I have a Key Vault with soft delete and purge protection enabled. In this case, I cannot use Terraform to deploy new versions of my certificate because it tries to delete the old cert and create a new one, which leads to the following error:

Error: keyvault.BaseClient#ImportCertificate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Certificate REDACTED is currently in a deleted but recoverable state, and its name cannot be reused; in this state, the certificate can only be recovered or purged." InnerError={"code":"ObjectIsDeletedButRecoverable"}

  on main.tf line 152, in resource "azurerm_key_vault_certificate" "cert":
 152: resource "azurerm_key_vault_certificate" "cert" {

Is there any way to work around this issue or do I need to create a new Key Vault that does not use purge protection and soft delete?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
