### ISSUE TITLE
Removing azurerm_virtual_machine_scale_set_extension does not wait for rolling upgrade

### ISSUE THREAD

**Issue by hbuckle** [hashicorp/terraform-provider-azurerm#7002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.10.0

### Affected Resource(s)

* `azurerm_virtual_machine_scale_set_extension `

### Expected Behavior

I have a scale set with a rolling upgrade policy and 2 extensions configured. When running terraform destroy one of the extensions is removed, which triggers a rolling upgrade of the scale set, but terraform does not wait and immediately tries to remove the next extension, resulting in an error

### Actual Behavior

```
Error: Error deleting Extension "init-script" (Virtual Machine Scale Set "eldat" / Resource Group "myrg"): compute.VirtualMachineScaleSetExtensionsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Virtual Machine Scale Set updates are not allowed while there is a Rolling Upgrade in progress. Please cancel Rolling Upgrade operation to continue with updates."
```

### Steps to Reproduce

Create a vmss with rolling upgrade policy and multiple extensions, then run terraform destroy

**Comment by NickCarton** [comment]
I am also running into this issue

**Comment by rakeshsiet** [comment]
I am facing this error,
I have rolling policy configured, and extension running on the scale set, when I try to update the extension it removes all the VM instances fro scale set and eventually giver error "Virtual Machine Scale Set updates are not allowed while there is a Rolling Upgrade in progress. Please cancel Rolling Upgrade operation to continue with updates."

**Comment by pollyapostolova** [comment]
Are there any updates on this?
We're having the same issue with **azurerm_linux_virtual_machine_scale_set** with extensions and rolling upgrade policy configured. When running terraform destroy we're getting the same error (regardless of the number of extensions) :

`Code="OperationNotAllowed" Message="Virtual Machine Scale Set updates are not allowed while there is a Rolling Upgrade in progress. Please cancel Rolling Upgrade operation to continue with updates."`

**Comment by WodansSon** [comment]
This scenario will not work against a `azurerm_linux_virtual_machine_scale_set` because it's orchestration mode is set to `Uniform` and attempting to use a `azurerm_linux_virtual_machine_scale_set` or a `azurerm_windows_virtual_machine_scale_set` will cause the below error:

```
Error: creating Linux Virtual Machine: (Name "repro-vm" / Resource Group "repro-vmss-7002"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="This operation is not allowed because referenced Virtual Machine Scale Set '/subscriptions/XXXXX/resourceGroups/repro-vmss-7002/providers/Microsoft.Compute/virtualMachineScaleSets/repro-vmss' does not have orchestration mode set to 'Flexible'."
```

Currently the `azurerm_virtual_machine_scale_set` resource is in a "**feature-frozen state**" and has been superseded by the `azurerm_linux_virtual_machine_scale_set` and the `azurerm_windows_virtual_machine_scale_set` resources. The existing `azurerm_virtual_machine_scale_set` will be removed from v3.0 of the Provider in the very near future.

Since `azurerm_orchestrated_virtual_machine_scale_set`, the only resource with the correct orchestration mode to support this functionality, does not currently support rolling upgrades at this time, unfortunately, this is not a supported scenario.

I hope I have answered your questions, please feel free to close this issue unless you have further questions. 🚀

**Comment by tombuildsstuff** [comment]
A couple of clarifications to @WodansSon's comment above:

Whilst the existing `azurerm_virtual_machine_scale_set` resource remains available - it's been superseded by the `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources and is feature-frozen at this time - meaning it'll receive no further updates (or new functionality). Whilst this resource will likely be deprecated at some point in the 3.x cycle, this won't be removed in 3.0 (and wouldn't be before at least 4.0 as removing the resource would be a breaking change).

The newer `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources both support defining VM Extensions inline - and during a Create/Update will automatically roll the instances in the Scale Set if required (the behaviour of which [can be configured using the `features` block within the `providers` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#features)) which I believe should work for you here - but if this doesn't then this would be a bug (and so please open an issue to track that).

However since the original resource is feature-frozen and has been superseded, and support for this is available in the replacement resources - I'm going to close this issue for the moment.

Thanks!

**Comment by hbuckle** [comment]
I'm pretty sure at the time inline extension support wasn't available in the new resources - now that it is this should work
