### ISSUE TITLE
Terraform not ignoring and still managing API Management `certificate` blocks when using `ignore_changes`.

### ISSUE THREAD

**Issue by akleiser-midmark** [hashicorp/terraform-provider-azurerm#7815]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.28
+ provider.azurerm v2.19.0

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
# Configure Azure Provider
provider "azurerm" {
  version = "~>2.19.0"
  features {}
}

# Create a new resource group
resource "azurerm_resource_group" "purge-resource-group" {
  name = "api-purge-rg"
  location = "eastus"
}

# Create the APIM Instance
resource "azurerm_api_management" "purge-apim" {
  name                = "purge-apim-test"
  location            = azurerm_resource_group.purge-resource-group.location
  resource_group_name = azurerm_resource_group.purge-resource-group.name
  publisher_name      = "Anthony"
  publisher_email     = "name@email.com"
  sku_name = "Developer_1"
  
  certificate {
    encoded_certificate = "<encoded_content>"
    store_name = "Root"
    certificate_password = ""
  }

  certificate {
    encoded_certificate = "<encoded_content>"
    store_name = "CertificateAuthority"
    certificate_password = ""
  }

  certificate {
    encoded_certificate = "<encoded_content>"
    store_name = "CertificateAuthority"
    certificate_password = ""
  }

  policy {
    xml_content = <<XML
    <policies>
      <inbound />
      <backend />
      <outbound />
      <on-error />
    </policies>
XML

  }

  lifecycle {
    ignore_changes = [certificate]
  }
}
```

### Debug Output

https://gist.github.com/akleiser-midmark/a8e50d8a1335dc88dd6ce915097af93b

### Expected Behavior

Certificates managed outside of terraform should not get silently deleted if no CA certificates are configured in the terraform files.

Use of the `ignore_changes` feature should stop terraform from deleting any existing CA certificates in API management.

### Actual Behavior

Certificates managed outside of terraform get continuously purged from APIM during deployments. This occurs whether or not any `certificate` blocks have been defined in the configuration. The `ignore_changes` feature does not stop terraform from overwriting any existing certificates it is unaware of.

### Steps to Reproduce

1. Create terraform configuration to create an API management instance.
1. `terraform plan` and `terraform apply -auto-approve` can be used to create resources
1. Manually upload a certificate to the API management instance's CA Certificates
1. Change an unrelated value in your terraform configuration, see no report of `certificate` values when you run `terraform plan`
1. Execute `terraform apply -auto-approve` and observe CA Certificates are not present in APIM.
1. Manually add the CA Certificate again
1. Change an unrelated value in your terraform configuration, add an ignore_changes for certificate, see no report of `certificate` values when you run `terraform plan`.
1. Execute `terraform apply -auto-approve` and observe CA Certificates are not present in APIM.

### References

The API Management Management REST APIs seem to hint that this should be possible.

Both the PUT and PATCH for API management service allow you to completely omit the `properties.certificates` structure or set it explicitly to `null`. When this is done the existing CA Certificates on the service are not deleted. The only time CA Certificates can be observed being deleted when using the REST APIs is when an empty block is defined - `{}`.

* https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apimanagementservice/update
* https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apimanagementservice/createorupdate

**Comment by yupwei68** [comment]
Hi @akleiser-midmark , thanks for opening this issue.

Firstly, I'd like to explain why the `terraform plan` shows no change and `ignore_changes` doesn't work. It's because the service api doesn't return `certificate` back, we can't get the remote value of the `certificate`. That's why we could not detect the difference between current TF configuration and the remote state of `api_management`.

Secondly, I'd like to explain why we always update the `api_management` as exactly the TF configuration, even if you don't config `certificate` and we'll update an empty list to the `api_management`. Because  a practice of leveraging terraform to manage Azure resources is to always use terraform end to end, which helps make state things consistent and manageable. Managing resources by the mixing usage of terraform and non-terraform (say operate on portal) would be likely to incur unexpected inconsistency. That's the practice to design the Terraform workflow. There are many resources following this design. If I change the action here,(if you don't change `certificate` TF configurations, we'll not update the `certificate`) it'll break other users' existing practice and cause confusions. 

Thirdly, I'd like to suggest to upload your certificate by Terraform to solve the current problem. I wish the following sample configuration could help you.
```
resource "azurerm_api_management" "test" {
  name                            = "acctestAM"
  location                       = azurerm_resource_group.test1.location
  resource_group_name = azurerm_resource_group.test1.name
  publisher_name            = "pub1"
  publisher_email           = "pub1@email.com"
  notification_sender_email = "notification@email.com"

  additional_location {
    location = azurerm_resource_group.test2.location
  }

  certificate {
    encoded_certificate  = filebase64("testdata/api_management_api_test.pfx")
    certificate_password = "terraform"
    store_name           = "CertificateAuthority"
  }
...

}

```

**Comment by akleiser-midmark** [comment]
I appreciate the response @yupwei68 , we will look at managing our certificates with the terraform.

I'm still suspicious of the `ignore_changes` not working for certificates correctly. My thought was that if the `ignore_changes` were set and terraform had no mention of certificates it would continue to send an explicity null value for the certificates or leave it out of the body being sent to the service API entirely. In my testing I was observing this made no changes to the APIM CA Certificates. 

Does this make sense for the `ignore_changes` on the `certificate`?

**Comment by yupwei68** [comment]
Hi @akleiser-midmark , `certificate` is a special case because it's sensitive and it'll not return back for service api. In other cases, `ignore_changes` could work because it could detect the changes and choose to not update them. In this case, we could not detect the changes, which is indicated from step 4. Thus we could not ignore the changes. Sorry that it caused some inconveniences for you. But we always want to keep a consistent practice for most users.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
