### ISSUE TITLE
Make test fails on Windows 10 with git bash

### ISSUE THREAD

**Issue by dzmitry-lahoda** [hashicorp/terraform-provider-azurerm#8206]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Master

### Terraform Configuration Files

```
make test
```

### Debug Output

````
dz@lahoda-pc MINGW64 /c/Go/src/github.com/terraform-providers/terraform-provider-azurerm (feaute/app-service-autoheal)
$ make test
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
==> Checking for use of gradually deprecated functions...
The Feature Flag for 'ShouldResourcesBeImported' will be deprecated in the future
and shouldn't be used in new resources - please remove new usages of the
'ShouldResourcesBeImported' function from these changes - since this is now enabled
by default.

In the future this function will be marked as Deprecated - however it's not for
the moment to not conflict with open Pull Requests.
==> Checking for use of deprecated functions...
Data Sources should return an error when a resource cannot be found rather than
setting an empty ID (by calling 'd.SetId()'.

Please remove the references to 'd.SetId() from the Data Sources listed below
and raise an error instead:

./azurerm/internal/services/datashare/data_source_data_share.go
==> Running Unit Tests...
./scripts/run-test.sh: line 18: /c/go/bin/go: Argument list too long
make: *** [GNUmakefile:87: test] Error 1
```

**Comment by manicminer** [comment]
Hi @dzmitry-lahoda, thanks for reporting this. When running in git-bash or cygwin, I get the same error (`Argument list too long`) and I think it may be due to ARG_MAX being very small. With Cygwin or git-bash on my machine, it's between one and two orders of magnitude smaller than my MacOS or Linux environments.

Whilst we could potentially alter the relevant script to descend into directories and not pass any module names to `go test`, this runs the risk of potentially missing some of the tests, and I suspect we might also hit path length limitations.

My suggestion would be to try with WSL (1 or 2). You can also invoke `go test` manually. I'll take a look at improving the documentation here.

**Comment by dzmitry-lahoda** [comment]
are any changes pure go or go test solution could be accepted in PR as runner? (if that reasonably possible to write just go script runner)

**Comment by manicminer** [comment]
I did play around with some optiojns for shortening the invoked command, but nothing that gives us the flexibility to scan for packages the way we have now.

**Comment by dzmitry-lahoda** [comment]
okey, will try WSL2

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
