### ISSUE TITLE
Missing Stack settings in App Service running on App Service Plan for Linux.

### ISSUE THREAD

**Issue by smigalni** [hashicorp/terraform-provider-azurerm#8678]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.3

### Affected Resource(s)
App Service Plan for Linux
App Service 

* `azurerm_2.0.0`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.0.0"
  features { }  
}

resource "azurerm_resource_group" "rg" {
  name     = var.resourceGroupName
  location = var.location
}

resource "azurerm_app_service_plan" "app_plan" {
  name                = var.appServicePlanName
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  kind                = "Linux"
  reserved            = true
  sku {
    tier = "Basic"
    size = "B1"
  }
}

resource "azurerm_app_service" "app_service" {
  name                = var.appServiceName
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  app_service_plan_id = azurerm_app_service_plan.app_plan.id
 
}
```

### Debug Output

everything created without problem

### Expected Behavior

When creating App Service on App Service Plan for Linux manually you chose the Runtime Stack. But when creating using terraform missing the possibility to specify that.

### Actual Behavior

Missing the stack settings when creating App Service on App Service Plan for Linux. The problem is that the node.js app doesn't work properly.

You can see it the Azure Portal.
Go to App Service created by terraform. -> Settings -> Configuration -> General Settings. Missing Node.js Stack settings. 

### Steps to Reproduce

1. Create API using TypeScript and Node.js f.ex clone my repo from here: https://dev.azure.com/sergeydotnet/CloudStoriesDemo/_git/CloudStoriesApi 

2. `terraform apply`

Got 
Access forbidden when trying to reach application.

### Walk around
```hcl
provider "azurerm" {
  version = "=2.0.0"
  features { }  
}

resource "azurerm_resource_group" "rg" {
  name     = var.resourceGroupName
  location = var.location
}

resource "azurerm_app_service_plan" "app_plan" {
  name                = var.appServicePlanName
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  kind                = "Linux"
  reserved            = true
  sku {
    tier = "Basic"
    size = "B1"
  }
}

resource "azurerm_app_service" "app_service" {
  name                = var.appServiceName
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  app_service_plan_id = azurerm_app_service_plan.app_plan.id

  site_config {
    linux_fx_version = "NODE|12.x"
  }
}
```
Has to be documented somewhere.

**Comment by trotroyanas** [comment]
Hi,
have a same problem with terraform v0.13.2 and azurerm 2.31.1.
Stack settings are empty :(

```terraform
resource "azurerm_app_service" "frontwebapp" {
  name                = "${var.app_owner}-${var.keykats}-${var.environment}-app-ariane-001"
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
  app_service_plan_id = azurerm_app_service_plan.plan.id

  site_config {
    always_on              = true
    java_version           = "11"
    java_container         = "JAVA"
    java_container_version = "11"
    app_command_line       = "java -jar /home/site/wwwroot/hello3.war"
    ftps_state             = "AllAllowed"
  }

  app_settings = {
  "WEBSITE_VNET_ROUTE_ALL" = "1"
  "MYSQL_HOST"             = azurerm_private_endpoint.default.private_service_connection[0].private_ip_address
  "MYSQL_LOGIN"            = "${var.bdduser}@${azurerm_mysql_server.default.name}"
  "MYSQL_PASSWORD"         = data.azurerm_key_vault_secret.SecretBddAccess.value
  "MYSQL_PORT"             = var.server_port
  "MYSQL_BDD"              = azurerm_mysql_database.bdd.name

  }

  tags = merge(local.mandatory_tags, local.extra_tags)

}

```

**Comment by trotroyanas** [comment]
with azurerm 2.36 same things...

**Comment by trotroyanas** [comment]
it's ok now for me add this property
 **linux_fx_version       = "JAVA|11-java11"**
```
  site_config {
    always_on              = true
    **linux_fx_version       = "JAVA|11-java11"**
    java_version           = "11"
    java_container         = "JAVA"
    java_container_version = "11"
    app_command_line       = "java -jar /home/site/wwwroot/webapp.war"
    ftps_state             = "AllAllowed"
  }
```

**Comment by CarlosLanderas** [comment]
Having the same problema with a linux appservice using 
> linux_fx_version = DOTNET|5.0

**Comment by vnextcoder** [comment]
I also have same issue

**Comment by rahul-roy1-maersk** [comment]
@trotroyanas @tombuildsstuff 
I ran into a similar issue.

In TF code, the web app plan was:

` "module": {
    "webapp-linux": {
      "source": "webapp-linux/azurerm",
      "version": "2.1.1",
      "app_service_plan_id": "${module.app-service-plan.id}",
      "name": "${var.webapp_name}",
      "ip_address": "${var.webapp_ip_address}",
      "resource_group": "${var.resource_group_name}",
      "https_only": "${var.webapp_https_only}",
      "app_settings": {
        "APPINSIGHTS_INSTRUMENTATIONKEY": "${module.application-insights.instrumentation_key}",
        "azurekeyvaulturi": "${module.key_vault.vault_uri}",
        "ENABLE_IN_PROC_AGENT": "true",
        "JAVA_OPTS": "-javaagent:/home/site/wwwroot/applicationinsights-agent-3.0.0.jar",
        "DBConnectionMode": "GATEWAY"
      }
    }
  }`

Now the runtime stack was supposed to be set through Release pipeline in Azure DevOps to `Java SE 8 (JAVA|8-jre8)`.
But we missed it and then when the webapp started coming up, it gave error as:
`2021-02-28T04:57:37.345201268Z Writing output script to '/opt/startup/startup.sh'
2021-02-28T04:57:37.998405067Z /opt/startup/startup.sh: 13: /opt/startup/startup.sh: java: not found`

Now we went back and updated the release pipeline runtime stack and redeployed - still didn't work.

Then deleted the Azure resources completely through updated TF plan and rerun the original TF code (above) and updated pipeline runtime stack.

Now in the webapp config through CLI, it shows:
`  "javaContainer": null,
  "javaContainerVersion": null,
  "javaVersion": null,
  "kind": null,
  "limits": null,
  "linuxFxVersion": "Java SE 8 (JAVA|8-jre8)",
`
But still the same error when web app starts: ` /opt/startup/startup.sh: java: not found`.

Now I am planning to delete the resources through TF and run an updated TF code like this:
`site_config {
    always_on              = true
    linux_fx_version       = "JAVA|8-jre8"
  }`

But I am not sure if this will work. Do I need to add the `java_container` and related fields as well?
Any help is appreciated - stuck on production go-live because of this.

Kind Regards,
Rahul

**Comment by rahulroy1** [comment]
@trotroyanas @tombuildsstuff 
I ran into a similar issue.

In TF code, the web app plan was:

` 
"module": {
    "webapp-linux": {
      "source": "webapp-linux/azurerm",
      "version": "2.1.1",
      "app_service_plan_id": "${module.app-service-plan.id}",
      "name": "${var.webapp_name}",
      "ip_address": "${var.webapp_ip_address}",
      "resource_group": "${var.resource_group_name}",
      "https_only": "${var.webapp_https_only}",
      "app_settings": {
        "APPINSIGHTS_INSTRUMENTATIONKEY": "${module.application-insights.instrumentation_key}",
        "azurekeyvaulturi": "${module.key_vault.vault_uri}",
        "ENABLE_IN_PROC_AGENT": "true",
        "JAVA_OPTS": "-javaagent:/home/site/wwwroot/applicationinsights-agent-3.0.0.jar",
        "DBConnectionMode": "GATEWAY"
      }
    }
  }
`

Now the runtime stack was supposed to be set through Release pipeline in Azure DevOps to `Java SE 8 (JAVA|8-jre8)`.
But we missed it and then when the webapp started coming up, it gave error as:
`
2021-02-28T04:57:37.345201268Z Writing output script to '/opt/startup/startup.sh'
2021-02-28T04:57:37.998405067Z /opt/startup/startup.sh: 13: /opt/startup/startup.sh: java: not found
`
Now we went back and updated the release pipeline runtime stack and redeployed - still didn't work.

Then deleted the Azure resources completely through updated TF plan and rerun the original TF code (above) and updated pipeline runtime stack.

Now in the webapp config through CLI, it shows:
`  
"javaContainer": null,
  "javaContainerVersion": null,
  "javaVersion": null,
  "kind": null,
  "limits": null,
  "linuxFxVersion": "Java SE 8 (JAVA|8-jre8)",
`
But still the same error when web app starts: ` /opt/startup/startup.sh: java: not found`.

Now I am planning to delete the resources through TF and run an updated TF code like this:
`
site_config {
    always_on              = true
    linux_fx_version       = "JAVA|8-jre8"
  }
`

But I am not sure if this will work. Do I need to add the `java_container` and related fields as well?
Any help is appreciated - stuck on production go-live because of this.

Kind Regards,
Rahul

**Comment by gogorichie** [comment]
I'm having a similar problem.

**Comment by rahulroy1** [comment]
> I'm having a similar problem.

For me, the below setting in `site_config` solved the problem:
`"linux_fx_version": "JAVA|8-jre8",`

**Comment by trotroyanas** [comment]
solve problem with this code :
  site_config {
    always_on              = true
    linux_fx_version       = "JAVA|11-java11"
    java_version           = 11
    java_container         = "JAVA"
    java_container_version = 11
    app_command_line       = "java -jar /home/site/wwwroot/webapp.war"
    ftps_state             = "AllAllowed"
    scm_type               = "none"
  }

**Comment by 0GiS0** [comment]
Same here, I tested with  linux_fx_version = "NODE|12.x" and  linux_fx_version = "NODE|14.x". I see it when I use az webapp config show -n WEBAPP_NAME -g RESOURCE_GROUP

![image](https://user-images.githubusercontent.com/175379/121560400-c1d5b980-ca17-11eb-9ce3-eb0993299a2c.png)

But no in the portal:

![image](https://user-images.githubusercontent.com/175379/121560561-f0539480-ca17-11eb-83b9-10b879cba3eb.png)

Cheers,

**Comment by 0GiS0** [comment]
Hi all!

I've just found it how you can fixed for Node.js. This are the possible values:

```
  site_config {
    websockets_enabled = true

    #Node.js values
    # linux_fx_version	Actual runtime
    # NODE|10.1	        10.1.0
    # NODE|10.6	        10.23.0 (not a typo)
    # NODE|10.14	      10.14.2
    # NODE|10-lts	      10.23.0
    # NODE|12-lts	      12.19.0
    # NODE|14-lts	      14.15.1

    linux_fx_version = "NODE|14-lts"
  }
```

Hope it helps

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
