### ISSUE TITLE
Support for customer-managed key disk encryption when creating a HDinsight cluster

### ISSUE THREAD

**Issue by serafeimgr** [hashicorp/terraform-provider-azurerm#8988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently we have the option to create a HDinsight cluster using customer-managed keys but the terraform provider does not give this option.

According to the docs is doable using az cli

example below

```
az hdinsight create -t spark -g MyResourceGroup -n MyCluster \
-p "HttpPassword1234!" --workernode-data-disks-per-node 2 \
--storage-account MyStorageAccount \
--encryption-key-name SparkClusterKey \
--encryption-key-version 00000000000000000000000000000000 \
--encryption-vault-uri https://MyKeyVault.vault.azure.net \
--assign-identity MyMSI

```

### References

https://docs.microsoft.com/en-us/azure/hdinsight/disk-encryption

**Comment by tombuildsstuff** [comment]
hey @serafeimgr 

From what I can see support for this [is available in the `disk_encryption` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/hdinsight_hadoop_cluster#disk_encryption) in the HDInsight Resources, and as such I believe this feature is now supported - since this appears to be available I'm going to close this feature request for the moment, but if you believe there's something additional needed here then please let us know and we can take another look.

Thanks!
