### ISSUE TITLE
Issue upgrading cluster from 1.6.7 to 1.6.15

### ISSUE THREAD

**Issue by ipalazzi** [hashicorp/terraform-provider-azurerm#9230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform: 0.12.26
AzureRM: 2.35.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "kubernetes_cluster" {
  name                = "MyK8SClusterName"
  location            = "northeurope"
  resource_group_name = "my-resource-group"

  dns_prefix          = MyK8SClusterName
  kubernetes_version  = "1.16.15"

  linux_profile {
    admin_username = "kube-admin"

    ssh_key {
      key_data = <redacted>
    }
  }

  default_node_pool {
    name            = "dev"
    vm_size         = "Standard_A2"

    orchestrator_version = "1.16.15"

    enable_auto_scaling = true
    min_count           = 1
    max_count           = 4
  }

  service_principal {
    client_id     = <redacted>
    client_secret = <redacted>
  }
}
```

### Debug Output

https://gist.github.com/ipalazzi/d40c77e47a199921d71e8498b6abe2a6

### Expected Behavior

The script above was intended to upgrade an existing cluster with version 1.6.7 to 1.6.15.

### Actual Behavior

Error on updating the _existing_ cluster because the VM size is not supported anymore. We are expecting to not be forced to recreate the cluster even if the new version requires a new VM sizing because this is an update to an old one, not a brand new cluster creation.

We are sure that this is not something with Azure because we were able to upgrade the cluster manually from the portal without the need for recreating it.

### Steps to Reproduce

This is not reproducible anymore from scratch because requires to create a cluster with version 1.6.7 and the, upgrade it to version 1.6.15.

**Comment by stephybun** [comment]
Hi @ipalazzi,

Apologies that no one was able to look into this and give you a response sooner. The error message thrown by the AKS API indicates that the VM size chosen for the cluster doesn't meet the minimum specifications required for a system node pool. 

Furthermore since updating the `vm_size` property of the `default_node_pool` isn't supported per se by the AKS API, this property had to force recreate the cluster at the time.

That said we have introduced the ability to update this property now through cycling the `default_node_pool` in *v3.47.0* of the provider.

Since this issue pertains to a version of the provider over 2 years old now and the error message relates to a [documented limitation in allowed VM sizes for system node pools](https://learn.microsoft.com/en-us/azure/aks/quotas-skus-regions#restricted-vm-sizes) I'm going to close this issue.

Thanks!
