### ISSUE TITLE
Support for creating Azure Application Gateway components from outside the application gateway resource

### ISSUE THREAD

**Issue by bhavikkumar** [hashicorp/terraform-provider-azurerm#9615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
Community Note

    Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
    Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
    If you are interested in working on this issue or have submitted a pull request, please leave a comment

Description

We have a number of applications which have their own repositories and it would be nice to have the application code and Terraform IaC in a single repository. However, our application gateway is shared across all of these applications.

It would be nice if we could have resources to attach backend http settings, address pool and routing rules to an existing application gateway.

New or Affected Resource(s)

Affected:

    azurerm_application_gateway
    New:
    azurerm_application_gateway_backend_address_pool
    azurerm_application_gateway_backend_address_pool_attachment
    azurerm_application_gateway_backend_http_settings
    azurerm_application_gateway_backend_http_settings_attachment
    azurerm_application_gateway_request_routing_rule
    azurerm_application_gateway_request_routing_rule_attachment

Potential Terraform Configuration

resource "azurerm_application_gateway" "test" {
  name                = "name"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  sku {
    name     = "Standard_Small"
    tier     = "Standard"
    capacity = 2
  }

  gateway_ip_configuration {
         ### OPTIONAL 
  }

  frontend_port {
         ### OPTIONAL 
  }

  frontend_ip_configuration {
         ### OPTIONAL 
  }

  backend_address_pool {
         ### OPTIONAL 
  }

  backend_http_settings {
         ### OPTIONAL 
  }

  http_listener {
         ### OPTIONAL 
  }

  request_routing_rule {
    name                       = "${local.request_routing_rule_name}"
    rule_type                  = "Basic"
    http_listener_name         = "${local.listener_name}"
    backend_address_pool_name  = "${local.backend_address_pool_name}"
    backend_http_settings_name = "${local.http_setting_name}"
  }
}

resource "azurerm_application_gateway_backend_address_pool" "backend_address_pool" {
  ...
}
resource "azurerm_application_gateway_backend_address_pool_attachment" "backend_address_pool_attachment" {
  application_gateway_id    = azurerm_application_gateway.test.id
  frontend_port_id = azurerm_application_gateway_backend_address_pool.backend_address_pool.id
  ...
}

resource "azurerm_application_gateway_backend_http_settings" "backend_http_settings" {
  ...
}

# Attachment for this following same conventions (avoided to replicate similar approach)

resource "azurerm_application_gateway_backend_address_pool" "backend_address_pool_attachment" {
  application_gateway_id    = azurerm_application_gateway.test.id
  frontend_port_id = azurerm_application_gateway_backend_address_pool.backend_address_pool.id
  ...
}

# Attachment for this following same conventions (avoided to replicate similar approach)
resource "azurerm_application_gateway_http_listener" "http_listener" {
  ...
}

resource "azurerm_application_gateway_request_routing_rule" "request_routing_rule" {
  ...
}

Attachment for this following same conventions (avoided to replicate similar approach)

References

Step-by-Step tutorial: https://docs.microsoft.com/en-us/azure/application-gateway/create-url-route-portal
Documentation on the service (URL based rules) : https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview

* #0000

**Comment by Purneau** [comment]
Making the backend_address_pool and other components optional, would also allow us to deploy an "empty" gateway, that we then later (during application deployment) fill with the applicable pools, routes, front-ends, etc.

We also have multiple applications running through the same gateway and would like to update these 'routes' on the go.

**Comment by samuelgautier** [comment]
That's definetly a need for multi-site hosting sharing the same gateway (previously created at the spoke infrastructure level for instance) with workloads having its own terraform code in the release pipeline that should be able to only add a few settings (Listners, rules, probes, backend pools ...).The current limitations of this resource is an obstacle to a end-to-end automation process in a HUB&SPOKE architecture looking for mutualization.

**Comment by samar-upadhyay** [comment]
Same issue here. Application gateway gets created as part of infrastructure creation. Individual applications get created separately and they need to attach the gateway components separately. I'm currently resorting to using null resource and azure cli to accomplish this.

**Comment by lotaezhao** [comment]
My solution to this predicament was to create an application gateway module using dynamic blocks to create the child resources. However, this means the app gateway deployment has to be updated independently of applications that are using it, increasing complexity. I'd prefer to do it this way and create the child resources as part of each application deployment.

Also, using dynamic blocks with azurerm_application_gateway currently causes conflicts when adding new child resources; https://github.com/hashicorp/terraform-provider-azurerm/issues/13468

**Comment by tombuildsstuff** [comment]
hi @bhavikkumar 

Thanks for opening this issue.

Unfortunately the Azure API requires specifying at least one of (almost all of) these components when creating the Application Gateway - as such whilst there's an API available to create each of the components, we're unable to introduce separate resources for these at this time as they would conflict with the components defined inline within the Application Gateway resource.

Whilst this is something we'd like to support in Terraform (and has been previously requested, for example #6703) - unfortunately at this time the Azure API requirement means that we're unable to do this - as such I'm going to suggest [opening an issue on the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs) where someone from the Network Service Team should be able to take a look.

Once this requirement in the Azure API is relaxed such that you can provision an Application Gateway without these components, then we can take a look into supporting this - but for the moment since we're unable to support this I'm going to close this issue.

Thanks!

**Comment by lotaezhao** [comment]
@tombuildsstuff Thanks for replying on this. Since this issue is being closed would you mind having a look at https://github.com/hashicorp/terraform-provider-azurerm/issues/13468? We need a method of dynamically adding new child resources to Application Gateway after it's deployed. But doing it inline within azurerm_application_gateway via dynamic blocks is broken at present. Appreciate if you could give it some attention as that seems the best workaround until the Azure API is fixed so we can manage child resources outside app gateway.
