### ISSUE TITLE
Aci connector linux should export the identity associated to its addon

### ISSUE THREAD

**Issue by jmcshane** [hashicorp/terraform-provider-azurerm#9733]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

ACI connector linux addon creates a managed identity that needs to be granted contributor on the target vnet. If that vnet is outside of the MC resource group, the identity is not able to read the subnet and the `aci-connector-linux` pod crashes when it cannot read the subnet.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
azurerm_kubernetes_cluster.aks.addon_profile[0].aci_connector_linux[0].identity[0].object_id
```

I should be able to reference the `identity` block on the aci connector similar to omsagent

### References

* This example is out of date and should be updated as well: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/kubernetes/aci_connector_linux/main.tf
* https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli#assign-permissions-to-the-virtual-network

**Comment by squasta** [comment]
Got the same issue, no way to get the identity and complete the ACI Network delegation and I am not sure that actually, this feature works on an AKS cluster with managed identities (that is supposed to become the recommended way to setup AKS)

**Comment by ppanyukov** [comment]
Just to say I've ran into the same issue where the ACI managed identity needs to be granted "Network Contributor" on the subnet it uses and it's not exposed anywhere.

The workaround, until there is a fix:

```hcl
# Use "data" to get ID of the ACI managed identity
data "azurerm_user_assigned_identity" "aci" {
  name  = "aciconnectorlinux-${var.cluster_name}"
  resource_group_name = azurerm_kubernetes_cluster.cluster[0].node_resource_group
  depends_on = [
    # not sure we actually need this
    azurerm_kubernetes_cluster.cluster,
  ]
}

# Do the required assignment
resource "azurerm_role_assignment" "aci_network_contributor_subnet" {
  scope                = azurerm_subnet.vnodes.id
  role_definition_name = "Network Contributor"
  principal_id         = data.azurerm_user_assigned_identity.aci[0].principal_id
}
```

The problems with this workaround are:

* We have to infer the name of the identity as `"aciconnectorlinux-${var.cluster_name}"` and who can tell this isn't going to change in the future?
* Bigger problem is that **any** unrelated change to the cluster (e.g. enable/disable OMS) leads to the "forces replacement of the azurerm_role_assignment" issue, because it depends on the `data.azurerm_user_assigned_identity` can only be established during apply so it's not known until any changes to the cluster are complete. Basically we delete and recreate this assignment due to any changes to the cluster.
